data_factory_linked_service_sql_server: supporting password in Key Vault
terraform-providers/terraform-provider-azurerm pull request #10032
Opened 2021-01-03 03:13 UTC by allantargino

fixes #6481

Following the same interface introduced at #9928, where we added `key_vault_password` property on `azurerm_data_factory_linked_service_synapse` to support passwords store in Key Vault through an ADF linked service, this PR adds the same capability to `azurerm_data_factory_linked_service_sql_server`.

The following example

```hcl
resource "azurerm_data_factory_linked_service_sql_server" "test" {
  name                = "SqlServerLinkedSvc"
  resource_group_name = azurerm_resource_group.test.name
  data_factory_name   = azurerm_data_factory.test.name
  connection_string = "Integrated Security=False;Data Source=test;Initial Catalog=test;User ID=test;"
  key_vault_password {
    linked_service_name = "KeyVaultLinkedSvc"
    secret_name         = "MySecret"
  }
}
```

produces the following Linked Service on ADF:

```json
{
    "name": "SqlServerLinkedSvc",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "annotations": [],
        "type": "SqlServer",
        "typeProperties": {
            "connectionString": "Integrated Security=False;Data Source=test;Initial Catalog=test;User ID=test;",
            "password": {
                "type": "AzureKeyVaultSecret",
                "store": {
                    "referenceName": "KeyVaultLinkedSvc",
                    "type": "LinkedServiceReference"
                },
                "secretName": "MySecret"
            }
        }
    }
}
```

2021-01-03 17:27 UTC, katbyte requested changes
Thanks @allantargino - one small comment i've left inline and this should be good

2021-01-03 17:27 UTC, katbyte commented on azurerm/internal/services/datafactory/data_factory_linked_service_sql_server_resource.go
> +		if keyVaultPassword, ok := properties.Password.AsAzureKeyVaultSecretReference(); ok {
We'll need to nic check password here

2021-01-06 16:35 UTC, allantargino commented on azurerm/internal/services/datafactory/data_factory_linked_service_sql_server_resource.go
> +		if keyVaultPassword, ok := properties.Password.AsAzureKeyVaultSecretReference(); ok {
Done @katbyte

2021-01-12 15:26 UTC, allantargino commented
Hi @katbyte, following the refactor from #10114, I refactored this PR and solved conflicts with master.

2021-01-13 05:24 UTC, katbyte approved these changes
Thanks @allantargino - LGTM 👍

2021-01-13 05:24 UTC, merged