New Resource: azurerm_security_center_assessment_metadata
terraform-providers/terraform-provider-azurerm pull request #10124
Opened 2021-01-11 05:34 UTC by neil-yechenwei

Currently, terraform doesn't support Security.AssessmentMetadata RP. So submitted this PR to implement it.

--- PASS: TestAccSecurityCenterAssessmentMetadata_basic (60.99s)
--- PASS: TestAccSecurityCenterAssessmentMetadata_complete (62.13s)
--- PASS: TestAccSecurityCenterAssessmentMetadata_requiresImport (75.11s)
--- PASS: TestAccSecurityCenterAssessmentMetadata_update (113.53s)

The rest api spec:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/security/resource-manager/Microsoft.Security/stable/2020-01-01/assessmentMetadata.json

2021-01-14 00:53 UTC, katbyte requested changes
We have some test failing:
```
------- Stdout: -------
=== RUN   TestAccSecurityCenterAssessmentMetadata_complete
=== PAUSE TestAccSecurityCenterAssessmentMetadata_complete
=== CONT  TestAccSecurityCenterAssessmentMetadata_complete
    testing.go:745: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: Check failed: "azurerm_security_center_assessment_metadata.test" still exists
        
        State: <no state>
--- FAIL: TestAccSecurityCenterAssessmentMetadata_complete (43.00s)
FAIL

------- Stdout: -------
=== RUN   TestAccSecurityCenterAssessmentMetadata_update
=== PAUSE TestAccSecurityCenterAssessmentMetadata_update
=== CONT  TestAccSecurityCenterAssessmentMetadata_update
    testing.go:684: Step 0 error: Check failed: Check 1/1 error: "azurerm_security_center_assessment_metadata.test" did not exist
--- FAIL: TestAccSecurityCenterAssessmentMetadata_update (22.06s)
FAIL
```

2021-01-14 01:35 UTC, neil-yechenwei commented
@katbyte , After rerun, seems all test cases passed on my local. Maybe rerun can resolve your problem?

$ make testacc TEST=./azurerm/internal/services/securitycenter/ TESTARGS="-parallel 11 -test.run=TestAccSecurityCenterAssessmentMetadata_"
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test ./azurerm/internal/services/securitycenter/ -v -parallel 11 -test.run=TestAccSecurityCenterAssessmentMetadata_ -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccSecurityCenterAssessmentMetadata_basic
=== PAUSE TestAccSecurityCenterAssessmentMetadata_basic
=== RUN   TestAccSecurityCenterAssessmentMetadata_requiresImport
=== PAUSE TestAccSecurityCenterAssessmentMetadata_requiresImport
=== RUN   TestAccSecurityCenterAssessmentMetadata_complete
=== PAUSE TestAccSecurityCenterAssessmentMetadata_complete
=== RUN   TestAccSecurityCenterAssessmentMetadata_update
=== PAUSE TestAccSecurityCenterAssessmentMetadata_update
=== CONT  TestAccSecurityCenterAssessmentMetadata_basic
=== CONT  TestAccSecurityCenterAssessmentMetadata_update
=== CONT  TestAccSecurityCenterAssessmentMetadata_complete
=== CONT  TestAccSecurityCenterAssessmentMetadata_requiresImport
--- PASS: TestAccSecurityCenterAssessmentMetadata_basic (64.15s)
--- PASS: TestAccSecurityCenterAssessmentMetadata_complete (65.74s)
--- PASS: TestAccSecurityCenterAssessmentMetadata_requiresImport (79.13s)
--- PASS: TestAccSecurityCenterAssessmentMetadata_update (116.31s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/securitycenter      121.073s

2021-01-19 00:23 UTC, neil-yechenwei commented
@katbyte , may I ask whether the test cases are passed from your side?

2021-01-27 06:35 UTC, neil-yechenwei commented
@katbyte , Seems test case can pass after rerun.

2021-01-27 12:31 UTC, tombuildsstuff requested changes
hi @neil-yechenwei 

Thanks for this PR - I've taken a look through and left some comments inline - since several of these fields can't be (or don't make sense to be, in the case of the uuid) user specified, it'd be worth rethinking the design here (since we can generate/default values for these as necessary) - but if we can fix those up then we should be able to take another look.

Thanks!

2021-01-28 01:48 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +		if existing.ID != nil && *existing.ID != "" {
updated

2021-01-28 01:57 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +		}
updated

2021-01-28 01:57 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +				threats = append(threats, (string)(item))
updated

2021-01-28 01:58 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +		return fmt.Errorf("deleting Security Center Assessment Metadata %q : %+v", id.AssessmentMetadataName, err)
updated

2021-01-28 01:58 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +		return fmt.Errorf("retrieving Security Center Assessment Metadata %q : %+v", id.AssessmentMetadataName, err)
updated

2021-01-28 01:59 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +			log.Printf("[INFO] security Center Assessment Metadata %q does not exist - removing from state", d.Id())
updated

2021-01-28 02:00 UTC, neil-yechenwei commented on website/docs/r/security_center_assessment_metadata.html.markdown
> +security AssessmentsMetadatums can be imported using the `resource id`, e.g.
updated

2021-01-28 02:05 UTC, neil-yechenwei commented on website/docs/r/security_center_assessment_metadata.html.markdown
> +* `severity` - (Required) The severity level of the Security Center Assessment. Possible values are `Low`, `Medium` and `High`.
updated

2021-01-28 02:08 UTC, neil-yechenwei commented on website/docs/r/security_center_assessment_metadata.html.markdown
> +* `assessment_type` - (Required) The type of the Security Center Assessment which can be specified by user. Possible value is `CustomerManaged`.
I am not sure whether more assessment types would be introduced. So I expose it here. Does it make sense?

2021-01-28 02:09 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +		d.Set("user_impact", props.UserImpact)
updated

2021-01-28 02:09 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +		d.Set("implementation_effort", props.ImplementationEffort)
updated

2021-01-28 02:10 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +		d.Set("assessment_type", props.AssessmentType)
updated

2021-01-28 02:10 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +		d.Set("severity", props.Severity)
updated

2021-01-28 02:10 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +				return fmt.Errorf("checking for present of existing Security Center Assessment Metadata %q : %+v", name, err)
updated

2021-01-28 02:11 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +		return fmt.Errorf("creating/updating Security Center Assessment Metadata %q : %+v", name, err)
updated

2021-01-28 02:51 UTC, neil-yechenwei commented on website/docs/r/security_center_assessment_metadata.html.markdown
> +* `user_impact` - (Optional) The user impact of the Security Center Assessment. Possible values are `Low`, `Moderate` and `High`.
Based on previous testing, there is no default value when this property isn't specified.

2021-01-28 07:03 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +			},
Updated.

2021-01-28 07:03 UTC, neil-yechenwei commented on azurerm/internal/services/securitycenter/security_center_assessment_metadata_resource.go
> +func resourceArmSecurityCenterAssessmentMetadataCreateUpdate(d *schema.ResourceData, meta interface{}) error {
Updated

2021-02-02 11:24 UTC, neil-yechenwei commented on website/docs/r/security_center_assessment_metadata.html.markdown
> +* `is_preview` - (Optional) Is the Security Center Assessment in preview release status?
After confirmed with service team, it's a read-only property.

2021-02-02 12:24 UTC, neil-yechenwei commented
@tombuildsstuff , thanks for your comments. I've updated code. Please have an another look.

2021-02-22 22:32 UTC, katbyte approved these changes
Thanks @neil-yechenwei - this LGTM 👍

2021-02-22 22:32 UTC, merged