`azurerm_data_factory_dataset_delimited_text`: Expose `compression_codec`
terraform-providers/terraform-provider-azurerm pull request #10182
Opened 2021-01-13 20:04 UTC by brunhil

Expose Compression Codec as requested in #9980

2021-01-20 15:50 UTC, manicminer requested changes
Thanks for this @brunhil. There's just one change needed in a test check, otherwise this LGTM.

2021-01-20 15:50 UTC, manicminer commented on azurerm/internal/services/datafactory/data_factory_dataset_delimited_text_resource_test.go
> +				check.That(data.ResourceName).Key("compression_level").HasValue("Optimal"),
`compression_level` is "Fastest" in the config here
```suggestion
				check.That(data.ResourceName).Key("compression_level").HasValue("Fastest"),
```

2021-01-21 18:37 UTC, mbfrahry approved these changes
LGTM!

2021-01-21 18:37 UTC, katbyte commented
linting failure seems spurious, merging

2021-01-21 18:40 UTC, merged