allow permanent delete of log_analytics_workspace_resource
terraform-providers/terraform-provider-azurerm pull request #10235
Opened 2021-01-18 18:09 UTC by lde

Allow permanent delete of log_analytics_workspace_resource without go to recycle bin.

2021-01-18 18:27 UTC, lde commented
refers issue #7282

2021-01-22 03:22 UTC, katbyte requested changes
Hi @lde - thanks for this pr, however due to the way terraform works we can't just put it into the schema. We'll have to add it to the providers feature block like `purge_soft_delete_on_destroy` or `delete_os_disk_on_delete`.

2021-02-12 15:49 UTC, lde commented
Pr updated for use feature block.

2021-02-18 20:13 UTC, katbyte requested changes
thanks @lde, Aside from one comment about the property name this is looking good

2021-02-18 20:13 UTC, katbyte commented on azurerm/internal/provider/features.go
> +					"permanent_delete": {
may i suggest
```suggestion
					"permanently_delete_on_destroy": {
```
or
```suggestion
					"delete_without_recovery": {
```

2021-02-18 20:25 UTC, lde commented
changes applied.

2021-03-04 16:54 UTC, rick-ha commented
hello - what is the status on this? I read that Ide made his changes - is there another underlying issue?

2021-03-05 00:08 UTC, katbyte approved these changes
Thanks @lde - LGTM now 👍

2021-03-05 00:08 UTC, merged