Feature: Azure Data Factory Integration Runtime (Azure + Azure-SSIS)
terraform-providers/terraform-provider-azurerm pull request #10236
Opened 2021-01-18 19:41 UTC by fernandoBRS

## Problem

In Azure Data Factory, it is possible to create 3 types of Integration Runtimes:

- Azure
- Azure-SSIS
- Self-hosted

However, currently Terraform supports only 2 types:

- **Azure-SSIS** through the `azurerm_data_factory_integration_runtime_managed` resource.
- **Self-hosted** through `azurerm_data_factory_integration_runtime_self_hosted` resource.

The purpose of this PR is to add support for **Azure** Integration Runtime.

## Proposal

In order to avoid confusion on describing **Azure** and **Azure-SSIS** IR resources, the following approach was followed:

- The existing `azurerm_data_factory_integration_runtime_managed` was renamed by `azurerm_data_factory_integration_runtime_managed_ssis` to support Azure-SSIS IR.
- The `azurerm_data_factory_integration_runtime_managed` resource was implemented to support Azure IR.

> An important aspect to consider is that Azure and Azure-SSIS IRs have different interfaces for compute properties, making even more sense to split them into two resources.

2021-01-22 03:19 UTC, katbyte requested changes
Hi @fernandoBRS - thank you for this PR, however this would be a breaking change for users of the existing resource. Instead of changing the behaviour of it could we perhapes deprecate it and copy its functionality to `azurerm_data_factory_integration_runtime_azure_ssis` and create a new one `azurerm_data_factory_integration_runtime_azure` ?

2021-01-26 12:35 UTC, fernandoBRS commented
Great suggestions @katbyte! I'll be working on these changes.

2021-01-28 13:48 UTC, fernandoBRS commented
@katbyte I made the suggested changes. Now we have two new resources:

- `azurerm_data_factory_integration_runtime_azure` for Azure Integration Runtime
- `azurerm_data_factory_integration_runtime_azure_ssis` for Azure-SSIS Integration Runtime

The `azurerm_data_factory_integration_runtime_managed` was marked as deprecated in the doc, with recommendations for `azurerm_data_factory_integration_runtime_azure_ssis` usage for new deployments.

2021-02-11 03:02 UTC, katbyte requested changes
Thanks @fernandoBRS - aside from a few comments this looks good. Once they are addressed this should be good to merge!

Also we'll need to update with master to fix the build:
```
[Step 4/5] ./data_factory_integration_runtime_azure_resource.go:56:19: undefined: "github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/validate".DataFactoryName
[02:58:23]	[Step 4/5] ./data_factory_integration_runtime_azure_ssis_resource.go:56:19: undefined: "github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/validate".DataFactoryName
[02:58:23]	[Step 4/5] Process exited with code 2
```

2021-02-11 14:25 UTC, fernandoBRS commented on azurerm/internal/services/datafactory/data_factory_integration_runtime_azure_resource.go
> +			"time_to_live": {
Sure, I changed it and updated the documentation as well to reflect the property name.

2021-02-11 14:27 UTC, fernandoBRS commented on azurerm/internal/services/datafactory/data_factory_integration_runtime_azure_ssis_resource_test.go
> +func TestAccDataFactoryIntegrationRuntimeManagedSsis_customSetupScript(t *testing.T) {
Yes, I created a `TestAccDataFactoryIntegrationRuntimeManagedSsis_complete` function that combines the tests for VNet integration, custom scripts and catalog info. Way easier, thanks for the suggestion!

2021-02-11 14:28 UTC, fernandoBRS commented on azurerm/internal/services/datafactory/data_factory_integration_runtime_azure_ssis_resource_test.go
> +func TestAccDataFactoryIntegrationRuntimeManagedSsis_basic(t *testing.T) {
I've updated the `basic` test to validate all required properties and created  `complete` test.

2021-02-11 18:09 UTC, katbyte approved these changes
Thanks @fernandoBRS - LGTM 👍

2021-02-11 18:09 UTC, merged