Adding new `application_gateway` data_source
terraform-providers/terraform-provider-azurerm pull request #10268
Opened 2021-01-21 11:57 UTC by petems

Closes https://github.com/terraform-providers/terraform-provider-azurerm/issues/5030

Draft for now, as I want to make sure I'm making the data_source correctly, after that I'll add the rest of the attributes

2021-01-21 17:25 UTC, tombuildsstuff requested changes
hey @petems

Thanks for opening this PR.

I've taken a look through and this is off to a good start - I've taken a look through and left some comments inline, as mentioned offline this'll need to be registered here to be usable in the provider: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/network/registration.go#L24

Thanks!

2021-01-22 02:45 UTC, petems commented on azurerm/internal/services/network/registration.go
> +		"azurerm_application_gateway":                       dataSourceApplicationGateway(),
@tombuildsstuff Is this correct?

2021-01-22 02:45 UTC, petems commented on azurerm/internal/services/network/application_gateway_data_source_test.go
> +`, AppGatewayDataSource{}.complete(data))
Done! 👍

2021-01-22 02:46 UTC, petems commented on azurerm/internal/services/network/application_gateway_data_source.go
> +	d.Set("resource_group_name", resourceGroup)
Good point, fixed

2021-01-22 02:56 UTC, petems commented
I've pulled most of the logic from the resource, so there's a lot of duplicted code here, is there value in refactoring this into a shared librariy? If so, is there an example out there?

2021-01-23 02:39 UTC, katbyte commented on azurerm/internal/services/network/registration.go
> +		"azurerm_application_gateway":                       dataSourceApplicationGateway(),
Yep this is!

2021-01-23 02:40 UTC, katbyte commented
@petems - we're going to need to flip all the properties to computed as this is a data source

2021-02-05 18:02 UTC, tombuildsstuff requested changes
hey @petems 

Thanks for pushing those changes - I've taken a look through and left some comments inline, if we can get those sorted (and subsequently add/generate some documentation, there's details on how to generate that in the readme) - then we should be able to run the tests here 👍 

Thanks!

2021-02-05 18:02 UTC, tombuildsstuff commented on azurerm/internal/services/network/application_gateway_data_source.go
> +	d.Set("zones", applicationGateway.Zones)
this data source only defines `name, location, resource_group_name, tags` above, these other fields don't exist (so will raise an error) - can we remove them, or add the additional fields to the schema?

2021-02-05 18:02 UTC, tombuildsstuff commented on azurerm/internal/services/network/application_gateway_data_source_test.go
> +`, AppGatewayResource{}.basic(data))
sorry, my bad - the type name for this is

```suggestion
`, ApplicationGatewayResource{}.basic(data))
```

2021-02-16 10:58 UTC, tombuildsstuff commented
Tests look good 👍

2021-02-16 10:59 UTC, merged