Add certificate_data_base64 field to key_vault_certificate
terraform-providers/terraform-provider-azurerm pull request #10275
Opened 2021-01-22 00:53 UTC by hazzik

Fixes #8072

2021-01-25 22:24 UTC, manicminer requested changes
Hi @hazzik, thanks for this PR. There is a related PR at https://github.com/hashicorp/terraform-provider-azuread/pull/386 which also solves this, however I believe it will still be useful to export the base64 encoded certificate data here since it can be used anywhere else in Terraform configuration. Related to this, I think we should keep the existing attribute (and not deprecate it) since it's likely used by some users in contexts we're not aware of.

2021-01-25 22:24 UTC, manicminer commented on azurerm/internal/services/keyvault/key_vault_certificate_data_source.go
> +				Deprecated: "Deprecated in favour of `certificate_data_base64`",
```suggestion
```

2021-01-25 22:24 UTC, manicminer commented on azurerm/internal/services/keyvault/key_vault_certificate_resource.go
> +				Deprecated: "Deprecated in favour of `certificate_data_base64`",
```suggestion
```

2021-01-25 22:24 UTC, manicminer commented on website/docs/d/key_vault_certificate.html.markdown
> +* `certificate_data` - (**Deprecated in favour of `certificate_data_base64`**) The raw Key Vault Certificate data represented as a hexadecimal string.
```suggestion
* `certificate_data` - The raw Key Vault Certificate data represented as a hexadecimal string.
```

2021-01-25 22:24 UTC, manicminer commented on website/docs/r/key_vault_certificate.html.markdown
> +* `certificate_data` - (**Deprecated in favour of `certificate_data_base64`**) The raw Key Vault Certificate data represented as a hexadecimal string.
```suggestion
* `certificate_data` - The raw Key Vault Certificate data represented as a hexadecimal string.
```

2021-01-25 23:14 UTC, hazzik commented
Thanks @manicminer for the review. I'll remove depreciation.

>There is a related PR at hashicorp/terraform-provider-azuread#386 which also solves this

Unfortunately I'm using the certificate not in `azuread` provider, but in `azurerm_application_gateway` resource (so it is #8482).

2021-01-25 23:23 UTC, hazzik commented
@manicminer changes applied.

2021-01-26 00:03 UTC, manicminer approved these changes
Thanks @hazzik, this LGTM

2021-01-26 11:28 UTC, manicminer commented
Test results

![Screenshot 2021-01-26 at 11 28 20](https://user-images.githubusercontent.com/251987/105839576-9fdc1d00-5fc9-11eb-9ea1-dc303f94a227.png)

2021-01-26 11:29 UTC, merged