azurerm_cosmosdb_account: Fix submitted key_vault_key_id values
terraform-providers/terraform-provider-azurerm pull request #10420
Opened 2021-02-02 02:56 UTC by tism

Fixes #10379 by removing the doubled `//` (left the trailing `/` on `KeyVaultBaseUrl`) and using a versionless ID for `azurerm_cosmosdb_account.key_vault_key_id`. Not sure how well `LatestVersionID` fits into the `NewxxID()`/`ID()` parse package pattern.

2021-02-03 12:22 UTC, tombuildsstuff requested changes
hey @tism 

Thanks for this PR - I've taken a look through and left some comments inline. On the whole this looks pretty good, but in retrospect perhaps we're being slightly misleading with the `key_vault_key_id` field, if we're requiring a versionless ID for the Key Vault Key, it'd be worth updating validation for this field to require this, rather than throwing away the version (and showing it in the plan) - WDYT?

Thanks!

2021-02-04 00:41 UTC, tism commented on azurerm/internal/services/keyvault/parse/nested_item.go
> +}
I like that, it makes the interface a lot clearer and the resource isn't making changes to the value under the covers.

2021-02-04 00:42 UTC, tism commented on azurerm/internal/services/keyvault/parse/nested_item.go
> +	return formatID([]string{strings.TrimSuffix(n.KeyVaultBaseUrl, "/"), n.NestedItemType, n.Name, n.Version})
👍 That'll also highlight if the struct was somehow populated incorrectly with missing values like name

2021-02-04 05:05 UTC, tism commented
While running the key vault acceptance tests I couldn't get it to stop trying to purge the soft deleted keys, so anything that uses `key_vault_uri` will leave dangling vaults. I thought `purge_soft_delete_on_destroy = false` would be enough to let the vault destroy pass buy it still fails when running `keyvault.BaseClient#PurgeDeletedKey`

2021-02-04 07:29 UTC, tombuildsstuff commented
> I thought purge_soft_delete_on_destroy = false would be enough to let the vault destroy pass and that is fine locally. Is there something different about how the acceptance tests are run?

This'll be due to a bug in the Plugin SDK where at this time the test framework doesn't honour the `provider` blocks - it's something we're working to fix - for the moment if this leaves some dangling resources during test cleanup this is fine, as they'll be caught by our Dalek (cleanup script).

2021-02-10 20:22 UTC, katbyte approved these changes
Thanks @tism - LGTM 👍

2021-02-10 20:27 UTC, merged