Support for Secure Webhook Receiver in `azurerm_monitor_action_group`
terraform-providers/terraform-provider-azurerm pull request #10509
Opened 2021-02-09 08:19 UTC by yupwei68

2021-02-11 03:44 UTC, katbyte requested changes
Thanks @yupwei68 - left a comment about the schema inline

2021-02-11 03:44 UTC, katbyte commented on azurerm/internal/services/monitor/monitor_action_group_resource.go
> +						"aad_auth_tenant_id": {
could we put this in a block?
```
aad_auth {
  enabled = true
  tenant_id = 1234
  object_id = 1234
  identifier_uri = url
}
```

2021-02-18 06:25 UTC, yupwei68 commented
Thanks @katbyte for comments. Changes have been pushed. Please continue reviewing.

2021-03-04 03:07 UTC, yupwei68 commented
@katbyte I've added the acctest. Please continue reviewing.
=== RUN   TestAccMonitorActionGroup_secureWebhookReceiver
=== PAUSE TestAccMonitorActionGroup_secureWebhookReceiver
=== CONT  TestAccMonitorActionGroup_secureWebhookReceiver
--- PASS: TestAccMonitorActionGroup_secureWebhookReceiver (287.65s)

2021-03-04 03:21 UTC, manicminer commented on azurerm/internal/services/monitor/monitor_action_group_resource.go
> +	if !*receiver.UseAadAuth {
We should add a nil check here to avoid a crash

2021-03-04 17:06 UTC, tombuildsstuff requested changes
hey @yupwei68 

Thanks for pushing those changes - I've taken a look through and left some comments inline but if we can fix those up then this should otherwise be good to go 👍 

Thanks!

2021-03-04 17:06 UTC, tombuildsstuff commented on azurerm/internal/services/monitor/monitor_action_group_resource.go
> +			receiver.TenantID = utils.String(secureWebhook["tenant_id"].(string))
this should default to the current tenant id if it's left unspecified e.g.

```suggestion
			if v := secureWebhook["tenant_id"].(string); v != "" {
				receiver.TenantID = utils.String(v)
			} else {
				tenantId := meta.(*clients.Client).Account.TenantID
				receiver.TenantID = utils.String(tenantId)
			}
```

2021-03-04 17:06 UTC, tombuildsstuff commented on website/docs/r/monitor_action_group.html.markdown
> +~> **NOTE:** Before adding a secure webhook receiver by setting `aad_auth`, please read [the configuration instruction of the AAD application](https://docs.microsoft.com/en-us/azure/azure-monitor/pla
```suggestion

~> **NOTE:** Before adding a secure webhook receiver by setting `aad_auth`, please read [the configuration instruction of the AAD application](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/action-groups#secure-webhook). 
```

2021-03-04 17:06 UTC, tombuildsstuff commented on azurerm/internal/services/monitor/monitor_action_group_resource.go
> +				"aad_auth":                flattenMonitorActionGroupSecureWebHookReceiver(&receiver),
there's no need to pass in a pointer here:

```suggestion
				"aad_auth":                flattenMonitorActionGroupSecureWebHookReceiver(receiver),
```

2021-03-04 17:06 UTC, tombuildsstuff commented on azurerm/internal/services/monitor/monitor_action_group_resource.go
> +func flattenMonitorActionGroupSecureWebHookReceiver(receiver *insights.WebhookReceiver) []interface{} {
there's no need for this to be a pointer here?

```suggestion
func flattenMonitorActionGroupSecureWebHookReceiver(receiver insights.WebhookReceiver) []interface{} {
```

2021-03-05 01:55 UTC, yupwei68 commented
Thanks Tom for your comments. Changes have been updated. Please continue reviewing.

2021-03-05 03:16 UTC, yupwei68 commented
=== RUN   TestAccMonitorActionGroup_secureWebhookReceiver
=== PAUSE TestAccMonitorActionGroup_secureWebhookReceiver
=== CONT  TestAccMonitorActionGroup_secureWebhookReceiver
--- PASS: TestAccMonitorActionGroup_secureWebhookReceiver (281.84s)

Test has passed.

2021-03-05 03:23 UTC, katbyte approved these changes
Thanks @yupwei68 - LGTM 👍

2021-03-05 03:23 UTC, merged

2021-03-05 11:07 UTC, alastairtree commented
FYI I looks like something in this change may have broken data.azurerm_monitor_action_group as suddenly our deploys have broken once they upgraded to using 2.50. The error looks like below. Will do some investigation and will create an issue if required.

```
Error setting `webhook_receiver`: Invalid address to set: []string{"webhook_receiver", "0", "aad_auth"} 
```

2021-03-08 01:45 UTC, yupwei68 commented
@alastairtree Unfortunately, I could not reproduce your error. I've created a webhook at version 2.49.0, and then update this at 2.50.0. They are applied successfully. Would you create an issue for this, with the details of reproducing steps and you've created the `azurerm_monitor_action_group` based on which version?

2021-03-08 09:07 UTC, alastairtree commented
It is the data source that's broken not the resource. See #10854

2021-03-08 11:24 UTC, marioanton commented
Same here, this is breaking the retrieval/refresh of action groups with webhooks not configured as securewebhooks.

2021-03-08 11:28 UTC, manicminer commented
There's a fix for this incoming in #10876