`azurerm_kubernetes_cluster`: Expose `auto_upgrade_channel`
terraform-providers/terraform-provider-azurerm pull request #10530
Opened 2021-02-10 20:32 UTC by brunhil

Fixes #10407 

=== RUN   TestAccKubernetesCluster_upgradeChannel
=== PAUSE TestAccKubernetesCluster_upgradeChannel
=== CONT  TestAccKubernetesCluster_upgradeChannel
--- PASS: TestAccKubernetesCluster_upgradeChannel (824.85s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers  828.691s

2021-02-10 23:50 UTC, shapeofarchitect approved these changes

2021-02-11 06:16 UTC, katbyte requested changes

2021-02-11 06:16 UTC, katbyte commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +			"auto_upgrade_channel": {
would this make more sense as
```suggestion
			"automatic_channel_upgrade": {
```

2021-02-11 08:33 UTC, shapeofarchitect commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +			"auto_upgrade_channel": {
yes agree - makes more sense.

2021-02-16 09:17 UTC, tombuildsstuff approved these changes
hey @brunhil 

Thanks for pushing those changes.

Taking a look through on the whole this looks pretty good - but we should remove the `none` option here in favour of inferring that when the field is omitted (since this is Optional and will be unset by default). Since this otherwise looks good and I've got a few other Kubernetes PR's to get in today, I hope you don't mind but I'm going to push a commit to fix up the comments so that we can get this merged.

Thanks!

2021-02-16 09:26 UTC, jackofallops approved these changes
Thanks @brunhil & @tombuildsstuff - LGTM 👍

2021-02-16 10:18 UTC, tombuildsstuff commented
The basicVMSS and Upgrade Channel tests look good:

```
$ TF_ACC=1 go test -v ./azurerm/internal/services/containers -run=TestAccKubernetesCluster_upgradeChannel -timeout=60m
=== RUN   TestAccKubernetesCluster_upgradeChannel
=== PAUSE TestAccKubernetesCluster_upgradeChannel
=== CONT  TestAccKubernetesCluster_upgradeChannel
--- PASS: TestAccKubernetesCluster_upgradeChannel (1045.71s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers	1045.774s
```

2021-02-16 10:19 UTC, merged