azurerm_data_factory_linked_service_azure_blob_storage: various enhancements
terraform-providers/terraform-provider-azurerm pull request #10551
Opened 2021-02-11 15:22 UTC by favoretti

Add support for SAS URI, Managed Identity and Service Principle auth

Fixes #10532

2021-02-11 15:25 UTC, favoretti commented
```
$ TF_ACC=1 go test -v ./azurerm/internal/services/datafactory -timeout=1000m -run=TestAccDataFactoryLinkedServiceAzureBlobStorage_sas_uri
=== RUN   TestAccDataFactoryLinkedServiceAzureBlobStorage_sas_uri
=== PAUSE TestAccDataFactoryLinkedServiceAzureBlobStorage_sas_uri
=== CONT  TestAccDataFactoryLinkedServiceAzureBlobStorage_sas_uri
--- PASS: TestAccDataFactoryLinkedServiceAzureBlobStorage_sas_uri (115.94s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/datafactory	117.954s

$ TF_ACC=1 go test -v ./azurerm/internal/services/datafactory -timeout=1000m -run=TestAccDataFactoryLinkedServiceAzureBlobStorage_managed_id
=== RUN   TestAccDataFactoryLinkedServiceAzureBlobStorage_managed_id
=== PAUSE TestAccDataFactoryLinkedServiceAzureBlobStorage_managed_id
=== CONT  TestAccDataFactoryLinkedServiceAzureBlobStorage_managed_id
--- PASS: TestAccDataFactoryLinkedServiceAzureBlobStorage_managed_id (110.85s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/datafactory	112.404s

$ TF_ACC=1 go test -v ./azurerm/internal/services/datafactory -timeout=1000m -run=TestAccDataFactoryLinkedServiceAzureBlobStorage_basic
=== RUN   TestAccDataFactoryLinkedServiceAzureBlobStorage_basic
=== PAUSE TestAccDataFactoryLinkedServiceAzureBlobStorage_basic
=== CONT  TestAccDataFactoryLinkedServiceAzureBlobStorage_basic
--- PASS: TestAccDataFactoryLinkedServiceAzureBlobStorage_basic (106.82s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/datafactory	108.743s
```

2021-02-24 15:53 UTC, jackofallops requested changes
Hi @favoretti - Thanks for this PR, it's off to a good start. I've made some suggestions on how the schema could be made more easily read; and there's a couple of crashes that need to be addressed.  If you can address those, I'll continue review and get the tests run. 

Thanks again!

2021-02-24 15:53 UTC, jackofallops commented on azurerm/internal/services/datafactory/data_factory_linked_service_azure_blob_storage_resource.go
> +				AtLeastOneOf:  []string{"service_principal_key", "service_principal_id", "use_managed_identity", "connection_string", "sas_uri"},
This I think can be simplified to:
```suggestion
				ExactlyOneOf:  []string{"service_principal_id", "use_managed_identity"},
```

2021-02-24 15:53 UTC, jackofallops commented on azurerm/internal/services/datafactory/data_factory_linked_service_azure_blob_storage_resource.go
> +				AtLeastOneOf:  []string{"service_principal_key", "service_principal_id", "use_managed_identity", "connection_string", "sas_uri"},
As per `use_managed_identity` above.

2021-02-24 15:53 UTC, jackofallops commented on azurerm/internal/services/datafactory/data_factory_linked_service_azure_blob_storage_resource.go
> +				AtLeastOneOf:  []string{"service_principal_key", "service_principal_id", "use_managed_identity", "connection_string", "sas_uri"},
I think with the other guards above, this can be removed.
```suggestion
```

2021-02-24 15:53 UTC, jackofallops commented on azurerm/internal/services/datafactory/data_factory_linked_service_azure_blob_storage_resource.go
> +			"tenant": {
Assuming this is the Tenant GUID, can we rename to `tenant_id` to keep consistent with the rest of the provider?

2021-02-24 15:53 UTC, jackofallops commented on azurerm/internal/services/datafactory/data_factory_linked_service_azure_blob_storage_resource.go
> +
We'll need to nil check `blobStorage.AzureBlobStorageLinkedServiceTypeProperties` before trying to access `Tenant` / `ServicePrincipalID` etc or these could cause crashes.

2021-02-24 18:15 UTC, favoretti commented
@jackofallops Thank you for your review. Feedback addressed.

2021-02-25 16:32 UTC, jackofallops commented
Tests looking good:
![image](https://user-images.githubusercontent.com/11830746/109184583-0d28cc80-7787-11eb-96e4-c7d5dc165981.png)

2021-02-25 16:33 UTC, jackofallops approved these changes

2021-02-25 16:43 UTC, merged