add network_profile to virtual_machine_scale_set data
terraform-providers/terraform-provider-azurerm pull request #10585
Opened 2021-02-15 02:21 UTC by shurikk

Knowing scale set `network_profile` is important when creating load balancers as a separate process/state because the scale set and the load balancer must be on the same virtual network.

2021-04-15 03:40 UTC, katbyte requested changes
Thanks for the pr @shurikk - could we update the docs to reflect this new property? thanks

2021-04-15 04:30 UTC, shurikk commented
yes, will do, was planning to but got distracted

2021-04-26 18:47 UTC, katbyte requested changes
Thanks @shurikk - overall this looks good but instead of referring to the schema in another resource could we pull that out? I think the new windows|linux virtual resources already have done that so you should be able to use `"network_interface": VirtualMachineScaleSetNetworkInterfaceSchema(),`

2021-04-26 18:47 UTC, katbyte commented on azurerm/internal/services/compute/virtual_machine_scale_set_data_source.go
> +		Elem:     resourceVirtualMachineScaleSet().Schema["network_profile"].Elem,
We should pull that out into a shared schema function instead of doing this

2021-04-26 18:47 UTC, katbyte commented on azurerm/internal/services/compute/virtual_machine_scale_set_data_source.go
> +			"network_profile": schemaNetworkProfileForDataSource(),
which would make this
```suggestion
			"network_interface": VirtualMachineScaleSetNetworkInterfaceSchema(),
```

2021-04-26 21:48 UTC, shurikk commented
@katbyte just to be on the same page, we want this change to be aligned with `linux_virtual_machine_scale_set` and `windows_virtual_machine_scale_set` rather than `virtual_machine_scale_set`? If yes, then the docs should be updated as well

2021-04-27 00:55 UTC, katbyte commented
@shurikk - correct, those are the new resources that will replace the old `virtual_machine_scale_set`. they share the `VirtualMachineScaleSetNetworkInterfaceSchema` so it should be fine to add this to the `virtual_machine_scale_set` data source

2021-04-27 02:01 UTC, shurikk commented
@katbyte updated, still need `schemaNetworkInterfaceForDataSource` to set `Computed: true`, cannot use `VirtualMachineScaleSetNetworkInterfaceSchema()` directly without that

2021-04-27 02:39 UTC, katbyte commented
oh right 🤦‍♀️🤦‍♀️ sorry i totally blanked on this, this is a datasource so we need to have everything be computed, which means copying that function's schema and changing everything to be computed

2021-04-27 16:19 UTC, shurikk commented
@katbyte how should we proceed from here? I've updated docs and the code to be aligned with `linux` and `windows` scale sets.

2021-04-27 17:54 UTC, shurikk commented
config

```
data azurerm_virtual_machine_scale_set vmss {
  name                = "test-vmss"
  resource_group_name = "test"
}

output x { 
  value = data.azurerm_virtual_machine_scale_set.vmss
}
```

terraform output

```
x = {
  "id" = "/subscriptions/.../.../Microsoft.Compute/virtualMachineScaleSets/test-vmss"
  "identity" = tolist([])
  "location" = tostring(null)
  "name" = "test-vmss"
  "network_interface" = tolist([
    {
      "dns_servers" = tolist([])
      "enable_accelerated_networking" = true
      "enable_ip_forwarding" = false
      "ip_configuration" = tolist([
        {
          "application_gateway_backend_address_pool_ids" = toset([])
          "application_security_group_ids" = toset([])
          "load_balancer_backend_address_pool_ids" = toset([
            "/subscriptions/.../.../backendAddressPools/test-lb",
          ])
          "load_balancer_inbound_nat_rules_ids" = toset([])
          "name" = "test-vmss"
          "primary" = true
          "public_ip_address" = tolist([])
          "subnet_id" = "/subscriptions/.../.../subnets/subnet12345"
          "version" = "IPv4"
        },
      ])
      "name" = "test-vmss"
      "network_security_group_id" = ""
      "primary" = true
    },
  ])
  "resource_group_name" = "test"
  "timeouts" = null /* object */
}
```

2021-04-27 18:08 UTC, katbyte commented
@shurikk - i hope you don't mind but I just pushed the changes required to get this merged, i'll have someone else review it and get it into this weeks release 🙂

2021-04-27 19:08 UTC, shurikk commented
> @shurikk - i hope you don't mind but I just pushed the changes required to get this merged, i'll have someone else review it and get it into this weeks release 🙂

thanks, works, it's not super urgent. also noticed some doc updates, still work in progress?

2021-04-27 22:01 UTC, WodansSon approved these changes
@katbyte, thank you for this PR... I left one super minor comment and there are a few lint errors. Other than that this LGTM! 🚀

2021-04-27 22:01 UTC, WodansSon commented on azurerm/internal/services/compute/virtual_machine_scale_set_data_source.go
> +		return fmt.Errorf("[DEBUG] Error setting `identity`: %+v", err)
```suggestion
		return fmt.Errorf("setting `identity`: %+v", err)
```

2021-04-27 23:53 UTC, manicminer approved these changes
LGTM! 🚀

2021-04-28 21:21 UTC, merged

2021-05-14 07:31 UTC, magodo reviewed
Shall we change the schemas above to be `Computed: true`?

2021-05-14 07:31 UTC, magodo commented on azurerm/internal/services/compute/virtual_machine_scale_set.go
> +		Required: true,
Should we change this to `Computed: true`?

2021-05-14 07:31 UTC, magodo commented on azurerm/internal/services/compute/virtual_machine_scale_set.go
> +		Optional: true,
Should we change this to `Computed: true`?