dns_zone: Compute resourceId from the parser, add state migration
terraform-providers/terraform-provider-azurerm pull request #10786
Opened 2021-03-02 09:52 UTC by favoretti

2021-03-02 11:26 UTC, favoretti commented
Complete output is not included, due to DEBUG logging, but complete suite passed.

```
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/dns	687.482s
```

2021-03-03 07:22 UTC, tombuildsstuff requested changes
hey @favoretti 

Thanks for pushing those changes - taking a look through on the whole this looks pretty good, but we should be able to remove the redundant `Get` call since we're not using that result as we're creating the ID's here - but if we can fix those up this should otherwise be good to merge 👍 

Thanks!

2021-03-03 07:22 UTC, tombuildsstuff commented on azurerm/internal/services/dns/dns_a_record_resource.go
>  	}
we can remove this Get call altogether now fwiw

2021-03-03 07:22 UTC, tombuildsstuff commented on azurerm/internal/services/dns/dns_aaaa_record_resource.go
>  	}
(same here) we can remove the redundant Get call here

2021-03-03 07:22 UTC, tombuildsstuff commented on azurerm/internal/services/dns/dns_caa_record_resource.go
>  	}
(same here) we can remove the redundant Get call here

2021-03-03 07:22 UTC, tombuildsstuff commented on azurerm/internal/services/dns/dns_cname_record_resource.go
>  	}
(same here) we can remove the redundant Get call here

2021-03-03 07:22 UTC, tombuildsstuff commented on azurerm/internal/services/dns/dns_mx_record_resource.go
>  	}
(same here) we can remove the redundant Get call here

2021-03-03 07:22 UTC, tombuildsstuff commented on azurerm/internal/services/dns/dns_ns_record_resource.go
>  	}
(same here) we can remove the redundant Get call here

2021-03-03 07:22 UTC, tombuildsstuff commented on azurerm/internal/services/dns/dns_ptr_record_resource.go
>  	}
(same here) we can remove the redundant Get call here

2021-03-03 07:22 UTC, tombuildsstuff commented on azurerm/internal/services/dns/dns_srv_record_resource.go
>  	}
(same here) we can remove the redundant Get call here

2021-03-03 07:22 UTC, tombuildsstuff commented on azurerm/internal/services/dns/dns_txt_record_resource.go
>  	}
(same here) we can remove the redundant Get call here

2021-03-03 07:22 UTC, tombuildsstuff commented on azurerm/internal/services/dns/dns_zone_resource.go
>  	}
(same here) we can remove the redundant Get call here

2021-03-03 07:35 UTC, favoretti commented
> hey @favoretti 
> 
> 
> 
> Thanks for pushing those changes - taking a look through on the whole this looks pretty good, but we should be able to remove the redundant `Get` call since we're not using that result as we're creating the ID's here - but if we can fix those up this should otherwise be good to merge 👍 
> 
> 
> 
> Thanks!

Ah, I thought that one served as additional creation verification :)

2021-03-04 18:13 UTC, tombuildsstuff approved these changes
LGTM 👍

2021-03-05 00:18 UTC, merged