`*_virtual_machine_scale_set`: Do not force recreation on `rolling_upgrade_policy` update.
terraform-providers/terraform-provider-azurerm pull request #10856
Opened 2021-03-05 13:14 UTC by favoretti

Fixes #10851

2021-03-08 08:20 UTC, IamBread commented
Hey @jackofallops, 
Can we get this merged as it's a minor change and fixes crucial configuration issues.
Regards

2021-03-08 15:54 UTC, jackofallops requested changes
Hi @favoretti - Thanks for this PR. It's off to a good start. Could you add tests that cover the update behaviour of these properties now that the can updated in place? 
Thanks!

2021-03-08 17:41 UTC, favoretti commented
@jackofallops certainly, will do so ASAP.

2021-03-10 09:28 UTC, jackofallops requested changes
Hi @favoretti - Thanks for adding the tests, unfortunately it appears the test you've used as the base is actually broken at the destroy stage due to dependency graph not having information to know when to delete the `azurerm_lb_rule` (it's on our list to fix these tests). I've added a suggestion that should allow the tests to pass for now. The same will be needed in the Windows test.

I didn't see a test for updating `health_probe_id`, could you add that also? 

Thanks!

2021-03-10 09:28 UTC, jackofallops commented on azurerm/internal/services/compute/linux_virtual_machine_scale_set_other_resource_test.go
> +}
I think this will allow the test to pass:
```suggestion

  depends_on = [azurerm_lb_rule.test]
}
```

2021-03-10 11:57 UTC, favoretti commented
```
$ make acctests SERVICE='compute' TESTARGS='-run=.*Linux.*otherHealthProbeUpdate' TESTTIMEOUT='600m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/compute -run=.*Linux.*otherHealthProbeUpdate -timeout 600m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/03/10 11:07:51 [DEBUG] not using binary driver name, it's no longer needed
2021/03/10 11:07:51 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccLinuxVirtualMachineScaleSet_otherHealthProbeUpdate
=== PAUSE TestAccLinuxVirtualMachineScaleSet_otherHealthProbeUpdate
=== CONT  TestAccLinuxVirtualMachineScaleSet_otherHealthProbeUpdate
--- PASS: TestAccLinuxVirtualMachineScaleSet_otherHealthProbeUpdate (486.56s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute	488.121s
```

```
$ make acctests SERVICE='compute' TESTARGS='-run=TestAccLinuxVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate' TESTTIMEOUT='600m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/compute -run=TestAccLinuxVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate -timeout 600m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/03/10 12:40:24 [DEBUG] not using binary driver name, it's no longer needed
2021/03/10 12:40:24 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccLinuxVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate
=== PAUSE TestAccLinuxVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate
=== CONT  TestAccLinuxVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate
--- PASS: TestAccLinuxVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate (615.53s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute	616.872s
```

I _assume_ windows tests would work too... Haven't ran them though, sorry.

2021-03-10 12:55 UTC, favoretti commented
```
$ make acctests SERVICE='compute' TESTARGS='-run=.*Windows.*otherHealthProbeUpdate' TESTTIMEOUT='600m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/compute -run=.*Windows.*otherHealthProbeUpdate -timeout 600m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/03/10 13:25:26 [DEBUG] not using binary driver name, it's no longer needed
2021/03/10 13:25:26 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccWindowsVirtualMachineScaleSet_otherHealthProbeUpdate
=== PAUSE TestAccWindowsVirtualMachineScaleSet_otherHealthProbeUpdate
=== CONT  TestAccWindowsVirtualMachineScaleSet_otherHealthProbeUpdate
--- PASS: TestAccWindowsVirtualMachineScaleSet_otherHealthProbeUpdate (566.97s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute	568.404s
```

2021-03-10 13:42 UTC, favoretti commented
```
$ make acctests SERVICE='compute' TESTARGS='-run=TestAccWindowsVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate' TESTTIMEOUT='600m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/compute -run=TestAccWindowsVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate -timeout 600m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/03/10 14:29:06 [DEBUG] not using binary driver name, it's no longer needed
2021/03/10 14:29:06 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccWindowsVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate
=== PAUSE TestAccWindowsVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate
=== CONT  TestAccWindowsVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate
--- PASS: TestAccWindowsVirtualMachineScaleSet_otherRollingUpgradePolicyUpdate (742.41s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute	744.236s
```

```
$ make acctests SERVICE='compute' TESTARGS='-run=.*Windows.*otherHealthProbeUpdate' TESTTIMEOUT='600m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/compute -run=.*Windows.*otherHealthProbeUpdate -timeout 600m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/03/10 14:28:58 [DEBUG] not using binary driver name, it's no longer needed
2021/03/10 14:28:58 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccWindowsVirtualMachineScaleSet_otherHealthProbeUpdate
=== PAUSE TestAccWindowsVirtualMachineScaleSet_otherHealthProbeUpdate
=== CONT  TestAccWindowsVirtualMachineScaleSet_otherHealthProbeUpdate
--- PASS: TestAccWindowsVirtualMachineScaleSet_otherHealthProbeUpdate (581.08s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute	582.717s
```

2021-03-10 22:22 UTC, katbyte approved these changes
Thanks @favoretti - LGTM 👍

2021-03-10 22:23 UTC, merged