azurerm_kubernetes_cluster: Allow for any identity type if `private_dns_zone_id` is `None`
terraform-providers/terraform-provider-azurerm pull request #10999
Opened 2021-03-17 11:33 UTC by favoretti

`None` use-case for `private_dns_zone_id` still has no acceptance tests, since it's not trivial to implement, as it implies some "on-prem" DNS that's pre-configured.

Winging this one thus.

Fixes #10952

2021-03-19 14:22 UTC, tombuildsstuff requested changes
hey @favoretti 

Thanks for this PR, whilst on the whole this looks good - could we reduce this `if` statement since it's getting a harder to parse quickly with each iteration?

Thanks!

2021-03-21 09:58 UTC, favoretti commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +			hasAUserIdentity := !servicePrincipalSet && parameters.Identity.Type != containerservice.ResourceIdentityTypeUserAssigned
Umm, wait a sec, shouldn't this be:
```suggestion
			hasAUserIdentity := !servicePrincipalSet && parameters.Identity.Type != containerservice.ResourceIdentityTypeSystemAssigned
```

2021-04-02 08:44 UTC, favoretti commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +			hasAUserIdentity := !servicePrincipalSet && parameters.Identity.Type != containerservice.ResourceIdentityTypeUserAssigned
Although nevermind, I get it now :)

2021-04-15 18:09 UTC, favoretti commented
Superseded by #11344

2021-04-15 18:09 UTC, closed without merging