fix update issue when using user assigned identity
terraform-providers/terraform-provider-azurerm pull request #10994
Opened 2021-03-17 09:36 UTC by njuCZ

fix #10406

I have asked the aks service team, they say there is no such error in their codebase. The error may be thrown in ARM side or somewhere else.

according to the error message, if we set the value of `identity.UserAssignedIdentities` to empty, everything is ok. I think maybe somewhere the rule is strengthened, the computed value should not exist in the request body

additionally, I refactor the identity part and extract to a new file

2021-03-19 12:05 UTC, tombuildsstuff commented
@njuCZ whilst this does workaround this API design flaw, ultimately this appears to be more of a modelling issue, for example:

https://github.com/Azure/azure-sdk-for-go/blob/52e3b873e1dc1eeb1d64e90754dbdc0d4851bab2/services/containerservice/mgmt/2020-12-01/containerservice/models.go#L1463-L1464
https://github.com/Azure/azure-sdk-for-go/blob/52e3b873e1dc1eeb1d64e90754dbdc0d4851bab2/services/containerservice/mgmt/2020-12-01/containerservice/models.go#L1479-L1485

Should likely be an array of User Assigned Identity ID's, or a list of nested blocks:

```
"identityIds": [
  {
    "id": "0000",
    # optional principal_id and tenant_id
  },
  {
    "id": "1111",
    # optional principal_id and tenant_id
  }
]
```

.. so can we file a Swagger bug about this, since this affects every resource using User Assigned Identities, so is a design flaw the API's which needs to be fixed there (although I can understand why it's been designed this way as a map, it's an odd design) - rather than working around in each consumer of the SDK/each service package in our case.

Thanks!

2021-03-24 05:06 UTC, clarenceb commented
Hi, can this be merged and the design improvements moved to another issue?  It's causing pain for AKS users using the terraform azurerm provider and various workarounds needing to be used.

2021-03-25 08:40 UTC, ducas commented
@tombuildsstuff I agree with @clarenceb. Not having this is preventing us from upgrading clusters using terraform, meaning we need to apply changes with the CLI and then sync state. Needless to say this is quite a pain...

The bug has been open for 7 weeks now so *something* needs to be done. I agree that the solution isn't ideal, but it's how the API works... :shrug:

2021-03-25 09:21 UTC, tombuildsstuff commented
@clarenceb unfortunately this affects *every* resource in Azure that uses a User Assigned Identity - so whilst I can understand the desire to hot fix this in just for AKS, this fix would ultimately need to be applied to every resource.

From our side, we're happy to hot fix this API bug for AKS once a Swagger issue has been opened to track this, as [requested in this comment](https://github.com/terraform-providers/terraform-provider-azurerm/pull/10994#issuecomment-802786650) - but that's waiting on @njuCZ

2021-03-25 09:52 UTC, njuCZ commented
@tombuildsstuff sorry for late response. I just tracked it internaly from email, still no further progress. This is the swagger issue: https://github.com/Azure/azure-rest-api-specs/issues/13631

2021-04-06 09:20 UTC, timja commented
@tombuildsstuff issue is created, see above ^^, a hotfix would be appreciated.

Thanks!

2021-04-20 20:57 UTC, katbyte requested changes
Thanks for the PR @njuCZ but why are we refactoring so much in a bugfix pr? its hard to tell what is going on here and being changed. Could we please remove all refactoring and just include the fix for the issue? thanks

2021-04-21 05:38 UTC, njuCZ commented
@katbyte done

2021-04-24 18:21 UTC, katbyte commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +	normalizeClusterUserAssignedIdentities(&existing)
is there a reason to pull this out into a function could we inline it?

2021-04-25 16:56 UTC, katbyte approved these changes
Thanks @njuCZ - LGTM 👍

2021-04-25 16:57 UTC, merged