*_template_deployment: Fix #8840 Missing parameters error when updating
terraform-providers/terraform-provider-azurerm pull request #11001
Opened 2021-03-17 12:07 UTC by lawrencegripper

Fix #8840 Missing parameters error when updating

Todo:
- [x] Reproduce issue with acc test on resource_group_template_deployment resource
- [x] Fix on resource_group_template_deployment resource
- [ ] Reproduce issue with acc test on subscription_template_deployment
- [ ] Fix on subscription_template_deployment

2021-03-17 12:43 UTC, lawrencegripper commented
Running all the tests for the resource I see the following failure

> === CONT  TestAccSubscriptionTemplateDeployment_withOutputs
    /workspaces/terraform-provider-azurerm/azurerm/internal/services/resource/testing.go:620: Step 1/2 error: Check failed: Check 2/2 error: azurerm_subscription_template_deployment.test: Attribute 'output_content' expected "{\"testOutput\":{\"type\":\"String\"", got "{\"testOutput\":{\"type\":\"String\",\"value\":\"some-value\"}}"
--- FAIL: TestAccSubscriptionTemplateDeployment_withOutputs (100.47s)

This appears to be unrelated to the changes I've made and given the test I'm unsure how it could have ever passed as the expected value isn't what I would expect ARM to return in this instance. It should indeed return a `testOutput` with a value defined as `some-value`.

2021-03-17 17:04 UTC, tombuildsstuff requested changes
hey @lawrencegripper 

Thanks for this PR - taking a look through on the whole this looks pretty good, but I've a feeling we should be pulling this from the API if it's returned, rather than the config - since this'd allow people to use `ignore_changes` on this field if that's necessary - WDYT?

Thanks!

2021-03-17 17:04 UTC, tombuildsstuff commented on azurerm/internal/services/resource/subscription_template_deployment_resource.go
> +	deployment.Properties.Parameters = parameters
(same here) presumably this wants to use the default API value if it's ignored:

```suggestion
	if d.HasChange("parameters_content") {
		parameters, err := expandTemplateDeploymentBody(d.Get("parameters_content").(string))
		if err != nil {
			return fmt.Errorf("expanding `parameters_content`: %+v", err)
		}
		deployment.Properties.Parameters = parameters
	} else {
		deployment.Properties.Parameters = template.Properties.Parameters
	}
```

2021-03-18 11:36 UTC, lawrencegripper commented on azurerm/internal/services/resource/resource_group_template_deployment_resource.go
> +	deployment.Properties.Parameters = parameters
Yeah looks good to me. Let me give this change a test to make 100% sure.

2021-03-18 11:53 UTC, lawrencegripper commented on azurerm/internal/services/resource/resource_group_template_deployment_resource.go
> +	deployment.Properties.Parameters = parameters
Yeah all works as expected. Thanks! 🙏

2021-03-18 12:00 UTC, lawrencegripper commented on azurerm/internal/services/resource/resource_group_template_deployment_resource.go
> +	deployment.Properties.Parameters = parameters
Actually not sure this does work, doing some more tests now.

2021-03-18 12:03 UTC, lawrencegripper commented
Woops messed up my original run with the change to use API response and thought it worked. 

Turns out it fails with

> Error: validating Template Deployment "acctest" (Resource Group "acctestrg-210318115512236865"): requesting validating: resources.DeploymentsClient#Validate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidDeploymentParameterType" Message="The type of deployment parameter 'someParam' should not be specified. Please see https://aka.ms/resource-manager-parameter-files for details."

It looks like the parameters expectation is 

```json
"someParam": { 
    "value": "someValue
}
```

But the returned value from the API call has the `type` field specified

```json
"parameters": {                                                                             
  "disableBgpRoutePropagation": {                                                           
    "type": "Bool",                                                                         
    "value": false                                                                          
  },                                                                                        
  "location": {                                                                             
    "type": "String",                                                                       
    "value": "ukwest"                                                                       
  },                                                                                        
  "name": {                                                                                 
    "type": "String",                                                                       
    "value": "r1"                                                                           
  },                                                                                        
  "tagsByResource": {                                                                       
    "type": "Object",                                                                       
    "value": {}                                                                             
  }                                                                                         
}
 ```

2021-03-18 15:31 UTC, lawrencegripper commented
For the time being I've reverted to the original method always pulling from state.

2021-03-19 11:41 UTC, tombuildsstuff approved these changes
LGTM 👍

2021-03-19 12:28 UTC, merged

2021-03-19 12:28 UTC, tombuildsstuff commented
(Tests look good)