feat: add has_root_access to netapp vol export rules
terraform-providers/terraform-provider-azurerm pull request #11105
Opened 2021-03-25 02:10 UTC by BrendanThompson

This adds the ability to set `has_root_access` on `export_policies`.

2021-03-25 02:55 UTC, BrendanThompson commented
@katbyte @tombuildsstuff – any chance that I could get a review here? Keen to get this merged in ASAP 😃.

2021-03-30 19:11 UTC, katbyte submitted a review, later dismissed
Thanks for the pr @BrendanThompson - aside from one comment about the schema this looks good. Could we change `has_root_access` to `root_access_enabled` to be consistent with the rest of the provider?

2021-03-30 22:06 UTC, BrendanThompson commented
@katbyte I have updated that as requested. Thanks 😊

2021-04-01 03:24 UTC, BrendanThompson commented
@katbyte – sorry I forgot to add this in everywhere -facepalm- I have pushed that change up now.

2021-04-05 09:15 UTC, BrendanThompson commented
@katbyte Will this change actually be released in this Friday's release?

2021-04-08 10:25 UTC, tombuildsstuff requested changes
hey @BrendanThompson 

Thanks for pushing those changes, I've left one comment around the documentation inline but this should otherwise be good to go 👍 

Thanks!

2021-04-08 10:25 UTC, tombuildsstuff commented on website/docs/r/netapp_volume.html.markdown
> +* `allow_root_access` - (Optional) Has root access to the volume?
presumably this should be:

```suggestion
* `allow_root_access` - (Optional) Is root access permitted to this volume?
```

2021-04-08 10:40 UTC, BrendanThompson commented
Hey @tombuildsstuff , thanks for that. I've updated as per the suggestion.

2021-04-08 12:06 UTC, tombuildsstuff approved these changes
LGTM - thanks for pushing that change @BrendanThompson

2021-04-08 12:07 UTC, merged