`azurerm_container_registry` - deprecated `classic` `sku` and `storage_account_id`
terraform-providers/terraform-provider-azurerm pull request #11165
Opened 2021-03-31 04:06 UTC by magodo

The `classic` sku is deprecated by service. The
[document](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-skus) even doesn't show it up. Meanwhile, the service reject this sku for (at least) `PUT` request, (at least) since 2017-10-01 (used by provider v2.0.0).

Since `storage_account_id` is used together with `classic` sku, this proeprty is also useless. Furthermore, this property has been removed in [Swagger](https://github.com/Azure/azure-rest-api-specs/pull/13001).

2021-03-31 19:51 UTC, katbyte requested changes
Thanks @magodo - comments have been left inline

2021-03-31 19:51 UTC, katbyte commented on azurerm/internal/services/containers/container_registry_data_source.go
> -			"storage_account_id": {
someone might be using this in a config so can we just deprecate it for now?

2021-03-31 19:51 UTC, katbyte commented on azurerm/internal/services/containers/container_registry_data_source.go
> -	if account := resp.StorageAccount; account != nil {
and it could be an old account so maybe we should leave this till 3.0 - should be migrated isn't a 100% yes they are all migrated

2021-03-31 19:51 UTC, katbyte commented on azurerm/internal/services/containers/container_registry_resource.go
> -					string(containerregistry.Classic),
this is probably fine if puts where failing, but what if someone had an old one that never udpated?

2021-03-31 19:51 UTC, katbyte commented on azurerm/internal/services/containers/container_registry_resource.go
> -			"storage_account_id": {
same here, i don't see any reason to remove it now instead of deprecating it and removing in 3.0

2021-04-14 09:59 UTC, magodo commented
@katbyte I've label this as a breaking-change now, let's wait until 3.0.

2021-04-14 19:14 UTC, katbyte commented
kk @magodo  - going to close this and we can revisit/reopen when we start 3.0 work

2021-04-14 19:14 UTC, closed without merging