`azurerm_app_service`, `azurerm_app_service_slot`, `azurerm_function_app`: Support for site_config.ip_restrictions.headers / site_config.scm_ip_restrictions.headers
terraform-providers/terraform-provider-azurerm pull request #11209
Opened 2021-04-02 17:46 UTC by aristosvo

Fixes #11156

## Example

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_app_service_plan" "example" {
  name                = "example-appserviceplan"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_app_service" "example" {
  name                = "example-app-service-2191"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  app_service_plan_id = azurerm_app_service_plan.example.id

  site_config {
    dotnet_framework_version = "v4.0"
    scm_type = "None"

    scm_ip_restriction {
        action     = "Allow"
        name       = "test"
        ip_address = "8.8.8.8/32"
        priority   = 100
        headers {
            x_azure_fdid      = ["1"]
            x_fd_health_probe = ["1"]
            x_forwarded_for   = ["test.com"]
            x_forwarded_host  = ["example.com"]
        }
    }
  }

  app_settings = {
    "SOME_KEY" = "some-value"
  }

  connection_string {
    name  = "Database"
    type  = "SQLServer"
    value = "Server=some-server.mydomain.com;Integrated Security=SSPI"
  }
}
```

## Acceptance Tests
- [ ] Not written yet

2021-04-20 13:22 UTC, jackofallops commented on azurerm/internal/services/web/app_service.go
> +							},
Spotted this while passing through, I think this should be:
```suggestion
							"x_fd_health_probe": {
								Type:     schema.TypeSet,
								Optional: true,
								MaxItems: 1,
								Elem: &schema.Schema{
									Type: schema.TypeString,
									ValidateFunc: validation.StringInSlice([]string{
										"1",
									}, false),
								},
							},
```
based on the header description here: https://docs.microsoft.com/en-us/azure/frontdoor/front-door-http-headers-protocol#front-door-to-backend

2021-04-20 18:52 UTC, aristosvo commented
```bash
❯ make acctests SERVICE='web' TESTARGS='-run=TestAccAppService_zeroedIpRestrictionHeaders'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/web -run=TestAccAppService_zeroedIpRestrictionHeaders -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/04/20 20:44:39 [DEBUG] not using binary driver name, it's no longer needed
2021/04/20 20:44:40 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccAppService_zeroedIpRestrictionHeaders
=== PAUSE TestAccAppService_zeroedIpRestrictionHeaders
=== CONT  TestAccAppService_zeroedIpRestrictionHeaders
--- PASS: TestAccAppService_zeroedIpRestrictionHeaders (400.28s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/web     403.909s
```

2021-04-27 13:41 UTC, jackofallops requested changes
Hi @aristosvo - Thanks for the updates!

Could you add in the necessary lint ignores for the Sets with MaxItems (S018 - see the changed files tab), whilst not a fail, this will help us keep the linting clean.

I think it's also worth adding an additional note to the docs for these new properties to ensure users are aware that these headers are combined with the other settings so if used, all items must match for the rule to apply. WDYT? 

Otherwise this LGTM so we should be able to get this merged as soon as this is done. 👍

2021-04-27 14:14 UTC, aristosvo commented
Thanks! Fixed it, will check later today if it complies to all linting.

2021-04-27 21:38 UTC, katbyte approved these changes
Thanks @aristosvo - LGTM 👍

2021-04-27 21:39 UTC, merged