r/(linux|windows)_virtual_machine(_scale_set): support for Force Delete
terraform-providers/terraform-provider-azurerm pull request #11216
Opened 2021-04-06 09:53 UTC by tombuildsstuff

This PR introduces support for the opt-in Force Delete behaviour for the following resources:

* `azurerm_linux_virtual_machine`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_windows_virtual_machine`
* `azurerm_windows_virtual_machine_scale_set`

This functionality is an optional behaviour during the deletion of a Virtual Machine where the machine will be hard powered-off and all devices forcibly removed from the Virtual Machine - which can both improve the shut-down time and work around issues within the Azure API where resources can remain attached to a Virtual Machine during deletion.

Whilst generally speaking that'd make sense to be the default behaviour - unfortunately the API makes this an opt-in behaviour at this point in time and errors if this preview functionality isn't enabled, so this will have to be defaulted off for the moment.

Fixes #11089

2021-04-06 19:42 UTC, mbfrahry reviewed
Hey @tombuildsstuff! I tried running the tests but I'm not sure if these new attributes have been added properly.

```
=== CONT  TestAccWindowsVirtualMachine_otherForceDelete
testing.go:620: Step 1/2 error: Error running pre-apply refresh:
Error: Unsupported argument
on config892966522/terraform_plugin_test.tf line 5, in provider "azurerm":
5:       force_delete = true
An argument named "force_delete" is not expected here.
--- FAIL: TestAccWindowsVirtualMachine_otherForceDelete (6.86s)
```

```
=== CONT  TestAccLinuxVirtualMachine_otherForceDelete
testing.go:620: Step 1/2 error: Error running pre-apply refresh:
Error: Unsupported argument
on config259639429/terraform_plugin_test.tf line 5, in provider "azurerm":
5:       force_delete = true
An argument named "force_delete" is not expected here.
--- FAIL: TestAccLinuxVirtualMachine_otherForceDelete (6.67s)
```

2021-04-06 23:23 UTC, grayzu commented
Also @tombuildsstuff, can you adjust this so that it will skip the Power off all together when Force delete is enabled? If force delete is enabled, the intent is to simply have the VM be deleted without waiting for it to shutdown or power off.

2021-04-08 20:15 UTC, madewithsmiles commented
@tombuildsstuff thanks for the quick turnaround. Please hold off merging this PR if possible. 
I am part of the service team and I am raising a few issues from this PR internally. I/@grayzu will follow up here once things are clear. Thanks.

2021-04-08 20:21 UTC, grayzu commented
@tombuildsstuff, I agree that having separate flags for shutdown and forceDelete makes sense. The ask here is to optimize the ForceDelete so that it aligns with the design intentions.

To explain a bit further, there are three phases that can be configured as part of a VM(SS) delete:
1.  Whether or not to wait for the VM(SS) to shut down as part of the power off.
2.  Whether or not to wait for the VM(SS) to be powered off.
3.  Whether or not to use forceDelete when deleting the VM(SS).

The flag that we have now allows users to skip the shutdown as part of the power off process (no 1 above).  With this flag set, the VM will still be powered off before it is deleted.

The new flag enables forceDelete to be turned on as part of the VM(SS) delete process (no 3 above).

The desire is to have steps 1 & 2 above skipped when forceDelete is turned on so the VM(SS) is not shutdown or powered off, it is just deleted.

So in the end the ask is to have a flag for Shutdown that would allow customers to control wether or not to skip shutdown as part of the power off process and a flag for forceDelete that would short cut the process and go straight to delete the VM(SS).

2021-04-09 05:12 UTC, katbyte approved these changes
LGTM 👍

2021-04-09 06:26 UTC, tombuildsstuff commented
@grayzu 

> So in the end the ask is to have a flag for Shutdown that would allow customers to control wether or not to skip shutdown as part of the power off process and a flag for forceDelete that would short cut the process and go straight to delete the VM(SS).

That's what the latest commit(s) do, there's now 2 flags available:

```
provider "azurerm" {
  features {
    virtual_machine {
      force_delete = true
      shutdown_before_deletion = false
    }
  }
}
```

which will give you that behaviour (skipping shutdown & "force delete") - and allow the inverse (for a shutdown with force delete, to allow the reliability benefits of Force Delete, when that OS disk ultimately needs to be reused, for example via capturing an image of the virtual machine)

2021-04-14 18:16 UTC, grayzu requested changes
Thanks. I have added a couple of comments regarding force delete to ensure that we align with the intended behavior of the new feature.

2021-04-14 18:16 UTC, grayzu commented on azurerm/internal/features/defaults.go
> +			// TODO: this should likely be defaulted true in 3.0
This should not ever default to true. This is a new feature that should be an opt-in for users.

2021-05-13 17:48 UTC, mbfrahry approved these changes
LGTM!

2021-05-20 00:41 UTC, grayzu commented
Thanks @katbyte! Your changes look good to me.

2021-05-26 22:26 UTC, merged