new resource `azurerm_spring_cloud_app_mysql_association`
terraform-providers/terraform-provider-azurerm pull request #11229
Opened 2021-04-07 04:51 UTC by njuCZ

second PR to associate spring cloud app with mysql server

![image](https://user-images.githubusercontent.com/2786738/113812057-f9b64b80-979f-11eb-9e07-f15609064c19.png)

2021-04-07 11:04 UTC, tombuildsstuff requested changes
hi @njuCZ 

Thanks for this PR.

I've taken a look through and left some comments inline but this is off to a good start - if we can fix up the comments then we should be able to take another look.

Thanks!

2021-04-07 11:04 UTC, tombuildsstuff commented on website/docs/r/spring_cloud_app_mysql_association.html.markdown
> +* `delete` - (Defaults to 30 minutes) Used when deleting the Spring Cloud Application Mysql Association.
```suggestion
* `id` - The ID of the Spring Cloud Application MySQL Association.

## Timeouts

The `timeouts` block allows you to specify [timeouts](https://www.terraform.io/docs/configuration/resources.html#timeouts) for certain actions:

* `create` - (Defaults to 30 minutes) Used when creating the Spring Cloud Application MySQL Association.
* `read` - (Defaults to 5 minutes) Used when retrieving the Spring Cloud Application MySQL Association.
* `update` - (Defaults to 30 minutes) Used when updating the Spring Cloud Application MySQL Association.
* `delete` - (Defaults to 30 minutes) Used when deleting the Spring Cloud Application MySQL Association.
```

2021-04-07 11:04 UTC, tombuildsstuff commented on website/docs/r/spring_cloud_app_mysql_association.html.markdown
> +Spring Cloud Application Mysql Association can be imported using the `resource id`, e.g.
```suggestion
Spring Cloud Application MySQL Association can be imported using the `resource id`, e.g.
```

2021-04-07 11:04 UTC, tombuildsstuff commented on website/docs/r/spring_cloud_app_mysql_association.html.markdown
> +  Associates a [Spring Cloud Application](spring_cloud_app.html) with a [Mysql Database](mysql_database.html).
```suggestion
  Associates a [Spring Cloud Application](spring_cloud_app.html) with a [MySQL Database](mysql_database.html).
```

2021-04-07 11:04 UTC, tombuildsstuff commented on website/docs/r/spring_cloud_app_mysql_association.html.markdown
> +* `id` - The ID of the Spring Cloud Application Mysql Association.
```suggestion
* `id` - The ID of the Spring Cloud Application MySQL Association.
```

2021-04-07 11:29 UTC, tombuildsstuff commented on azurerm/internal/services/springcloud/spring_cloud_app_mysql_association_resource.go
> +			"password": {
also this is a password, so isn't this a sensitive value?

2021-04-08 03:31 UTC, njuCZ commented
@tombuildsstuff thanks for your review. I have updated this PR, all acctest could pass

2021-04-13 01:57 UTC, katbyte approved these changes
Thanks @njuCZ - LGTM 👍

2021-04-13 01:58 UTC, merged