"azurerm_kubernetes_cluster" - supports property "private_cluster_custom_dns_prefix"
terraform-providers/terraform-provider-azurerm pull request #11321
Opened 2021-04-14 06:42 UTC by njuCZ

this property in swagger is "fqdnSubdomain", it is used in private cluster to set custom dns subdomain, so I renamed it to "private_cluster_custom_dns_prefix"

Doc refer to https://docs.microsoft.com/en-us/azure/aks/private-clusters#configure-private-dns-zone

difference between property "dns_prefix" and "private_cluster_custom_dns_prefix"":
1. use "dns_prefix", the fqdn format is like "<dns-prefix>-<random-hash>.xxx.<region>.azmk8s.io"
2. use "private_cluster_custom_dns_prefix", the fqdn format is like "<fqdnsubdomain>.privatelink.<region>.azmk8s.io"

there should be exactly one of `dns_prefix` and `private_cluster_custom_dns_prefix`

![image](https://user-images.githubusercontent.com/2786738/114665479-ac058a00-9d2f-11eb-82d2-cd9ad35ac71a.png)

2021-04-20 21:15 UTC, katbyte requested changes
aside from one comment about this property name this is looking good

2021-04-20 21:15 UTC, katbyte commented on website/docs/r/kubernetes_cluster.html.markdown
> +* `private_cluster_custom_dns_prefix` - (Optional) Specifies the Custom DNS prefix when creating the private cluster. Changing this forces a new resource to be created.
grammar and i think custom is redundant?

```suggestion
* `private_cluster_dns_prefix` - (Optional) Specifies the DNS prefix to use with private clusters. Changing this forces a new resource to be created.
```

also given there is a dns_prefix property, maybe this makes sense to keep them ordered/auto completed at the same time

```suggestion
* `dns_prefix_private_cluster` - (Optional) Specifies the DNS prefix to use with private clusters. Changing this forces a new resource to be created.
```

2021-04-21 03:06 UTC, njuCZ commented
@katbyte Thanks for the suggestion. I have renamed this property

2021-04-27 02:42 UTC, katbyte approved these changes
Thanks @njuCZ - LGTM 👍

2021-04-27 02:48 UTC, merged