[RESOURCE] Mssql Elastic Job Credential
terraform-providers/terraform-provider-azurerm pull request #11363
Opened 2021-04-19 06:05 UTC by r0bnet

Job Credential resource as part of the Elastic Job Agents.

see: GH-11248

2021-04-19 13:26 UTC, jackofallops requested changes
Hi @r0bnet - Many thanks for this PR, looking mostly good, but I've left a few suggestions for making use of the generated ID code.  We're aiming to use these throughout the provider, so newly introduced resources can make use of them on Create (we're working through existing resources slowly as they will need state migrations, hence largely looking like only in Read).
Thanks again!

2021-04-19 13:26 UTC, jackofallops commented on azurerm/internal/services/mssql/mssql_job_credential_resource.go
> +	jaId, _ := parse.JobAgentID(jobAgentId)
Can we make use of the generated ID Function here:
```suggestion
	jaId, err := parse.JobAgentID(d.Get("job_agent_id").(string))
	if err != nil {
		return err
	}
	jobCredentialId := parse.NewJobCredentialID(jaId.SubscriptionId, jaId.ResourceGroup, jaId.ServerName, jaId.Name, d.Get("name").(string))

```

2021-04-19 13:26 UTC, jackofallops commented on azurerm/internal/services/mssql/mssql_job_credential_resource.go
> +		existing, err := client.Get(ctx, jaId.ResourceGroup, jaId.ServerName, jaId.Name, name)
```suggestion
		existing, err := client.Get(ctx, jobCredentialId.ResourceGroup, jobCredentialId.ServerName, jobCredentialId.JobAgentName, jobCredentialId.CredentialName)
```

2021-04-19 13:26 UTC, jackofallops commented on azurerm/internal/services/mssql/mssql_job_credential_resource.go
> +				return fmt.Errorf("Failed to check for presence of existing MsSql Job Credential %q (Job Agent %q / MsSql Server %q / Resource Group %q): %s", name, jaId.Name, jaId.ServerName, jaId.ResourceGroup
```suggestion
				return fmt.Errorf("checking for presence of existing MsSql %s: %+v", jobCredentialId, err)
```

2021-04-19 13:40 UTC, r0bnet commented on azurerm/internal/services/mssql/mssql_job_credential_resource.go
> +	d.SetId(*cred.ID)
Yeah, sure! :)

2021-04-19 13:42 UTC, r0bnet commented
Thanks @jackofallops. I committed your suggestions. Hope it's good to go now 👍

2021-04-22 06:59 UTC, tombuildsstuff approved these changes
LGTM - thanks for pushing those changes @r0bnet

2021-04-24 17:32 UTC, merged