"azurerm_kubernetes_cluster" - supports "max_node_provision_time","max_total_unready_percentage" and "ok_total_unready_count"
terraform-providers/terraform-provider-azurerm pull request #11406
Opened 2021-04-21 08:18 UTC by njuCZ

This PR adds support for the `max_node_provision_time`, `max_total_unready_percentage` and `ok_total_unready_count` property in the `auto_scaler_profile block` for `azurerm_kubernetes_cluster`.

As per https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler#using-the-autoscaler-profile

![image](https://user-images.githubusercontent.com/2786738/115520961-41b79100-a2bd-11eb-9899-2d245f0fa453.png)

2021-04-22 03:28 UTC, magodo requested changes
Thanks for this PR!
I've taken a look through and left some comments inline, but this is mostly looking good to me 👍

2021-04-22 03:28 UTC, magodo commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +						},
Can we add a validation here?

2021-04-22 03:28 UTC, magodo commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +						},
Can we add a validation here?

2021-04-22 03:28 UTC, magodo commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +							Type:     schema.TypeString,
Does it make sense to change this to `TypeInt`?

2021-04-22 03:28 UTC, magodo commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +							Type:     schema.TypeString,
Does it make sense to change this to `TypeInt`?

2021-04-22 09:19 UTC, magodo commented
LGTM 👍
![image](https://user-images.githubusercontent.com/7970698/115689702-eb1a8780-a38e-11eb-9523-85e9adbd64b6.png)

2021-04-23 01:16 UTC, magodo commented
@njuCZ About the default values, I'm a bit concerned if some existing resource has different default values being set when they created the resource with old provider, then they'll get a diff in the new provider. Though this is not likely to happen if the service keeps the behavior consistent.

2021-04-23 01:52 UTC, njuCZ commented
@magodo the simplest way is to make them typeString, empty string will make the backend service return the  default value. This is a little common for aks. But I also agrees that exlipcit type is more helpful. To make it TypeInt,  we should set a default value, because 0 is also a valid value.

2021-04-23 01:59 UTC, magodo commented
If they are O+C, I assume the default is not necessary?

2021-04-23 02:03 UTC, njuCZ commented
If it's TypeString, O+C has no problem. but if we set it as TypeInt, it will have a default value 0, 0 is a valid value for this property, and the backend service will think client want to set it as 0 and does not return the default value

2021-04-23 02:22 UTC, magodo commented
Ah.. Because those properties are inside a nested block, which means there is no way to tell whether they are omitted in the config or not..

2021-04-23 03:50 UTC, katbyte requested changes
Thanks @njuCZ - just a couple comments

2021-04-23 03:50 UTC, katbyte commented on website/docs/r/kubernetes_cluster.html.markdown
> +* `ok_total_unready_count` - Number of allowed unready nodes. Defaults to `3`.
ok does not make sense here
```suggestion
* `unready_nodes_allowed` - Number of allowed unready nodes. Defaults to `3`.
```

or for consistancy

```suggestion
* `max_unready_nodes` - Number of allowed unready nodes. Defaults to `3`.
```

2021-04-23 03:50 UTC, katbyte commented on website/docs/r/kubernetes_cluster.html.markdown
> +* `max_node_provision_time` - Maximum time the autoscaler waits for a node to be provisioned. Defaults to `15m`.
grammer
```suggestion
* `max_node_provisioning_time` - Maximum time the autoscaler waits for a node to be provisioned. Defaults to `15m`.
```

2021-04-23 03:50 UTC, katbyte commented on website/docs/r/kubernetes_cluster.html.markdown
> +* `max_total_unready_percentage` - Maximum percentage of unready nodes the cluster autoscaler will stop if the percentage is exceeded. Defaults to `45`.
```suggestion
* `max_unready_percentage` - Maximum percentage of unready nodes the cluster autoscaler will stop if the percentage is exceeded. Defaults to `45`.
```

2021-04-23 13:17 UTC, njuCZ commented
@katbyte thanks for your opinion, I have renamed those fields.

2021-04-27 02:58 UTC, katbyte approved these changes
Thanks @njuCZ - LGTM 👍

2021-04-27 02:58 UTC, merged