Supports for `nfs_v3_enabled`, `azure_files_identity_based_authentication`, `routing_preference` in `azurerm_storage_account`
terraform-providers/terraform-provider-azurerm pull request #11485
Opened 2021-04-27 06:20 UTC by yupwei68

Extend: https://github.com/terraform-providers/terraform-provider-azurerm/pull/8961

Fix: https://github.com/terraform-providers/terraform-provider-azurerm/issues/8960
https://github.com/terraform-providers/terraform-provider-azurerm/issues/9221
https://github.com/terraform-providers/terraform-provider-azurerm/issues/11373

All tests have passed

2021-04-30 18:16 UTC, katbyte requested changes
Thanks @yupwei68 - left some comments inline

2021-04-30 18:16 UTC, katbyte commented on website/docs/r/storage_account.html.markdown
> +A `azure_files_identity_based_authentication` block supports the following:
I think this is unclear, is this to configure files authentication? so shouldn't it be
```suggestion
A `azure_files_authentication` block supports the following:
```

2021-04-30 18:16 UTC, katbyte commented on website/docs/r/storage_account.html.markdown
> +* `directory_service_options` - (Required) Specifies the directory service used. Possible values are `AADDS` and `AD`.
```suggestion
* `directory_type` - (Required) Specifies the directory service used. Possible values are `AADDS` and `AD`.
```

2021-04-30 18:16 UTC, katbyte commented on website/docs/r/storage_account.html.markdown
> +* `azure_storage_sid` - (Required) Specifies the security identifier (SID) for Azure Storage.
```suggestion
* `storage_sid` - (Required) Specifies the security identifier (SID) for Azure Storage.
```

2021-04-30 18:16 UTC, katbyte commented on website/docs/r/storage_account.html.markdown
> +* `net_bios_domain_name` - (Required) Specifies the NetBIOS domain name.
netbois is one word
```suggestion
* `netbios_domain_name` - (Required) Specifies the NetBIOS domain name.
```

2021-05-07 06:29 UTC, katbyte approved these changes
Thanks @yupwei68 - LGTM 👍

2021-05-07 06:30 UTC, merged

2021-06-17 03:25 UTC, singhalss commented
Hi @yupwei68 / @katbyte - While looking at the documentation, I found that we need to specify **storage_sid** as one of the required values in **azure_files_authentication** block. **storage_sid** is generated once the storage account joins AD, not sure what value to specify to storage SID while creating the storage account.

Also, one more doubt, while running terraform in context of service principal (SPN), what permissions are required to be given to SPN to accomplish this task. As per my understanding, service account/SPN will need to have domain join permissions for accomplishing this task and also in automation context, it needs to be executed from a domain join machine.

Please correct me if I am wrong and guide further to make use of this feature in terraform provider.