add resource azurerm_cosmosdb_sql_user_defined_function
terraform-providers/terraform-provider-azurerm pull request #11537
Opened 2021-04-30 02:32 UTC by ms-henglu

The added tests are listed as follows.
```
=== RUN   TestAccCosmosDbSQLUserDefinedFunction_basic
=== PAUSE TestAccCosmosDbSQLUserDefinedFunction_basic
=== CONT  TestAccCosmosDbSQLUserDefinedFunction_basic
--- PASS: TestAccCosmosDbSQLUserDefinedFunction_basic (1286.92s)
=== RUN   TestAccCosmosDbSQLUserDefinedFunction_requiresImport
=== PAUSE TestAccCosmosDbSQLUserDefinedFunction_requiresImport
=== CONT  TestAccCosmosDbSQLUserDefinedFunction_requiresImport
--- PASS: TestAccCosmosDbSQLUserDefinedFunction_requiresImport (1300.76s)
=== RUN   TestAccCosmosDbSQLUserDefinedFunction_update
=== PAUSE TestAccCosmosDbSQLUserDefinedFunction_update
=== CONT  TestAccCosmosDbSQLUserDefinedFunction_update
--- PASS: TestAccCosmosDbSQLUserDefinedFunction_update (1342.00s)
PASS
```

2021-04-30 05:20 UTC, katbyte requested changes

2021-04-30 05:20 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_sql_user_defined_function_resource.go
> +			},
there is no validation here, also couldn't we just take in a sql_database_id and parse this all out?

2021-04-30 05:20 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_sql_user_defined_function_resource_test.go
> +	})
could we finish with a -> basic step?

2021-04-30 05:20 UTC, katbyte commented on azurerm/internal/services/cosmos/registration.go
> +		"azurerm_cosmosdb_sql_user_defined_function": resourceCosmosDbSQLUserDefinedFunction(),
is user defined really necessary given we are define it?
```suggestion
		"azurerm_cosmosdb_sql_function": resourceCosmosDbSQLUserDefinedFunction(),
```

2021-05-06 03:45 UTC, ms-henglu commented
@katbyte hi, I have updated this PR, could you please take another look? Thanks

2021-05-06 19:33 UTC, katbyte requested changes
Thanks @ms-henglu - one comment to address and this hsould be good to merge

2021-05-06 19:33 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_sql_function_resource.go
> +	id := parse.NewSqlFunctionID(subscriptionId, resourceGroup, accountName, databaseName, containerName, name)
we don't need to assign the ID parts to variables here?

2021-05-07 02:08 UTC, ms-henglu commented
@katbyte , thanks for code review, I updated pr according to your suggestion.

2021-05-07 03:36 UTC, katbyte approved these changes
Thanks @ms-henglu - LGTM 👍

2021-05-07 03:36 UTC, merged