add resource azurerm_cosmosdb_sql_trigger
terraform-providers/terraform-provider-azurerm pull request #11535
Opened 2021-04-30 02:28 UTC by ms-henglu

The added tests are listed as follows.
```
=== RUN   TestAccCosmosDbSQLTrigger_basic
=== PAUSE TestAccCosmosDbSQLTrigger_basic
=== CONT  TestAccCosmosDbSQLTrigger_basic
--- PASS: TestAccCosmosDbSQLTrigger_basic (1271.04s)
=== RUN   TestAccCosmosDbSQLTrigger_requiresImport
=== PAUSE TestAccCosmosDbSQLTrigger_requiresImport
=== CONT  TestAccCosmosDbSQLTrigger_requiresImport
--- PASS: TestAccCosmosDbSQLTrigger_requiresImport (1224.34s)
=== RUN   TestAccCosmosDbSQLTrigger_update
=== PAUSE TestAccCosmosDbSQLTrigger_update
=== CONT  TestAccCosmosDbSQLTrigger_update
--- PASS: TestAccCosmosDbSQLTrigger_update (1339.53s)
```

2021-04-30 05:22 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_sql_trigger_resource.go
> +				ValidateFunc: validate.CosmosEntityName,
we can parse this out of a resource id?

2021-04-30 05:22 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_sql_trigger_resource.go
> +			"trigger_operation": {
trigger is in the resource name?
```suggestion
			"operation": {
```

2021-04-30 05:23 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_sql_trigger_resource.go
> +			"trigger_type": {
```suggestion
			"type": {
```

2021-05-06 03:13 UTC, ms-henglu commented
@katbyte , hi, I updated this PR, could you please take another look? Thanks!

2021-05-06 19:33 UTC, katbyte requested changes
Thanks @ms-henglu - one last comment and this should be good to merge

2021-05-06 19:33 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_sql_trigger_resource.go
> +	id := parse.NewSqlTriggerID(subscriptionId, resourceGroup, accountName, databaseName, containerName, name)
we don't need to assign these to an intermediate?
```suggestion

	body := d.Get("body").(string)
	triggerOperation := d.Get("operation").(string)
	triggerType := d.Get("type").(string)

	id := parse.NewSqlTriggerID(subscriptionId, containerId.ResourceGroup, containerId.AccountName, containerId.DatabaseName, containerId.Name, name)
```

2021-05-06 19:33 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_sql_trigger_resource.go
> +	future, err := client.CreateUpdateSQLTrigger(ctx, resourceGroup, accountName, databaseName, containerName, name, createUpdateSqlTriggerParameters)
same here

2021-05-07 02:08 UTC, ms-henglu commented
@katbyte , thanks for code review, I updated pr according to your suggestion.

2021-05-07 03:43 UTC, katbyte approved these changes
Thanks @ms-henglu - LGTM 👍

2021-05-07 03:43 UTC, merged