add resource azurerm_cosmosdb_notebook_workspace
terraform-providers/terraform-provider-azurerm pull request #11536
Opened 2021-04-30 02:29 UTC by ms-henglu

The added tests are listed as follows.

```
=== RUN   TestAccCosmosDbNotebookWorkspace_basic
=== PAUSE TestAccCosmosDbNotebookWorkspace_basic
=== CONT  TestAccCosmosDbNotebookWorkspace_basic
--- PASS: TestAccCosmosDbNotebookWorkspace_basic (1047.41s)
=== RUN   TestAccCosmosDbNotebookWorkspace_requiresImport
=== PAUSE TestAccCosmosDbNotebookWorkspace_requiresImport
=== CONT  TestAccCosmosDbNotebookWorkspace_requiresImport
--- PASS: TestAccCosmosDbNotebookWorkspace_requiresImport (1024.83s)
```

2021-04-30 05:21 UTC, katbyte requested changes

2021-04-30 05:21 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_notebook_workspace_resource.go
> +			"notebook_server_endpoint": {
```suggestion
			"server_endpoint": {
```
notebook is in the resource name

2021-05-06 04:01 UTC, ms-henglu commented
@katbyte  hi, I have updated this PR, could you please take another look? Thanks

2021-05-06 19:34 UTC, katbyte approved these changes
Thanks @ms-henglu - LGTM 👍

2021-05-06 19:35 UTC, merged