New Resource - sentinel_alert_rule_ml_behaviour_analytics
terraform-providers/terraform-provider-azurerm pull request #11552
Opened 2021-05-01 22:15 UTC by kaovd

PR implements Azure Sentinel ML Behavior Analytics rules as per #11551
This quite literally just copies from Fusion rules as it has the exact same properties. 

# Reference

- Properties/Spec Ref: https://github.com/Azure/bicep-types-az/blob/9d7f9f5caab4cf0b9645aee3dd6328406f0904ab/generated/securityinsights/microsoft.securityinsights/2019-01-01-preview/types.md#mlbehavioranalyticsalertruleproperties
- API: https://github.com/AzureSDKAutomation/azure-resource-manager-schemas/pull/1487/commits/e31fdb6c651295486de179225dae79bd8a02aa7c

# Test Results
```
2021/05/01 22:51:52 [DEBUG] not using binary driver name, it's no longer needed
2021/05/01 22:51:52 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccSentinelAlertRuleMLBehaviorAnalytics_basic
=== PAUSE TestAccSentinelAlertRuleMLBehaviorAnalytics_basic
=== RUN   TestAccSentinelAlertRuleMLBehaviorAnalytics_complete
=== PAUSE TestAccSentinelAlertRuleMLBehaviorAnalytics_complete
=== RUN   TestAccSentinelAlertRuleMLBehaviorAnalytics_update
=== PAUSE TestAccSentinelAlertRuleMLBehaviorAnalytics_update
=== RUN   TestAccSentinelAlertRuleMLBehaviorAnalytics_requiresImport
=== PAUSE TestAccSentinelAlertRuleMLBehaviorAnalytics_requiresImport
=== CONT  TestAccSentinelAlertRuleMLBehaviorAnalytics_basic
=== CONT  TestAccSentinelAlertRuleMLBehaviorAnalytics_update
=== CONT  TestAccSentinelAlertRuleMLBehaviorAnalytics_complete
=== CONT  TestAccSentinelAlertRuleMLBehaviorAnalytics_requiresImport
--- PASS: TestAccSentinelAlertRuleMLBehaviorAnalytics_basic (253.75s)
--- PASS: TestAccSentinelAlertRuleMLBehaviorAnalytics_complete (255.03s)
--- PASS: TestAccSentinelAlertRuleMLBehaviorAnalytics_requiresImport (363.84s)
--- PASS: TestAccSentinelAlertRuleMLBehaviorAnalytics_update (563.17s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/sentinel    563.286s
```
![image](https://user-images.githubusercontent.com/29356754/116796217-c632bc80-aad2-11eb-8193-d7885a6c7370.png)

2021-05-06 07:50 UTC, magodo requested changes
@kaovd Thanks for this PR!
I have left some additional mostly minor comments that once addressed this should be good to merge 👍

2021-05-06 07:50 UTC, magodo commented on website/docs/r/azurerm_sentinel_alert_rule_ml_behavior_analytics.html.markdown
> +}
Can we remove these to make the example a minimal section?
```suggestion
```

2021-05-06 07:50 UTC, magodo commented on website/docs/r/azurerm_sentinel_alert_rule_ml_behavior_analytics.html.markdown
> +## Arguments Reference
Can we replace the `Fusion` below to `Machine Learning Behavior Analytics`?

2021-05-06 07:50 UTC, magodo commented on azurerm/internal/services/sentinel/registration.go
> +		"azurerm_sentinel_alert_rule_ml_behavior_analytics":                             resourceSentinelAlertRuleMLBehaviorAnalytics(),
Can we move this line upwards in alphamatic order?

2021-05-07 03:24 UTC, magodo commented
@kaovd Shall we change the resource name a bit to expanding the `ml` to `machine_learning`? (sorry to bring this so late)

2021-05-07 06:49 UTC, kaovd commented
> @kaovd Shall we change the resource name a bit to expanding the `ml` to `machine_learning`? (sorry to bring this so late)

No problem

2021-05-07 08:11 UTC, magodo commented
@kavod Excellent! LGTM 👍

![image](https://user-images.githubusercontent.com/7970698/117419183-de7d5e00-af4e-11eb-966e-7a835909f6ae.png)

2021-05-07 08:13 UTC, merged

2021-05-07 09:34 UTC, favoretti commented
@magodo Hmm, file name is not following the naming convention as it has `azurerm_` in the beginning. I'll fix that with my SDK upgrade PR if that's ok with you?