`kubernetes_cluster`/`kubernetes_cluster_node_pool`: Node Public IP Prefix added for resources and data sources
terraform-providers/terraform-provider-azurerm pull request #11635
Opened 2021-05-08 16:36 UTC by aristosvo

Fixes #11424

Tasks:
- [x] Add Node Public IP Prefix for `kubernetes_cluster` resource
  - [x] Acctest added (`TestAccKubernetesCluster_nodePublicIPPrefix`)
  - [x] Acctest fixed, `enable_node_public_ip` cannot be changed (`TestAccKubernetesCluster_enableNodePublicIP`)
  - [ ] Docs
- [x] Add Node Public IP Prefix for `kubernetes_cluster` data source
  - [x] Acctest adjusted (`TestAccDataSourceKubernetesCluster_enableNodePublicIP` -> `TestAccDataSourceKubernetesCluster_nodePublicIP`) 
  - [ ] Docs
- [x] Add Node Public IP Prefix for `kubernetes_cluster_node_pool` resource
  - [x] Acctest adjusted for `kubernetes_cluster_node_pool` resource (`TestAccKubernetesClusterNodePool_nodePublicIP`)
  - [ ] Docs
- [x] Add Node Public IP Prefix for `kubernetes_cluster_node_pool` data source
  - [ ] Docs

2021-06-01 15:56 UTC, nickvth commented
@aristosvo great job, only the conflicts need to be fixed. 
We hope this MR will be merged soon, because we need this 👍

2021-06-01 16:21 UTC, aristosvo commented
@nickvth Thanks! I reordered some code without separated commits, so I basically asked for it :)

2021-06-01 18:52 UTC, aristosvo commented
```
❯ make acctests SERVICE='containers' TESTARGS='-run=nodePublicIP\|NodePublicIP'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/containers -run=nodePublicIP\|NodePublicIP -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/06/01 20:12:53 [DEBUG] not using binary driver name, it's no longer needed
2021/06/01 20:12:54 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccDataSourceKubernetesCluster_nodePublicIP
=== PAUSE TestAccDataSourceKubernetesCluster_nodePublicIP
=== RUN   TestAccKubernetesCluster_enableNodePublicIP
=== PAUSE TestAccKubernetesCluster_enableNodePublicIP
=== RUN   TestAccKubernetesCluster_nodePublicIPPrefix
=== PAUSE TestAccKubernetesCluster_nodePublicIPPrefix
=== RUN   TestAccKubernetesClusterNodePool_nodePublicIP
=== PAUSE TestAccKubernetesClusterNodePool_nodePublicIP
=== CONT  TestAccDataSourceKubernetesCluster_nodePublicIP
=== CONT  TestAccKubernetesClusterNodePool_nodePublicIP
=== CONT  TestAccKubernetesCluster_nodePublicIPPrefix
=== CONT  TestAccKubernetesCluster_enableNodePublicIP
--- PASS: TestAccKubernetesCluster_enableNodePublicIP (682.92s)
--- PASS: TestAccDataSourceKubernetesCluster_nodePublicIP (691.89s)
--- PASS: TestAccKubernetesCluster_nodePublicIPPrefix (700.33s)
--- PASS: TestAccKubernetesClusterNodePool_nodePublicIP (979.57s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers  983.162s
```

2021-06-01 20:18 UTC, mbfrahry requested changes
Hey @aristosvo! About 30 of the cluster tests are now failing with these changes. 

`TestAccKubernetesClusterNodePool_autoScaleUpdate` fails with
```
Code="LinkedInvalidPropertyId" Message="Property id '' at path 'properties.nodePublicIPPrefixID'
```

and `TestAccKubernetesCluster_enableNodePublicIP` is failing as well

```
testing.go:620: Step 1/2 error: Error running pre-apply refresh: exit status 1
Error: "default_node_pool.0.enable_node_public_ip": all of `default_node_pool.0.enable_node_public_ip,default_node_pool.0.node_public_ip_prefix_id` must be specified
with azurerm_kubernetes_cluster.test,
on terraform_plugin_test.tf line 11, in resource "azurerm_kubernetes_cluster" "test":
11: resource "azurerm_kubernetes_cluster" "test" {
--- FAIL: TestAccKubernetesCluster_enableNodePublicIP (5.99s)
```

I think we should be nearly there if we get those issues fixed up

2021-06-01 20:47 UTC, aristosvo commented
@mbfrahry Thanks for running all the AccTests!

I believe I fixed the last one already with commit `21d0359`, `RequiredWith the other way around`.

I've tried to fix the first one as well, checks are running atm! Are these failing tests only `ClusterNodePool` related tests or should I dig deeper here?

2021-06-01 21:11 UTC, mbfrahry commented
Ack! I'm so sorry! I was looking at the wrong commit. I'm running through the tests again against the latest changes here. I'll report back as soon as they are done

2021-06-01 21:15 UTC, aristosvo commented
No problem, I hadn't noticed the failing `ClusterNodePool` tests yet.

Thanks a lot!

2021-06-02 23:53 UTC, mbfrahry approved these changes
LGTM! Thanks @aristosvo!

2021-06-02 23:53 UTC, merged