Refactor `azurerm_network_watcher_flow_log` and add supports for `location` and `tags`
terraform-providers/terraform-provider-azurerm pull request #11670
Opened 2021-05-12 07:25 UTC by magodo

This refactors the `azurerm_network_watcher_flow_log` to using its own separate endpoint - rather than using the `configureFlowLog` endpoint of the Network Watcher.

This PR is implemented in a way to avoid breaking changes on the existing instances and ensure backward compatiblility (locally tested).

Besides, I've modified the test cases to make them sequential - the prior implementation actually are still running in parallel at the end.

Fixes: #11587 

## Test Result

```bash
💤 TF_ACC=1 go test -v -timeout=8h ./azurerm/internal/services/network -run="TestAccNetworkWatcherFlowLog_"
2021/05/12 14:25:23 [DEBUG] not using binary driver name, it's no longer needed
2021/05/12 14:25:23 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccNetworkWatcherFlowLog_basic
--- PASS: TestAccNetworkWatcherFlowLog_basic (228.54s)
=== RUN   TestAccNetworkWatcherFlowLog_disabled
--- PASS: TestAccNetworkWatcherFlowLog_disabled (228.47s)
=== RUN   TestAccNetworkWatcherFlowLog_reenabled
--- PASS: TestAccNetworkWatcherFlowLog_reenabled (298.10s)
=== RUN   TestAccNetworkWatcherFlowLog_retentionPolicy
--- PASS: TestAccNetworkWatcherFlowLog_retentionPolicy (323.25s)
=== RUN   TestAccNetworkWatcherFlowLog_updateStorageAccount
--- PASS: TestAccNetworkWatcherFlowLog_updateStorageAccount (359.24s)
=== RUN   TestAccNetworkWatcherFlowLog_trafficAnalytics
--- PASS: TestAccNetworkWatcherFlowLog_trafficAnalytics (566.27s)
=== RUN   TestAccNetworkWatcherFlowLog_version
--- PASS: TestAccNetworkWatcherFlowLog_version (371.40s)
=== RUN   TestAccNetworkWatcherFlowLog_location
--- PASS: TestAccNetworkWatcherFlowLog_location (234.28s)
=== RUN   TestAccNetworkWatcherFlowLog_tags
--- PASS: TestAccNetworkWatcherFlowLog_tags (317.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network     2926.746s
```

2021-05-26 09:37 UTC, magodo commented
@katbyte Would you please take a look at this PR? Some customers are blocked by this.

2021-06-01 21:32 UTC, katbyte requested changes

2021-06-01 21:32 UTC, katbyte commented on azurerm/internal/services/network/network_watcher_resource_test.go
> +	data.ResourceSequentialTest(t, r, []acceptance.TestStep{
is this working correctly? all the tests are failing in teamcity now, worse then before

2021-06-03 16:12 UTC, katbyte approved these changes
Thanks @magodo - LGTM 👍

2021-06-04 06:04 UTC, merged