migrate `azurerm_synapse_role_assignment` to support new roles and scopes
terraform-providers/terraform-provider-azurerm pull request #11690
Opened 2021-05-13 03:07 UTC by njuCZ

fix #10141 

in old api version, the only supported role is `Workspace Admin`, `Sql Admin` and `Apache Spark Admin`. The scope is workspace.

in new api version, exsiting roles are renamed and new roles are added, Users could also specify different scope, workspace, spark pool or others (not suported in terraform, so not added in this PR) .

![image](https://user-images.githubusercontent.com/2786738/118071934-5a5a2900-b3db-11eb-8ee4-f0823dae4cbd.png)

2021-05-28 06:45 UTC, njuCZ commented
this PR contains breaking changes, is it possible to be merged in the next major version 3.0 ?

2021-06-01 21:55 UTC, katbyte requested changes
@njuCZ - is there a reason we can't map the old roles to the new ones so this isn't a breaking change? (at least for upgrading?)

2021-06-02 01:51 UTC, njuCZ commented
@katbyte we could map the old roles to the new, in this PR I also added a stateUpgrade func to make it. But in the old api, the scope of role assignment is always workspace level, while the new api could be workspace level, sparkpool level and others. So I removed property `synapse_workspace_id` and add property `synapse_scope`, I think this is a breaking change for users.

2021-06-02 06:47 UTC, chrsundermann commented
Does it make sense not to hardcode possible roles? As soon as new roles will be integrated they can't be picked and code has to be updated.

2021-06-03 16:15 UTC, katbyte commented
> But in the old api, the scope of role assignment is always workspace level, while the new api could be workspace level, sparkpool level and others

if we default to workspace level and mark that as optional it's not a breaking change?

2021-06-07 02:24 UTC, njuCZ commented
@katbyte yes, in the state upgrade func I did that. I thought changing the schema name (synapse_workspace_id -> syanpse_scope) belongs to breaking change because we need users to modify the property name in TF config file. If this change is OK, I think we could remove the breaking change label.

2021-06-07 02:26 UTC, njuCZ commented
another way to make this PR: we could mark `synapse_workspace_id` optional, and add other schema for scope, for example: spark_pool_id. In this way, we would have multiple specific schema to represent scope and only one of them should be specified.

2021-06-08 00:15 UTC, katbyte commented
> another way to make this PR: we could mark synapse_workspace_id optional, and add other schema for scope, for example: spark_pool_id. In this way, we would have multiple specific schema to represent scope and only one of them should be specified.

I like this id! and then we get proper validation on the id of the scope and no breaking change, this works for me!

2021-06-08 05:32 UTC, njuCZ commented
@katbyte I have refined this PR, now there is no breaking change. All acctest could pass.
![image](https://user-images.githubusercontent.com/2786738/121128176-8f805c80-c85d-11eb-9b5b-847b132ff909.png)

2021-06-09 02:53 UTC, njuCZ commented
@chrsundermann sorry for late reply. Currently there is not many roles, so we could hardcode in the validation function and provide more friendly user experience . If there are many roles added in future, we could add another data source for role definition. 

As for synapse scope, since integrationRuntimes, credentials, linkedservice are not supported in terraform yet, so in this PR, I don't support them. I think it's easy to add support for those scope in future.

2021-06-11 11:49 UTC, njuCZ commented
@katbyte the acctest in teamcity could pass now.

2021-06-11 20:28 UTC, katbyte requested changes
one last comment i think

2021-06-11 20:28 UTC, katbyte commented on azurerm/internal/services/synapse/synapse_role_assignment_resource.go
> -					"Sql Admin",
i think we'll still need to keep these around until 3.0 so the user doesn't have to change their config (prevent breaking change(

2021-06-15 00:30 UTC, katbyte commented on azurerm/internal/services/synapse/synapse_role_assignment_resource.go
> -					"Sql Admin",
and could we add a comment to be removed

2021-06-15 07:16 UTC, njuCZ commented
@katbyte thanks for your suggestions. I have added support for old roles and add a suppressFunc to avoid diff between old roles and new roles.

![image](https://user-images.githubusercontent.com/2786738/122009445-accca200-cdec-11eb-8362-34d5ba7e642c.png)

2021-06-15 22:22 UTC, katbyte approved these changes
Thanks @njuCZ - LGTM aside from one comment which i'll fix now 🍰

2021-06-15 22:22 UTC, katbyte commented on azurerm/internal/services/synapse/client/client.go
> +	// the service team hopes to rename it to sparkPool, mso rename the sdk here
```suggestion
	// the service team hopes to rename it to sparkPool, so rename the sdk here
```

2021-06-15 22:57 UTC, merged