allow azurerm_application_insights_smart_detection_rule to configure all rules
terraform-providers/terraform-provider-azurerm pull request #12012
Opened 2021-05-31 06:13 UTC by komal-SkyNET

Addresses the issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/11999  

In the smart detection resource, there is currently a validation(which has become a restriction) – that accepts only a set of rule names – that is hindering support for new rules as and when they become available.  This also requires us to update our code every time a rule name is added/updated/deleted by microsoft. 

To simplify this, I propose to remove this restriction so that users can reference [microsoft docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/proactive-arm-config#smart-detection-rule-names) and pass the internal rule name as required. This will also relieve us from having to update the code every time a smart detection rule name is updated/added/deleted.

2021-05-31 06:40 UTC, komal-SkyNET commented
Resolves #11999

2021-06-11 20:38 UTC, katbyte requested changes
Thanks for opening this pr, however we do not just remove validation from constants like this (and fwiw these should be added to the SDK) except in some exceptional circumstances. 

instead could we update the list with the new constants? thanks

2021-06-11 20:38 UTC, katbyte commented on azurerm/internal/services/applicationinsights/application_insights_smart_detection_rule_resource.go
> +	name := strings.Join(strings.Split(strings.ToLower(d.Get("name").(string)), " "), "")
this is a breaking change so we can't change this behaviour till 3.0, could we add a comment to that affect?

2021-06-11 20:38 UTC, katbyte commented on azurerm/internal/services/applicationinsights/application_insights_smart_detection_rule_resource.go
> -					"Long dependency duration",
and we'll need to keep these for people who are still using them

2021-08-05 15:58 UTC, katbyte commented
@komal-SkyNET - i'm going to close this as #12857 has been opened which addresses my feedback - thanks

2021-08-05 15:58 UTC, closed without merging

2021-08-06 02:40 UTC, komal-SkyNET commented
Thanks @katbyte! Sorry, didn't get a chance to look at this after our last conversation. Glad that it's been addressed. Do we know which release version it will be included in?