New resource `azurerm_api_management_cache`
terraform-providers/terraform-provider-azurerm pull request #12174
Opened 2021-06-11 07:13 UTC by yupwei68

Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/4765

--- PASS: TestAccApiManagementCache_basic (1980.64s)
--- PASS: TestAccApiManagementCache_requiresImport (2013.39s)
--- PASS: TestAccApiManagementCache_complete (1991.81s)
--- PASS: TestAccApiManagementCache_update (2277.54s)

2021-06-11 21:12 UTC, katbyte requested changes

2021-06-11 21:12 UTC, katbyte commented on website/docs/r/api_management_cache.html.markdown
> +* `use_from_location` - (Optional) The location where to use cache from. Possible values are `default` and valid Azure regions. Defaults to `default`.
this is not the best name, what about
```suggestion
* `cache_location` - (Optional) The location where to use cache from. Possible values are `default` and valid Azure regions. Defaults to `default`.
```

also how is this different from the redis cache location

2021-06-11 21:12 UTC, katbyte commented on azurerm/internal/services/apimanagement/registration.go
> +		"azurerm_api_management_cache":                       resourceApiManagementCache(),
is this always redis?
```suggestion
		"azurerm_api_management_redis_cache":                       resourceApiManagementRedisCache(),
```

2021-06-15 04:58 UTC, yupwei68 commented
Thanks kt, Please continue reviewing.

2021-06-16 06:01 UTC, katbyte commented
thanks, i do want to know why we have a `cache_location` property - how is this different from the redis location and cannot we not just query the redis cache to get the location from it?

2021-06-16 06:23 UTC, yupwei68 commented
Hi kt, I think in that way, we could not set a cache with useFromLocation "default". I think the "default" cache is for apim service in non-specified location.

Here is from [MS document](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-cache-external#-add-an-external-cache)

> The Use from setting specifies an Azure region or a self-hosted gateway location that will use the configured cache. The caches configured as Default will be overridden by caches with a specific matching region or location value.
> 
> For example, if API Management is hosted in the East US, Southeast Asia and West Europe regions and there are two caches configured, one for Default and one for Southeast Asia, API Management in Southeast Asia will use its own cache, while the other two regions will use the Default cache entry.

2021-06-17 17:19 UTC, katbyte approved these changes
LGTM 👍

2021-06-17 17:19 UTC, merged