Support for `key_vault` in `azurerm_api_management_named_value`
terraform-providers/terraform-provider-azurerm pull request #12309
Opened 2021-06-22 06:22 UTC by yupwei68

Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/12308

--- PASS: TestAccApiManagementNamedValue_keyVault (404.38s)
--- PASS: TestAccApiManagementNamedValue_keyVaultUpdate (594.69s)

2021-07-06 23:31 UTC, manicminer requested changes
Hi @yupwei, thanks for this addition. This mostly LGTM, I made a few suggestions inline below. Could you rebase this branch to remove all the merge commits? Also, there's another PR #12356 which will likely be merged shortly and will cause a conflict on this change. Once these updates are done, and the tests pass, this should be good to merge, thanks!

2021-07-06 23:31 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_named_value_resource.go
> +				ConflictsWith: []string{"value"},
We don't need `ConflictsWith` here since this is implied by `ExactlyOneOf`
```suggestion
```

2021-07-06 23:31 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_named_value_resource.go
> +				ConflictsWith: []string{"key_vault"},
Same here

```suggestion
```

2021-07-06 23:31 UTC, manicminer commented on website/docs/r/api_management_named_value.html.markdown
> +* `secret_id` - (Required) The resource id of the Key Vault Secret.
```suggestion
* `secret_id` - (Required) The resource ID of the Key Vault Secret.
```

2021-07-06 23:31 UTC, manicminer commented on website/docs/r/api_management_named_value.html.markdown
> +* `identity_client_id` - (Required) The client id of the SystemAssigned Identity or UserAssigned Identity of the Api Management Service, which will be used to access the key vault secret.
```suggestion
* `identity_client_id` - (Required) The client ID of the System Assigned Identity, or User Assigned Identity, for the API Management Service, which will be used to access the key vault secret.
```

2021-07-09 02:34 UTC, yupwei68 commented
Thanks @manicminer . Please continue reviewing.

2021-07-10 20:36 UTC, katbyte requested changes

2021-07-10 20:36 UTC, katbyte commented on azurerm/internal/services/apimanagement/api_management_named_value_resource.go
> +			"key_vault": {
i think this would be better UZ as 
```suggestion
			"value_from_key_vault": {
```

or

```suggestion
			"value_key_vault": {
```

2021-07-12 02:04 UTC, yupwei68 commented
Thanks @katbyte . Please continue reviewing.

2021-07-12 11:08 UTC, manicminer approved these changes

2021-07-12 16:10 UTC, merged