add resource "azurerm_data_protection_backup_policy_blob_storage"
terraform-providers/terraform-provider-azurerm pull request #12362
Opened 2021-06-25 08:10 UTC by ms-henglu

The tests are listed as the following.

```
=== RUN   TestAccDataProtectionBackupPolicyBlobStorage_basic
=== PAUSE TestAccDataProtectionBackupPolicyBlobStorage_basic
=== CONT  TestAccDataProtectionBackupPolicyBlobStorage_basic
--- PASS: TestAccDataProtectionBackupPolicyBlobStorage_basic (227.33s)
=== RUN   TestAccDataProtectionBackupPolicyBlobStorage_requiresImport
=== PAUSE TestAccDataProtectionBackupPolicyBlobStorage_requiresImport
=== CONT  TestAccDataProtectionBackupPolicyBlobStorage_requiresImport
--- PASS: TestAccDataProtectionBackupPolicyBlobStorage_requiresImport (263.34s)
```

2021-07-01 05:26 UTC, katbyte requested changes

2021-07-01 05:26 UTC, katbyte commented on azurerm/internal/services/dataprotection/data_protection_backup_policy_blob_storage_resource.go
> +			},
can we validatse this?

2021-07-01 06:53 UTC, ms-henglu commented
@katbyte , I've added validate on duration, thanks!

2021-07-19 23:27 UTC, katbyte approved these changes
LGTM 🌿

2021-07-19 23:28 UTC, merged