fix #12268 NotFoundChecks for all certs
terraform-providers/terraform-provider-azurerm pull request #12388
Opened 2021-06-28 10:30 UTC by alexinthesky

fix #12268

2021-06-28 13:39 UTC, alexinthesky commented
@tombuildsstuff could you have a look there pleaaase? ty

2021-06-29 09:58 UTC, mancaus commented
FWIW this looks good to me, and we're really suffering until we have a fix available.

2021-07-05 14:52 UTC, alexinthesky commented
hi @katbyte would you give this MR some love? ty

2021-07-16 13:26 UTC, jackofallops requested changes
Hi @alexinthesky. Thanks for this, just one minor change and I think this will be OK to merge if this is still a problem. (I've asked for confirmation on the linked issue)

Thanks again!

2021-07-16 13:26 UTC, jackofallops commented on azurerm/internal/services/keyvault/key_vault_certificate_resource.go
> +			MinTimeout:   15 * time.Second,
`PollInterval` overrides `MinTimeout` so we should probably make this:
```suggestion
			PollInterval: 15 * time.Second,
```

2021-07-23 07:19 UTC, jackofallops commented
Hi @alexinthesky - Thanks for this PR. Since it appears that the problem this is intended to resolve was actually a problem in the service that has been subsequently patched / resolved on Azure's side, I'm going to close this for now. I'd like to thank you for the work here, and if this issue resurfaces we can revisit this.

2021-07-23 07:19 UTC, closed without merging