`azurerm_traffic_manager_endpoint` - supports for `min_child_endpoints_ipv4` and `min_child_endpoints_ipv6`
terraform-providers/terraform-provider-azurerm pull request #12400
Opened 2021-06-29 01:39 UTC by magodo

This PR bumps API version of `trafficmanager` from `2018-04-01` to `2018-08-01`.

Also this PR adds support of the `min_child_endpoints_ipv4` and `min_child_endpoints_ipv6` for the `azurerm_traffic_manager_endpoint`.

2021-06-29 20:17 UTC, katbyte requested changes
just one comment but otherwise LGTM 👍

2021-06-29 20:17 UTC, katbyte commented on website/docs/r/traffic_manager_endpoint.html.markdown
> +    and defaults to `1`.
could we remove the line breaks here and format it normally?

2021-06-29 20:17 UTC, katbyte commented on azurerm/internal/services/trafficmanager/traffic_manager_endpoint_resource.go
> +			"min_child_endpoints_ipv6": {
could we rename these too
```suggestion
			"minimum_required_child_endpoints_ipv4": {
				Type:     pluginsdk.TypeInt,
				Optional: true,
			},

			"minimum_required_child_endpoints_ipv6": {
```

2021-06-30 07:11 UTC, magodo commented
@katbyte I've updated the document and rename the properties per your comments.

I didn't add the sanity check on the `min_child_endpoints` as it has to be larger than 0, which means I can't both add a check for `min_child_endpoints >= minimum_required_child_endpoints_ipv4 + minimum_required_child_endpoints_ipv6`, and also allows users to only specify either ipv4/ipv6 ones by only applying above check when `min_child_endpoints > 0`. Otherwise, if the `min_child_endpoints` is less than 1, the API will raise error. For this reason, I also added a validation for the `min_child_endpoints` to ensure it is larger than 0.

2021-06-30 09:18 UTC, magodo commented
The test failures are not related to this PR.

2021-07-02 01:30 UTC, katbyte approved these changes
LGTM 🚀

2021-07-02 02:47 UTC, merged