Update data factory parquet filename to be null
terraform-providers/terraform-provider-azurerm pull request #12414
Opened 2021-06-29 20:34 UTC by gkman

The UI allows the filename to be empty/null so this being a required field doesn't seem to make sense.

2021-06-30 06:02 UTC, katbyte requested changes
Thanks @gkman - could we update the docs and remove this property from the basic test?

2021-06-30 15:00 UTC, gkman commented
> Thanks @gkman - could we update the docs and remove this property from the basic test?

@katbyte Updated the docs, that is obviously easy. But, not sure what you mean by the basic test, and the change I made just made things worse. Could you possibly point me in the right direction and I'll do my best to sort things out.

2021-07-01 15:49 UTC, jackofallops commented
> > Thanks @gkman - could we update the docs and remove this property from the basic test?
> 
> @katbyte Updated the docs, that is obviously easy. But, not sure what you mean by the basic test, and the change I made just made things worse. Could you possibly point me in the right direction and I'll do my best to sort things out.

Hi @gkman - We had an underlying issue with GitHub Actions yesterday that will have caused the checks to fail on this PR. These are now resolved and I'd restarted the affected job.  

One question on the changes here, if the filename value is omitted is a "default" filename created? If so, and this value is returned by the API, you may need to made the property `Computed` to prevent a diff. (If no value is set or returned in the API, this won't be necessary)

2021-07-01 18:59 UTC, katbyte commented
@gkman - in the acctest file there are basic, complete and update tests. the basic test usually just sets all required propeties, and as this is no longer required could we remove it from its tf config?

2021-07-06 14:53 UTC, gkman commented
> > > Thanks @gkman - could we update the docs and remove this property from the basic test?
> > 
> > 
> > @katbyte Updated the docs, that is obviously easy. But, not sure what you mean by the basic test, and the change I made just made things worse. Could you possibly point me in the right direction and I'll do my best to sort things out.
> 
> Hi @gkman - We had an underlying issue with GitHub Actions yesterday that will have caused the checks to fail on this PR. These are now resolved and I'd restarted the affected job.
> 
> One question on the changes here, if the filename value is omitted is a "default" filename created? If so, and this value is returned by the API, you may need to made the property `Computed` to prevent a diff. (If no value is set or returned in the API, this won't be necessary)

Hey @jackofallops the UI seems to just leave this empty. I have not tried this against the API itself. The UI seems to allow it to just be empty, so I don't think anything would need to be computed.

<img width="1093" alt="Screen Shot 2021-07-06 at 9 52 53 AM" src="https://user-images.githubusercontent.com/12501773/124621596-051d1f80-de40-11eb-9c91-aae817031252.png">

2021-07-06 15:27 UTC, gkman commented
> @gkman - in the acctest file there are basic, complete and update tests. the basic test usually just sets all required propeties, and as this is no longer required could we remove it from its tf config?

@katbyte ok, then I think I updated it just fine. I just had the unit testing step fail, but 40k lines of output and 100 matches of the word `fail` made it hard to get what was going on. 

I did a rebase off master and pushed and it does seem that my issues were upstream.

2021-07-08 15:25 UTC, katbyte approved these changes
Thanks @gkman! LGTM 🍰

2021-07-08 15:26 UTC, merged