Support for `data_masking` in `azurerm_api_management_api_diagnostic`
terraform-providers/terraform-provider-azurerm pull request #12419
Opened 2021-06-30 06:09 UTC by yupwei68

Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/12418

--- PASS: TestAccApiManagementApiDiagnostic_basic (292.38s)
--- PASS: TestAccApiManagementApiDiagnostic_update (404.77s)
--- PASS: TestAccApiManagementApiDiagnostic_requiresImport (312.74s)
--- PASS: TestAccApiManagementApiDiagnostic_complete (290.99s)
--- PASS: TestAccApiManagementApiDiagnostic_dataMasking (377.64s)

2021-07-08 23:17 UTC, katbyte requested changes

2021-07-08 23:17 UTC, katbyte commented on azurerm/internal/services/apimanagement/api_management_api_diagnostic_resource.go
> +				"data_masking": schemaz.SchemaApiManagementDataMasking(),
how come we are not inlining this and pulling it out into a function?

2021-07-09 01:44 UTC, yupwei68 commented
kt, Please continue reviewing.

2021-07-09 17:13 UTC, katbyte approved these changes
aside from a couple minor comments this LGTM 🍔

2021-07-09 17:13 UTC, katbyte commented on website/docs/r/api_management_api_diagnostic.html.markdown
> +A `query_params`, `headers` block supports the following:
```suggestion
The `query_params` and `headers` blocks support the following:
```

2021-07-12 15:56 UTC, merged