Added support Standard SKU to azure static site
terraform-providers/terraform-provider-azurerm pull request #12510
Opened 2021-07-07 16:09 UTC by CasperNaudts

Static sites recently went GA and therefore added a new "Standard" SKU which includes an SLA.

2021-07-08 14:03 UTC, jackofallops requested changes
Hi @CasperNaudts - Thanks for this PR, it's off to a good start.  I've left some comments inline below that will need to be addressed.  
Something that also needs consideration is whether or not the properties can be updated in place?  If so, the `createupdate` function may need some checking to ensure the value is used correctly, and if not, we will need to add `Forcenew: true,` to   those schema items also.
Thanks again!

2021-07-09 07:22 UTC, CasperNaudts commented on azurerm/internal/services/web/static_site_resource_test.go
> +  sku_tier            = "Standard"
Hi @jackofallops

Thanks for your feedback. Given the behavior of the Azure portal I am guessing this can be modified without recreation.

2021-07-26 15:48 UTC, wasfree commented on website/docs/r/static_site.html.markdown
> +* `sku_tier` - (Required) The Sku of the static site ("Free" or "Standard")
According to schema sku_tier and sku_size are optional and default to Free.

 (Optional) Specifies the sku tier of the Static Web App. Possible values are "Free" or "Standard". Defaults to "Free".

2021-08-05 06:19 UTC, jackofallops approved these changes
Hi @CasperNaudts - Thanks for this. We have an issue with creating static sites on our test subscription at the moment, so we've been delayed in getting to review/test while we work through that with support, apologies.  That said, this looks good to me and I've managed to test it successfully on another subscription. 👍

2021-08-05 06:20 UTC, merged