New resource `azurerm_api_management_tag`
terraform-providers/terraform-provider-azurerm pull request #12535
Opened 2021-07-09 06:08 UTC by yupwei68

Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/10833

2021-07-14 23:48 UTC, manicminer requested changes
Hi @yupwei68, thanks for the PR. I've made some small suggestions below, mostly around string/error formatting. If you can fix these up and the tests pass, this should be good to merge.

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +	id := parse.NewTagID(subscriptionId, apiManagementId.ResourceGroup, apiManagementId.ServiceName, name)
```suggestion

	id := parse.NewTagID(subscriptionId, apiManagementId.ResourceGroup, apiManagementId.ServiceName, d.Get("name").(string))
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +				return fmt.Errorf("checking for presence of existing Tag %q: %s", id, err)
```suggestion
				return fmt.Errorf("checking for presence of existing %s: %s", id, err)
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +		return fmt.Errorf("creating/updating %q: %+v", id, err)
```suggestion
		return fmt.Errorf("creating/updating %s: %+v", id, err)
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +				return fmt.Errorf("checking for presence of existing Tag %q: %s", id, err)
```suggestion
				return fmt.Errorf("checking for presence of existing %s: %+v", id, err)
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +		existing, err := client.Get(ctx, apiManagementId.ResourceGroup, apiManagementId.ServiceName, name)
```suggestion
		existing, err := client.Get(ctx, apiManagementId.ResourceGroup, apiManagementId.ServiceName, id.Name)
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +	displayName := d.Get("name").(string)
```suggestion
	displayName := name
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +	if _, err := client.CreateOrUpdate(ctx, apiManagementId.ResourceGroup, apiManagementId.ServiceName, name, parameters, ""); err != nil {
```suggestion
	if _, err := client.CreateOrUpdate(ctx, apiManagementId.ResourceGroup, apiManagementId.ServiceName, id.Name, parameters, ""); err != nil {
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +	subscriptionId := meta.(*clients.Client).Account.SubscriptionId
```suggestion
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +	d.Set("api_management_id", parse.NewApiManagementID(subscriptionId, id.ResourceGroup, id.ServiceName).ID())
```suggestion
	d.Set("api_management_id", parse.NewApiManagementID(id.SubscriptionId, id.ResourceGroup, id.ServiceName).ID())
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +			log.Printf("[DEBUG] %q was not found - removing from state!", id)
```suggestion
			log.Printf("[DEBUG] %s was not found - removing from state!", id)
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +		return fmt.Errorf("retrieving %q: %+v", id, err)
```suggestion
		return fmt.Errorf("retrieving %s: %+v", id, err)
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +		return fmt.Errorf("deleting %q: %+v", id, err)
```suggestion
		return fmt.Errorf("deleting %s: %+v", id, err)
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource_test.go
> +		return nil, fmt.Errorf("reading %q: %+v", id, err)
```suggestion
		return nil, fmt.Errorf("reading %s: %+v", id, err)
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource_test.go
> +%s
```suggestion
%[1]s
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource_test.go
> +  name              = "acctest-Op-Tag-%d"
```suggestion
  name              = "acctest-Op-Tag-%[2]d"
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource_test.go
> +%s
```suggestion
%[1]s
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource_test.go
> +%s
```suggestion
%[1]s
```

2021-07-14 23:48 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_tag_resource_test.go
> +  name              = "acctest-Op-Tag-%d"
```suggestion
  name              = "acctest-Op-Tag-%[2]d"
```

2021-07-30 05:52 UTC, yupwei68 commented on azurerm/internal/services/apimanagement/api_management_tag_resource.go
> +	displayName := d.Get("name").(string)
removed name := d.get("name").(string), so I keep displayName := d.Get("name").(string)

2021-07-30 06:02 UTC, yupwei68 commented
@manicminer Thanks for comments. Please continue reviewing.

2021-08-05 16:35 UTC, katbyte approved these changes
Thanks @yupwei68 - LGTM 🚀

2021-08-05 16:35 UTC, merged