Support for `user_assigned_identity` in `azurerm_storage_account_customer_managed_key`
terraform-providers/terraform-provider-azurerm pull request #12547
Opened 2021-07-12 06:04 UTC by yupwei68

Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/12489

--- PASS: TestAccStorageAccountCustomerManagedKey_userAssignedIdentity (392.21s)

2021-07-12 16:45 UTC, katbyte requested changes

2021-07-12 16:45 UTC, katbyte commented on azurerm/internal/services/storage/storage_account_customer_managed_key_resource.go
> +			"user_assigned_identity": {
could we be consistent with the rest of the provider?
```suggestion
			"user_assigned_identity_id": {
```

2021-07-13 00:20 UTC, katbyte commented
duplicate of #12516

2021-07-13 01:55 UTC, yupwei68 commented
Thanks @katbyte ,Please continue reviewing.

2021-07-13 05:53 UTC, closed without merging