enhancement for `azurerm_data_factory_integration_runtime_azure_ssis`
terraform-providers/terraform-provider-azurerm pull request #12545
Opened 2021-07-12 02:16 UTC by njuCZ

supports a bunch of properties for resource "azurerm_data_factory_integration_runtime_azure_ssis"

**notes:**
1. for the public_ips property, in the portal, it should be set with size 2.
![image](https://user-images.githubusercontent.com/2786738/125221034-2d9e9100-e2fa-11eb-8c96-55357c563a2e.png)

2021-07-12 02:46 UTC, njuCZ commented
![image](https://user-images.githubusercontent.com/2786738/125223466-693b5a00-e2fe-11eb-9623-c3730f44738b.png)

2021-07-15 20:23 UTC, katbyte requested changes
Aside from a couple minor comments this looks good

2021-07-15 20:23 UTC, katbyte commented on azurerm/internal/services/datafactory/data_factory_integration_runtime_azure_ssis_resource.go
> +						"env": {
```suggestion
						"environment": {
```

2021-07-15 20:23 UTC, katbyte commented on azurerm/internal/services/datafactory/data_factory_integration_runtime_azure_ssis_resource.go
> +	result := &datafactory.IntegrationRuntimeDataProxyProperties{
```suggestion
	raw := input[0].(map[string]interface{})

	result := &datafactory.IntegrationRuntimeDataProxyProperties{
```

2021-07-16 05:42 UTC, njuCZ commented
@katbyte thanks for your suggestions. I have refined this PR

2021-07-17 00:22 UTC, katbyte approved these changes
Thanks @njuCZ - LGTM 🚀

2021-07-17 00:23 UTC, merged