r/`machine_learning_compute_cluster`: make `subnet_resource_id` optional
terraform-providers/terraform-provider-azurerm pull request #12558
Opened 2021-07-12 20:45 UTC by gro1m

PR to address complaint in https://github.com/terraform-providers/terraform-provider-azurerm/pull/12508 that `subnet_resource_id` is *not really* optional.

2021-07-13 11:08 UTC, aristosvo commented on azurerm/internal/services/machinelearning/machine_learning_compute_cluster_resource.go
> +		computeClusterAmlComputeProperties = machinelearningservices.AmlComputeProperties{
I'd do it like this:
```suggestion
	if d.Get("subnet_resource_id") != nil {
		computeClusterAmlComputeProperties..AmlComputeProperties.Subnet = &machinelearningservices.ResourceID{ID: utils.String(d.Get("subnet_resource_id").(string))}
```

2021-07-15 12:08 UTC, manicminer requested changes
Hi @gro1m, thanks for this fix. I have one suggestion, similar to @aristosvo's but using d.GetOk to test the value of `subnet_resource_id` and whether it is set.

2021-07-15 12:08 UTC, manicminer commented on azurerm/internal/services/machinelearning/machine_learning_compute_cluster_resource.go
> +		computeClusterAmlComputeProperties.Subnet = &machinelearningservices.ResourceID{ID: utils.String(d.Get("subnet_resource_id").(string))}
With `d.GetOk()`, we can check if the property was set, retrieve it and check if it's [not] the zero value

```suggestion
	if subnetId, ok := d.GetOk("subnet_resource_id"); ok && subnetId.(string) != "" {
		computeClusterAmlComputeProperties.Subnet = &machinelearningservices.ResourceID{ID: utils.String(subnetId.(string))}
```

2021-07-16 00:12 UTC, katbyte approved these changes
Thanks @gro1m - LGTM 🍰

2021-07-16 00:12 UTC, merged