New resource `azurerm_api_management_api_release`
terraform-providers/terraform-provider-azurerm pull request #12562
Opened 2021-07-13 06:39 UTC by yupwei68

Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/12428

2021-07-14 12:10 UTC, manicminer requested changes
Hi @yupwei68, thanks for this PR. I made some small suggestions below, if you can look at these and check the final argument for the CreateOrUpdate method, this should be good to merge assuming tests are passing. Thanks!

2021-07-14 12:10 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_api_release.go
> +		d.Set("api_id", props.APIID)
Can we construct a `parse.ApiId{}` and use it to set the `api_id` attribute?

2021-07-14 12:10 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_api_release.go
> +			log.Printf("[INFO] apimanagement %q does not exist - removing from state", d.Id())
```suggestion
			log.Printf("[INFO] apimanagement %s does not exist - removing from state", d.Id())
```

2021-07-14 12:10 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_api_release.go
> +		return fmt.Errorf("creating/ updating %q: %+v", id, err)
```suggestion
		return fmt.Errorf("creating/ updating %s: %+v", id, err)
```

2021-07-14 12:10 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_api_release.go
> +				return fmt.Errorf("checking for existing %q: %+v", id, err)
```suggestion
				return fmt.Errorf("checking for existing %s: %+v", id, err)
```

2021-07-14 12:10 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_api_release.go
> +		return fmt.Errorf("retrieving %q: %+v", id, err)
```suggestion
		return fmt.Errorf("retrieving %s: %+v", id, err)
```

2021-07-14 12:10 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_api_release.go
> +		return fmt.Errorf("deleting %q: %+v", id, err)
```suggestion
		return fmt.Errorf("deleting %s: %+v", id, err)
```

2021-07-14 12:10 UTC, manicminer commented on azurerm/internal/services/apimanagement/api_management_api_release.go
> +	if _, err := client.CreateOrUpdate(ctx, apiId.ResourceGroup, apiId.ServiceName, apiId.Name, name, parameters, ""); err != nil {
The method docstring for `APIReleaseClient{}.CreateOrUpdate()` says that `ifMatch` is required when updating a release; should it perhaps be `"*"` like it is for the `Delete()` method, or something else?

2021-07-15 07:56 UTC, yupwei68 commented
@manicminer Thanks. Please continue reviewing.

2021-07-15 10:57 UTC, manicminer approved these changes
Thanks @yupwei68, this LGTM 👍 

<img width="657" alt="Screenshot 2021-07-15 at 11 56 39" src="https://user-images.githubusercontent.com/251987/125777196-7b42522c-e4c0-49dc-947c-93757e5f0737.png">

2021-07-15 10:57 UTC, merged