new resource "azurerm_data_factory_managed_private_endpoint"
terraform-providers/terraform-provider-azurerm pull request #12618
Opened 2021-07-16 06:44 UTC by njuCZ

fixs #12364

if managed private endpoint is not existed, the get rest api will return 400 but not 404. So I use list rest api and then filter by name.

![image](https://user-images.githubusercontent.com/2786738/125904009-329083dd-f9d5-4378-8aa4-054a12222518.png)

2021-07-17 00:27 UTC, katbyte requested changes

2021-07-17 00:27 UTC, katbyte commented on website/docs/r/data_factory_managed_private_endpoint.html.markdown
> +* `subresource_name` - (Required) Specifies the sub resource name which the Data Factory Private Endpoint is able to connect to. Changing this forces a new resource to be created.
shouldn't this be
```suggestion
* `subresource_type` - (Required) Specifies the sub resource type which the Data Factory Private Endpoint is able to connect to. Changing this forces a new resource to be created.
```

2021-07-19 01:42 UTC, njuCZ commented
this resource is somewhat similar with source `azurerm_private_endpoint` and `azurerm_synpase_managed_private_endpoint`. To lign with these two resource, I think `subresource_name` might be better ? https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_managed_private_endpoint#subresource_name
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint#subresource_names

2021-07-19 23:32 UTC, katbyte approved these changes
Its not ideal that the other resources use a unclear name but they are what they are - LGTM 👍

2021-07-19 23:32 UTC, merged