fix crash when create compute cluster without specifying subtnetId
terraform-providers/terraform-provider-azurerm pull request #12658
Opened 2021-07-20 04:37 UTC by ms-henglu

2021-07-20 05:21 UTC, katbyte requested changes

2021-07-20 05:21 UTC, katbyte commented on azurerm/internal/services/machinelearning/machine_learning_compute_cluster_resource.go
> +	}
this all should be wrapped in a 
```
if (props := computeCluster.Properties; props != nil) {
```

block

2021-07-20 06:01 UTC, ms-henglu commented
@katbyte , thanks! I modified it according to your suggestion.

2021-07-21 00:27 UTC, manicminer approved these changes
Thanks @ms-henglu, this LGTM.

Test results with one unrelated failure:
<img width="664" alt="Screenshot 2021-07-21 at 01 26 37" src="https://user-images.githubusercontent.com/251987/126411584-e61dc4f6-bcb7-479f-ab0b-654ad73e863b.png">

2021-07-21 00:28 UTC, merged