"azurerm_data_factory_pipeline" - supports "concurrency", "elapsed_time_metric_duration" and "run_dimension"
terraform-providers/terraform-provider-azurerm pull request #12685
Opened 2021-07-22 06:38 UTC by njuCZ

fix #11506

"run_dimension" is a key value pair, but the value could be a string or an expression type, so made it TypeList. It's used by ChainingTrigger.

ChainingTrigger allows the referenced pipeline to depend on other pipeline runs based on runDimension Name/Value pairs. Upstream pipelines should declare the same runDimension Name and their runs should have the values for those runDimensions. The referenced pipeline run would be triggered if the values for the runDimension match for all upstream pipeline runs.

![image](https://user-images.githubusercontent.com/2786738/126598672-e15f0270-593f-4ee6-af2b-05ebb93f1be9.png)

2021-07-27 03:02 UTC, katbyte requested changes

2021-07-27 03:02 UTC, katbyte commented on website/docs/r/data_factory_pipeline.html.markdown
> +* `elapsed_time_metric_duration` - (Optional) The TimeSpan value after which an Azure Monitoring Metric is fired.
this property doesn't match the description
```suggestion
* `moniter_metrics_after_duration` - (Optional) The TimeSpan value after which an Azure Monitoring Metric is fired.
```

2021-07-27 03:02 UTC, katbyte commented on website/docs/r/data_factory_pipeline.html.markdown
> +
could we not have a _ in the sentance?
```suggestion
* `name` - The name of the run dimension.

* `value` - The value of the run dimension.

```

2021-07-27 03:02 UTC, katbyte commented on website/docs/r/data_factory_pipeline.html.markdown
> +* `dynamic_value_enabled` - is dynamic expression enabled for value?
what is a dynamic value?

2021-07-27 03:02 UTC, katbyte commented on website/docs/r/data_factory_pipeline.html.markdown
> +* `run_dimension` - (Optional) One or more `run_dimension` blocks as defined below.
what is a run dimension?

2021-07-27 07:06 UTC, ms-henglu commented
Hi @katbyte , I contacted with service team and removed `runDimension` property. Could you please take another look? Thanks!

2021-07-28 18:24 UTC, katbyte approved these changes
Thanks @njuCZ - LGTM 🚀

2021-07-28 18:24 UTC, merged