New Resource: azurerm_bot_channel_facebook
terraform-providers/terraform-provider-azurerm pull request #12709
Opened 2021-07-23 02:32 UTC by neil-yechenwei

Currently, TF doesn't support Bot Facebook Channel. So I submitted this PR to implement it.

Please refer this [doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0) to create test data for facebook.

--- PASS: TestAccBotChannelsRegistration/channel/facebookBasic (214.49s)
--- PASS: TestAccBotChannelsRegistration/channel/facebookUpdate (335.30s)
--- PASS: TestAccBotChannelsRegistration/channel/facebookRequiresImport (261.06s)

API reference:
https://github.com/Azure/azure-rest-api-specs/blob/b20011746ef065a8ab6572045de9578c192f2ffd/specification/botservice/resource-manager/Microsoft.BotService/stable/2021-03-01/botservice.json#L1437

2021-07-24 21:29 UTC, katbyte requested changes

2021-07-24 21:29 UTC, katbyte commented on website/docs/r/bot_channel_facebook.markdown
> +* `app_id` - (Required) The Facebook Application ID for the Facebook Channel.
lets be explicit with what this is?
```suggestion
* `facebook_application_id` - (Required) The Facebook Application ID for the Facebook Channel.
```

2021-07-24 21:29 UTC, katbyte commented on website/docs/r/bot_channel_facebook.markdown
> +* `app_secret` - (Required) The Facebook Application Secret for the Facebook Channel.
and here
```suggestion
* `facebook_application_secret` - (Required) The Facebook Application Secret for the Facebook Channel.
```

2021-07-25 06:37 UTC, neil-yechenwei commented on website/docs/r/bot_channel_facebook.markdown
> +* `app_id` - (Required) The Facebook Application ID for the Facebook Channel.
Updated

2021-07-25 06:40 UTC, neil-yechenwei commented on website/docs/r/bot_channel_facebook.markdown
> +* `app_secret` - (Required) The Facebook Application Secret for the Facebook Channel.
Updated

2021-07-25 08:14 UTC, neil-yechenwei commented
@katbyte , thanks for your comments. I've updated code. Please have an another look. Thanks.

2021-07-26 03:20 UTC, katbyte approved these changes
Thanks @neil-yechenwei - LGTM 🚀

2021-07-26 03:20 UTC, merged