New Resource: azurerm_bot_channel_sms
terraform-providers/terraform-provider-azurerm pull request #12713
Opened 2021-07-23 08:50 UTC by neil-yechenwei

Currently, TF doesn't support Bot SMS Channel. So I submitted this PR to implement it.

Please refer this [doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-4.0) to create SMS account for testing.

I cannot add update test case for below issues:
1. It requires phone verification while creating the SMS account and the phone number cannot be used while creating another SMS account. As I have only one mobile phone, so I only can create a private SMS account for testing.
2. Once the SMS account is created, this account has one month free trial and it only can bind one phone number. So I cannot create two phone numbers for testing.

--- PASS: TestAccBotChannelsRegistration/channel/smsBasic (230.10s)
--- PASS: TestAccBotChannelsRegistration/channel/smsRequiresImport (251.26s)

API Reference:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/botservice/resource-manager/Microsoft.BotService/stable/2021-03-01/botservice.json#L1785

2021-07-24 21:27 UTC, katbyte requested changes

2021-07-24 21:27 UTC, katbyte commented on website/docs/r/bot_channel_sms.markdown
> +* `account_sid` - (Required) The account security identifier (SID) for the SMS Channel.
lets be a bit more clear here?

```suggestion
* `sms_channel_account_security_id` - (Required) The account security identifier (SID) for the SMS Channel.
```

2021-07-24 21:27 UTC, katbyte commented on website/docs/r/bot_channel_sms.markdown
> +* `auth_token` - (Required) The authorization token for the SMS Channel.
```suggestion
* `sms_channel_auth_token` - (Required) The authorization token for the SMS Channel.
```

2021-07-25 05:44 UTC, neil-yechenwei commented on website/docs/r/bot_channel_sms.markdown
> +* `auth_token` - (Required) The authorization token for the SMS Channel.
Updated

2021-07-25 05:56 UTC, neil-yechenwei commented on website/docs/r/bot_channel_sms.markdown
> +* `account_sid` - (Required) The account security identifier (SID) for the SMS Channel.
Updated

2021-07-25 06:29 UTC, neil-yechenwei commented
@katbyte , thanks for your comments. I've updated code. Please have an another look. Thanks.

2021-07-26 03:21 UTC, katbyte approved these changes
LGTM 🌿  - just needs conflicts fixed up

2021-07-26 04:15 UTC, merged