kubernetes_cluster supports maintenance_config
terraform-providers/terraform-provider-azurerm pull request #12762
Opened 2021-07-28 04:25 UTC by ms-henglu

2021-07-30 18:21 UTC, katbyte requested changes
THis is causing all tests to fail:
```
------- Stdout: -------
=== RUN   TestAccKubernetesCluster_privateClusterOnWithPrivateDNSZoneSubDomain
=== PAUSE TestAccKubernetesCluster_privateClusterOnWithPrivateDNSZoneSubDomain
=== CONT  TestAccKubernetesCluster_privateClusterOnWithPrivateDNSZoneSubDomain
    testcase.go:88: Step 1/1 error: Error running apply: exit status 1
        
        Error: retrieving Maintenance Configuration for Managed Kubernetes Cluster ("Cluster: (Managed Cluster Name \"acctestaks210730050729703273\" / Resource Group \"acctestRG-aks-210730050729703273\")"): containerservice.MaintenanceConfigurationsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="Could not find the maintenance configuration: default in subscription: *******, resourceGroup: acctestRG-aks-210730050729703273, resourceName: acctestaks210730050729703273."
        
          with azurerm_kubernetes_cluster.test,
          on terraform_plugin_test.tf line 28, in resource "azurerm_kubernetes_cluster" "test":
          28: resource "azurerm_kubernetes_cluster" "test" {
        
--- FAIL: TestAccKubernetesCluster_privateClusterOnWithPrivateDNSZoneSubDomain (1021.31s)
FAIL
```

2021-08-04 01:25 UTC, ms-henglu commented
@katbyte , Hi, I've updated the commit, could you please take another look? Thanks!

2021-08-04 02:58 UTC, katbyte requested changes

2021-08-04 02:58 UTC, katbyte commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +			"maintenance_config": {
i think config is redundant here, this is more a window?
```suggestion
			"maintenance_window": {
```

2021-08-04 02:58 UTC, katbyte commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +						"maintenance_allowed": {
and maintaince is redundant
```suggestion
						"allowed": {
```

2021-08-04 02:58 UTC, katbyte commented on azurerm/internal/services/containers/kubernetes_cluster_resource.go
> +									"hour_slots": {
does slots make sense? hours seems fine
```suggestion
									"hours": {
```

2021-08-04 04:32 UTC, ms-henglu commented
@katbyte , thanks! I've added a commit to rename the fields according to your suggestions.

2021-08-05 03:09 UTC, katbyte approved these changes
thanks @ms-henglu - LGTM 🚀

2021-08-05 03:10 UTC, merged