`azurerm_monitor_activity_log_alert` - fix action webhook
terraform-providers/terraform-provider-azurerm pull request #19425
Opened 2022-11-24 11:02 UTC by teowa

resolves #19408

Change `action` block from `TypeSet` to `TypeList`.  I think no need to use `TypeSet` here.
```
make acctests SERVICE="monitor" TESTARGS="-parallel 1 -test.run=TestAccMonitorActivityLogAlert_actionWebhook" TESTTIMEOUT='1440m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/monitor -parallel 1 -test.run=TestAccMonitorActivityLogAlert_actionWebhook -timeout 1440m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccMonitorActivityLogAlert_actionWebhook
=== PAUSE TestAccMonitorActivityLogAlert_actionWebhook
=== CONT  TestAccMonitorActivityLogAlert_actionWebhook
--- PASS: TestAccMonitorActivityLogAlert_actionWebhook (521.17s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/monitor       522.369s

```

2022-11-24 11:46 UTC, jackofallops requested changes
Hi @teowa 
Can you add testing around multiple `action` blocks?  The behaviour of the List vs Set won't be apparent with only 1 item, we'll need several to ensure that there are not ordering issues in the responses etc.

Thanks!

2022-11-24 12:58 UTC, teowa commented
```
TF_ACC=1 go test -v ./internal/services/monitor -parallel 1 -test.run=TestAccMonitorActivityLogAlert_actionWebhook -timeout 1440m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccMonitorActivityLogAlert_actionWebhook
=== PAUSE TestAccMonitorActivityLogAlert_actionWebhook
=== CONT  TestAccMonitorActivityLogAlert_actionWebhook
--- PASS: TestAccMonitorActivityLogAlert_actionWebhook (353.24s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/monitor       354.404s

```

2022-11-28 10:05 UTC, stephybun approved these changes
Thanks @teowa, LGTM 🌵

2022-11-28 10:05 UTC, merged

2022-11-29 13:30 UTC, sanderrhorst commented
Hi @teowa and @stephybun, the issue that I reported ( #19408 ) is not fixed. I have just updated to the latest version of the azurerm provider in my config and changed the webhook_properties in the action block, but again, with running terraform plan, no changes to the webhook_properties are shown in the plan. 

Please look into this!