New Resource: `azurerm_certificate_order_certificate`
terraform-providers/terraform-provider-azurerm pull request #25464
Opened 2024-03-29 02:24 UTC by xiaxyi

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Enable user to bind certificate order to key vault using the api:["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CertificateRegistration/certificateOrders/{certificateOrderName}/certificates/{name}"](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.CertificateRegistration/stable/2023-01-01/AppServiceCertificateOrders.json#L401)

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

* `azurerm_app_service_certificate_order_certificate` - Support key vault binding.

This is a (please select all that apply):

- [ ] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-04-17 13:12 UTC, stephybun reviewed
Thanks @xiaxyi. Would you be able to provide some more detail on what this actually does? I see in the description that it enables binding a certificate order to a key vault, but what does that mean or do in an App Service context?

2024-04-23 07:37 UTC, xiaxyi commented
Thanks @stephybun for the review!

The feature is to configure the key vault information for a purchased app service certificate. After user buy an app service certificate using `azurerm_app_service_certificate_order`, the certificate configuration isn't completed as displayed in bleow screenshots:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/92154856/05a9f014-d84d-409d-b94a-d2a0f9bfa9a9)
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/92154856/ee5f1746-74eb-46b2-a6f6-ec896cc6a6e4)

API reference:https://learn.microsoft.com/en-us/rest/api/appservice/app-service-certificate-orders/create-or-update-certificate?view=rest-appservice-2023-01-01&tabs=HTTP
Docs" https://learn.microsoft.com/en-us/azure/app-service/configure-ssl-app-service-certificate?tabs=portal

Let me know if there is anything that's still not clear to you.

2024-05-21 09:08 UTC, stephybun requested changes
@xiaxyi could you please take a look through the comments and suggestions left in-line. Once those are fixed up we can take another look through this.

2024-05-21 09:08 UTC, stephybun commented on website/docs/r/app_service_certificate_order_certificate.html.markdown
> +* `name` - (Required) Specifies the name of the certificate order certificate key vault binding. Changing this forces a new resource to be created.
```suggestion
* `name` - (Required) Specifies the name of the Certificate Key Vault Store. Changing this forces a new resource to be created.
```

2024-05-21 09:08 UTC, stephybun commented on website/docs/r/app_service_certificate_order_certificate.html.markdown
> +* `certificate_order_id` - (Required) The id of the certificate order in which to configure the certificate. Changing this forces a new resource to be created.
```suggestion
* `certificate_order_id` - (Required) The ID of the Certificate Order in which to configure the Certificate Key Vault Store Binding. Changing this forces a new resource to be created.
```

2024-05-21 09:08 UTC, stephybun commented on website/docs/r/app_service_certificate_order_certificate.html.markdown
> +* `key_vault_id` - (Required) The id of the key vault in which to bind the certificate order certificate.
```suggestion
* `key_vault_id` - (Required) The ID of the Key Vault in which to bind the Certificate.
```

2024-05-21 09:08 UTC, stephybun commented on website/docs/r/app_service_certificate_order_certificate.html.markdown
> +* `key_vault_secret_name` - (Required) The name of the key vault secrete in which to bind the certificate order certificate.
```suggestion
* `key_vault_secret_name` - (Required) The name of the Key Vault Secret to bind to the Certificate.
```

2024-05-21 09:08 UTC, stephybun commented on website/docs/r/app_service_certificate_order_certificate.html.markdown
> +* `location` - The location of the certificate order certificate.
```suggestion
* `location` - The location of the Certificate.
```

2024-05-21 09:08 UTC, stephybun commented on website/docs/r/app_service_certificate_order_certificate.html.markdown
> +* `type` - The type of the certificate order certificate.
```suggestion
* `type` - The type of Certificate.
```

2024-06-03 06:31 UTC, xiaxyi commented on internal/services/appservice/app_service_certificate_order_certificate.go
> +		},
I'm afraid not, because we are not referring to a key vault secret, instead, we are creating the secret in the key vault with a name specified.

2024-09-23 22:40 UTC, Gabryel8818 commented
Hello Guys, any updates for this? 

I have used terraform app_service_certificate and missing key store 

I have very animated for this resource

2024-11-11 20:12 UTC, Gabryel8818 commented
[stephybun](https://github.com/stephybun)

@stephybun Hello, how are you? :D 

 do you can check this PR with your Request Change?

2024-11-11 20:12 UTC, igoritos22 commented
Hi guys, this feature is very important.
Any updates about that?

2025-01-29 10:50 UTC, stephybun requested changes

2025-01-29 10:50 UTC, stephybun commented on internal/services/appservice/client/client.go
> +	AppServiceCertificatesOrderClient *appservicecertificateorders.AppServiceCertificateOrdersClient
Alphabetical ordering

2025-01-29 10:50 UTC, stephybun commented on internal/services/appservice/client/client.go
> +		AppServiceCertificatesOrderClient: appServiceCertificatesOrderClient,
Alphabetical ordering

2025-01-29 10:50 UTC, stephybun commented on internal/services/appservice/app_service_certificate_order_key_vault_store.go
> +			DiffSuppressFunc: suppress.CaseDifference,
We handle differences in casing by parsing the resource ID insensitively in the read so this doesn't need to be set.
```suggestion
```

2025-01-29 10:50 UTC, stephybun commented on internal/services/appservice/app_service_certificate_order_key_vault_store.go
> +			state.CertificateOrderId = certificateOrderId.ID()
```suggestion
				Name: id.CertificateName,
				CertificateOrderId: appservicecertificateorders.NewCertificateOrderID(id.SubscriptionId, id.ResourceGroupName, id.CertificateOrderName)
			}
```

2025-01-29 10:50 UTC, stephybun commented on internal/services/appservice/app_service_certificate_order_key_vault_store.go
> +		},
We don't expose the top level `type` field for resources, also this isn't defined in the resource's model struct and isn't being set in the read so this should be removed 
```suggestion
```

2025-01-29 10:50 UTC, stephybun commented on website/docs/r/app_service_certificate_order_key_vault_store.html.markdown
> +    object_id = "f8daea97-62e7-4026-becf-13c2ea98e8b4"
Probably not a good idea to use what looks like an actual value here
```suggestion
    object_id = data.azurerm_client_config.test.object_id
```

2025-01-29 10:50 UTC, stephybun commented on website/docs/r/app_service_certificate_order_key_vault_store.html.markdown
> +    object_id = "ed47c2a1-bd23-4341-b39c-f4fd69138dd3"
Same here, can you please replace this with an appropriate reference

2025-01-29 10:50 UTC, stephybun commented on website/docs/r/app_service_certificate_order_key_vault_store.html.markdown
> +Manages an App Service Certificate Order Certificate.
Please update these description to better reflect what the resource does and the resource's name
```suggestion
  Manages an App Service Certificate Order for Storage in a Key Vault.

---

# azurerm_app_service_certificate_order_key_vault_store

Manages an App Service Certificate Order for Storage in a Key Vault.
```

2025-01-29 10:50 UTC, stephybun commented on website/docs/r/app_service_certificate_order_key_vault_store.html.markdown
> +* `type` - The type of the certificate.
```suggestion
* `type` - The type of the certificate.
```

2025-01-29 10:50 UTC, stephybun commented on website/docs/r/app_service_certificate_order_key_vault_store.html.markdown
> +* `type` - The type of the certificate.
```suggestion
```

2025-01-29 10:50 UTC, stephybun commented on website/docs/r/app_service_certificate_order_key_vault_store.html.markdown
> +* `location` - The location of the certificate.
```suggestion
* `location` - The location of the Certificate.
```

2025-01-29 10:50 UTC, stephybun commented on website/docs/r/app_service_certificate_order_key_vault_store.html.markdown
> +App Service Certificate Order Certificate can be imported using the `resource id`, e.g.
```suggestion
* `create` - (Defaults to 30 minutes) Used when creating the App Service Certificate Order Key Vault Store.
* `update` - (Defaults to 30 minutes) Used when updating the App Service Certificate Order Key Vault Store.
* `read` - (Defaults to 5 minutes) Used when retrieving the App Service Certificate Order Key Vault Store.
* `delete` - (Defaults to 30 minutes) Used when deleting the App Service Certificate Order Key Vault Store.

## Import

An App Service Certificate Order Key Vault Store can be imported using the `resource id`, e.g.
```

2025-02-11 05:58 UTC, xiaxyi commented on website/docs/r/app_service_certificate_order_key_vault_store.html.markdown
> +    object_id = "ed47c2a1-bd23-4341-b39c-f4fd69138dd3"
I will avoid using the real value next time.

2025-02-11 06:04 UTC, xiaxyi commented
Thanks @stephybun , the codes are updated.

2025-05-06 17:27 UTC, montgomery-plattner-kh commented
@stephybun @xiaxyi Has there been any progress on this PR since 02/2025?

2025-07-11 01:06 UTC, lonegunmanb commented
For anyone who is eager to use this resource in Terraform, we have just released an AVM module as pilot, you can try it here: https://registry.terraform.io/modules/Azure/avm-res-certificateregistration-certificateorder/azurerm/latest

2026-01-29 22:05 UTC, Gabryel8818 commented
any updates for this?

2026-06-24 07:20 UTC, closed without merging