`azurerm_windows_web_app`, `azurerm_windows_function_app`, `azurerm_linux_function_app`, `azurerm_linux_web_app` - add `minimum_tls_cipher_suite` property
terraform-providers/terraform-provider-azurerm pull request #26584
Opened 2024-07-10 06:49 UTC by xiaxyi

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_windows_web_app`, `azurerm_windows_function_app`, `azurerm_linux_function_app`, `azurerm_linux_web_app` - support for the`minimum_tls_cipher_suite` property.
* 

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #24223 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-07-31 06:29 UTC, jackofallops requested changes
Thanks @xiaxyi - This looks good, but we'll end up with the related `slot` resources out of step, can you either add the same property there, or open a 2nd PR with those in so we can merge it all together? 

Thanks

2024-08-07 09:45 UTC, xiaxyi commented
Thanks @jackofallops for the review! Added the property to the slot in this pr. Let me know if anything needed.

2024-09-09 01:07 UTC, Tolbin400 commented
@xiaxyi @jackofallops what outstanding items are there before the pr can be approved for release?

2024-09-23 11:34 UTC, DempseySbaiz commented
Any updates on this please, our client is asking for this feature.
The change request has been addressed in the PR.

2024-10-21 17:07 UTC, serakis commented
Also interested to get this feature! Any news on the progress?

2024-12-03 09:20 UTC, jackofallops requested changes
Hi @xiaxyi - Thanks for making those changes. I've left one comment below regarding what appears to be a copy-paste error if you can take a look. Also, some tests are now failing with errors of the following type:
```performing CreateOrUpdateSlot:
        unexpected status 400 (400 Bad Request) with response:
        {"Code":"BadRequest","Message":"Tls13 does not support re-negotiation. Please
        either disable ClientCert, or set ClientCertMode to Application or Required
        (without exclsuion paths).","Target":null,"Details":[{"Message":"Tls13 does
        not support re-negotiation. Please either disable ClientCert, or set
        ClientCertMode to Application or Required (without exclsuion
        paths)``` 
(The typo in the error message there is from the API)

I'll link you the regression test run from the CI server offline.

2025-01-21 10:37 UTC, jackofallops requested changes
Hi @xiaxyi - Thanks for the updates, looks like there's still a test that is failing due to a `ForceNew` change.
```
------- Stdout: -------
=== RUN   TestAccLinuxFunctionApp_tlsSettingUpdate
=== PAUSE TestAccLinuxFunctionApp_tlsSettingUpdate
=== CONT  TestAccLinuxFunctionApp_tlsSettingUpdate
    testcase.go:173: Step 4/12 error: Pre-apply plan check(s) failed:
        'azurerm_linux_function_app.test' - expected action to not be Replace, path: [[name]] tried to update a value that is ForceNew
--- FAIL: TestAccLinuxFunctionApp_tlsSettingUpdate (433.71s)
```

2025-03-08 04:08 UTC, xiaxyi commented
@jackofallops Sorry for the late update, the test case is updated, would you mind taking another look?
@katbyte FYI

2025-03-19 08:25 UTC, jackofallops commented
> @jackofallops Sorry for the late update, the test case is updated, would you mind taking another look? @katbyte FYI

Hi @xiaxyi - Looks like there are still test failures relating to this change on CI, can you take a look at the latest run for the branch? (Run ID: 518)

2025-03-21 09:19 UTC, xiaxyi commented
Thank @jackofallops , no worries, I updated the test cases to remove the conflict between the client cert setting and the tls 13 suite.

2025-04-10 19:47 UTC, mbfrahry requested changes, later dismissed
Hey @xiaxyi, this looks good but the docs could use a little cleanup

2025-04-10 19:47 UTC, mbfrahry commented on website/docs/r/linux_function_app.html.markdown
> +~> **Note:**   TLS 1.3 and HTTP 2.0 don't support TLS renegotiation. These protocols will not work if your app is configured with client certificate settings that use TLS renegotiation. Either disabl
It's not immediately clear what `ClientCert` or `ClientCertMode` are in Terraform terms. We should have those Terraform variable names in the note instead

2025-04-10 19:47 UTC, mbfrahry commented on website/docs/r/linux_function_app_slot.html.markdown
> +~> **Note:**   TLS 1.3 and HTTP 2.0 don't support TLS renegotiation. These protocols will not work if your app is configured with client certificate settings that use TLS renegotiation. Either disabl
We should have these notes in the same place across the docs

2025-04-10 19:47 UTC, mbfrahry commented on website/docs/r/linux_function_app_slot.html.markdown
> +~> **Note:**   TLS 1.3 and HTTP 2.0 don't support TLS renegotiation. These protocols will not work if your app is configured with client certificate settings that use TLS renegotiation. Either disabl
Also, just to confirm, are these notes also applicable to the other resources that have been touched?

2025-05-02 08:36 UTC, WodansSon commented
`TLS 1.3` implementations affects multiple resources [Frontdoor](https://github.com/hashicorp/terraform-provider-azurerm/issues/25881), [SQL Server](https://github.com/hashicorp/terraform-provider-azurerm/issues/26240), [Storage Account](https://github.com/hashicorp/terraform-provider-azurerm/issues/26712), etc. So we need to be very mindful of how this is implemented and should make the implementation across all Terraform resources consistent.

2025-05-02 16:51 UTC, rmcolbert commented
This PR is not about TLS 1.3 implementation. This is purely to support the minimum cipher property (which covers ciphers of various strengths and protocol as implemented by Microsoft). It just so happens that the first two ciphers in the list are TLS 1.3-only but this is not specifically related to the TLS version property.

2025-05-07 08:18 UTC, xiaxyi commented on website/docs/r/linux_function_app_slot.html.markdown
> +~> **Note:**   TLS 1.3 and HTTP 2.0 don't support TLS renegotiation. These protocols will not work if your app is configured with client certificate settings that use TLS renegotiation. Either disabl
updated the notes to all the toched resources

2025-05-28 23:36 UTC, dvasdekis commented
Hi @mbfrahry would you have time to re-review these changes?

2025-06-13 02:36 UTC, dvasdekis commented
Another gentle nudge for @mbfrahry @stephybun and @jackofallops as we approach the 1 year mark for this issue

2025-09-29 09:08 UTC, ranjan-tim commented
gentle reminder @katbyte . thanks !

2025-10-31 14:51 UTC, rmcolbert commented
Another gentle nudge for @mbfrahry @stephybun and @jackofallops

2025-12-10 00:39 UTC, Tolbin400 commented
Nudge again please can we get this closed off @jackofallops @mbfrahry

2026-05-18 12:15 UTC, xiaxyi commented
update rerun acctests:
```
--- PASS: TestAccLinuxFunctionApp_tlsSettingUpdate (1037.98s)
--- PASS: TestAccLinuxFunctionAppSlot_tlsSettingUpdate (1037.98s)

--- PASS: TestAccWindowsFunctionApp_tlsSettingUpdate (752.86s)
--- PASS: TestAccWindowsFunctionAppSlot_tlsSettingUpdate (1009.68s)

--- PASS: TestAccLinuxWebApp_tlsSettingUpdate (622.42s)
--- PASS: TestAccLinuxWebAppSlot_tlsSettingUpdate (895.21s)

--- PASS: TestAccWindowsWebApp_tlsSettingUpdate (607.39s)
--- PASS: TestAccWindowsWebAppSlot_tlsSettingUpdate (918.67s)
```

2026-05-19 01:12 UTC, ziyeqf approved these changes
Thanks @xiaxyi! mostly LGTM, please update the PR description accrodingly.

2026-05-19 07:01 UTC, jackofallops approved these changes
Thanks @xiaxyi - LGTM 👍

2026-05-19 07:03 UTC, merged