`azurerm_container_app_environment`: fix `infrastructure_resource_group_name` behavior with `workload_profile` set to `Consumption`
terraform-providers/terraform-provider-azurerm pull request #27502
Opened 2024-09-25 08:56 UTC by jiaweitao001

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

`infrastructure_resource_group_name` will be generated by the service even with `workload_profile` set to `Consumption`, this will cause unexpected changes in the state file.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_container_app_environment`: fix `infrastructure_resource_group_name` behavior with `workload_profile` set to `Consumption` [GH-27481]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27481

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-09-26 15:53 UTC, J0F3 commented on internal/services/containerapps/container_app_environment_resource.go
> +			DiffSuppressFunc: func(k, oldValue, newValue string, d *pluginsdk.ResourceData) bool { // If this is omitted, then the service generates a value for the required manage resource group.
```suggestion
			DiffSuppressFunc: func(k, oldValue, newValue string, d *pluginsdk.ResourceData) bool { // If this is omitted and workload_profile is set, then the service generates a value for the required manage resource group.
```

Maybe?

2024-09-26 15:53 UTC, J0F3 commented on internal/services/containerapps/container_app_environment_resource.go
> +					return true
LGTM 👍🏻

2024-09-27 06:12 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_environment_resource.go
> +			DiffSuppressFunc: func(k, oldValue, newValue string, d *pluginsdk.ResourceData) bool { // If this is omitted, then the service generates a value for the required manage resource group.
Make sense, will add this line.

2024-09-27 06:12 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_environment_resource_test.go
> +  zone_redundancy_enabled = true
Sure.

2026-04-17 15:46 UTC, catriona-m requested changes
Thanks for submitting this @jiaweitao001 - this looks good to me, however it seems there are merge conflicts on this pr now, but once that is fixed up I will take another look.

2026-04-20 03:23 UTC, jiaweitao001 commented
> Thanks for submitting this @jiaweitao001 - this looks good to me, however it seems there are merge conflicts on this pr now, but once that is fixed up I will take another look.

Sure. Rebased.

2026-04-20 14:52 UTC, catriona-m requested changes
Thanks @jiaweitao001 - I ran the tests on this and it looks like there is a failure, could you take a look?

```
------- Stdout: -------
=== RUN   TestAccContainerAppEnvironment_zoneRedundant
=== PAUSE TestAccContainerAppEnvironment_zoneRedundant
=== CONT  TestAccContainerAppEnvironment_zoneRedundant
    testcase.go:203: Step 1/3 error: After applying this test step, the non-refresh plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
        -/+ destroy and then create replacement
        Terraform will perform the following actions:
          # azurerm_container_app_environment.test must be replaced
        -/+ resource "azurerm_container_app_environment" "test" {
              ~ custom_domain_verification_id               = "633CA537530783A9D6C4F655280B4FACA5D10CD906F227C70F7B5C7DD73DE026" -> (known after apply)
              ~ default_domain                              = "kindbush-b381635c.southcentralus.azurecontainerapps.io" -> (known after apply)
              + docker_bridge_cidr                          = (known after apply)
              ~ id                                          = "/subscriptions/*******/resourceGroups/acctestRG-CAE-260420111650481139/providers/Microsoft.App/managedEnvironments/acctest-CAEnv260420111650481139" -> (known after apply)
              - infrastructure_resource_group_name          = "ME_acctest-CAEnv260420111650481139_acctestRG-CAE-260420111650481139_southcentralus" -> null # forces replacement
              + logs_destination                            = (known after apply)
                name                                        = "acctest-CAEnv260420111650481139"
              + platform_reserved_cidr                      = (known after apply)
              + platform_reserved_dns_ip_address            = (known after apply)
              ~ public_network_access                       = "Disabled" -> (known after apply)
              ~ static_ip_address                           = "10.0.1.39" -> (known after apply)
                tags                                        = {
                    "Foo"    = "Bar"
                    "secret" = "sauce"
                }
                # (8 unchanged attributes hidden)
            }
        Plan: 1 to add, 0 to change, 1 to destroy.
--- FAIL: TestAccContainerAppEnvironment_zoneRedundant (1395.94s)
FAIL
```

2026-04-21 02:31 UTC, jiaweitao001 commented
> Thanks @jiaweitao001 - I ran the tests on this and it looks like there is a failure, could you take a look?
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccContainerAppEnvironment_zoneRedundant
> === PAUSE TestAccContainerAppEnvironment_zoneRedundant
> === CONT  TestAccContainerAppEnvironment_zoneRedundant
>     testcase.go:203: Step 1/3 error: After applying this test step, the non-refresh plan was not empty.
>         stdout:
>         Terraform used the selected providers to generate the following execution
>         plan. Resource actions are indicated with the following symbols:
>         -/+ destroy and then create replacement
>         Terraform will perform the following actions:
>           # azurerm_container_app_environment.test must be replaced
>         -/+ resource "azurerm_container_app_environment" "test" {
>               ~ custom_domain_verification_id               = "633CA537530783A9D6C4F655280B4FACA5D10CD906F227C70F7B5C7DD73DE026" -> (known after apply)
>               ~ default_domain                              = "kindbush-b381635c.southcentralus.azurecontainerapps.io" -> (known after apply)
>               + docker_bridge_cidr                          = (known after apply)
>               ~ id                                          = "/subscriptions/*******/resourceGroups/acctestRG-CAE-260420111650481139/providers/Microsoft.App/managedEnvironments/acctest-CAEnv260420111650481139" -> (known after apply)
>               - infrastructure_resource_group_name          = "ME_acctest-CAEnv260420111650481139_acctestRG-CAE-260420111650481139_southcentralus" -> null # forces replacement
>               + logs_destination                            = (known after apply)
>                 name                                        = "acctest-CAEnv260420111650481139"
>               + platform_reserved_cidr                      = (known after apply)
>               + platform_reserved_dns_ip_address            = (known after apply)
>               ~ public_network_access                       = "Disabled" -> (known after apply)
>               ~ static_ip_address                           = "10.0.1.39" -> (known after apply)
>                 tags                                        = {
>                     "Foo"    = "Bar"
>                     "secret" = "sauce"
>                 }
>                 # (8 unchanged attributes hidden)
>             }
>         Plan: 1 to add, 0 to change, 1 to destroy.
> --- FAIL: TestAccContainerAppEnvironment_zoneRedundant (1395.94s)
> FAIL
> ```

Hi @catriona-m - This is an existing issue on this resource. It's irrelevant to the change here. I can create another PR for it.

2026-04-24 14:33 UTC, catriona-m commented
> > Thanks @jiaweitao001 - I ran the tests on this and it looks like there is a failure, could you take a look?
> > ```
> > ------- Stdout: -------
> > === RUN   TestAccContainerAppEnvironment_zoneRedundant
> > === PAUSE TestAccContainerAppEnvironment_zoneRedundant
> > === CONT  TestAccContainerAppEnvironment_zoneRedundant
> >     testcase.go:203: Step 1/3 error: After applying this test step, the non-refresh plan was not empty.
> >         stdout:
> >         Terraform used the selected providers to generate the following execution
> >         plan. Resource actions are indicated with the following symbols:
> >         -/+ destroy and then create replacement
> >         Terraform will perform the following actions:
> >           # azurerm_container_app_environment.test must be replaced
> >         -/+ resource "azurerm_container_app_environment" "test" {
> >               ~ custom_domain_verification_id               = "633CA537530783A9D6C4F655280B4FACA5D10CD906F227C70F7B5C7DD73DE026" -> (known after apply)
> >               ~ default_domain                              = "kindbush-b381635c.southcentralus.azurecontainerapps.io" -> (known after apply)
> >               + docker_bridge_cidr                          = (known after apply)
> >               ~ id                                          = "/subscriptions/*******/resourceGroups/acctestRG-CAE-260420111650481139/providers/Microsoft.App/managedEnvironments/acctest-CAEnv260420111650481139" -> (known after apply)
> >               - infrastructure_resource_group_name          = "ME_acctest-CAEnv260420111650481139_acctestRG-CAE-260420111650481139_southcentralus" -> null # forces replacement
> >               + logs_destination                            = (known after apply)
> >                 name                                        = "acctest-CAEnv260420111650481139"
> >               + platform_reserved_cidr                      = (known after apply)
> >               + platform_reserved_dns_ip_address            = (known after apply)
> >               ~ public_network_access                       = "Disabled" -> (known after apply)
> >               ~ static_ip_address                           = "10.0.1.39" -> (known after apply)
> >                 tags                                        = {
> >                     "Foo"    = "Bar"
> >                     "secret" = "sauce"
> >                 }
> >                 # (8 unchanged attributes hidden)
> >             }
> >         Plan: 1 to add, 0 to change, 1 to destroy.
> > --- FAIL: TestAccContainerAppEnvironment_zoneRedundant (1395.94s)
> > FAIL
> > ```
> 
> Hi @catriona-m - This is an existing issue on this resource. It's irrelevant to the change here. I can create another PR for it.

Thanks @jiaweitao001, it would be good to fix this up in another pr

2026-04-24 14:33 UTC, catriona-m approved these changes
Thanks @jiaweitao001 LGTM!

2026-04-24 14:35 UTC, merged