`azurerm_databricks_workspace`: managed service/disk support managed hsm key
terraform-providers/terraform-provider-azurerm pull request #27849
Opened 2024-11-01 03:19 UTC by wuxu92

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

**DRAFT FOR INTERNAL REVIEW**

This PR adds Managed HSM Key support for both managed services and managed disks.

It also deprecates the optional key vault ID property for both, as it is unnecessary. The Databricks server can validate the key's availability, so `managed_services_cmk_key_vault_id` and `managed_disk_cmk_key_vault_id` have been removed from the documentation. A deprecated description has been added to them, but they are not being removed from the schema to avoid introducing a breaking change.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

![image](https://github.com/user-attachments/assets/c684a575-103b-4444-902a-efa35d4dba1f)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_databricks_workspace` - support managed hsm key as managed service and managed disk encription [GH-27738]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27738

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-11-15 03:41 UTC, WodansSon requested changes
Hi @wuxu92, I have given this PR and it mostly looks good, however I have left a few minor comments around the schema and depreciation text. If you can get those fixed up, I think this will be good to move out of draft state. 🚀

2024-11-15 03:41 UTC, WodansSon commented on internal/services/databricks/databricks_workspace_resource.go
> +				ConflictsWith: []string{"managed_disk_cmk_managed_hsm_key_id"},
Shouldn't this also conflict with `managed_disk_cmk_key_vault_id`?
```suggestion
				ConflictsWith: []string{"managed_disk_cmk_managed_hsm_key_id", "managed_disk_cmk_key_vault_id"},
```

2024-11-15 07:08 UTC, WodansSon commented
@wuxu92, thanks for pushing those changes so quickly. This LGTM now! 🚀

2024-11-15 09:05 UTC, stephybun requested changes
Hey @wuxu92, could you please follow the guidance in our [breaking changes guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-breaking-changes.md#breaking-schema-changes-and-deprecations) when deprecating properties? Once those changes have been made can you please also provide testing evidence in both 4.x and 5.0 mode. Thanks!

2025-01-28 10:51 UTC, stephybun commented
@wuxu92 I started a review on this a while ago, but since then the CreateUpdate method in this resource has been split. Could you please rebase this PR? I can continue the review once that's been done.

2025-02-24 14:03 UTC, stephybun requested changes
Thanks for rebasing @wuxu92.

In addition to the comments left in-line, can you please provide local testing evidence for the tests in 4.x as well as 5.0 mode?

2025-02-24 14:03 UTC, stephybun commented on website/docs/r/databricks_workspace.html.markdown
> +* `managed_services_cmk_key_vault_key_id` - (Optional) Customer managed encryption properties using a versioned Key Vaule Key ID for the Databricks Workspace managed resources(e.g. Notebooks and Arti
```suggestion
* `managed_services_cmk_key_vault_key_id` - (Optional) Customer managed encryption properties using a versioned Key Vault Key ID for the Databricks Workspace managed resources e.g. Notebooks and Artifacts.
```

2025-02-24 14:03 UTC, stephybun commented on website/docs/r/databricks_workspace.html.markdown
> +* `managed_services_cmk_managed_hsm_key_id` - (Optional) Customer managed encryption properties using a versioned Managed Hardware Security Key ID for the Databricks Workspace managed resources(e.g.
```suggestion
* `managed_services_cmk_managed_hsm_key_id` - (Optional) Customer managed encryption properties using a versioned Managed Hardware Security Key ID for the Databricks Workspace managed resources e.g. Notebooks and Artifacts.
```

2025-02-24 14:03 UTC, stephybun commented on website/docs/r/databricks_workspace.html.markdown
> +* `managed_disk_cmk_key_vault_key_id` - (Optional) Customer managed encryption properties using a versioned Key Vaule Key ID for the Databricks Workspace managed disks.
```suggestion
* `managed_disk_cmk_key_vault_key_id` - (Optional) Customer managed encryption properties using a versioned Key Vault Key ID for the Databricks Workspace managed disks.
```

2025-02-27 21:03 UTC, sreallymatt commented on internal/customermanagedkeys/key_vault_or_managed_hsm_key.go
> +}
I noticed `azurerm_log_analytics_cluster_customer_managed_key` is on your list here, I have started work on this as part of #27433

2025-03-13 19:24 UTC, sreallymatt reviewed
Hi @wuxu92, as I have a PR open that uses some of the helper functions introduced here, I figured I'd give this a review. I've left a few comments inline if you wouldn't mind taking a look!

2025-03-17 17:39 UTC, sreallymatt commented on internal/services/databricks/databricks_workspace_resource.go
> +func databricksWorkspaceSchema() map[string]*pluginsdk.Schema {
I meant if we could remove `databricksWorkspaceSchema()` and modify the schema within `resourceDatabricksWorkspace`. I'm not seeing the benefit of splitting out the schema here?

```
func resourceDatabricksWorkspace() *pluginsdk.Resource {
	resource := &pluginsdk.Resource{
		Create: resourceDatabricksWorkspaceCreate,
		Read:   resourceDatabricksWorkspaceRead,
		Update: resourceDatabricksWorkspaceUpdate,
		Delete: resourceDatabricksWorkspaceDelete,
	...
		Schema: map[string]*pluginsdk.Schema{
			"name": {
				Type:         pluginsdk.TypeString,
				Required:     true,
				ForceNew:     true,
				ValidateFunc: validate.WorkspaceName,
			},
	...

	}

	if !features.FivePointOh() {
		resource.Schema["managed_services_cmk_key_vault_id"] = &pluginsdk.Schema{
			...
		}
	}

	return resource
}
```

2025-12-11 22:49 UTC, wuxu92 commented
close this to use the way as #31146 to support managed hsm key.

2025-12-11 22:49 UTC, closed without merging