`azurerm_monitor_workspace` - add `private_endpoint_connections` export to resource and data source
terraform-providers/terraform-provider-azurerm pull request #27902
Opened 2024-11-05 17:24 UTC by djryanj

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR adds support for an exported list of `private_endpoint_connections`, to both `azurerm_monitor_workspace` resource and data sources. This is required in order for Terraform to (eventually) be able to automatically approve connections from e.g., an `azurerm_dashboard_grafana_managed_private_endpoint`.

Acceptance tests have been added for this, and a bit of cleanup to the overall acceptance test code for the resource (reduced duplicate code).

Note that this does not close or fix the linked issue, but is a necessary step to getting there.

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_monitor_workspace` - export `private_endpoint_connections` property [GH-27786]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [X] Enhancement
- [ ] Breaking Change

## Related Issue(s)
#27786 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-11-06 15:57 UTC, djryanj commented
Added some extra changes to satisfy a few comments made in #27781.

New acceptance tests:

```shell
$ make acctests SERVICE='dashboard' TESTARGS='-run=TestAccDashboardGrafanaManagedPrivateEndpoint_' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/dashboard -run=TestAccDashboardGrafanaManagedPrivateEndpoint_ -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccDashboardGrafanaManagedPrivateEndpoint_basic
--- PASS: TestAccDashboardGrafanaManagedPrivateEndpoint_basic (744.69s)
=== RUN   TestAccDashboardGrafanaManagedPrivateEndpoint_requiresImport
--- PASS: TestAccDashboardGrafanaManagedPrivateEndpoint_requiresImport (714.27s)
=== RUN   TestAccDashboardGrafanaManagedPrivateEndpoint_complete
--- PASS: TestAccDashboardGrafanaManagedPrivateEndpoint_complete (807.23s)
=== RUN   TestAccDashboardGrafanaManagedPrivateEndpoint_update
--- PASS: TestAccDashboardGrafanaManagedPrivateEndpoint_update (682.95s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/dashboard     2949.151s
```

2024-11-11 09:21 UTC, Poltergeisen commented
looking forward to this!

2025-02-06 16:55 UTC, catriona-m requested changes
Hi @djryanj thanks for submitting this. I had a look through these changes and left a couple of comments inline but once those are addressed we can take another look. Thanks!

2025-02-06 16:55 UTC, catriona-m commented on website/docs/d/monitor_workspace.html.markdown
> +- `group_ids` - A list of group ID's (sometimes called subresource names) that this private endpoint connection allws access to.
```suggestion
A `private_endpoint_connections` block exports the following:

- `name` - The name of the private endpoint connection.

- `id` - The ID of the private endpoint connection.

- `group_ids` - A list of group IDs (sometimes called subresource names) that this private endpoint connection allows access to.
```

2025-02-06 16:55 UTC, catriona-m commented on website/docs/r/monitor_workspace.html.markdown
> +- `group_ids` - A list of group ID's (sometimes called subresource names) that this private endpoint connection allws access to.
```suggestion
A `private_endpoint_connections` block exports the following:

- `name` - The name of the private endpoint connection.

- `id` - The ID of the private endpoint connection.

- `group_ids` - A list of group IDs (sometimes called subresource names) that this private endpoint connection allows access to.
```

2025-02-06 16:55 UTC, catriona-m commented on internal/services/monitor/monitor_workspace_resource_test.go
> +`, template, data.RandomInteger, data.RandomIntOfLength(8))
```suggestion
`, r.basic(data), data.RandomInteger, data.RandomIntOfLength(8))
```

2025-02-06 16:55 UTC, catriona-m commented on internal/services/monitor/monitor_workspace_resource_test.go
> +	template := r.basic(data)
```suggestion
```

2025-02-06 16:55 UTC, catriona-m commented on internal/services/monitor/monitor_workspace_resource_test.go
> +			),
can we check the properties from the `private_endpoint_connections` block have values here?

2025-02-08 00:49 UTC, djryanj commented
@catriona-m hooray for acceptance tests. 

In attempting to add in your last suggestion to check if the `private_endpoint_connections` block has values, I discovered that I need to trigger a refresh on the linked `azurerm_monitor_workspace` _after_ the `azurerm_dashboard_grafana_managed_private_endpoint` has been created, otherwise the `private_endpoint_connections` is empty.

Note that this is not an acceptance test bug, but a bug somewhere else in the code, probably in `azurerm_dashboard_grafana_managed_private_endpoint` . I'm not quite sure how to trigger that refresh. Any hints?

2025-05-16 20:09 UTC, djryanj commented
@catriona-m still looking for some guidance here.

2025-11-27 11:52 UTC, 0xMH commented
Hi @catriona-m, @djryanj. I'm curious to know what’s blocking this PR from being merged? I’d love to pick it up and do the work needed to move it forward if you don't have the time.

2025-11-27 15:05 UTC, djryanj commented
@0xMH - I can try to lean back into this one. Part of my original issue was "skills" - but I think perhaps I may be able to resolve that now with a bit of concerted effort.

On the other hand if you have time now, feel free!

2025-11-28 10:51 UTC, 0xMH commented
Thanks @djryanj, I created this PR https://github.com/hashicorp/terraform-provider-azurerm/pull/31217 to fix this issue and https://github.com/hashicorp/terraform-provider-azurerm/issues/27903

2026-04-01 06:43 UTC, closed without merging