`azurerm_container_app`, `data.azurerm_container_app` - support for `additional_port_mapping` in `ingress` block
terraform-providers/terraform-provider-azurerm pull request #28148
Opened 2024-12-02 06:12 UTC by lonegunmanb

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This pr added a new `additional_port_mapping` block in `ingress` block. It should solve #23442

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

=== RUN   TestAccContainerAppDataSource_basic
=== PAUSE TestAccContainerAppDataSource_basic
=== RUN   TestAccContainerAppDataSource_complete
=== PAUSE TestAccContainerAppDataSource_complete
=== CONT  TestAccContainerAppDataSource_basic
=== CONT  TestAccContainerAppDataSource_complete
--- PASS: TestAccContainerAppDataSource_basic (603.13s)
--- PASS: TestAccContainerAppDataSource_complete (663.33s)
=== RUN   TestAccContainerAppResource_basic
=== PAUSE TestAccContainerAppResource_basic
=== RUN   TestAccContainerAppResource_workloadProfile
=== PAUSE TestAccContainerAppResource_workloadProfile
=== RUN   TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
=== PAUSE TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
=== RUN   TestAccContainerAppResource_workloadProfileUpdate
=== PAUSE TestAccContainerAppResource_workloadProfileUpdate
=== RUN   TestAccContainerAppResource_withSystemAssignedIdentity
=== PAUSE TestAccContainerAppResource_withSystemAssignedIdentity
=== RUN   TestAccContainerAppResource_withUserAssignedIdentity
=== PAUSE TestAccContainerAppResource_withUserAssignedIdentity
=== RUN   TestAccContainerAppResource_withSystemAndUserAssignedIdentity
=== PAUSE TestAccContainerAppResource_withSystemAndUserAssignedIdentity
=== RUN   TestAccContainerAppResource_withIdentityUpdate
=== PAUSE TestAccContainerAppResource_withIdentityUpdate
=== RUN   TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
=== PAUSE TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
=== RUN   TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
=== PAUSE TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
=== RUN   TestAccContainerAppResource_basicUpdate
=== PAUSE TestAccContainerAppResource_basicUpdate
=== RUN   TestAccContainerAppResource_requiresImport
=== PAUSE TestAccContainerAppResource_requiresImport
=== RUN   TestAccContainerAppResource_complete
=== PAUSE TestAccContainerAppResource_complete
=== RUN   TestAccContainerAppResource_completeVolumeEmptyDir
=== PAUSE TestAccContainerAppResource_completeVolumeEmptyDir
=== RUN   TestAccContainerAppResource_completeWithNoDaprAppPort
=== PAUSE TestAccContainerAppResource_completeWithNoDaprAppPort
=== RUN   TestAccContainerAppResource_completeWithVNet
=== PAUSE TestAccContainerAppResource_completeWithVNet
=== RUN   TestAccContainerAppResource_completeWithSidecar
=== PAUSE TestAccContainerAppResource_completeWithSidecar
=== RUN   TestAccContainerAppResource_completeWithMultipleContainers
=== PAUSE TestAccContainerAppResource_completeWithMultipleContainers
=== RUN   TestAccContainerAppResource_completeUpdate
=== PAUSE TestAccContainerAppResource_completeUpdate
=== RUN   TestAccContainerAppResource_completeTcpExposedPort
=== PAUSE TestAccContainerAppResource_completeTcpExposedPort
=== RUN   TestAccContainerAppResource_removeDaprAppPort
=== PAUSE TestAccContainerAppResource_removeDaprAppPort
=== RUN   TestAccContainerAppResource_secretChangeName
=== PAUSE TestAccContainerAppResource_secretChangeName
=== RUN   TestAccContainerAppResource_secretRemove
=== PAUSE TestAccContainerAppResource_secretRemove
=== RUN   TestAccContainerAppResource_scaleRules
=== PAUSE TestAccContainerAppResource_scaleRules
=== RUN   TestAccContainerAppResource_multipleScaleRules
=== PAUSE TestAccContainerAppResource_multipleScaleRules
=== RUN   TestAccContainerAppResource_scaleRulesUpdate
=== PAUSE TestAccContainerAppResource_scaleRulesUpdate
=== RUN   TestAccContainerAppResource_ipSecurityRulesUpdate
=== PAUSE TestAccContainerAppResource_ipSecurityRulesUpdate
=== RUN   TestAccContainerAppResource_ingressTrafficValidation
=== PAUSE TestAccContainerAppResource_ingressTrafficValidation
=== RUN   TestAccContainerAppResource_maxInactiveRevisionsUpdate
=== PAUSE TestAccContainerAppResource_maxInactiveRevisionsUpdate
=== CONT  TestAccContainerAppResource_basic
=== CONT  TestAccContainerAppResource_completeWithVNet
=== CONT  TestAccContainerAppResource_secretRemove
=== CONT  TestAccContainerAppResource_removeDaprAppPort
=== CONT  TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
=== CONT  TestAccContainerAppResource_completeTcpExposedPort
=== CONT  TestAccContainerAppResource_secretChangeName
=== CONT  TestAccContainerAppResource_completeWithMultipleContainers
=== CONT  TestAccContainerAppResource_completeUpdate
=== CONT  TestAccContainerAppResource_completeWithSidecar
=== CONT  TestAccContainerAppResource_complete
=== CONT  TestAccContainerAppResource_completeWithNoDaprAppPort
=== CONT  TestAccContainerAppResource_completeVolumeEmptyDir
=== CONT  TestAccContainerAppResource_withSystemAssignedIdentity
=== CONT  TestAccContainerAppResource_withIdentityUpdate
=== CONT  TestAccContainerAppResource_withSystemAndUserAssignedIdentity
--- PASS: TestAccContainerAppResource_completeWithNoDaprAppPort (567.57s)
=== CONT  TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
=== CONT  TestAccContainerAppResource_workloadProfileUpdate
--- PASS: TestAccContainerAppResource_withSystemAndUserAssignedIdentity (631.74s)
--- PASS: TestAccContainerAppResource_basic (646.26s)
=== CONT  TestAccContainerAppResource_ipSecurityRulesUpdate
--- PASS: TestAccContainerAppResource_removeDaprAppPort (665.38s)
=== CONT  TestAccContainerAppResource_maxInactiveRevisionsUpdate
--- PASS: TestAccContainerAppResource_withSystemAssignedIdentity (665.57s)
=== CONT  TestAccContainerAppResource_ingressTrafficValidation
--- PASS: TestAccContainerAppResource_ingressTrafficValidation (6.68s)
=== CONT  TestAccContainerAppResource_basicUpdate
--- PASS: TestAccContainerAppResource_secretRemove (672.78s)
=== CON [...]

2025-02-18 05:07 UTC, lonegunmanb commented
Rebased with the latest `main` branch, test passed:

=== RUN   TestAccContainerAppResource_basic
=== PAUSE TestAccContainerAppResource_basic
=== CONT  TestAccContainerAppResource_basic
--- PASS: TestAccContainerAppResource_basic (782.31s)
=== RUN   TestAccContainerAppResource_workloadProfile
=== PAUSE TestAccContainerAppResource_workloadProfile
=== CONT  TestAccContainerAppResource_workloadProfile
--- PASS: TestAccContainerAppResource_workloadProfile (2470.24s)
=== RUN   TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
=== PAUSE TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
=== CONT  TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
--- PASS: TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations (2464.61s)
=== RUN   TestAccContainerAppResource_workloadProfileUpdate
=== PAUSE TestAccContainerAppResource_workloadProfileUpdate
=== CONT  TestAccContainerAppResource_workloadProfileUpdate
--- PASS: TestAccContainerAppResource_workloadProfileUpdate (2541.10s)
=== RUN   TestAccContainerAppResource_withSystemAssignedIdentity
=== PAUSE TestAccContainerAppResource_withSystemAssignedIdentity
=== CONT  TestAccContainerAppResource_withSystemAssignedIdentity
--- PASS: TestAccContainerAppResource_withSystemAssignedIdentity (764.67s)
=== RUN   TestAccContainerAppResource_withUserAssignedIdentity
=== PAUSE TestAccContainerAppResource_withUserAssignedIdentity
=== CONT  TestAccContainerAppResource_withUserAssignedIdentity
--- PASS: TestAccContainerAppResource_withUserAssignedIdentity (819.60s)
=== RUN   TestAccContainerAppResource_withSystemAndUserAssignedIdentity
=== PAUSE TestAccContainerAppResource_withSystemAndUserAssignedIdentity
=== CONT  TestAccContainerAppResource_withSystemAndUserAssignedIdentity
--- PASS: TestAccContainerAppResource_withSystemAndUserAssignedIdentity (621.96s)
=== RUN   TestAccContainerAppResource_withIdentityUpdate
=== PAUSE TestAccContainerAppResource_withIdentityUpdate
=== CONT  TestAccContainerAppResource_withIdentityUpdate
--- PASS: TestAccContainerAppResource_withIdentityUpdate (962.92s)
=== RUN   TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
=== PAUSE TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
=== CONT  TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
--- PASS: TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate (1107.26s)
=== RUN   TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
=== PAUSE TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
=== CONT  TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
--- PASS: TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate (1282.77s)
=== RUN   TestAccContainerAppResource_basicUpdate
=== PAUSE TestAccContainerAppResource_basicUpdate
=== CONT  TestAccContainerAppResource_basicUpdate
--- PASS: TestAccContainerAppResource_basicUpdate (800.03s)
=== RUN   TestAccContainerAppResource_requiresImport
=== PAUSE TestAccContainerAppResource_requiresImport
=== CONT  TestAccContainerAppResource_requiresImport
--- PASS: TestAccContainerAppResource_requiresImport (727.68s)
=== RUN   TestAccContainerAppResource_complete
=== PAUSE TestAccContainerAppResource_complete
=== CONT  TestAccContainerAppResource_complete
--- PASS: TestAccContainerAppResource_complete (801.19s)
=== RUN   TestAccContainerAppResource_completeVolumeEmptyDir
=== PAUSE TestAccContainerAppResource_completeVolumeEmptyDir
=== CONT  TestAccContainerAppResource_completeVolumeEmptyDir
--- PASS: TestAccContainerAppResource_completeVolumeEmptyDir (798.52s)
=== RUN   TestAccContainerAppResource_completeWithNoDaprAppPort
=== PAUSE TestAccContainerAppResource_completeWithNoDaprAppPort
=== CONT  TestAccContainerAppResource_completeWithNoDaprAppPort
--- PASS: TestAccContainerAppResource_completeWithNoDaprAppPort (803.21s)
=== RUN   TestAccContainerAppResource_completeWithVNet
=== PAUSE TestAccContainerAppResource_completeWithVNet
=== CONT  TestAccContainerAppResource_completeWithVNet
--- PASS: TestAccContainerAppResource_completeWithVNet (1211.77s)
=== RUN   TestAccContainerAppResource_completeWithSidecar
=== PAUSE TestAccContainerAppResource_completeWithSidecar
=== CONT  TestAccContainerAppResource_completeWithSidecar
--- PASS: TestAccContainerAppResource_completeWithSidecar (798.36s)
=== RUN   TestAccContainerAppResource_completeWithMultipleContainers
=== PAUSE TestAccContainerAppResource_completeWithMultipleContainers
=== CONT  TestAccContainerAppResource_completeWithMultipleContainers
--- PASS: TestAccContainerAppResource_completeWithMultipleContainers (818.18s)
=== RUN   TestAccContainerAppResource_completeUpdate
=== PAUSE TestAccContainerAppResource_completeUpdate
=== CONT  TestAccContainerAppResource_completeUpdate
--- PASS: TestAccContainerAppResource_completeUpdate (938.91s)
=== RUN   TestAccContainerAppResource_completeTcpExposedPort
=== PAUSE TestAccContainerAppResource_completeTcpExposedPort
=== CONT  TestAccContainerAppResource_completeTcpExposedPort
--- PASS: TestAccContainerAppResource_completeTcpExposedPort (1225.55s)
=== RUN   TestAccContainerAppResource_removeDaprAppPort
=== PAUSE TestAccContainerAppResource_removeDaprAppPort
=== CONT  TestAccContainerAppResource_removeDaprAppPort
--- PASS: TestAccContainerAppResource_removeDaprAppPort (914.22s)
=== RUN   TestAccContainerAppResource_secretChangeName
=== PAUSE TestAccContainerAppResource_secretChangeName
=== CONT  TestAccContainerAppResource_secretChangeName
--- PASS: TestAccContainerAppResource_secretChangeName (824.26s)
=== RUN   TestAccContainerAppResource_secretRemove
=== PAUSE TestAccContainerAppResource_secretRemove
=== CONT  TestAccContainerAppResource_secretRemove
--- PASS: TestAccContainerAppResource_secretRemove (830.80s)
=== RUN   TestAccContainerAppResource_scaleRules
=== PAUSE TestAccContainerAppResource_scaleRules
=== CONT  TestAccContainerAppResource_scaleRules
--- PASS: TestAccContainerAppResource_scaleRules (795.86s)
=== RUN   TestAccContainerAppResource_multipleScaleRules
=== PAUSE TestAccContainerAppResource_multipleScaleRules
=== CONT  TestAccContainerAppResource_multipleScaleRules
--- PASS: TestAccContainerAppResource_multipleScaleRules (760.14s)
=== RUN   TestAccContainerAppResource_scaleRulesUpdate
=== PAUSE TestAccContainerAppResource_scaleRulesUpdate
=== CONT  TestAccContainerAppResource_scaleRulesUpdate
--- PASS: TestAccContainerAppResource_scaleRulesUpdate (1034.24s)
=== RUN   TestAccContainerAppResource_ipSecurityRulesUpdate
=== PAUSE TestAccContainerAppResource_ipSecurityRulesUpdate
=== CONT  TestAccContainerAppResource_ipSecurityRulesUpdate
--- PASS: TestAccContainerAppResource_ipSecurityRulesUpdate (1073.32s)
=== RUN   TestAccContainerAppResource_ingressTrafficValidation
=== PAUSE TestAccContainerAppResource_ingressTrafficValidation
=== CONT  TestAccContainerAppResource_ingressTrafficValidation
--- PASS: TestAccContainerAppResource_ingressTrafficValidation (13.07s)
=== RUN   TestAccContainerAppResource_maxInactiveRevisionsUpdate
=== PAUSE TestAccContainerAppResource_maxInactiveRevisionsUpdate
=== CONT  TestAccContainerAppResource_maxInactiveRevisionsUpdate
--- PASS: TestAccContainerAppResource_maxInactiveRevisionsUpdate (870.18s)
PASS

2025-02-25 04:58 UTC, lonegunmanb commented
Rebased with the latest `main` branch, tests passed:

=== RUN   TestAccContainerAppResource_basic
=== PAUSE TestAccContainerAppResource_basic
=== CONT  TestAccContainerAppResource_basic
--- PASS: TestAccContainerAppResource_basic (738.61s)
=== RUN   TestAccContainerAppResource_workloadProfile
=== PAUSE TestAccContainerAppResource_workloadProfile
=== CONT  TestAccContainerAppResource_workloadProfile
--- PASS: TestAccContainerAppResource_workloadProfile (2237.39s)
=== RUN   TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
=== PAUSE TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
=== CONT  TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
--- PASS: TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations (2306.89s)
=== RUN   TestAccContainerAppResource_workloadProfileUpdate
=== PAUSE TestAccContainerAppResource_workloadProfileUpdate
=== CONT  TestAccContainerAppResource_workloadProfileUpdate
--- PASS: TestAccContainerAppResource_workloadProfileUpdate (2426.75s)
=== RUN   TestAccContainerAppResource_withSystemAssignedIdentity
=== PAUSE TestAccContainerAppResource_withSystemAssignedIdentity
=== CONT  TestAccContainerAppResource_withSystemAssignedIdentity
--- PASS: TestAccContainerAppResource_withSystemAssignedIdentity (782.50s)
=== RUN   TestAccContainerAppResource_withUserAssignedIdentity
=== PAUSE TestAccContainerAppResource_withUserAssignedIdentity
=== CONT  TestAccContainerAppResource_withUserAssignedIdentity
--- PASS: TestAccContainerAppResource_withUserAssignedIdentity (829.02s)
=== RUN   TestAccContainerAppResource_withSystemAndUserAssignedIdentity
=== PAUSE TestAccContainerAppResource_withSystemAndUserAssignedIdentity
=== CONT  TestAccContainerAppResource_withSystemAndUserAssignedIdentity
--- PASS: TestAccContainerAppResource_withSystemAndUserAssignedIdentity (720.76s)
=== RUN   TestAccContainerAppResource_withIdentityUpdate
=== PAUSE TestAccContainerAppResource_withIdentityUpdate
=== CONT  TestAccContainerAppResource_withIdentityUpdate
--- PASS: TestAccContainerAppResource_withIdentityUpdate (988.03s)
=== RUN   TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
=== PAUSE TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
=== CONT  TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
--- PASS: TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate (1074.67s)
=== RUN   TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
=== PAUSE TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
=== CONT  TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
--- PASS: TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate (1175.68s)
=== RUN   TestAccContainerAppResource_basicUpdate
=== PAUSE TestAccContainerAppResource_basicUpdate
=== CONT  TestAccContainerAppResource_basicUpdate
--- PASS: TestAccContainerAppResource_basicUpdate (783.57s)
=== RUN   TestAccContainerAppResource_requiresImport
=== PAUSE TestAccContainerAppResource_requiresImport
=== CONT  TestAccContainerAppResource_requiresImport
--- PASS: TestAccContainerAppResource_requiresImport (780.87s)
=== RUN   TestAccContainerAppResource_complete
=== PAUSE TestAccContainerAppResource_complete
=== CONT  TestAccContainerAppResource_complete
--- PASS: TestAccContainerAppResource_complete (829.49s)
=== RUN   TestAccContainerAppResource_completeVolumeEmptyDir
=== PAUSE TestAccContainerAppResource_completeVolumeEmptyDir
=== CONT  TestAccContainerAppResource_completeVolumeEmptyDir
--- PASS: TestAccContainerAppResource_completeVolumeEmptyDir (842.77s)
=== RUN   TestAccContainerAppResource_completeWithNoDaprAppPort
=== PAUSE TestAccContainerAppResource_completeWithNoDaprAppPort
=== CONT  TestAccContainerAppResource_completeWithNoDaprAppPort
--- PASS: TestAccContainerAppResource_completeWithNoDaprAppPort (787.61s)
=== RUN   TestAccContainerAppResource_completeWithVNet
=== PAUSE TestAccContainerAppResource_completeWithVNet
=== CONT  TestAccContainerAppResource_completeWithVNet
--- PASS: TestAccContainerAppResource_completeWithVNet (1662.63s)
=== RUN   TestAccContainerAppResource_completeWithSidecar
=== PAUSE TestAccContainerAppResource_completeWithSidecar
=== CONT  TestAccContainerAppResource_completeWithSidecar
--- PASS: TestAccContainerAppResource_completeWithSidecar (856.34s)
=== RUN   TestAccContainerAppResource_completeWithMultipleContainers
=== PAUSE TestAccContainerAppResource_completeWithMultipleContainers
=== CONT  TestAccContainerAppResource_completeWithMultipleContainers
--- PASS: TestAccContainerAppResource_completeWithMultipleContainers (855.26s)
=== RUN   TestAccContainerAppResource_completeUpdate
=== PAUSE TestAccContainerAppResource_completeUpdate
=== CONT  TestAccContainerAppResource_completeUpdate
--- PASS: TestAccContainerAppResource_completeUpdate (998.34s)
=== RUN   TestAccContainerAppResource_completeTcpExposedPort
=== PAUSE TestAccContainerAppResource_completeTcpExposedPort
=== CONT  TestAccContainerAppResource_completeTcpExposedPort
--- PASS: TestAccContainerAppResource_completeTcpExposedPort (1274.83s)
=== RUN   TestAccContainerAppResource_removeDaprAppPort
=== PAUSE TestAccContainerAppResource_removeDaprAppPort
=== CONT  TestAccContainerAppResource_removeDaprAppPort
--- PASS: TestAccContainerAppResource_removeDaprAppPort (1041.51s)
=== RUN   TestAccContainerAppResource_secretChangeName
=== PAUSE TestAccContainerAppResource_secretChangeName
=== CONT  TestAccContainerAppResource_secretChangeName
--- PASS: TestAccContainerAppResource_secretChangeName (788.01s)
=== RUN   TestAccContainerAppResource_secretRemove
=== PAUSE TestAccContainerAppResource_secretRemove
=== CONT  TestAccContainerAppResource_secretRemove
--- PASS: TestAccContainerAppResource_secretRemove (868.18s)
=== RUN   TestAccContainerAppResource_scaleRules
=== PAUSE TestAccContainerAppResource_scaleRules
=== CONT  TestAccContainerAppResource_scaleRules
--- PASS: TestAccContainerAppResource_scaleRules (742.70s)
=== RUN   TestAccContainerAppResource_multipleScaleRules
=== PAUSE TestAccContainerAppResource_multipleScaleRules
=== CONT  TestAccContainerAppResource_multipleScaleRules
--- PASS: TestAccContainerAppResource_multipleScaleRules (777.42s)
=== RUN   TestAccContainerAppResource_scaleRulesUpdate
=== PAUSE TestAccContainerAppResource_scaleRulesUpdate
=== CONT  TestAccContainerAppResource_scaleRulesUpdate
--- PASS: TestAccContainerAppResource_scaleRulesUpdate (827.82s)
=== RUN   TestAccContainerAppResource_ipSecurityRulesUpdate
=== PAUSE TestAccContainerAppResource_ipSecurityRulesUpdate
=== CONT  TestAccContainerAppResource_ipSecurityRulesUpdate
--- PASS: TestAccContainerAppResource_ipSecurityRulesUpdate (1019.19s)
=== RUN   TestAccContainerAppResource_ingressTrafficValidation
=== PAUSE TestAccContainerAppResource_ingressTrafficValidation
=== CONT  TestAccContainerAppResource_ingressTrafficValidation
--- PASS: TestAccContainerAppResource_ingressTrafficValidation (50.25s)
=== RUN   TestAccContainerAppResource_maxInactiveRevisionsUpdate
=== PAUSE TestAccContainerAppResource_maxInactiveRevisionsUpdate
=== CONT  TestAccContainerAppResource_maxInactiveRevisionsUpdate
--- PASS: TestAccContainerAppResource_maxInactiveRevisionsUpdate (802.18s)
PASS

2025-03-31 08:46 UTC, MinZe25 commented
Hi @jackofallops  @lonegunmanb  It seems the branch has conflicts. Could somebody resolve it? :)

2025-04-03 07:42 UTC, lonegunmanb commented
As your wish @MinZe25 

=== RUN   TestAccContainerAppResource_basic
=== PAUSE TestAccContainerAppResource_basic
=== CONT  TestAccContainerAppResource_basic
--- PASS: TestAccContainerAppResource_basic (731.67s)
=== RUN   TestAccContainerAppResource_workloadProfile
=== PAUSE TestAccContainerAppResource_workloadProfile
=== CONT  TestAccContainerAppResource_workloadProfile
--- PASS: TestAccContainerAppResource_workloadProfile (2240.72s)
=== RUN   TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
=== PAUSE TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
=== CONT  TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
--- PASS: TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations (2339.81s)
=== RUN   TestAccContainerAppResource_workloadProfileUpdate
=== PAUSE TestAccContainerAppResource_workloadProfileUpdate
=== CONT  TestAccContainerAppResource_workloadProfileUpdate
--- PASS: TestAccContainerAppResource_workloadProfileUpdate (2584.19s)
=== RUN   TestAccContainerAppResource_withSystemAssignedIdentity
=== PAUSE TestAccContainerAppResource_withSystemAssignedIdentity
=== CONT  TestAccContainerAppResource_withSystemAssignedIdentity
--- PASS: TestAccContainerAppResource_withSystemAssignedIdentity (720.82s)
=== RUN   TestAccContainerAppResource_withUserAssignedIdentity
=== PAUSE TestAccContainerAppResource_withUserAssignedIdentity
=== CONT  TestAccContainerAppResource_withUserAssignedIdentity
--- PASS: TestAccContainerAppResource_withUserAssignedIdentity (698.31s)
=== RUN   TestAccContainerAppResource_withSystemAndUserAssignedIdentity
=== PAUSE TestAccContainerAppResource_withSystemAndUserAssignedIdentity
=== CONT  TestAccContainerAppResource_withSystemAndUserAssignedIdentity
--- PASS: TestAccContainerAppResource_withSystemAndUserAssignedIdentity (831.15s)
=== RUN   TestAccContainerAppResource_withIdentityUpdate
=== PAUSE TestAccContainerAppResource_withIdentityUpdate
=== CONT  TestAccContainerAppResource_withIdentityUpdate
--- PASS: TestAccContainerAppResource_withIdentityUpdate (969.91s)
=== RUN   TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
=== PAUSE TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
=== CONT  TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
--- PASS: TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate (1144.52s)
=== RUN   TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
=== PAUSE TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
=== CONT  TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
--- PASS: TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate (1298.24s)
=== RUN   TestAccContainerAppResource_basicUpdate
=== PAUSE TestAccContainerAppResource_basicUpdate
=== CONT  TestAccContainerAppResource_basicUpdate
--- PASS: TestAccContainerAppResource_basicUpdate (773.29s)
=== RUN   TestAccContainerAppResource_requiresImport
=== PAUSE TestAccContainerAppResource_requiresImport
=== CONT  TestAccContainerAppResource_requiresImport
--- PASS: TestAccContainerAppResource_requiresImport (542.06s)
=== RUN   TestAccContainerAppResource_complete
=== PAUSE TestAccContainerAppResource_complete
=== CONT  TestAccContainerAppResource_complete
--- PASS: TestAccContainerAppResource_complete (773.83s)
=== RUN   TestAccContainerAppResource_completeVolumeEmptyDir
=== PAUSE TestAccContainerAppResource_completeVolumeEmptyDir
=== CONT  TestAccContainerAppResource_completeVolumeEmptyDir
--- PASS: TestAccContainerAppResource_completeVolumeEmptyDir (740.35s)
=== RUN   TestAccContainerAppResource_completeWithNoDaprAppPort
=== PAUSE TestAccContainerAppResource_completeWithNoDaprAppPort
=== CONT  TestAccContainerAppResource_completeWithNoDaprAppPort
--- PASS: TestAccContainerAppResource_completeWithNoDaprAppPort (801.89s)
=== RUN   TestAccContainerAppResource_completeWithVNet
=== PAUSE TestAccContainerAppResource_completeWithVNet
=== CONT  TestAccContainerAppResource_completeWithVNet
--- PASS: TestAccContainerAppResource_completeWithVNet (1337.19s)
=== RUN   TestAccContainerAppResource_completeWithSidecar
=== PAUSE TestAccContainerAppResource_completeWithSidecar
=== CONT  TestAccContainerAppResource_completeWithSidecar
--- PASS: TestAccContainerAppResource_completeWithSidecar (795.31s)
=== RUN   TestAccContainerAppResource_completeWithMultipleContainers
=== PAUSE TestAccContainerAppResource_completeWithMultipleContainers
=== CONT  TestAccContainerAppResource_completeWithMultipleContainers
--- PASS: TestAccContainerAppResource_completeWithMultipleContainers (765.29s)
=== RUN   TestAccContainerAppResource_completeUpdate
=== PAUSE TestAccContainerAppResource_completeUpdate
=== CONT  TestAccContainerAppResource_completeUpdate
--- PASS: TestAccContainerAppResource_completeUpdate (846.12s)
=== RUN   TestAccContainerAppResource_completeTcpExposedPort
=== PAUSE TestAccContainerAppResource_completeTcpExposedPort
=== CONT  TestAccContainerAppResource_completeTcpExposedPort
--- PASS: TestAccContainerAppResource_completeTcpExposedPort (1226.37s)
=== RUN   TestAccContainerAppResource_removeDaprAppPort
=== PAUSE TestAccContainerAppResource_removeDaprAppPort
=== CONT  TestAccContainerAppResource_removeDaprAppPort
--- PASS: TestAccContainerAppResource_removeDaprAppPort (866.16s)
=== RUN   TestAccContainerAppResource_secretChangeName
=== PAUSE TestAccContainerAppResource_secretChangeName
=== CONT  TestAccContainerAppResource_secretChangeName
--- PASS: TestAccContainerAppResource_secretChangeName (806.72s)
=== RUN   TestAccContainerAppResource_secretRemove
=== PAUSE TestAccContainerAppResource_secretRemove
=== CONT  TestAccContainerAppResource_secretRemove
--- PASS: TestAccContainerAppResource_secretRemove (789.07s)
=== RUN   TestAccContainerAppResource_scaleRules
=== PAUSE TestAccContainerAppResource_scaleRules
=== CONT  TestAccContainerAppResource_scaleRules
--- PASS: TestAccContainerAppResource_scaleRules (703.54s)
=== RUN   TestAccContainerAppResource_multipleScaleRules
=== PAUSE TestAccContainerAppResource_multipleScaleRules
=== CONT  TestAccContainerAppResource_multipleScaleRules
--- PASS: TestAccContainerAppResource_multipleScaleRules (701.63s)
=== RUN   TestAccContainerAppResource_scaleRulesUpdate
=== PAUSE TestAccContainerAppResource_scaleRulesUpdate
=== CONT  TestAccContainerAppResource_scaleRulesUpdate
--- PASS: TestAccContainerAppResource_scaleRulesUpdate (979.77s)
=== RUN   TestAccContainerAppResource_ipSecurityRulesUpdate
=== PAUSE TestAccContainerAppResource_ipSecurityRulesUpdate
=== CONT  TestAccContainerAppResource_ipSecurityRulesUpdate
--- PASS: TestAccContainerAppResource_ipSecurityRulesUpdate (1043.18s)
=== RUN   TestAccContainerAppResource_ingressTrafficValidation
=== PAUSE TestAccContainerAppResource_ingressTrafficValidation
=== CONT  TestAccContainerAppResource_ingressTrafficValidation
--- PASS: TestAccContainerAppResource_ingressTrafficValidation (13.32s)
=== RUN   TestAccContainerAppResource_maxInactiveRevisionsUpdate
=== PAUSE TestAccContainerAppResource_maxInactiveRevisionsUpdate
=== CONT  TestAccContainerAppResource_maxInactiveRevisionsUpdate
--- PASS: TestAccContainerAppResource_maxInactiveRevisionsUpdate (748.41s)
PASS

2025-04-10 10:39 UTC, DennisvDijk commented
Hi @jackofallops, what's the status on this? Not having add. ports available via the tf provider is a huge limitation. Kindly check this pr.

2025-04-10 15:38 UTC, MinZe25 commented
Hi @catriona-m ! Could somebody make a review of this? :)

2025-04-22 08:32 UTC, lonegunmanb commented
Conflict resolved.

=== RUN   TestAccContainerAppResource_basic
=== PAUSE TestAccContainerAppResource_basic
=== CONT  TestAccContainerAppResource_basic
--- PASS: TestAccContainerAppResource_basic (721.59s)
=== RUN   TestAccContainerAppResource_workloadProfile
=== PAUSE TestAccContainerAppResource_workloadProfile
=== CONT  TestAccContainerAppResource_workloadProfile
--- PASS: TestAccContainerAppResource_workloadProfile (2181.62s)
=== RUN   TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
=== PAUSE TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
=== CONT  TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations
--- PASS: TestAccContainerAppResource_smallerGranularityCPUMemoryCombinations (2179.00s)
=== RUN   TestAccContainerAppResource_workloadProfileUpdate
=== PAUSE TestAccContainerAppResource_workloadProfileUpdate
=== CONT  TestAccContainerAppResource_workloadProfileUpdate
--- PASS: TestAccContainerAppResource_workloadProfileUpdate (2414.06s)
=== RUN   TestAccContainerAppResource_withSystemAssignedIdentity
=== PAUSE TestAccContainerAppResource_withSystemAssignedIdentity
=== CONT  TestAccContainerAppResource_withSystemAssignedIdentity
--- PASS: TestAccContainerAppResource_withSystemAssignedIdentity (678.88s)
=== RUN   TestAccContainerAppResource_withUserAssignedIdentity
=== PAUSE TestAccContainerAppResource_withUserAssignedIdentity
=== CONT  TestAccContainerAppResource_withUserAssignedIdentity
--- PASS: TestAccContainerAppResource_withUserAssignedIdentity (688.33s)
=== RUN   TestAccContainerAppResource_withSystemAndUserAssignedIdentity
=== PAUSE TestAccContainerAppResource_withSystemAndUserAssignedIdentity
=== CONT  TestAccContainerAppResource_withSystemAndUserAssignedIdentity
--- PASS: TestAccContainerAppResource_withSystemAndUserAssignedIdentity (677.08s)
=== RUN   TestAccContainerAppResource_withIdentityUpdate
=== PAUSE TestAccContainerAppResource_withIdentityUpdate
=== CONT  TestAccContainerAppResource_withIdentityUpdate
--- PASS: TestAccContainerAppResource_withIdentityUpdate (840.55s)
=== RUN   TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
=== PAUSE TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
=== CONT  TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate
--- PASS: TestAccContainerAppResource_withKeyVaultSecretVersioningUpdate (1163.86s)
=== RUN   TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
=== PAUSE TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
=== CONT  TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate
--- PASS: TestAccContainerAppResource_withKeyVaultSecretIdentityUpdate (1291.97s)
=== RUN   TestAccContainerAppResource_basicUpdate
=== PAUSE TestAccContainerAppResource_basicUpdate
=== CONT  TestAccContainerAppResource_basicUpdate
--- PASS: TestAccContainerAppResource_basicUpdate (813.73s)
=== RUN   TestAccContainerAppResource_requiresImport
=== PAUSE TestAccContainerAppResource_requiresImport
=== CONT  TestAccContainerAppResource_requiresImport
--- PASS: TestAccContainerAppResource_requiresImport (696.94s)
=== RUN   TestAccContainerAppResource_complete
=== PAUSE TestAccContainerAppResource_complete
=== CONT  TestAccContainerAppResource_complete
--- PASS: TestAccContainerAppResource_complete (702.96s)
=== RUN   TestAccContainerAppResource_completeVolumeEmptyDir
=== PAUSE TestAccContainerAppResource_completeVolumeEmptyDir
=== CONT  TestAccContainerAppResource_completeVolumeEmptyDir
--- PASS: TestAccContainerAppResource_completeVolumeEmptyDir (730.55s)
=== RUN   TestAccContainerAppResource_completeWithNoDaprAppPort
=== PAUSE TestAccContainerAppResource_completeWithNoDaprAppPort
=== CONT  TestAccContainerAppResource_completeWithNoDaprAppPort
--- PASS: TestAccContainerAppResource_completeWithNoDaprAppPort (780.73s)
=== RUN   TestAccContainerAppResource_completeWithVNet
=== PAUSE TestAccContainerAppResource_completeWithVNet
=== CONT  TestAccContainerAppResource_completeWithVNet
--- PASS: TestAccContainerAppResource_completeWithVNet (1232.64s)
=== RUN   TestAccContainerAppResource_completeWithSidecar
=== PAUSE TestAccContainerAppResource_completeWithSidecar
=== CONT  TestAccContainerAppResource_completeWithSidecar
--- PASS: TestAccContainerAppResource_completeWithSidecar (722.86s)
=== RUN   TestAccContainerAppResource_completeWithMultipleContainers
=== PAUSE TestAccContainerAppResource_completeWithMultipleContainers
=== CONT  TestAccContainerAppResource_completeWithMultipleContainers
--- PASS: TestAccContainerAppResource_completeWithMultipleContainers (747.49s)
=== RUN   TestAccContainerAppResource_completeUpdate
=== PAUSE TestAccContainerAppResource_completeUpdate
=== CONT  TestAccContainerAppResource_completeUpdate
--- PASS: TestAccContainerAppResource_completeUpdate (832.34s)
=== RUN   TestAccContainerAppResource_completeTcpExposedPort
=== PAUSE TestAccContainerAppResource_completeTcpExposedPort
=== CONT  TestAccContainerAppResource_completeTcpExposedPort
--- PASS: TestAccContainerAppResource_completeTcpExposedPort (1179.71s)
=== RUN   TestAccContainerAppResource_removeDaprAppPort
=== PAUSE TestAccContainerAppResource_removeDaprAppPort
=== CONT  TestAccContainerAppResource_removeDaprAppPort
--- PASS: TestAccContainerAppResource_removeDaprAppPort (866.90s)
=== RUN   TestAccContainerAppResource_secretChangeName
=== PAUSE TestAccContainerAppResource_secretChangeName
=== CONT  TestAccContainerAppResource_secretChangeName
--- PASS: TestAccContainerAppResource_secretChangeName (858.24s)
=== RUN   TestAccContainerAppResource_secretRemove
=== PAUSE TestAccContainerAppResource_secretRemove
=== CONT  TestAccContainerAppResource_secretRemove
--- PASS: TestAccContainerAppResource_secretRemove (708.67s)
=== RUN   TestAccContainerAppResource_scaleRules
=== PAUSE TestAccContainerAppResource_scaleRules
=== CONT  TestAccContainerAppResource_scaleRules
--- PASS: TestAccContainerAppResource_scaleRules (786.93s)
=== RUN   TestAccContainerAppResource_multipleScaleRules
=== PAUSE TestAccContainerAppResource_multipleScaleRules
=== CONT  TestAccContainerAppResource_multipleScaleRules
--- PASS: TestAccContainerAppResource_multipleScaleRules (661.27s)
=== RUN   TestAccContainerAppResource_scaleRulesUpdate
=== PAUSE TestAccContainerAppResource_scaleRulesUpdate
=== CONT  TestAccContainerAppResource_scaleRulesUpdate
--- PASS: TestAccContainerAppResource_scaleRulesUpdate (959.99s)
=== RUN   TestAccContainerAppResource_ipSecurityRulesUpdate
=== PAUSE TestAccContainerAppResource_ipSecurityRulesUpdate
=== CONT  TestAccContainerAppResource_ipSecurityRulesUpdate
--- PASS: TestAccContainerAppResource_ipSecurityRulesUpdate (1083.82s)
=== RUN   TestAccContainerAppResource_ingressTrafficValidation
=== PAUSE TestAccContainerAppResource_ingressTrafficValidation
=== CONT  TestAccContainerAppResource_ingressTrafficValidation
--- PASS: TestAccContainerAppResource_ingressTrafficValidation (13.55s)
=== RUN   TestAccContainerAppResource_maxInactiveRevisionsUpdate
=== PAUSE TestAccContainerAppResource_maxInactiveRevisionsUpdate
=== CONT  TestAccContainerAppResource_maxInactiveRevisionsUpdate
--- PASS: TestAccContainerAppResource_maxInactiveRevisionsUpdate (784.82s)

2025-06-16 07:00 UTC, TimoW-Wago commented
Any news on this?

2025-07-12 17:54 UTC, mengunogul commented
Hi, just wondering if there’s anything blocking this from moving forward? I’d love to see this feature merged.

2025-08-25 14:39 UTC, 7Hazard commented
This would be cruical to have in Terraform. Please make sure this PR gets merged.

2025-10-17 10:15 UTC, Ily83 commented
What is the conflict?

2025-10-17 10:19 UTC, Ily83 requested changes
I think the API need to be updated from 2025-01-01 to 2025-07-01

2025-10-29 20:06 UTC, Ily83 commented
Can I help with this?

2026-01-07 11:07 UTC, bellackn commented
hello everyone, this is still a much anticipated feature and i guess a lot of people would love to see this merged...

2026-03-05 19:46 UTC, hoivikaj commented
@lonegunmanb @katbyte Do we know whats holding up this PR? Will help if possible

2026-04-30 08:10 UTC, closed without merging

2026-05-02 20:04 UTC, pedropcamellon commented
@sreallymatt Are you working on this on a new branch?