feat: add kusto_eventhub_data_connection supports retrieval_start_date parameter
terraform-providers/terraform-provider-azurerm pull request #28292
Opened 2024-12-16 09:45 UTC by FakieHeelflip

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Add for the kusto_eventhub_data_connection the parameter "retrieval_start_date" to ingest older stored data from an Event Hub. 

When defined, the data connection retrieves existing Event hub events created since the Retrieval start date. It can only retrieve events retained by the Event hub, based on its retention period.

- add the missing parameter for CRUD
- add test case for the new parameter
- add updated docs

Made CRUD tests locally. 

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_kusto_eventhub_data_connection` - support the `retrieval_start_date` parameter 

This is a (please select all that apply):

- [ ] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)

No known open issue for that.

2024-12-17 17:56 UTC, FakieHeelflip commented
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/32899357-b8fc-44f3-bf2f-6cab6b24dca4" />

Besides, it is not clear to me what tests you need from me to approve that PR.

2024-12-19 06:12 UTC, FakieHeelflip commented
Thank you for triggering the checks. There were indeed a format error (1 space) in the terraform blocks of the website documentation and in the test file for the azurerm_kusto_eventhub_data_connection. Used `terraform fmt` for both of the resource blocks.

2025-01-09 18:49 UTC, FakieHeelflip commented
Hello, politely asking what I can do to get things merged? :)

2025-01-10 11:24 UTC, FakieHeelflip commented
All checks have passed. Who can review and merge it? :)

2025-01-10 11:55 UTC, catriona-m requested changes
Hi @FakieHeelflip thanks for submitting this. I left one minor comment here, but once that is addressed I can take another look. Thanks!

2025-01-10 11:55 UTC, catriona-m commented on internal/services/kusto/kusto_eventhub_data_connection_resource.go
> +				ValidateFunc: validation.StringIsNotEmpty,
should we use some validation here to ensure this is a valid timestamp?

```suggestion
				ValidateFunc:     validation.IsRFC3339Time,
```

2025-01-10 17:09 UTC, FakieHeelflip commented
Hi @catriona-m , thank you for the review. You are right, totally overlooked that validation function. Thanks. Commited your suggestion.

2025-01-14 15:43 UTC, catriona-m requested changes
Hi @FakieHeelflip thanks for updating the validation on this. I ran the tests on this and it looks like this property is causing some failures that would need to be address before we can merge this:

```

Copy to clipboard
------- Stdout: -------
=== RUN   TestAccKustoEventHubDataConnection_databaseRoutingType
=== PAUSE TestAccKustoEventHubDataConnection_databaseRoutingType
=== CONT  TestAccKustoEventHubDataConnection_databaseRoutingType
    testcase.go:173: Step 1/3 error: After applying this test step, the non-refresh plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # azurerm_kusto_eventhub_data_connection.test will be updated in-place
          ~ resource "azurerm_kusto_eventhub_data_connection" "test" {
                id                      = "/subscriptions/*******/resourceGroups/acctestRG-250110120520846318/providers/Microsoft.Kusto/clusters/acctestkco721m/databases/acctestkd-250110120520846318/dataConnections/acctestkedc-250110120520846318"
                name                    = "acctestkedc-250110120520846318"
              - retrieval_start_date    = "2025-01-10T12:18:51.7164161Z" -> null
                # (11 unchanged attributes hidden)
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccKustoEventHubDataConnection_databaseRoutingType (1130.62s)
FAIL
```

2025-01-14 15:43 UTC, catriona-m commented on website/docs/r/kusto_eventhub_data_connection.html.markdown
> +  retrieval_start_date = "2024-11-25T04:44:44Z"
since this is an optional property, we can omit this from the example

2025-01-15 06:32 UTC, FakieHeelflip commented on website/docs/r/kusto_eventhub_data_connection.html.markdown
> +  retrieval_start_date = "2024-11-25T04:44:44Z"
Alright. Thank you so much @catriona-m for guiding me through this. 
Removed the optional parameter from the markdown file.

2025-01-17 06:42 UTC, FakieHeelflip commented
Hi @catriona-m , do I need to do something?

2025-01-24 08:30 UTC, FakieHeelflip commented
@catriona-m I am again confused what to do... could you please help?

2025-01-28 16:22 UTC, catriona-m requested changes
Hi @FakieHeelflip. It appears this change is causing test failures which would need to be addressed before this can be merged:

```
------- Stdout: -------
=== RUN   TestAccKustoEventHubDataConnection_basic
=== PAUSE TestAccKustoEventHubDataConnection_basic
=== CONT  TestAccKustoEventHubDataConnection_basic
    testcase.go:173: Step 1/3 error: After applying this test step, the non-refresh plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # azurerm_kusto_eventhub_data_connection.test will be updated in-place
          ~ resource "azurerm_kusto_eventhub_data_connection" "test" {
                id                      = "/subscriptions/*******/resourceGroups/acctestRG-250128093507931138/providers/Microsoft.Kusto/clusters/acctestkchqfcy/databases/acctestkd-250128093507931138/dataConnections/acctestkedc-250128093507931138"
                name                    = "acctestkedc-250128093507931138"
              - retrieval_start_date    = "2025-01-28T09:48:12.1927294Z" -> null
                # (9 unchanged attributes hidden)
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccKustoEventHubDataConnection_basic (1027.27s)
FAIL
```

It also appears that this has a linting error on it, if you could run `gofmt` on this to fix it? Once those are addressed I can take another look, thanks!

2025-01-30 06:01 UTC, FakieHeelflip commented
@catriona-m used go fmt for all files.

2025-01-30 11:45 UTC, catriona-m requested changes
Hi @FakieHeelflip thank you for addressing the linting. It seems there is still an issue causing the above test failures which will need to be addressed before this can be merged but once that is resolved I can take another look at this. Thanks!

2026-05-12 09:00 UTC, catriona-m commented
Hi @FakieHeelflip thanks for working on this. I was having another look at this PR and it seems this property has now been added as part of another change made [here](https://github.com/hashicorp/terraform-provider-azurerm/pull/31445) so it seems this can be closed now.

2026-05-12 09:00 UTC, closed without merging