Support Managed DevOps Pools service
terraform-providers/terraform-provider-azurerm pull request #28325
Opened 2024-12-18 00:12 UTC by ajaykn

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2025-03-07 15:13 UTC, ajaykn commented
> Hi @ajaykn We're eagerly awaiting the new Terraform resources - do you have any indication of when these might be released?

@jgschwendswica I will plan to wrap up this soon.  Pending to add few unit tests and bit testing locally.

2025-03-18 06:40 UTC, TyranVDM commented
@ajaykn any rough timelines for this?

2025-03-18 15:14 UTC, jsloan117 commented
Our company is very interested in utilizing this new feature as well!

2025-03-27 22:09 UTC, tylerforaie commented
It would awesome to see this get implemented soon

2025-03-31 16:28 UTC, ajaykn commented
> @ajaykn any rough timelines for this?

This is ready for review, will followup on reviews and get it released.

2025-04-10 01:32 UTC, ajaykn commented
> @stephybun Can I please get some feedback on this

@stephybun Can we please get reviews on this.

2025-04-17 08:32 UTC, ms-henglu requested changes

2025-04-17 08:32 UTC, ms-henglu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      resource_id = "/Subscriptions/e21f7bce-1728-44ad-a62d-344064a0d69a/Providers/Microsoft.Compute/Locations/australiaeast/publishers/canonical/artifacttypes/vmimage/offers/0001-com-ubuntu-server-f
The testcases will run in the Hashicorp's testing subscriptions, can this resource will be used?

2025-04-17 08:32 UTC, ms-henglu commented on internal/services/manageddevopspools/schema_definitions.go
> +				"days_data": {
From its doc, this field only accepts `json` format, maybe add a JSON string validation function?

2025-04-17 08:32 UTC, ms-henglu commented on internal/services/manageddevopspools/schema_definitions.go
> +								Required: true,
Please add validation function for subnet id.

2025-04-17 08:32 UTC, ms-henglu commented on internal/services/manageddevopspools/schema_definitions.go
> +				"sku": {
Can this be simplified to `sku_name`(string, required)?

2025-04-17 08:34 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"type": {
What if customers want to check the provisioning_state in their flow ?

2025-04-17 10:04 UTC, ajaykn commented on internal/services/manageddevopspools/schema_definitions.go
> +				"sku": {
This is for future extension, where we might see Sku :{name, tier, cpu, ram)

2025-04-17 15:31 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"type": {
Removed `type` but kept `provisioning_state` so customers can see the status of data source

2025-04-17 15:47 UTC, ajaykn commented on internal/services/manageddevopspools/schema_definitions.go
> +								Required: true,
added, please check

2025-04-17 15:48 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      resource_id = "/Subscriptions/e21f7bce-1728-44ad-a62d-344064a0d69a/Providers/Microsoft.Compute/Locations/australiaeast/publishers/canonical/artifacttypes/vmimage/offers/0001-com-ubuntu-server-f
updated to use the data.client().subscriptoin and these are compute images from marketplace available on every subscription.

2025-04-17 15:48 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"agent_profile": AgentProfileSchema(),
Thanks for guidance. Updated, please check

2025-04-18 02:10 UTC, ms-henglu commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"type": {
Please also remove them from the data model.

2025-04-18 03:50 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"type": {
Good catch, removed from model and assignments as well in resource, data source.

2025-04-30 19:56 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +esource "azurerm_managed_devops_pool" "test" {
Thanks a catching this

2025-04-30 20:22 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			if err := expandResourceModel(config, properties); err != nil {
@ms-zhenhua  In our case, we support PUT operation. we dont support PATCH, so we need to pass anyways the entire object.
Can you please share even in this case do we need to do `metadata.ResourceData.HasChange` ?

2025-04-30 20:23 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			if err := expandResourceModel(config, &payload); err != nil {
What does inline mean in this context. Can you please share more details ?

2025-05-06 02:32 UTC, ms-zhenhua commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +				"Name must consist of alphanumeric characters, '.' or '-'. Name must also start with alphanumeric characters and cannot end with '.'.",
```suggestion
				"`name` can only include alphanumeric characters, periods (.) and hyphens (-). It must also start with alphanumeric characters and cannot end with periods (.).",
```

2025-05-06 02:32 UTC, ms-zhenhua commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			if err := expandResourceModel(config, &payload); err != nil {
it means directly put code here without define `expandResourceModel` method. You may refer to other existing resource code for more details.

2025-05-06 02:32 UTC, ms-zhenhua commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			if err := expandResourceModel(config, properties); err != nil {
For whatever PUT or PATCH API, in the Update method, only changed properties should be assigned a new value. For those unchanged properties, they should reuse values inherited from GET method.

2025-05-06 02:32 UTC, ms-zhenhua commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"dev_center_project_resource_id": {
could you reuse `dev_center_project_id` in `dev_center_project_pool_resource.go` ?

2025-05-06 02:32 UTC, ms-zhenhua commented on website/docs/r/managed_devops_pool.html.markdown
> +* `certificate_store_location` - (Optional) Specified where to store certificates on the machine.
```suggestion
* `certificate_store_location` - (Optional) Specifies where to store certificates on the machine.
```

2025-05-09 01:24 UTC, ms-zhenhua commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			if err := expandResourceModel(config, &payload); err != nil {
we should keep the same code style with existing resources

2025-05-11 15:20 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"dev_center_project_resource_id": {
Good suggestion. I have updated., please check

2025-05-11 15:20 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			if err := expandResourceModel(config, properties); err != nil {
Got it. I have followed your suggestion and updated. please check.

2025-05-11 15:21 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			if err := expandResourceModel(config, &payload); err != nil {
Done updated, please check

2025-05-11 16:23 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"dev_center_project_resource_id": {
Done, thanks for suggestion

2025-05-12 02:23 UTC, ms-zhenhua commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			if metadata.ResourceData.HasChange("location") {
`Location` is a `ForceNew` property which will not enter `Update` method. Please double check the code and remove all `ForceNew` properties from `Update`

2025-05-12 05:38 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			if metadata.ResourceData.HasChange("location") {
I see, thanks for sharing. Have updated and cross checked all ForceNew properties (location and ResourceGroup) and now none of them are being used in Update flow.

2025-05-12 06:42 UTC, ms-henglu submitted a review, later dismissed
Thanks for the PR, LGTM

2025-05-20 16:44 UTC, juicybaba commented
merge, merge, merge :wink:

2025-05-26 19:50 UTC, katbyte requested changes, later dismissed
Thanks @ajaykn - i've taken a quick look over this and left some comments inline. once those are addressed we can give this a more through review

2025-05-26 19:50 UTC, katbyte commented on website/docs/r/managed_devops_pool.html.markdown
> +* `grace_period_time_span` - (Optional) How long should the machine be kept around after it ran a workload when there are no stand-by agents. The maximum is one week. This is needed when kind is `Sta
what format is this in? seconds? iso duration?
```suggestion
* `grace_period_in_seconds` - (Optional) How long should the machine be kept around after it ran a workload when there are no stand-by agents. The maximum is one week. This is needed when kind is `Stateful`.
```
or 
```suggestion
* `grace_period_Duration` - (Optional) How long should the machine be kept around after it ran a workload when there are no stand-by agents in ISO8601 duration format, for example `P14D`. The maximum is one week. This is required when kind is `Stateful`.
```

2025-05-26 19:50 UTC, katbyte commented on website/docs/r/managed_devops_pool.html.markdown
> +* `max_agent_lifetime` - (Optional) How long should stateful machines be kept around. The maximum is one week. This is needed when kind is `Stateful`.
same as above

2025-05-26 19:50 UTC, katbyte commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"agent_profile":                  AgentProfileSchema(),
we do not abstract schema like this, could you please inline it and get rid of this function?

2025-05-26 19:50 UTC, katbyte commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"fabric_profile":                 FabricProfileSchema(),
and here

2025-05-26 19:50 UTC, katbyte commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"organization_profile": OrganizationProfileSchema(),
and here

2025-06-08 09:53 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"agent_profile":                  AgentProfileSchema(),
Curious to know the reson behind this.
I made it separate, just to avoid a very large resource.go file and keep all schema defn's in one place.
However went ahead and made changes according to your suggesttion.

Do we need to do same for datasource.go as well ?

2025-06-08 09:54 UTC, ajaykn commented on website/docs/r/managed_devops_pool.html.markdown
> +* `grace_period_time_span` - (Optional) How long should the machine be kept around after it ran a workload when there are no stand-by agents. The maximum is one week. This is needed when kind is `Sta
This is our public docs for our reference and want to keep it in the same way.
However, I have updated the description. please check.

https://learn.microsoft.com/en-us/azure/devops/managed-devops-pools/configure-scaling?view=azure-devops&tabs=azure-portal
![image](https://github.com/user-attachments/assets/6822928b-e899-49a2-8544-a936f4f9ba0c)

2025-06-08 09:54 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"fabric_profile":                 FabricProfileSchema(),
Done

2025-06-08 09:54 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"organization_profile": OrganizationProfileSchema(),
done

2025-06-10 01:47 UTC, ajaykn commented
> Thanks @ajaykn - i've taken a quick look over this and left some comments inline. once those are addressed we can give this a more through review

Thanks @katbyte for taking a look. I have addressed your comments. Please check and let me know.

2025-06-18 23:12 UTC, sreallymatt requested changes
Hi @ajaykn, I've left some comments inline. Some are suggestions, others are questions on how this API behaves as that will influence the schema design for this resource.

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"agent_profile": AgentProfileComputedSchema(),
Could you inline this schema since it's only used here?

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"fabric_profile": FabricProfileComputedSchema(),
This one as well

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"organization_profile": OrganizationProfileComputedSchema(),
and this one

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +				}
We have flatten functions specifically for `LegacySystemAndUserAssignedMap` we can use here, these flatten functions also handle the nil check for us so we can remove the condition and use of `pointer.From`.

```suggestion
				expandedIdentity, err := identity.FlattenLegacySystemAndUserAssignedMapToModel(model.Identity)
				if err != nil {
					return err
				}
				state.Identity = expandedIdentity
```

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"kind": {
Instead of exposing `kind`, it may make more sense to expose 2 separate blocks (e.g. `stateful_agent_profile` and `stateless_agent_profile`) since `kind: Stateful` requires `grace_period_time_span` and `max_agent_lifetime`?

To ensure only one is set, we could use `ExactlyOneOf`.

There are cases where we'd use separate resources to configure items like this, but since the API requires this the agent profile field to be set we unfortunately can't do that in this case. ([ref](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/schema-design-considerations.md#the-type-field))

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"images": ImagesSchema(),
Can we inline this schema and make the field name singular?

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					},
If there is only one option, we should remove `kind`, if there will be multiple we may want to take a similar approach as my suggestion for `agent_profile`

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +										"Subnet ID must match the format '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworks/{vnetName}/subnets/{subnetName}'.",
We can use the subnet ID validation function here instead of a regex

```suggestion
									ValidateFunc: commonids.ValidateSubnetID,
```

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"os_profile": OsProfileSchema(),
Can we inline this schema

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					},
This might make more sense as `sku_name`? Based on some of the examples in [the API reference](https://learn.microsoft.com/en-us/rest/api/devopspools/pools/create-or-update?view=rest-devopspools-2025-01-21&tabs=HTTP#examples) this is unlikely to get additional fields?

We can always revisit it at a later date if needed

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"storage_profile": StorageProfileSchema(),
Can we inline this

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"kind": {
If the plan is to only support `kind: AzureDevops` we should remove `kind`, if `kind: GitHub` may be supported by this resource we should split this into separate blocks.

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"organizations": {
Blocks are generally singular

```suggestion
					"organization": {
```

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									ValidateFunc: validation.StringInSlice(pools.PossibleValuesForAzureDevOpsPermissionType(), false),
Are the `groups` and `users` properties accepted for any `kind`, or only `SpecificAccounts`? This also might make sense as separate blocks/or top level properties depending on how this behaves in the API. Could you clarify? (Unfortunately we don't have the ability to test these resources to see how this behaves)

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		},
I'm not sure this adds any value to the resource, since this resource uses polling methods, if the state is `Succeeded` then Terraform will report the resource was created. If it's `Failed`, Terraform should report an error. Any in between state won't be tracked since Terraform would still be polling the API, unless the operation times out, in which case Terraform will also report an error.

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			identity, err := identity.ExpandLegacySystemAndUserAssignedMapFromModel(config.Identity)
While unlikely to cause any problems, this variable name collides with the `identity` package. Could we rename it?

```suggestion
			expandedIdentity, err := identity.ExpandLegacySystemAndUserAssignedMapFromModel(config.Identity)
```

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +				payload.Identity = identity
While unlikely to cause any problems, this variable name collides with the `identity` package. Could we rename it?

```suggestion
				expandedIdentity, err := identity.ExpandLegacySystemAndUserAssignedMapFromModel(config.Identity)
				if err != nil {
					return fmt.Errorf("expanding `identity`: %+v", err)
				}
				payload.Identity = expandedIdentity
```

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +				}
```suggestion
				expandedIdentity, err := identity.FlattenLegacySystemAndUserAssignedMapToModel(model.Identity)
				if err != nil {
					return err
				}
				state.Identity = expandedIdentity
```

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      url         = "https://dev.azure.com/managed-org-demo"
We don't currently have an Azure Devops org, and since our accounts won't have access to this one, these tests will fail when run in teamcity on our end. Could you make `organizations.url` a parameter retrieved from an environment variable (e.g. `ARM_MANAGED_DEVOPS_ORG_URL` or similar) and skip all tests unless that variable is supplied?

[For reference](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/source_control_token_resource_test.go#L25-L29)

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      resource_id = "/Subscriptions/%s/Providers/Microsoft.Compute/Locations/australiaeast/publishers/canonical/artifacttypes/vmimage/offers/0001-com-ubuntu-server-focal/skus/20_04-lts-gen2/versions/
Minor, but we could use `azurerm_platform_image` and then reference the ID from that, e.g.

```suggestion
      resource_id = data.azurerm_platform_image.test.id
```

and add this to the template:

```hcl
data "azurerm_platform_image" "test" {
  location  = azurerm_resource_group.test.location
  publisher = "Canonical"
  offer     = "0001-com-ubuntu-server-focal"
  sku       = "20_04-lts-gen2"
}
```

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +				"time_zone": {
The resource doc specifies this defaults to `UTC`, we should add that to the schema

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +				"kind": {
Based on the REST API docs, only `kind: Automatic` supports `prediction_preference` while the `ManualResourcePredictionsProfile` object only contains the `kind` field. Could you clarify what the usage is for `kind: Manual`?

Looking at this we could probably do away with `kind`, move `prediction_preference` up to `agent_profile`, and set `kind` based on whether or not `prediction_preference` was defined by the user?

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +				},
I can't tell from the API spec, but logically it would seem at least one of these is required for the request to be valid, can you confirm?

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +				"logon_type": {
API reference states this defaults to `Service`, we should do the same and make this optional

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +				"key_exportable": {
Booleans should be named with _enabled suffix ([ref](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-naming.md?plain=1#L28-L31)), maybe something like key_export_enabled?

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +				"data_disks": {
Block property names should generally be singular

```suggestion
				"data_disk": {
```

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +					MaxItems: 1,
Based on this being an array in the API, it seems like this would support more than 1, could you confirm?

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +								Optional: true,
Is there a min/max size? What is the behaviour of the API if the disk size is not included in the request?

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +								Optional: true,
The documentation says if not specified, it will be the first available letter, which would make this a computed property if returned by the API, could you confirm if this is the case?

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +func AgentProfileComputedSchema() *pluginsdk.Schema {
Computed schemas should mark all nested fields as computed as well

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +				"resource_predictions_profile": ResourcePredictionsProfileSchema(),
The schemas referenced here would need their values updated to computed

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +func FabricProfileComputedSchema() *pluginsdk.Schema {
Please update all nested fields to computed

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +func OrganizationProfileComputedSchema() *pluginsdk.Schema {
Please update all nested fields to computed

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `maximum_concurrency` - Defines how many resources can there be created at any given time.
This sentence is a bit off, would something like this make sense?

```suggestion
* `maximum_concurrency` - The maximum number of agents that can be created.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `type` - This is the resource type `Microsoft.DevOpsInfrastructure/pools.
Not in schema?

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +An `agent_profile` block supports the following:
Since this is a data source we would use `exports` instead of `supports`

```suggestion
An `agent_profile` block exports the following:
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `grace_period_time_span` - Configures the amount of time an agent in a `stateful` pool waits for new jobs before shutting down after all current and queued jobs are complete. The format for Grace P
For data sources we don't usually add formats or defaults

```suggestion
* `grace_period_time_span` - The amount of time an agent in a `stateful` pool waits for new jobs before shutting down after all current and queued jobs are complete.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `max_agent_lifetime` - Configures the maximum duration an agent in a `stateful` pool can run before it is shut down and discarded. The format for Max time to live for standby agents is `dd.hh:mm:ss
```suggestion
* `max_agent_lifetime` - The maximum duration an agent in a `stateful` pool can run before it is shut down and discarded.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `resource_predictions_profile` - One or more `resource_predictions_profile` blocks as defined below.
The schema specifies `MaxItems: 1`

```suggestion
* `resource_predictions_profile` - A `resource_predictions_profile` block as defined below.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `days_data` - A JSON string containing a list of maps, where each map represents a day of the week. Each map includes keys for start and end times, with corresponding values indicating the number o
```suggestion
* `days_data` - A JSON string containing a list of maps, where each map represents a day of the week. Each map includes keys for start and end times, with corresponding values indicating the number of agents available during those times.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `time_zone` - Specifies the time zone for the predictions data to be provisioned at. Default is UTC.
```suggestion
* `time_zone` - The time zone for the predictions data to be provisioned at.
```

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/helpers.go
> +	resource_predictions := expandResourcePredictionsModel(agentProfile.ResourcePredictions)
```suggestion
	resourcePredictions := expandResourcePredictionsModel(agentProfile.ResourcePredictions)
```

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +				"secrets_management_settings": SecretsManagementSettingsSchema(),
We can drop redundant parts of the name like `settings`, `configuration`, etc. ([ref](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-naming.md#property-naming))

```suggestion
				"secrets_management": SecretsManagementSettingsSchema(),
```

2025-06-18 23:12 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_data_source_test.go
> +func TestAccManagedDevOpsPoolDataSource_basic(t *testing.T) {
Similar to my comment in the resource test file, can we skip this unless `ARM_MANAGED_DEVOPS_ORG_URL ` env var exists?

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +A `resource_predictions_profile` block supports the following:
```suggestion
A `resource_predictions_profile` block exports the following:
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `prediction_preference` - Specifies the desired balance between cost and performance. Accepted values are: `MostCostEffective`, `MoreCostEffective`, `Balanced`, `MorePerformance`, and `BestPerforma
```suggestion
* `prediction_preference` - The desired balance between cost and performance.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +An `images` block supports the following:
```suggestion
An `images` block exports the following:
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `aliases` - List of aliases to reference the image by.
```suggestion
* `aliases` - A list of image aliases.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `buffer` - The percentage of the buffer to be allocated to this image.
```suggestion
* `buffer` - The percentage of the buffer allocated to this image.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `well_known_image_name` - The image to use from a well-known set of images made available to customers.
Since this is a data source `to use` doesn't really fit since it's not configurable.

```suggestion
* `well_known_image_name` - The image name from a well-known set of images made available to customers.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `name` - (Required) The Azure SKU of the machines in the pool.
Since it's a data source this would be computed so we can remove `(Required)`

```suggestion
* `name` - The Azure SKU of the machines in the pool.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `subnet_id` - The subnet id on which to put all machines created in the pool.
```suggestion
* `subnet_id` - The ID of the subnet associated with the Managed DevOps Pool.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `logon_type` - Determines how the service should be run. Accepted values are: `Interactive` and `Service`.
```suggestion
* `logon_type` - The logon type.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +A `secrets_management_settings` block supports the following:
```suggestion
A `secrets_management_settings` block exports the following:
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `certificate_store_location` - Specifies where to store certificates on the machine.
```suggestion
* `certificate_store_location` - The location where the certificates are stored.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `certificate_store_name` - Name of the certificate store to use on the machine. Possible values are: 'My' and 'Root'.
```suggestion
* `certificate_store_name` - The certificate store name.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `key_exportable` - Defines if the key of the certificates should be exportable.
```suggestion
* `key_exportable` - Whether the keys of the certificates are exportable.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `observed_certificates` - Specifies the list of certificates from Azure Key vault to install on all machines in the pool.
```suggestion
* `observed_certificates` - A list of certificates installed on the machines in the Managed DevOps Pool.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +A `storage_profile` block supports the following:
```suggestion
A `storage_profile` block exports the following:
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `os_disk_storage_account_type` - The storage account type of the OS disk. Possible values are: `Premium`, `Standard` and `StandardSSD`.
```suggestion
* `os_disk_storage_account_type` - The storage account type of the OS disk.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +A `data_disks` block supports the following:
```suggestion
A `data_disks` block exports the following:
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `caching` - The type of caching in a data disk. Possible values are: `None`, `ReadOnly` and `ReadWrite`.
```suggestion
* `caching` - The type of caching on the data disk.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `drive_letter` - The drive letter for the empty data disk. If not specified, it will be the first available letter.
```suggestion
* `drive_letter` - The drive letter for the empty data disk.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `storage_account_type` - The storage Account type to be used for the data disk. If omitted, the default is "standard_lrs".
```suggestion
* `storage_account_type` - The Storage Account type.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `type` - The type of managed service identity. The only possible value is `UserAssigned`.
For consistency, could we use the following for the identity block? This is generally just a copy paste from other resources with `identity` blocks with the exception of the brand name at the end.

```suggestion
* `type` - The type of Managed Service Identity that is configured on this Managed DevOps Pool

* `principal_id` - The Principal ID of the System Assigned Managed Service Identity that is configured on this Managed DevOps Pool.

* `tenant_id` - The Tenant ID of the System Assigned Managed Service Identity that is configured on this Managed DevOps Pool.

* `identity_ids` - A list of User Assigned Identity IDs assigned to this Managed DevOps Pool.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +An `organization_profile` block supports the following:
```suggestion
An `organization_profile` block exports the following:
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `projects` - (Optional) List of projects in which the pool should be created.
Could you update these descriptions, there should be no `Required/Optional` and could you phrase these without `Specifies`, `should be created`, etc. since these are not user specifiable within the data source

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `users` - (Optional) Specifies a list of user email addresses.
Please update this, same as comment above, and we don't list possible values for data source fields that are computed

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/r/managed_devops_pool.html.markdown
> +## Arguments Reference
Could you please reorder the arguments following the same convention as the schema

1. Any fields that make up the resource's ID, with the last user specified segment (usually the resource's name) first. (e.g. `name` then `resource_group_name`, or `name` then `parent_resource_id`)
2. The `location` field.
3. Required fields, sorted alphabetically.
4. Optional fields, sorted alphabetically.
5. Computed fields, sorted alphabetically. (Although in a typed resource these are always added within the `Attributes` method)

([ref](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-new-resource.md?plain=1#L171-L175))

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/r/managed_devops_pool.html.markdown
> +* `max_agent_lifetime` - Configures the maximum duration an agent in a `stateful` pool can run before it is shut down and discarded. The format for Max time to live for standby agents is `dd.hh:mm:ss
Missing `(Optional)`

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/r/managed_devops_pool.html.markdown
> +* `caching` - (Optional) The type of caching in a data disk. Accepted values are: `None`, `ReadOnly` and `ReadWrite`.
For consistency with the rest of the provider can we use `Possible values are`

```suggestion
* `caching` - (Optional) The type of caching in a data disk. Possible values are `None`, `ReadOnly` and `ReadWrite`.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/r/managed_devops_pool.html.markdown
> +* `storage_account_type` - (Optional) The storage Account type to be used for the data disk. If omitted, the default is "standard_lrs".
For consistency, default values are added as `` Defaults to `value`. ``. The value listed here doesn't match the casing of the constants used by the validate func, and could you add this default to the schema?

```suggestion
* `storage_account_type` - (Optional) The Storage Account type to be used for the data disk. Defaults to `Standard_LRS`.
```

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/r/managed_devops_pool.html.markdown
> +* `type` - (Required) The type of managed service identity. Accepted value is `UserAssigned`.
Based on the schema, the possible values are `SystemAssigned`, `UserAssigned`, and `SystemAssigned, UserAssigned`. Could you confirm which is correct?

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/r/managed_devops_pool.html.markdown
> +* `well_known_image_name` - (Optional) The image to use from a well-known set of images made available to customers.
Is this list documented anywhere so we can add a [note](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-documentation-standards.md#notes) and link to it?

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/r/managed_devops_pool.html.markdown
> +* `logon_type` - (Required) Determines how the service should be run. Accepted values are: `Interactive` and `Service`.
Could you replace all remaining instances of `Accepted values are:` with `Possible values are`

2025-06-18 23:12 UTC, sreallymatt commented on website/docs/r/managed_devops_pool.html.markdown
> +* `type` - This is the resource type `Microsoft.DevOpsInfrastructure/pools`.
This isn't in the schema

2025-06-25 02:02 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"images": ImagesSchema(),
Hi, want to know the guidance of when to inline schema.
Below are the reasons i placed in a separate file:
1. I use this same schema "ImagesScehma" in both data source and resource to avoid duplicate.
2. If I inline, then it will have the main resource / datasource files nested deep and difficult to read.

Let me know your thoughts.
For now, I am just going with fixing the field name.

2025-06-25 02:05 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					},
We are currently adding support for Container type and for that Sku will be  complex object : `{name, cpu_cores, memory_in_gb}`. So I would like to proceed with the current one. What do you think ?

2025-06-25 02:11 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +										"Subnet ID must match the format '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworks/{vnetName}/subnets/{subnetName}'.",
Thanks for sharing, this is very convenient.

2025-06-25 02:11 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +				}
I see. thanks for sharing , this is very convenient.

2025-06-25 02:11 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"agent_profile": AgentProfileComputedSchema(),
Got it, I have moved. Thanks for suggestion

2025-06-25 02:12 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"organizations": {
Got it, Done.

2025-06-25 02:16 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									ValidateFunc: validation.StringInSlice(pools.PossibleValuesForAzureDevOpsPermissionType(), false),
yes `groups` and `users` are for `SpecificAccounts` only. I will make change accordingly

2025-06-25 02:21 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		},
thanks for sharing your thoughts, I think it makes sense. Removed from resource but kept it only in data_source.

2025-06-25 02:31 UTC, ajaykn commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      resource_id = "/Subscriptions/%s/Providers/Microsoft.Compute/Locations/australiaeast/publishers/canonical/artifacttypes/vmimage/offers/0001-com-ubuntu-server-focal/skus/20_04-lts-gen2/versions/
This is nice,  have updated in r.template part.

2025-06-25 02:40 UTC, ajaykn commented on internal/services/manageddevopspools/schema_definitions.go
> +				},
Thats right, only one of this needed. added the `OneOf` validation

2025-06-25 03:01 UTC, ajaykn commented on internal/services/manageddevopspools/schema_definitions.go
> +				"key_exportable": {
I wanted to keep the variables close to API, so customers who are using the terraform resource wont have confusion.
But having said that, I understand the guidelines and naming patterns in terraform.
Will go ahead and change as per your suggestion only in the exposed schema, but underlying variables will be `KeyExportable`, so its easy to corelate in expands and flattens.

2025-06-25 03:14 UTC, ajaykn commented on internal/services/manageddevopspools/schema_definitions.go
> +				"logon_type": {
Good suggestion. updated accordingly.

2025-06-25 03:17 UTC, ajaykn commented on internal/services/manageddevopspools/schema_definitions.go
> +					MaxItems: 1,
Currenlty we support only one disk.
Regardless of Api schema, we have a service level validation, might be for future support.
> Multiple storage disks are not allowed for the pool

2025-06-25 03:20 UTC, ajaykn commented on internal/services/manageddevopspools/schema_definitions.go
> +								Optional: true,
int32 is max, but again technically we dont expect the customers to provide such large value.
> $"Disk size needs to be between 1 and 32767 inclusive for the pool {pool}."

2025-06-25 03:22 UTC, ajaykn commented on internal/services/manageddevopspools/schema_definitions.go
> +								Optional: true,
If not specified, API wont return any computed value.
So in our product, pool is just a configuration. But when customer actually refer this pool to run their Azure pipelines job (or Github Actions in future), then we provide a machine where this letter will be used and as mentioned, if not specified, we use the first available letter at that moment for that specific pool machine.

2025-06-25 03:24 UTC, ajaykn commented on internal/services/manageddevopspools/schema_definitions.go
> +func AgentProfileComputedSchema() *pluginsdk.Schema {
I see, But as mentioned in one of the previous comment, I have the same nested schema thats being used in both resource and data source file.
Do we duplicate those schemas and mark the datasource ones as computed.
Any side effects if we go this way ? (the only reason i went with is to avoid duplicate sceham defn's)

2025-06-25 03:27 UTC, ajaykn commented on website/docs/d/managed_devops_pool.html.markdown
> +* `type` - This is the resource type `Microsoft.DevOpsInfrastructure/pools.
good catch. I have cleaned up before in schema but missed in docs. Now updated.

2025-06-25 03:31 UTC, ajaykn commented on website/docs/d/managed_devops_pool.html.markdown
> +An `agent_profile` block supports the following:
Thanks for this suggestion

2025-06-25 03:32 UTC, ajaykn commented on website/docs/d/managed_devops_pool.html.markdown
> +* `grace_period_time_span` - Configures the amount of time an agent in a `stateful` pool waits for new jobs before shutting down after all current and queued jobs are complete. The format for Grace P
Got it.

2025-06-25 03:37 UTC, ajaykn commented on internal/services/manageddevopspools/helpers.go
> +	resource_predictions := expandResourcePredictionsModel(agentProfile.ResourcePredictions)
Oh, thanks for catching this. fixe.d

2025-06-25 03:39 UTC, ajaykn commented on internal/services/manageddevopspools/schema_definitions.go
> +				"secrets_management_settings": SecretsManagementSettingsSchema(),
Makes sense, thanks for the link.

2025-06-25 03:42 UTC, ajaykn commented on website/docs/d/managed_devops_pool.html.markdown
> +* `prediction_preference` - Specifies the desired balance between cost and performance. Accepted values are: `MostCostEffective`, `MoreCostEffective`, `Balanced`, `MorePerformance`, and `BestPerforma
If I understand correctly, we dont need to specifiy possible values for data source ?

2025-06-25 03:52 UTC, ajaykn commented on website/docs/d/managed_devops_pool.html.markdown
> +* `storage_account_type` - The storage Account type to be used for the data disk. If omitted, the default is "standard_lrs".
Thanks for suggestion: Updated to: `The storage account type of the data disk.`

2025-06-25 13:46 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +func AgentProfileComputedSchema() *pluginsdk.Schema {
Yes, we'd duplicate them and mark one as computed. As an example, [container apps](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containerapps/helpers/container_apps.go#L234)

2025-06-25 13:51 UTC, sreallymatt commented on internal/services/manageddevopspools/schema_definitions.go
> +								Optional: true,
Is the message you included from an API response, or a portal validation message? (If the API will return a 400 or other errors occur if we exceed `32767` we should add validation for that to the schema)

e.g. `ValidateFunc: validation.IntBetween(1, 32767),`

2025-06-25 13:57 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					},
Makes sense in that case, disregard my comment

2025-06-25 14:00 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"images": ImagesSchema(),
As all data source fields will need to be set to computed, we would need to have `ImagesSchema` and `ImagesSchemaComputed`.

Generally we avoid moving schemas elsewhere (different file, separate function) unless it's being used multiple times. If there were 2 managed devops pool related resources, that both used `ImageSchema` then we could look at separating it. (That said, there are some legacy resources that do separate out schemas that are only used once, but these will be updated over time)

2025-06-25 14:03 UTC, sreallymatt commented on website/docs/d/managed_devops_pool.html.markdown
> +* `prediction_preference` - Specifies the desired balance between cost and performance. Accepted values are: `MostCostEffective`, `MoreCostEffective`, `Balanced`, `MorePerformance`, and `BestPerforma
Correct, since a data source just retrieves data, the user doesn't really need to know all possible values. For resources, we add this so that the user knows what the provider will accept.

2025-08-04 05:10 UTC, QixiaLu commented
Hi @ajaykn , thanks for contributing to AzureRM provider and developing this resource! Just wondering if this PR is still in progress? Cause there are some Github issues requesting for it.

2025-09-20 05:37 UTC, Sharmanand commented
hi @ajaykn is it ready to shipped?

2025-09-26 13:55 UTC, MonzThomas commented
Any news here about this?

2025-09-30 04:40 UTC, ajaykn commented
> Hi @ajaykn , thanks for contributing to AzureRM provider and developing this resource! Could I kindly ask if this PR is still under development? Cause there are some Github issues requesting for it.

As we discussed offline, I was away for vacation in last month and got into oncall support. 
For others, @QixiaLu will be contributing forward and addressing the comments. Thank you so much.

2025-10-22 18:03 UTC, Jingwei-MS commented
I have passed this PR to our engineering folks for the internal review. Thanks!

2025-10-23 13:56 UTC, Lingkar commented on website/docs/r/managed_devops_pool.html.markdown
> +-> **Note:** Exactly one of `resource_id` and `well_known_image_name` are required per `image`
"An image can only have one or the other."

I think "and" should become "or" for clarity.

2025-10-23 14:08 UTC, Lingkar commented on website/docs/r/managed_devops_pool.html.markdown
> +-> **Note:** Exactly one of `resource_id` and `well_known_image_name` are required per `image`
Isn't it the case that an image can only have one or the other?
I think "and" should become "or" for clarity.

2025-10-23 14:12 UTC, Lingkar commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      resource_id = data.azurerm_platform_image.test.id
Would be good to add a test case for adding a vm image via a well_known_image_name?
I am having some issues getting it to work, and would love to see a working example.

2025-10-23 14:25 UTC, Lingkar commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      resource_id = data.azurerm_platform_image.test.id
Would be good to add a test case for adding a vm image via a well_known_image_name?
I am having some issues getting it to work, and would love to see a working example.
I am trying it with the following configuration:
```    
image {
      well_known_image_name = "ubuntu-24.04/latest"
      aliases = [
        "ubuntu-24.04",
      ]
      buffer = "*"
}
```
However receiving error:
```
performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: LinkedInvalidPropertyId: Property id '' at path 'properties.fabricProfile.images[0].resourceId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
```

2025-10-23 15:57 UTC, Lingkar commented
@QixiaLu I am attempting to deploy this resource via a Service Principal identity, (use-case running terraform from pipelines).
When one wants to configure the agent pool in ADO organizations from different tenants, what is the appropriate way of adding the Service Principal pipeline identity to the target tenants?

I am probably doing something wrong, so please correct me what I am doing wrong!
As I don't think this kind of authentication was explicitly mentioned in the documentation of the managed pool.

I tried the following approach:
```
https://login.microsoftonline.com/{{TARGET_TENANT}}/adminconsent?client_id={{CLIENT_ID APP_REGISTRATION}}&redirect_uri=https://localhost
```
With appropriate role assignments in the target tenant i am able to authenticate with this Service Principal and manipulate azure resources in the target tenant.
In the target tenant's ADO organization we add the Service Principal as a user to the organization. Than we give appropriate permissions, we add the Service Principal to the target project and we give the Service Principal "Administrator" rights via the Project's "Agent pools" security tab.

One would expect that just like a normal user account which has similair permissions in both tenants and in the target tenant's ADO organization the Service Principal is able to configure the Agent Pool in the target tenant's ADO organization.
However for the Service Principal we get back the following API error response:
```
│ ----[start]----
│ {"id":"/subscriptions/{{SOURCE_SUBSCRIPTION}}/providers/Microsoft.DevOpsInfrastructure/locations/SWEDENCENTRAL/operationStatuses/************","name":"**********","resourceId":"/subscriptions/{{SOURCE_SUBSCRIPTION}}/resourceGroups/test-managed-ado-pool/providers/Microsoft.DevOpsInfrastructure/pools/test-ado-pool","status":"Failed","startTime":"2025-10-23T15:41:54.7544578Z","endTime":"2025-10-23T15:44:11.790049Z","error":{"message":"The
│ request has been completed with result Failed. Please check details with more
│ information.","details":[{"code":"PoolProvisioningFailed","message":"Failed to provision agent pool. Exception: The logged in user,
│ {{OBJECT_ID_SERVICE_PRINCIPAL_SOURCE_TENANT}}, was not found in the Azure DevOps organization provided,
│ https://dev.azure.com/vfpfweb.","details":[],"additionalInfo":[]}],"additionalInfo":[]}}
│ -----[end]-----
```

The API request is trying to authenticate to the target tenant's ADO organization with the object id of the service principal from the source tenant and not that of the target tenant. This object id is different per tenant, for this kind of authentication it would probably be more appropriate to use the application id instead.

I was having the same issue when trying to create the managed pool with the Service Principal directly via the azapi provider.

2025-10-23 23:59 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      resource_id = data.azurerm_platform_image.test.id
@QixiaLu Would you mind to complement the test case to cover this?

2025-10-24 00:03 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +-> **Note:** Exactly one of `resource_id` and `well_known_image_name` are required per `image`
thanks for pointing it out, i'll update it.

2025-10-24 00:05 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      resource_id = data.azurerm_platform_image.test.id
sure, i'll add a test case for this

2025-10-24 03:31 UTC, magodo requested changes
@QixiaLu I've put some comments below, appreciate if you can take a look! Meanwhile, there are quite a few comments pending resolved in Matt's review: https://github.com/hashicorp/terraform-provider-azurerm/pull/28325#pullrequestreview-2940827094.

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +      subnet_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/subnet1"
Could we make this a reference to another `azurerm_subnet` resource defined above?

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +* `dev_center_project_resource_id` - (Required) The ID of the Dev Center project.
Can we make sure the `name`, `resource_group_name` and `location` are positioned first, to be consistent with the other documents?

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +* `stateless_agent_profile` - (Optional) A `stateless_agent_profile` block as defined below. Exactly one of `stateful_agent_profile` or `stateless_agent_profile` must be specified.
Based on https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-documentation-standards.md#warning-note, this shall be modified to:


```suggestion
* `stateful_agent_profile` - (Optional) A `stateful_agent_profile` block as defined below.

* `stateless_agent_profile` - (Optional) A `stateless_agent_profile` block as defined below.

~> **NOTE:** Exactly one of `stateful_agent_profile` or `stateless_agent_profile` must be specified.
```

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +* `automatic_resource_predictions_profile` - (Optional) An `automatic_resource_predictions_profile` block as defined below. Exactly one of `manual_resource_predictions_profile` or `automatic_resource
Same here

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +* `automatic_resource_predictions_profile` - (Optional) An `automatic_resource_predictions_profile` block as defined below. Exactly one of `manual_resource_predictions_profile` or `automatic_resource
Same here

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +-> **Note:** Exactly one of `resource_id` and `well_known_image_name` are required per `image`
```suggestion
~> **Note:** Exactly one of `resource_id` and `well_known_image_name` are required per `image`
```

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +      resource_id = "/Subscriptions/00000000-0000-0000-0000-000000000000/Providers/Microsoft.Compute/Locations/australiaeast/publishers/canonical/artifacttypes/vmimage/offers/0001-com-ubuntu-server-f
Can we reference an existing data source/resource (created above) instead of using a hardcoded resource id?

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +      subnet_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/subnet1"
Can we reference a `azurerm_subnet` (created above) instead of using a hardcoded resource id?

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +
Can we position the `name`, `resource_group_name` and `location` first to be consistent among the other documents?

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +* `stateless_agent_profile` - (Optional) A `stateless_agent_profile` block as defined below. Exactly one of `stateful_agent_profile` or `stateless_agent_profile` must be specified.
Based on https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-documentation-standards.md#warning-note, this shall be:


```suggestion
* `stateful_agent_profile` - (Optional) A `stateful_agent_profile` block as defined below.

* `stateless_agent_profile` - (Optional) A `stateless_agent_profile` block as defined below.

~> **NOTE:** Exactly one of `stateful_agent_profile` or `stateless_agent_profile` must be specified.
```

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +* `automatic_resource_predictions_profile` - (Optional) An `automatic_resource_predictions_profile` block as defined below. Exactly one of `manual_resource_predictions_profile` or `automatic_resource
Same here.

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +* `automatic_resource_predictions_profile` - (Optional) An `automatic_resource_predictions_profile` block as defined below. Exactly one of `manual_resource_predictions_profile` or `automatic_resource
Same here.

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +-> **Note:** Exactly one of `resource_id` and `well_known_image_name` are required per `image`
```suggestion
~> **Note:** Exactly one of `resource_id` and `well_known_image_name` are required per `image`
```

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +* `days_data` - (Required) A JSON string containing a list of maps, where each map represents a day of the week. Each map includes keys for start and end times, with corresponding values indicating t
Can we re-model this to be an array of map to be terraform idiomatic?

2025-10-24 03:31 UTC, magodo commented on website/docs/r/managed_devops_pool.html.markdown
> +* `sku` - (Required) A `sku` block as defined below.
Since it only has a `name`, can we flatten this to be `sku_name`?

2025-10-24 05:23 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"kind": {
I have removed `kind` and split `agent_profile` to `stateful_agent_profile` and `stateless_agent_profile`.

2025-10-24 05:26 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"images": ImagesSchema(),
Since there's only 1 managed devops pool resource for now, placing them in a separate file seems to be redundant. I have removed `schema_definitions.go` and make it inline.

2025-10-24 05:51 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					},
Checked with @ajaykn that there will be container fabric profile in the future. Removed `kind` and make `agent_profile` to be `vmss_fabric_profile`.

2025-10-24 05:51 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"os_profile": OsProfileSchema(),
Updated to be inline

2025-10-24 05:52 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"storage_profile": StorageProfileSchema(),
Updated to be inline

2025-10-24 05:56 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"kind": {
Since `github` is going to be supported, removed `kind` and updated it to `azure_devops_organization_profile`

2025-10-24 06:08 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			identity, err := identity.ExpandLegacySystemAndUserAssignedMapFromModel(config.Identity)
Updated to be expandedIdentity

2025-10-24 06:08 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      url         = "https://dev.azure.com/managed-org-demo"
Added `ARM_MANAGED_DEVOPS_ORG_URL` to skip tests

2025-10-24 06:09 UTC, QixiaLu commented on internal/services/manageddevopspools/schema_definitions.go
> +				"time_zone": {
Added default value

2025-10-24 06:31 UTC, QixiaLu commented on internal/services/manageddevopspools/schema_definitions.go
> +				"kind": {
This documentation contains a more comprehensive explanation of `agent_profile` and how `prediction_profile` works . (https://learn.microsoft.com/en-us/azure/devops/managed-devops-pools/configure-scaling?view=azure-devops&tabs=azure-portal)

Here is a summary of the bahavior based on the above and Azure Portal:

`agent_profile` == `stateful`: 
   (Users can update)
   1.1. grace_period_time_span
   1.2. max_agent_lifetime
   1.3. manual_resource_predictions_profile
   1.4 automatic_resource_predictions_profile

`agent_profile` == `stateless`:
   (Users can update)
   2.1. manual_resource_predictions_profile
   2.2. automatic_resource_predictions_profile
   
 `resource_predictions_profile` == `manual`:
    (Users can update)
    3.1 `resource_predictions`
 
 `resource_predictions_profile` == `automatic`:
   (Users can update)
   4.1 `prediction_prefrence`
   
 So, I have removed the `kind` here, and split `resource_predictions_profile` to `manual_*` and `automatic_*`

2025-10-24 06:32 UTC, QixiaLu commented on internal/services/manageddevopspools/schema_definitions.go
> +				"key_exportable": {
Updated to `key_export_enabled`

2025-10-24 06:32 UTC, QixiaLu commented on internal/services/manageddevopspools/schema_definitions.go
> +				"data_disks": {
Update to be `data_disk`

2025-10-24 06:33 UTC, QixiaLu commented on internal/services/manageddevopspools/schema_definitions.go
> +func AgentProfileComputedSchema() *pluginsdk.Schema {
Updated schema in data source to be computed

2025-10-24 06:34 UTC, QixiaLu commented on internal/services/manageddevopspools/schema_definitions.go
> +				"resource_predictions_profile": ResourcePredictionsProfileSchema(),
Updated to be computed for data source

2025-10-24 06:34 UTC, QixiaLu commented on internal/services/manageddevopspools/schema_definitions.go
> +func FabricProfileComputedSchema() *pluginsdk.Schema {
Updated.

2025-10-24 06:34 UTC, QixiaLu commented on internal/services/manageddevopspools/schema_definitions.go
> +func OrganizationProfileComputedSchema() *pluginsdk.Schema {
Updated, cheers

2025-10-24 06:35 UTC, QixiaLu commented on website/docs/d/managed_devops_pool.html.markdown
> +* `prediction_preference` - Specifies the desired balance between cost and performance. Accepted values are: `MostCostEffective`, `MoreCostEffective`, `Balanced`, `MorePerformance`, and `BestPerforma
Updated for data source documentation

2025-10-24 06:35 UTC, QixiaLu commented on website/docs/d/managed_devops_pool.html.markdown
> +* `os_disk_storage_account_type` - The storage account type of the OS disk. Possible values are: `Premium`, `Standard` and `StandardSSD`.
Removed possible values for data source doc

2025-10-24 06:36 UTC, QixiaLu commented on website/docs/d/managed_devops_pool.html.markdown
> +* `type` - The type of managed service identity. The only possible value is `UserAssigned`.
Updated identity block

2025-10-24 06:37 UTC, QixiaLu commented on website/docs/d/managed_devops_pool.html.markdown
> +An `organization_profile` block supports the following:
Updated text

2025-10-24 06:38 UTC, QixiaLu commented on website/docs/d/managed_devops_pool.html.markdown
> +* `projects` - (Optional) List of projects in which the pool should be created.
Removed `Required/Optional` in data source documentation. And rephrased these lines

2025-10-24 06:38 UTC, QixiaLu commented on website/docs/d/managed_devops_pool.html.markdown
> +* `users` - (Optional) Specifies a list of user email addresses.
Updated

2025-10-24 06:39 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `storage_account_type` - (Optional) The storage Account type to be used for the data disk. If omitted, the default is "standard_lrs".
Added Possible values and Default value to `storage_account_type`

2025-10-24 06:42 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `type` - (Required) The type of managed service identity. Accepted value is `UserAssigned`.
Currently, only `UserAssinged` is supported (https://learn.microsoft.com/en-us/azure/devops/managed-devops-pools/configure-identity?view=azure-devops). But `identity` is defined as defined as ManagedServiceIdentity, which accepts SystemAssigned, UserAssignedIdentity and SystemAssigned, UserAssignedIdentity. So I have added a workaround to expand/flatten identity. And updated the documentation.

2025-10-24 06:42 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `well_known_image_name` - (Optional) The image to use from a well-known set of images made available to customers.
Added a link to the `well_known_image_name`

2025-10-24 06:43 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `logon_type` - (Required) Determines how the service should be run. Accepted values are: `Interactive` and `Service`.
Updated to `Possible values are`

2025-10-24 06:43 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `type` - This is the resource type `Microsoft.DevOpsInfrastructure/pools`.
Removed `provisioning_state` and `type` from Schema and documentations.

2025-10-24 06:51 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +-> **Note:** Exactly one of `resource_id` and `well_known_image_name` are required per `image`
Updated to use `exactly one of * or *`

2025-10-24 06:53 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      resource_id = data.azurerm_platform_image.test.id
There seemed to be a validation on the API that when `resource_id=""` and `well_known_image_name=*`, it still tries to view this image as from the resource, not from the well known image. I have added a workaround to fix it. And updated the test file to cover this property.

2025-10-24 06:55 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +      subnet_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/subnet1"
I have added a `azurerm_subnet` block and reference id from that resource. thanks!

2025-10-24 06:56 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `dev_center_project_resource_id` - (Required) The ID of the Dev Center project.
Updated these args' order

2025-10-24 06:56 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `stateless_agent_profile` - (Optional) A `stateless_agent_profile` block as defined below. Exactly one of `stateful_agent_profile` or `stateless_agent_profile` must be specified.
Updated. thanks for noticing this!

2025-10-24 06:56 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `automatic_resource_predictions_profile` - (Optional) An `automatic_resource_predictions_profile` block as defined below. Exactly one of `manual_resource_predictions_profile` or `automatic_resource
Updated, thanks!

2025-10-24 06:57 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `automatic_resource_predictions_profile` - (Optional) An `automatic_resource_predictions_profile` block as defined below. Exactly one of `manual_resource_predictions_profile` or `automatic_resource
Updated

2025-10-24 06:57 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +-> **Note:** Exactly one of `resource_id` and `well_known_image_name` are required per `image`
Fixed this sign

2025-10-24 06:58 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +      resource_id = "/Subscriptions/00000000-0000-0000-0000-000000000000/Providers/Microsoft.Compute/Locations/australiaeast/publishers/canonical/artifacttypes/vmimage/offers/0001-com-ubuntu-server-f
Added an `azurerm_platform_image` data source, and reference it from there

2025-10-24 06:59 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +      subnet_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/subnet1"
I think these comments are duplicated for some reasons. But I have updated it as above

2025-10-24 06:59 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +
Updated

2025-10-24 06:59 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `stateless_agent_profile` - (Optional) A `stateless_agent_profile` block as defined below. Exactly one of `stateful_agent_profile` or `stateless_agent_profile` must be specified.
Updated as above

2025-10-24 06:59 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `automatic_resource_predictions_profile` - (Optional) An `automatic_resource_predictions_profile` block as defined below. Exactly one of `manual_resource_predictions_profile` or `automatic_resource
Updated as above

2025-10-24 06:59 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `automatic_resource_predictions_profile` - (Optional) An `automatic_resource_predictions_profile` block as defined below. Exactly one of `manual_resource_predictions_profile` or `automatic_resource
Updated as above

2025-10-24 07:00 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +-> **Note:** Exactly one of `resource_id` and `well_known_image_name` are required per `image`
Updated as above

2025-10-28 10:26 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									ValidateFunc: validation.StringInSlice(pools.PossibleValuesForAzureDevOpsPermissionType(), false),
Because there are 3 types for `kind`: `SpecificAccounts`, `Inherited` and `CreatorOnly`. When `permission_profile` is omitted, the API will add a default value to `kind` (`CreatorOnly`). Because of this, if we move kind and groups+users to the top level, it will create a perpetual drift unless we make it as required.

So, I have grouped users and groups in a separate block, and add a customizeDiff to make it as required when kind === `SpecificAccounts`.

2025-10-28 10:29 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `sku` - (Required) A `sku` block as defined below.
Good point! I have flattened it into `sku_name`. Thanks!

2025-10-28 10:34 UTC, QixiaLu commented on website/docs/r/managed_devops_pool.html.markdown
> +* `days_data` - (Required) A JSON string containing a list of maps, where each map represents a day of the week. Each map includes keys for start and end times, with corresponding values indicating t
As list of custom map is not supported, I have tried several ways to[ re-model this](https://learn.microsoft.com/en-us/azure/devops/managed-devops-pools/configure-scaling?view=azure-devops&tabs=azure-portal#manual). As discussed offline, I have updated the `days_data` to be following:

- `all_week_schedule`: an integer reprensenting the number of agents required to run 7*24 all week
- `*_schedule` for each day in the week: A map of time-to-agent-count pairs for that day.

2025-10-28 22:56 UTC, QixiaLu commented
Hi @magodo , I have updated the PR to address your comments and answered Matt's comments. Could you please have another look? Thank you! 

About acctests, There's an issue with provisioning pools either via API or Portal. It's stuck in Creation until timeout. I'll provide the tests result after it's resolved.

2025-10-29 06:12 UTC, magodo requested changes
I've left some more comments for the resource, once resolved I'll further look at the data source. Thanks!

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									Type:     pluginsdk.TypeSet,
Any reason to use `TypeSet` here? Can we either test or confirm with the service team that whether the order of `aliases` will be conserved, in which case we shall prefer using `TypeList`?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									Optional: true,
Can we add an validation here?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
Can we add an validation here?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					}
Shall we also ensure one of them is set?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +											},
Can we move these two required attributes before the optional ones?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Type:     pluginsdk.TypeSet,
Can we use `TypeList` instead?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +													Type: pluginsdk.TypeString,
Can we add an validation here?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +						ValidateFunc: validation.StringIsNotEmpty,
Is there a fixed list of possible values? Otherwise, can we add a link in the document of `sku_name` that points to the possible values listed in some official Azure document?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Optional: true,
Can we add an validation here?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									ValidateFunc: validation.IsURLWithHTTPS,
Order this please

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									Type:     pluginsdk.TypeSet,
Can we prefer to using typelist?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									Optional: true,
Can we add a validation here?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +										Type: pluginsdk.TypeString,
Can we add a validation here?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +						Computed: true,
Can we add a comment to explain why using O+C?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +													Type: pluginsdk.TypeString,
Can we add a validation here?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Type:     pluginsdk.TypeSet,
Can we prefer `TypeList`?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Type:     pluginsdk.TypeSet,
Same here

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												},
Can we add a validation here?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +				Location: location.Normalize(config.Location),
We don't have to use the `location.Normalize` in CU, but shall use it in the R. Just FYI.

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +						return fmt.Errorf("only one of `resource_id` or `well_known_image_name` can be specified for image %d in vmss_fabric_profile", i)
```suggestion
						return fmt.Errorf("only one of `resource_id` or `well_known_image_name` can be specified for image %d in `vmss_fabric_profile`", i)
```

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					if permProfile.Kind != "SpecificAccounts" {
Can we use the SDK enum instead of hard coded here?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +							return fmt.Errorf("administrator_accounts block is not required when permission_profile kind is '%s'", permProfile.Kind)
```suggestion
							return fmt.Errorf("`administrator_account` block is not required when `permission_profile` kind is `%s`", permProfile.Kind)
```

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								"administrator_accounts": {
We shall rename it to be singular: `administrator_account`

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		return fmt.Errorf("%s all_week_schedule agent count (%d) cannot exceed maximum_concurrency (%d)",
```suggestion
		return fmt.Errorf("%s `all_week_schedule` agent count (%d) cannot exceed `maximum_concurrency` (%d)",
```

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			agentCount = int64(count)
Since you've define the element type in the schema as `TypeInt`, hence it is safe to simply cast the count to `int64`/`int`.

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			return fmt.Errorf("%s %s time slot %s has agent count (%d) that exceeds maximum_concurrency (%d)",
```suggestion
			return fmt.Errorf("%s %s time slot %s has agent count (%d) that exceeds `maximum_concurrency` (%d)",
```

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +		data.ImportStep(),
Can we add one more step to test update from `complete` back to `basic`?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +  stateful_agent_profile {}
Minor, but shouldn't this be `stateless_agent_profile`?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +    sku_name = "Standard_D2ads_v5"
Can we change this to another value to test it can be updated?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      well_known_image_name = "ubuntu-24.04"
Can we change this to another value to test it can be updated?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +  maximum_concurrency            = 1
Can we change this to another value to test it can be updated?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +  dev_center_project_resource_id = azurerm_dev_center_project.test.id
Can we change this to another value to test it can be updated?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      url         = "%s"
Can we change this to another value to test it can be updated?

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/models.go
> +	MaxAgentLifetime                    *string                                    `tfschema:"max_agent_lifetime"`
Please avoid using pointer in the model

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/models.go
> +	PredictionPreference *string `tfschema:"prediction_preference"`
Please avoid using pointer in the model

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/models.go
> +	PredictionPreference *string `tfschema:"prediction_preference"`
Please avoid using pointer in the model

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/models.go
> +	WellKnownImageName *string   `tfschema:"well_known_image_name"`
Please avoid using pointer in the model

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/models.go
> +	CertificateStoreName     *string  `tfschema:"certificate_store_name"`
Please avoid using pointer in the model

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/models.go
> +	StorageAccountType *string `tfschema:"storage_account_type"`
Please avoid using pointer in the model

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/models.go
> +	Projects    *[]string `tfschema:"projects"`
Please avoid using pointer in the model

2025-10-29 06:12 UTC, magodo commented on internal/services/manageddevopspools/models.go
> +	Users  *[]string `tfschema:"users"`
Please avoid using pointer in the model

2025-10-30 22:40 UTC, QixiaLu reviewed
Hi @magodo , thanks for reviewing! I have addressed all your comments. And the acctests are passed. Could I get another review please?
<img width="1894" height="914" alt="Screenshot 2025-10-31 093651" src="https://github.com/user-attachments/assets/09248cb3-399e-40a1-926a-7b0e637655ec" />

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +													Type: pluginsdk.TypeString,
I have tested that it only accepts certificate versionless secret id. Added the validation. thanks!

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
I have added string is not empty validation.

Justifications: ([source](https://learn.microsoft.com/en-us/azure/devops/managed-devops-pools/configure-images?view=azure-devops&tabs=arm#azure-pipelines-images))
1. `well_known_image_name` aliases will change over time
2. Users are able to append versions, which is difficult to validate

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									Optional: true,
Verified in Portal that it needs to be in [1, 20000]. Added validation. Thanks!

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +						Computed: true,
Thanks for catching it! It is not O+C, but a typo. I have removed `Computed`

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								"administrator_accounts": {
Updated, thanks

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Type:     pluginsdk.TypeSet,
Updated, thanks!

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +				Location: location.Normalize(config.Location),
thanks! i have removed it from Create

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +							return fmt.Errorf("administrator_accounts block is not required when permission_profile kind is '%s'", permProfile.Kind)
updated

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		return fmt.Errorf("%s all_week_schedule agent count (%d) cannot exceed maximum_concurrency (%d)",
updated, cheers!

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			agentCount = int64(count)
updated, thank!

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +  dev_center_project_resource_id = azurerm_dev_center_project.test.id
Updated, cheers

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +    sku_name = "Standard_D2ads_v5"
sure, updated. thanks

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/models.go
> +	Users  *[]string `tfschema:"users"`
removed

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Type:     pluginsdk.TypeSet,
Updated to TypeList

2025-10-30 22:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +													Type: pluginsdk.TypeString,
Added a validation for email, ([reference](https://learn.microsoft.com/en-us/rest/api/devopspools/pools/create-or-update?view=rest-devopspools-2025-01-21&tabs=HTTP#azuredevopspermissionprofile))

2025-10-30 22:44 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									Type:     pluginsdk.TypeSet,
I have tested that the order is conserved. Changed to TypeList. thanks!

2025-10-30 22:44 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									Optional: true,
added the validation

2025-10-30 22:44 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +											},
updated the order. thanks!

2025-10-30 22:46 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +													Type: pluginsdk.TypeString,
added the validation. thanks!

2025-10-30 22:48 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									Optional: true,
added the validation to match with maximum_concurrency. As [documented](https://learn.microsoft.com/en-us/rest/api/devopspools/pools/create-or-update?view=rest-devopspools-2025-01-21&tabs=HTTP#pool), the upper limit is `10000`. Even though it's shown as 20000 in portal, as confirmed with the service team, we'll leave it as 10000 for safety

2025-10-30 22:48 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									ValidateFunc: validation.IsURLWithHTTPS,
Updated the order. thanks!

2025-10-30 22:48 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +													Type: pluginsdk.TypeString,
Added missing validation. thx

2025-10-30 22:48 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Type:     pluginsdk.TypeSet,
updated, thx

2025-10-30 22:48 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												},
added missing validation for emails

2025-10-30 22:50 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_data_source_test.go
> +func TestAccManagedDevOpsPoolDataSource_basic(t *testing.T) {
added a check to skip tests

2025-10-30 22:51 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
I have added string is not empty validation.

Justifications: ([source](https://learn.microsoft.com/en-us/azure/devops/managed-devops-pools/configure-images?view=azure-devops&tabs=arm#azure-pipelines-images))

- well_known_image_name aliases will change over time
- Users are able to append versions, which is difficult to validate

2025-10-30 22:51 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Type:     pluginsdk.TypeSet,
I have tested that the order is conservative. Updated to `TypeList`.

2025-10-30 22:52 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +						ValidateFunc: validation.StringIsNotEmpty,
The sku_name varies on the location. I have added a link in the document.

2025-10-30 22:52 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Optional: true,
Added a validation to make sure it's a single letter and not A, C, D or E. ([reference](https://learn.microsoft.com/en-us/azure/devops/managed-devops-pools/configure-storage?view=azure-devops&tabs=bicep%2Cwindows#attach-an-empty-data-disk))

2025-10-30 22:52 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									Type:     pluginsdk.TypeSet,
I have tested that projects is order conserved. Updated.

2025-10-30 22:52 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +										Type: pluginsdk.TypeString,
Updated the project's name validation to match [ADO project names](https://learn.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops#project-names)

2025-10-30 22:53 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +						Computed: true,
Thanks for catching it! It is not O+C, but a typo. I have removed Computed

2025-10-30 22:53 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								"administrator_accounts": {
Updated, thanks

2025-10-30 22:53 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Type:     pluginsdk.TypeSet,
Updated, thanks!

2025-10-30 22:53 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +				Location: location.Normalize(config.Location),
thanks! i have removed it from Create

2025-10-30 22:54 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +						return fmt.Errorf("only one of `resource_id` or `well_known_image_name` can be specified for image %d in vmss_fabric_profile", i)
Updated, thx

2025-10-30 22:54 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					}
Updated to validate from the raw config. this is to prevent false positive on unknown resource id from data source.

2025-10-30 22:54 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					if permProfile.Kind != "SpecificAccounts" {
updated, thanks!

2025-10-30 22:54 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +							return fmt.Errorf("administrator_accounts block is not required when permission_profile kind is '%s'", permProfile.Kind)
updated

2025-10-30 22:54 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		return fmt.Errorf("%s all_week_schedule agent count (%d) cannot exceed maximum_concurrency (%d)",
updated, cheers!

2025-10-30 22:55 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			agentCount = int64(count)
updated, thank!

2025-10-30 22:55 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			return fmt.Errorf("%s %s time slot %s has agent count (%d) that exceeds maximum_concurrency (%d)",
updated

2025-10-30 22:55 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +		data.ImportStep(),
Included this step, thanks

2025-10-30 22:55 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +  stateful_agent_profile {}
uh, nice catch! updated

2025-10-30 22:56 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +  maximum_concurrency            = 1
Updated to 2, which is acceptable by the sku

2025-10-30 22:56 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +  dev_center_project_resource_id = azurerm_dev_center_project.test.id
Updated, cheers

2025-10-30 22:56 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      url         = "%s"
updated, thanks!

2025-10-30 22:56 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +      well_known_image_name = "ubuntu-24.04"
Updated!

2025-10-30 22:56 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource_test.go
> +    sku_name = "Standard_D2ads_v5"
sure, updated. thanks

2025-10-30 22:57 UTC, QixiaLu commented on internal/services/manageddevopspools/models.go
> +	MaxAgentLifetime                    *string                                    `tfschema:"max_agent_lifetime"`
Removed pointers in the model. thanks!

2025-10-30 22:57 UTC, QixiaLu commented on internal/services/manageddevopspools/models.go
> +	PredictionPreference *string `tfschema:"prediction_preference"`
removed

2025-10-30 22:57 UTC, QixiaLu commented on internal/services/manageddevopspools/models.go
> +	WellKnownImageName *string   `tfschema:"well_known_image_name"`
removed

2025-10-30 22:57 UTC, QixiaLu commented on internal/services/manageddevopspools/models.go
> +	CertificateStoreName     *string  `tfschema:"certificate_store_name"`
removed

2025-10-30 22:57 UTC, QixiaLu commented on internal/services/manageddevopspools/models.go
> +	StorageAccountType *string `tfschema:"storage_account_type"`
removed

2025-10-30 22:57 UTC, QixiaLu commented on internal/services/manageddevopspools/models.go
> +	Projects    *[]string `tfschema:"projects"`
removed

2025-10-30 22:58 UTC, QixiaLu commented on internal/services/manageddevopspools/models.go
> +	Users  *[]string `tfschema:"users"`
removed

2025-10-30 23:07 UTC, QixiaLu commented
Hi @magodo , thanks for reviewing! I have updated the PR based on your review, and fix some issues I have noticed. The acctests are passed. Could I get a rereview please? thank you!
<img width="1894" height="914" alt="Screenshot 2025-10-31 093651" src="https://github.com/user-attachments/assets/1be0d3ad-3e47-48a6-98b8-342a6f9931ec" />

2025-10-31 00:04 UTC, magodo submitted a review, later dismissed
Thanks @QixiaLu! I've left some more comments, please take a look!

2025-10-31 00:04 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +	vmssFabricSlice := vmssFabricValue.AsValueSlice()
This will panic if the `vmssFabricValue` is unknown. Instead, you can call `vmssFabricValue.IsWhollyKnown` and return early if it is false. Otherwise if it is known, you can just do the validation based on `vmssFabricProfiles`.

2025-10-31 00:04 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"provisioning_state": {
We don't need this as it is useless for the users.

2025-10-31 00:04 UTC, magodo commented on internal/services/manageddevopspools/managed_devops_pool_data_source_test.go
> +				check.That(data.ResourceName).Key("location").HasValue(location.Normalize(data.Locations.Primary)),
Can we add more checks on those computed attributes to ensure they are correctly set during `Read()`?

2025-10-31 00:04 UTC, magodo commented on website/docs/d/managed_devops_pool.html.markdown
> +* `name` - (Required) The name of this Managed DevOps Pool. Changing this forces a new Managed DevOps Pool to be created.
```suggestion
* `name` - (Required) The name of this Managed DevOps Pool.
```

2025-10-31 00:04 UTC, magodo commented on website/docs/d/managed_devops_pool.html.markdown
> +* `resource_group_name` - (Required) The name of the Resource Group where the Managed DevOps Pool exists. Changing this forces a new Managed DevOps Pool to be created.
```suggestion
* `resource_group_name` - (Required) The name of the Resource Group where the Managed DevOps Pool exists.
```

2025-10-31 03:12 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +	vmssFabricSlice := vmssFabricValue.AsValueSlice()
I didn't know that there is such useful method `IsWhollyKnown`! Thanks for pointing it out. Simplified the code by using it. 

One comment on this is that if it's unknown during plan, we'll rely on the API to validate. But on this way, we can avoid panic

2025-10-31 03:12 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"provisioning_state": {
Removed `provisioning_state`

2025-10-31 03:12 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_data_source_test.go
> +				check.That(data.ResourceName).Key("location").HasValue(location.Normalize(data.Locations.Primary)),
Added additional checks on required fields

2025-10-31 03:12 UTC, QixiaLu commented on website/docs/d/managed_devops_pool.html.markdown
> +* `name` - (Required) The name of this Managed DevOps Pool. Changing this forces a new Managed DevOps Pool to be created.
removed the force new def

2025-10-31 03:12 UTC, QixiaLu commented on website/docs/d/managed_devops_pool.html.markdown
> +* `resource_group_name` - (Required) The name of the Resource Group where the Managed DevOps Pool exists. Changing this forces a new Managed DevOps Pool to be created.
removed the force new def

2025-10-31 03:12 UTC, QixiaLu commented
Hi @magodo , I have addressed your above comments. I also updated the documentation - fix the ordering, to make it consistent with the `reference-documentation-standards.md`.  here's a rerun of the data source acctest. Could i get a rereview please? thanks!

<img width="1876" height="151" alt="Screenshot 2025-10-31 134947" src="https://github.com/user-attachments/assets/0d0173da-ca25-4e9a-b0f7-600511e8c924" />

2025-11-16 01:37 UTC, davidkarlsen commented
Anything left to do here or is it ripe for merging?

2025-11-16 12:41 UTC, Lingkar commented
> @QixiaLu I am attempting to deploy this resource via a Service Principal identity, (use-case running terraform from pipelines). When one wants to configure the agent pool in ADO organizations from different tenants, what is the appropriate way of adding the Service Principal pipeline identity to the target tenants?
> 
> I am probably doing something wrong, so please correct me what I am doing wrong! As I don't think this kind of authentication was explicitly mentioned in the documentation of the managed pool.
> 
> I tried the following approach:
> 
> ```
> https://login.microsoftonline.com/{{TARGET_TENANT}}/adminconsent?client_id={{CLIENT_ID APP_REGISTRATION}}&redirect_uri=https://localhost
> ```
> 
> With appropriate role assignments in the target tenant i am able to authenticate with this Service Principal and manipulate azure resources in the target tenant. In the target tenant's ADO organization we add the Service Principal as a user to the organization. Than we give appropriate permissions, we add the Service Principal to the target project and we give the Service Principal "Administrator" rights via the Project's "Agent pools" security tab.
> 
> One would expect that just like a normal user account which has similair permissions in both tenants and in the target tenant's ADO organization the Service Principal is able to configure the Agent Pool in the target tenant's ADO organization. However for the Service Principal we get back the following API error response:
> 
> ```
> │ ----[start]----
> │ {"id":"/subscriptions/{{SOURCE_SUBSCRIPTION}}/providers/Microsoft.DevOpsInfrastructure/locations/SWEDENCENTRAL/operationStatuses/************","name":"**********","resourceId":"/subscriptions/{{SOURCE_SUBSCRIPTION}}/resourceGroups/test-managed-ado-pool/providers/Microsoft.DevOpsInfrastructure/pools/test-ado-pool","status":"Failed","startTime":"2025-10-23T15:41:54.7544578Z","endTime":"2025-10-23T15:44:11.790049Z","error":{"message":"The
> │ request has been completed with result Failed. Please check details with more
> │ information.","details":[{"code":"PoolProvisioningFailed","message":"Failed to provision agent pool. Exception: The logged in user,
> │ {{OBJECT_ID_SERVICE_PRINCIPAL_SOURCE_TENANT}}, was not found in the Azure DevOps organization provided,
> │ https://dev.azure.com/vfpfweb.","details":[],"additionalInfo":[]}],"additionalInfo":[]}}
> │ -----[end]-----
> ```
> 
> The API request is trying to authenticate to the target tenant's ADO organization with the object id of the service principal from the source tenant and not that of the target tenant. This object id is different per tenant, for this kind of authentication it would probably be more appropriate to use the application id instead.
> 
> I was having the same issue when trying to create the managed pool with the Service Principal directly via the azapi provider.

@davidkarlsen I didn't receive a response yet on my question about cross-tenant ADO configuration via Service Principal.

2025-11-17 01:23 UTC, QixiaLu commented
Hi @Lingkar , thanks for testing this resource. As it's an Azure service-related issue, I have shared it with the service team. Please expect some responses from them. Meanwhile, you could find more details [here](https://developercommunity.azure.com/t/Managed-DevOps-Pools-Feature-Request:/10763366?ftype=idea). If it's urgent, please open a support ticket. Thanks for your understanding!

2025-11-17 01:25 UTC, QixiaLu commented
Hi @davidkarlsen , thanks for reaching out! This PR is still under internal review. I'll try to get some prioritizations on the review.

2025-11-17 23:15 UTC, magodo commented
This LGTM now :+1:

2025-11-19 03:58 UTC, wuxu92 reviewed
Thank you for the new resources! I've added a few comments; otherwise, everything looks good to me. 🏷️

2025-11-19 03:58 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"permission_profile": {
Insert a blank line between top-level schema blocks to align with the provider. This formatting should also apply to other schemas.

```suggestion
					},

					"permission_profile": {
```

2025-11-19 03:58 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +										},
IIRC we should not define all nested arguments as optional, at least one should be required, or `AtLeastOneOf` should be added, so user would not define a empty block in configuration.

2025-11-19 03:58 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
can we specify the `aliases`, `resource_id` and `well_known_image_name` at the same time? if not we may add a conflict with to make it clear and easier to use.

2025-11-19 03:58 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
this `network_profile` block only contains one argument, can we make it a top-level argument to make it clear?

2025-11-19 03:58 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			payload := pools.Pool{
```suggestion
			azureDevOpsOrganizationProfile := expandAzureDevOpsOrganizationProfileModel(config.AzureDevOpsOrganizationProfile)
			fabricProfile := expandVmssFabricProfileModel(config.VmssFabricProfile)
			payload := pools.Pool{
```

2025-11-19 09:11 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"permission_profile": {
Updated this and others in the schema, thanks!

2025-11-19 09:12 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +										},
Good point! I have addeded AtLeastOneOf since users are able to set these 2 values at the same time. thanks

2025-11-19 09:12 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
`resource_id` and `well_knwon_image_name` cannot be set at the same time. Because `image` is a TypeList with more than 1 item, I cannot add `ExactlyOneOf`. So I implemented `validateVmssFabricProfileImages` in `CustomizeDiff` as a workaround.

2025-11-19 09:12 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
yep, good point. Updated it. cheers

2025-11-19 09:12 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			payload := pools.Pool{
Fixed, thanks!

2025-11-20 00:03 UTC, wuxu92 approved these changes
Thanks @QixiaLu LGTM ☘️

2025-11-20 01:19 UTC, QixiaLu commented
Hi @sreallymatt , thanks for reviewing this PR🥇! I have addressed your comments above. And our team has done a round of internal review. It's now ready for some rereviews from your end. Cheers!

2025-11-26 22:44 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"vmss_fabric_profile": {
Could you update this following our naming conventions? ([ref](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/reference-naming.md?plain=1#L15-L16))

```suggestion
		"virtual_machine_scale_set_fabric_profile": {
```

2025-11-26 22:44 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +											"disk_size_gb": {
Could you update this to `disk_size_in_gb` to follow our naming conventions?

```suggestion
											"disk_size_in_gb": {
```

2025-11-26 22:51 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"dev_center_project_resource_id": commonschema.ResourceIDReferenceRequired(&projects.ProjectId{}),
When referencing an Azure Resource ID we generally omit `resource` from the field name

```suggestion
		"dev_center_project_id": commonschema.ResourceIDReferenceRequired(&projects.ProjectId{}),
```

2025-11-26 22:54 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +											"disk_size_gb": {
```suggestion
											"disk_size_in_gb": {
```

2025-11-26 23:11 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +							return fmt.Errorf("`administrator_account` block is not required when `permission_profile` kind is `%s`", permProfile.Kind)
Given we're returning an error and preventing this configuration from being provisioned, would it make sense to update the message to something like the below?

imo `is not required` makes it sound optional, but not necessarily incorrect

```suggestion
							return fmt.Errorf("`administrator_account` block must not be specified when `permission_profile` kind is `%s`", permProfile.Kind)
```

2025-11-28 13:03 UTC, a-fatemi commented
This PR is almost a year old! Where do we celebrate its one-year anniversary? 🥳

2025-11-28 15:14 UTC, jgschwendswica commented
> This PR is almost a year old! Where do we celebrate its one-year anniversary? 🥳

We constantly postponed the implementation with Azapi since half a year, since the PR was about to get merged any time soon... :joy:

2026-02-13 06:27 UTC, wuxu92 reviewed
I have left some comments to update the validate function and default value of devops pools

2026-02-13 06:27 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +				regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9-.]*[a-zA-Z0-9-]$`),
pool name should be less than 45 characters, means [3,44] characters

2026-02-13 06:27 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			ValidateFunc: validation.IntBetween(1, 10000),
the limit in portal is at most 20000

2026-02-13 06:27 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +						ValidateFunc: validation.StringIsNotEmpty,
add validate for `Agent lifetime for stateful pools can not be higher than 7 days (07.00:00:00).`

2026-02-13 06:27 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									Optional: true,
`buffer` will be set to "*" by API, so we may need to add a default value for it.

```
          ~ image {
              - buffer                = "*" -> null
                # (3 unchanged attributes hidden)
            }
```

2026-02-13 06:27 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		for i, image := range vmssFabricProfile.Images {
if the config with a empty `image {}` block, it will not be loaded to `vmssFabricProfile`, so user will see drift after apply  below, but if we add default value to `buffer` field, this issue not exists.

```
      ~ vmss_fabric_profile {
            # (2 unchanged attributes hidden)

          + image {}

            # (1 unchanged block hidden)
        }
```

2026-02-13 06:27 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
a validation is still helpful to validate the value should starts with the given list, even we don't validate the version part?

2026-02-16 04:31 UTC, wuxu92 reviewed
this resource works over all, I left some comments to improve the schema design, validation and behavior align with Portal.

2026-02-16 04:31 UTC, wuxu92 commented on internal/services/manageddevopspools/helpers.go
> +					Default:  "UTC",
a ValidateFunc is required as the API does not valiate the value, users can provide any value and apply with no error but actually wrong. time zone validate example: https://github.com/hashicorp/terraform-provider-azurerm/blob/c79555275135d279b206be3095cb945ef4d1e6ff/internal/services/compute/validate/compute.go#L104

2026-02-16 04:31 UTC, wuxu92 commented on internal/services/manageddevopspools/helpers.go
> +					Type:          pluginsdk.TypeMap,
define as `TypeMap` we can't validate the key which should be a time in 24-hour format, curretly the API does not validate the time so user can put "27:00:00" as key and apply with no error(the API actually set as "27.00:00:00" in backend which cause drfit after apply and break the Portal display), but this is no possible in Portal.

2026-02-16 04:31 UTC, wuxu92 commented on internal/services/manageddevopspools/helpers.go
> +					Optional:      true,
what about use a unified schema like below to add validations and simply the schema

```
		"monday_schedule": {
			Type: pluginsdk.TypeList,
			MinItems: 1,
			Elem: &pluginsdk.Resource{
				Schema: map[string]*pluginsdk.Schema{
					"time": {
						Type: pluginsdk.TypeString,
						Required: true,
						ValidateFunc: validation.StringMatch(regexp.MustCompile(`^([01]\d|2[0-3]):[0-5]\d:[0-5]\d$`), "time in 24-hour format from 00:00:00 to 24:00:00"),
					},

					"count": {
						Type:pluginsdk.TypeInt,
						Required: true,
						ValidateFunc: validation.IntAtLeast(0),
					},
				},
			},
```

so the all_week_schedule can be specified as:

```hcl
sunday_schedule {
    time = "00:00:00",
    count = 1
}
```

and other schedules can be specified by multiple `xxx_schedule` block:

```hcl
sunday_schedule {
    time = "08:00:00",
    count = 1
}

monday_schedule {
    time = "20:00:00",
    count = 0
}
```

2026-02-16 04:31 UTC, wuxu92 commented on internal/services/manageddevopspools/helpers.go
> +	}
<del>can we simplify the schema as it's a block with only one property? use a property like `automatic_resource_prediction_preference` to replace the `automatic_resource_predictions_profile` block</del> we can use the current design as the `prediction_preference` has a default value.

2026-02-16 04:31 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
this property can move `os_disk_storage_account_type` to upper level to the sibling of `sku_name` and `images` just like the Portal, then the `storage_profile` focus on the the data disk and we can simplify the schema by removing the `data_disk` layer. `os_disk_storage_account_type` should have a default value as Standard or the API will response error for config like:

```
    storage_profile {
      data_disk {
      }
    }
```

2026-02-16 04:31 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Optional:     true,
data disk size is required not optional, and to align with the guidance the naming should be `disk_size_in_gb`

2026-02-16 04:31 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"os_profile": {
while directly mapping the SDK property name works most of the time, but name `os_profile` here looks not helpful, what about rename it to `security` like the naming in Portal: this block works for the security part of the devops pool in Portal

2026-02-16 04:31 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								"logon_type": {
may we rename this is `interactive_logon_enabled` as boolean type and default as false to make it clear to user and use the same logic as Portal?

2026-02-16 04:31 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +											},
while this value is not required by API, Portal does validate on this field must not be empty. can we confirm with service team about it?

2026-02-16 04:31 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												ValidateFunc: validation.StringInSlice(pools.PossibleValuesForCertificateStoreNameOption(), false),
though the swagger and SDK defined this as an enum list and the possible values, but "My" and "Root" are actually only for windows, for linux this name can be any possible directory, we need to confirm with service team if the swagger need to be updated. if yes then we have to support other values rather than only "My" and "Root".

2026-02-16 04:31 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"stateful_agent_profile": {
can we rename all properties `xxx_profile` by removing suffix `_profile` according to guidance https://github.com/hashicorp/terraform-provider-azurerm/blob/7a5c692e36666cbcc8459b53b260a6ad89bdb915/contributing/topics/reference-naming.md?plain=1#L18 .

2026-02-16 04:52 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +											},
defaults to `false`?

2026-02-16 04:52 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +											"observed_certificates": {
rename to `key_vaule_certificate_url` for clear and align with other resource of provider

2026-02-16 04:52 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +													ValidateFunc: keyvaultvalidate.NestedItemIdWithOptionalVersion,
it seems versioned id is not supported, the API responses with error whilse the backed did updated the entity(portal shows the key vault id with version after apply), so we need to update this validate func to limit to versionless id.

```
│ request has been completed with result Failed. Please check details with more information.","details":[{"code":"InvalidKeyVaultUrl","message":"The request contains an invalid keyvault URI
│ 'https://xuwu-devops-kvtest.vault.azure.net/secrets/xuwu-devops-certtest2/326f73bce2b04e0ebdeb60e10a14876d'.","details":[],"additionalInfo":[]}],"additionalInfo":[]}}
```

2026-02-18 03:35 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"dev_center_project_resource_id": commonschema.ResourceIDReferenceRequired(&projects.ProjectId{}),
`dev_center_project_resource_id` to `dev_center_project_id`

2026-02-18 03:35 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								"resource_id": {
`id` should be enough

2026-02-18 03:35 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								"secrets_management": {
rename it to liek `key_vault_management`

2026-02-18 03:35 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +													ValidateFunc: keyvaultvalidate.NestedItemIdWithOptionalVersion,
use validate function from go azure helpers: `keyvault.ValidateNestedItemID(keyvault.VersionTypeVersioned, keyvault.NestedItemTypeSecret)`

https://github.com/hashicorp/terraform-provider-azurerm/blob/faf6310c4b4d7b4f6934f4b15489cdd90d9337be/vendor/github.com/hashicorp/go-azure-helpers/resourcemanager/keyvault/nested_item.go#L139

2026-02-18 03:35 UTC, wuxu92 commented on internal/services/manageddevopspools/helpers.go
> +					Default:  "UTC",
rename to `time_zone_name`

2026-02-18 03:35 UTC, wuxu92 commented on internal/services/manageddevopspools/helpers.go
> +					Optional:      true,
update the typeMap to a list of block instead of a new list of block above

2026-02-18 03:35 UTC, wuxu92 commented on internal/services/manageddevopspools/helpers.go
> +	}
this block is fine as the prediction_preference has a default value.

2026-02-18 03:35 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
we need to confirm from service team about this parallelism when setting with more than 1 orgs. I set the maximum_concurrency of this pool to 1, and left first org parallelism unset (say defaults to 0) and the second org parallelism=1 which should meet the requirement of `The sum of parallelism for all organizations must equal the max pool size.`  but I got below error in Update but actually the update is success and Portal displayed the updated value.

```
        "message": "The request has been completed with result Failed. Please check details with more information.",
        "details": [
            {
                "code": "InvalidOrganizationParallelism",
                "message": "Organizations parallelism cannot be zero for pool acctest-pool-xuwue-1.",
                "details": [],
                "additionalInfo": []
            }

```

2026-02-25 01:12 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			ValidateFunc: validation.IntBetween(1, 10000),
The API only allows up to 10k concurrencies ([documentation](https://learn.microsoft.com/en-us/rest/api/devopspools/pools/get?view=rest-devopspools-2025-01-21&tabs=HTTP#pool)). Setting to value greater than 10k fails: 
```
{"error":{"code":"HttpRequestPayloadAPISpecValidationFailed","target":"Microsoft.DevOpsInfrastructure/pools/acctest-pool-lucia-1","message":"HTTP request payload failed validation against API specification with one or more errors. Please see details for more information.","details":[{"code":"Maximum","message":"Value 10001 is greater than maximum 10000. Paths in payload: '$.properties.maximumConcurrency'"}]}}
```
I'll double check with the service team to see if it's expected

Update: Confirmed with the service team that the upper limit is `10k`

2026-02-26 05:43 UTC, QixiaLu commented on internal/services/manageddevopspools/helpers.go
> +					Optional:      true,
Updated to the suggested format and added one more validation:

Same day schedule entry with the same time slot should be merged into a single unit, otherwise, the API will merge them automatically and cause drift:

Config:
```
manual_resource_prediction {
      time_zone_name = "UTC-11"
      monday_schedule {
        count = 2
        time = "02:00:00"
      }
      monday_schedule {
        count = 0
        time = "02:30:00"
      }
      monday_schedule {
        count = 1
        time = "02:30:00"
      }
      monday_schedule {
        count = 0
        time = "05:00:00"
      }
    }
```
API returns:
`"daysData":[{},{"02:00:00":2,"02:30:00":1,"05:00:00":0},{},{},{},{},{}]}`

2026-02-27 02:54 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +						ValidateFunc: validation.StringIsNotEmpty,
Added additional validation. Thx!

Currently confirming additional validation format with the service team. In portal, it doesn't accept values with `hh` greater than 7, e.g. `08:00:00`. But API request is successful.

2026-02-27 03:00 UTC, QixiaLu commented on internal/services/manageddevopspools/helpers.go
> +					Default:  "UTC",
Added additional validation for `time_zone_name`. Possible values are from `[System.TimeZoneInfo]::GetSystemTimeZones()` in Powershell as it provides more comprehensive value sets.

2026-02-27 03:01 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
Updated schema design. Thx!

2026-02-27 03:02 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +											},
Thanks, have triaged this inconsistency with the service team, waiting for responses. 

Updated: confirmed with the service team that this is an optional field.

2026-02-27 04:36 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"os_profile": {
Updated to `security`. Thanks!

2026-02-27 06:35 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												ValidateFunc: validation.StringInSlice(pools.PossibleValuesForCertificateStoreNameOption(), false),
Confirming with the service team, will update once they get back on this. thx!

2026-03-01 23:59 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +				regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9-.]*[a-zA-Z0-9-]$`),
Updated, thanks

2026-03-02 00:00 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									Optional: true,
Added default value to buffer, thanks

2026-03-02 00:01 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +												Optional:     true,
Updated name and requiredness

2026-03-02 00:02 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								"logon_type": {
Updated to boolean type with false as default

2026-03-02 00:16 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +													ValidateFunc: keyvaultvalidate.NestedItemIdWithOptionalVersion,
Updated validation for versionless with Certificate only

2026-03-02 02:06 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +								},
Service team has confirmed that the `parallelism` is an optional field. 

- If users don't provide it, the backend will compute a value for it (could be value other than `0`).
- If users provide a value, it has to be within [1, 10k], and the sum of parallelism equals to the maximum Concurrency or not (so I have added a precheck in the customDiff for this)

2026-03-03 01:18 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		for i, image := range vmssFabricProfile.Images {
Added default value, cheers

2026-03-03 01:19 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"stateful_agent_profile": {
Removed `_profile` suffix

2026-03-03 01:19 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +											},
Updated to optional with default false

2026-03-03 01:19 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +											"observed_certificates": {
Updated, thx!

2026-03-03 01:20 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"dev_center_project_resource_id": commonschema.ResourceIDReferenceRequired(&projects.ProjectId{}),
Renamed, thx!

2026-03-03 02:24 UTC, QixiaLu commented
Thanks @wuxu92  for reviewing! I have addressed your comments above and left some follow ups. Could I get a rereview please? Below is the latest acctest results:

<img width="2332" height="899" alt="image" src="https://github.com/user-attachments/assets/6bd1dff5-d08d-481d-a3a2-89e3e9b7d89d" />

2026-03-05 02:09 UTC, QixiaLu commented
Latest acctest result:

<img width="1529" height="502" alt="Screenshot 2026-03-05 130814" src="https://github.com/user-attachments/assets/9738f7b1-e690-4cd2-8ca5-e9ae3b9d6e39" />

2026-03-30 02:59 UTC, wuxu92 reviewed
Thanks @QixiaLu for the updates, it look good to me now, but we can improve the validation function for the name of the resource/data source, once this is fixed we can make this PR ready for review!

2026-03-30 02:59 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +			),
merge to one single regexp:
```suggestion
			ValidateFunc: validation.StringMatch(
				regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9-.]{1,42}[a-zA-Z0-9-]$`),
				"`name` can only include alphanumeric characters, periods (.) and hyphens (-). It must also start with alphanumeric characters and cannot end with periods (.) and length between 3 and 44.",
			),
```

2026-03-30 02:59 UTC, wuxu92 commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			),
merge to one single regexp:
```suggestion
			ValidateFunc: validation.StringMatch(
				regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9-.]{1,42}[a-zA-Z0-9-]$`),
				"`name` can only include alphanumeric characters, periods (.) and hyphens (-). It must also start with alphanumeric characters and cannot end with periods (.) and length between 3 and 44.",
			),
```

2026-03-30 04:53 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +			),
Updated, thank you!

2026-03-30 04:53 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			),
Updated to one regex, thanks!

2026-03-30 04:54 UTC, QixiaLu commented
Thanks @wuxu92 for reviewing! Here is the latest acctests result

<img width="1101" height="429" alt="image" src="https://github.com/user-attachments/assets/4ced0818-6d42-49dc-91f6-bcd3ca08c189" />

2026-03-31 03:43 UTC, wuxu92 approved these changes
Thanks @QixiaLu LGTM :shipit:

2026-03-31 04:20 UTC, ms-henglu approved these changes
LGTM

2026-04-06 16:18 UTC, sreallymatt requested changes
Thanks for the work you've put into this PR @QixiaLu - I've left just a couple comments regarding some of our documented conventions. Once those are resolved this should be good to go :shipit:

2026-04-06 16:18 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +					"max_agent_lifetime": {
minor, but given the naming reference states to avoid abbreviations can we use `maximum_*` here

```suggestion
					"maximum_agent_lifetime": {
```

2026-04-06 16:18 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"vmss_fabric": {
as above, can we expand this out?

```suggestion
		"virtual_machine_scale_set_fabric": {
```

2026-04-06 16:18 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			),
Partially resolved, based on Xu's suggestion, ln56 can also be removed as it's made redundant by the updated regex

2026-04-06 16:18 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +		"vmss_fabric": {
Same as my comment in the datasource

```suggestion
		"virtual_machine_scale_set_fabric": {
```

2026-04-06 16:18 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					"max_agent_lifetime": {
```suggestion
					"maximum_agent_lifetime": {
```

2026-04-06 16:18 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			if metadata.ResourceData.HasChange("stateful_agent") || metadata.ResourceData.HasChange("stateless_agent") {
functionally the same and this is not blocking the merge of this PR, but for future reference we could use `HasChanges` in place of chaining `HasChange` calls with `||` (or `&&`)

```suggestion
			if metadata.ResourceData.HasChanges("stateful_agent", "stateless_agent") {
```

2026-04-06 16:18 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +				payload.Properties.OrganizationProfile = organization
Also not a blocking issue, but in cases like this where the expand func returns only the expanded object we generally skip the variable and assign directly to the payload object


```suggestion
				payload.Properties.OrganizationProfile = expandAzureDevOpsOrganizationModel(config.AzureDevOpsOrganization)
```

2026-04-06 16:18 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					state.DevCenterProjectId = props.DevCenterProjectResourceId
In the past we've seen issues with Azure returning incorrect casing for the static segments in a resource ID, since the provider is largely case-sensitive (except in special cases or workarounds to bugs), we should parse this ID using a resource ID parser and set the result into state.

This will ensure that if the casing is/does become a problem it is caught and we can parse insensitively and normalize static/constant segments before setting it into state, avoiding a diff.

2026-04-06 16:18 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +							return fmt.Errorf("`administrator_account` block is not required when `permission` kind is `%s`", perm.Kind)
`is not required` to me sounds like it doesn't need to be set, but setting it is not necessarily incorrect. Rephrasing it to the below should be clearer.

```suggestion
							return fmt.Errorf("`administrator_account` must not be set when `permission` kind is `%s`", perm.Kind)
```

2026-04-06 16:18 UTC, sreallymatt commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									ValidateFunc: validation.StringInSlice(pools.PossibleValuesForCachingType(), false),
This currently exposes `None` as a value, we generally avoid exposing `None` as an explicit value in favour of inferring omission of the argument as `None` ([ref](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/schema-design-considerations.md#the-none-value-or-similar))

2026-04-08 03:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +					"max_agent_lifetime": {
Updated to `maximum_agent_lifetime` in the resource and data source. Thanks!

2026-04-08 03:40 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_data_source.go
> +		"vmss_fabric": {
Updated to `virtual_machine_scale_set_fabric`. Cheers!

2026-04-08 03:41 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +			if metadata.ResourceData.HasChange("stateful_agent") || metadata.ResourceData.HasChange("stateless_agent") {
Updated, thanks!

2026-04-08 03:42 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +				payload.Properties.OrganizationProfile = organization
Removed unnecessary declaration

2026-04-08 03:43 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +					state.DevCenterProjectId = props.DevCenterProjectResourceId
Updated to parseID()

2026-04-08 03:44 UTC, QixiaLu commented on internal/services/manageddevopspools/managed_devops_pool_resource.go
> +									ValidateFunc: validation.StringInSlice(pools.PossibleValuesForCachingType(), false),
Removed `None` from the possible list. thanks!

2026-04-08 05:28 UTC, QixiaLu commented
Thanks @sreallymatt  for reviewing! I have addressed your comments above. Following is the latest tests result. 

I've also upgraded the SDK version and included one new property `work_folder` to be consistent with portal. 

`staticIpAddressCount` is excluded since there's a bug (https://github.com/Azure/azure-rest-api-specs/issues/42195)

<img width="1562" height="703" alt="image" src="https://github.com/user-attachments/assets/6d965725-888e-48b9-b7ea-a8561082d527" />

2026-04-08 14:57 UTC, sreallymatt approved these changes
Thanks @QixiaLu - LGTM 🚢

2026-04-08 14:58 UTC, merged