New service: `DeviceRegistry`
terraform-providers/terraform-provider-azurerm pull request #28399
Opened 2024-12-30 22:46 UTC by mryanlo

This PR introduces support for the Device Registry service, comprising of:

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `device_registry` service [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2025-02-21 22:55 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource_test.go
> +		t.Skipf("Skipping test due to missing environment variables %s and/or %s", ASSET_CUSTOM_LOCATION_NAME, ASSET_RESOURCE_GROUP_NAME)
For both asset and asset endpoint profile resource tests, we require env vars `ARM_DEVICE_REGISTRY_CUSTOM_LOCATION` and `ARM_DEVICE_REGISTRY_RESOURCE_GROUP` to be set or else the tests will fail (to prevent this we skip the tests).

however, the resource group, custom location, and the AIO cluster must be pre-existing this test run. Investigation and efforts to get the acceptance tests to create and provision an AIO cluster are flakey, take a long time to run (45+ minutes), and we found that the test steps delete the cluster resources before the asset/asset endpoint profile resource tests run (causing the latter ones to fail). awaiting response from Hashicorp and Terraform PMs what the best course of action is here.

2025-03-03 18:56 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource.go
> +					// Bug with `go-azure-sdk` library: you can't set retain to null because empty string will cause
Linking issue https://github.com/hashicorp/go-azure-sdk/issues/1143 and PR https://github.com/hashicorp/pandora/pull/4633

The go sdk does not support sending null properties. After the PR goes in, this issue can be fixed but might require a code change here

2025-03-04 07:53 UTC, stephybun commented on internal/services/deviceregistry/device_registry_asset_resource_test.go
> +		t.Skipf("Skipping test due to missing environment variables %s and/or %s", ASSET_CUSTOM_LOCATION_NAME, ASSET_RESOURCE_GROUP_NAME)
Hey @mryanlo,

In short it would be acceptable for the tests to run against existing infrastructure for the time being to help move this PR forwards, but the maintainers do need to be able to independently run the acceptance tests for new RPs and resources that are in the provider. I'd like to better understand the procedure required to test these resources so that we can setup the tests to run without a dependence on pre-existing resources.

We have [acceptance tests in the provider for arc enabled clusters](https://github.com/hashicorp/terraform-provider-azurerm/blob/21e34f9573367c7441d67a50844c99cd9f87b49b/internal/services/arckubernetes/arc_kubernetes_cluster_resource_test.go#L30-L52) where we need to provision the prerequisite network resources and a VM that runs the necessary setup scripts for the cluster.

Would you be able to take a look and let me know if there are parts of this setup that you would be able to re-use and what modifications you would need to make for setting up AIO on the cluster specifically? e.g. perhaps the setup script etc.

Once we have a better understanding of what's required we can begin looking at ways to cut down the provisioning time and improving the stability of the test.

2025-03-04 09:04 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource_test.go
> +		t.Skipf("Skipping test due to missing environment variables %s and/or %s", ASSET_CUSTOM_LOCATION_NAME, ASSET_RESOURCE_GROUP_NAME)
Hi @stephybun thanks for reaching out! the exact steps to install AIO onto a cluster are found here: https://review.learn.microsoft.com/en-us/azure/iot-operations/get-started-end-to-end-sample/quickstart-deploy?branch=main

I've seen that link you sent me in the past and have been unable to successfully modify it for AIO's purposes. This is due to the complexity and flakiness of the bash/python script that the VM must run, and our restrictions with the linux distro for installing AIO (you need linux Ubuntu 24.04 with a k3s cluster, not kind cluster to succeed). Additionally there are a bunch of az cli commands that must run and this process is the only available way to install AIO on a cluster, so we need to install az cli and k3s.

If you'd like to see my latest attempt at modifying the scripts to get these to work (the tests will try to sequentially first create a single cluster with AIO installed and then run the acc tests to create resources on only that cluster), here are links: 
- https://github.com/mryanlo/terraform-provider-azurerm/blob/rylo/adr-tf-tests/internal/services/deviceregistry/device_registry_assetendpointprofile_resource_test.go
- https://github.com/mryanlo/terraform-provider-azurerm/tree/rylo/adr-tf-tests/internal/services/deviceregistry/testdata

Thanks, and let me know if you have any more questions about this process.

2025-03-04 09:09 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource_test.go
> +		t.Skipf("Skipping test due to missing environment variables %s and/or %s", ASSET_CUSTOM_LOCATION_NAME, ASSET_RESOURCE_GROUP_NAME)
Note: my code modifies the acceptance tests to run via a managed identity since due to security reasons we are not allowed to make service principals to run terraform anymore.

2025-03-07 08:35 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource_test.go
> +		t.Skipf("Skipping test due to missing environment variables %s and/or %s", ASSET_CUSTOM_LOCATION_NAME, ASSET_RESOURCE_GROUP_NAME)
@stephybun is there a way to ignore the terraform plan check in acceptance tests from running on the VM portions? we don't care about the VM changing since it's not the resource that we want to test. however, one of the issues with my script above is that even if the AIO installation succeeds, the test flags the terraform plan step of the VM as modified after creating.

![image](https://github.com/user-attachments/assets/1c0c9776-206d-4b1f-bdb4-0e8e9cb877ce)

2025-03-24 22:52 UTC, mryanlo commented
Update: figured out a way to get all terraform tests to succeed. Here is the final results:

```
$ make acctests SERVICE='deviceregistry' TESTARGS='-run=TestAccAssetEndpointProfile_basic'
TF_ACC=1 go test -v ./internal/services/deviceregistry -run=TestAccAssetEndpointProfile_basic -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAssetEndpointProfile_basic
=== PAUSE TestAccAssetEndpointProfile_basic
=== CONT  TestAccAssetEndpointProfile_basic
--- PASS: TestAccAssetEndpointProfile_basic (2653.32s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/deviceregistry        2673.792s
```
![image](https://github.com/user-attachments/assets/d094cc9d-f66a-44e9-8945-e42a95c5f1cb)

2025-03-28 18:01 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource_test.go
> +		t.Skipf("Skipping test due to missing environment variables %s and/or %s", ASSET_CUSTOM_LOCATION_NAME, ASSET_RESOURCE_GROUP_NAME)
@stephybun I updated the tests in this PR to run completely on their own with all infra setup steps working. In order to do this, I had to use the `PreConfig` step to ssh into the VM and run all the AIO cluster setup script commands, because I noticed the flakiness would happen (the Asset and Asset Endpoint Profile resources would attempt to create even though the setup script didn't finish running via `remote-exec`.). The PreConfig is necessary to block creating all the Assets and Asset Endpoint Profile resources so that it waits for the setup script to finish sequentially before creating the resources. I've tried many things and this is the best solution because having golang sleep or using null_resource did not fix the issue (and would stop the remote-exec steps), and I don't think sleep is a good idea anyways because the setup script can take anywhere between 2000 to 3500 seconds to complete as you see in my screenshots of the results below. Please let me know if this solution is okay. Thank you!

2025-04-28 21:02 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource_test.go
> +		t.Skipf("Skipping test due to missing environment variables %s and/or %s", ASSET_CUSTOM_LOCATION_NAME, ASSET_RESOURCE_GROUP_NAME)
Hi @stephybun  do you have an update on this PR?

2025-05-08 22:15 UTC, sreallymatt requested changes
Hi @mryanlo, I've taken a look over this PR. Just to provide a heads up, as this is a large PR, it will likely take multiple reviews to fully cover everything, I've left some comments inline on my first pass.

I've skipped the test configuration entirely for now, as we'll have to discuss this within the team since it deviates significantly from how we usually do our testing.

2025-05-08 22:15 UTC, sreallymatt commented on internal/services/deviceregistry/device_registry_asset_resource.go
> +		"datasets": {
Since this is a block, this would usually be singular as multiple blocks could be defined, one per dataset

```suggestion
		"dataset": {
```

2025-05-08 22:15 UTC, sreallymatt commented on internal/services/deviceregistry/device_registry_asset_resource.go
> +					"data_points": {
This should be singular

```suggestion
					"data_point": {
```

2025-05-08 22:15 UTC, sreallymatt commented on internal/services/deviceregistry/device_registry_asset_resource.go
> +		"events": {
This should be singular
```suggestion
		"event": {
```

2025-05-12 20:57 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_assetendpointprofile_resource.go
> +		"extended_location_type": {
Right now only "CustomLocation" is accepted. So we can put a check there that it is "CustomLocation" or just remove this property entirely

2025-05-12 20:59 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_assetendpointprofile_resource.go
> +		"discovered_asset_endpoint_profile_ref": {
no this is not a computed property. The user can essentially put whatever string they want here.

2025-05-12 21:00 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_assetendpointprofile_resource.go
> +		"authentication_method": {
we can make it an `authentication` block. Certificate is the default yes. my question is when do we want to just copy the API pattern vs just take all the properties out of the block and keep them on the root level of the properties object?

2025-05-12 23:51 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource.go
> +		"default_topic_path": {
no there is no validation to be done here. for most properties, the validation happens at the ARM spec or User RP level. for future reference, when do we want the validation to match that of the ARM spec or UserRP? Or is one validation enough and is replicating it here in terraform redundant?

2025-05-12 23:52 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource.go
> +		"discovered_asset_refs": {
it is not a computed property. this can be any string value the user desires

2025-05-12 23:53 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource.go
> +		},
no there is no validation that needs to be done on these properties. These can be whatever strings the user wants with the exception of those that are too long (e.g. 512 chars max i believe). The UserRP already validates this and returns the error to terraform, so we don't need to double check the validation here. Does terraform require validation on all properties?

2025-05-13 00:25 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_assetendpointprofile_resource.go
> +			ValidateFunc: validation.StringIsNotEmpty,
I assume you're talking about the validation like this: 
![image](https://github.com/user-attachments/assets/110850ad-8d13-4a76-857f-a9ad866eff9b)

We can certainly add validation to the name property, but i would like to ask if there is a standard that terraform wants to set for the resource property validation. A lot of our validation is set either at the ARM spec (api reference you mention) level or at the User RP and returns errors to terraform if one of those validation checks fails. As a result, I find this really redundant to keep checking the same validation checks here in terraform especially if the validation changes in the future. But if terraform has some standards to follow, please let me know! thanks

2025-05-13 00:29 UTC, mryanlo commented on website/docs/r/device_registry_asset.html.markdown
> +* `default_datasets_configuration` - (Optional) Stringified JSON that contains connector-specific default configuration for all datasets. Each dataset can have its own configuration that overrides th
we have to use json strings for these `default_` properties. If you look at the documentation, the ARM spec payload indicates it's a stringified json that's expected.

2025-05-13 07:03 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource.go
> +		},
as shown in the [API specs](https://github.com/Azure/azure-rest-api-specs/blob/ba0c086df0ebe03a61579485c1c10de0d17804b2/specification/deviceregistry/resource-manager/Microsoft.DeviceRegistry/stable/2024-11-01/deviceregistry.json#L1156C8-L1159C11), the `enabled` boolean is an optional property. users can set it to be null/nil, or true/false. Because of this support, we can't set a default here

2025-05-13 07:04 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource.go
> +		},
no there is no validation we could add here and if you look at the ARM specs, there is no validation done on these fields https://github.com/Azure/azure-rest-api-specs/blob/main/specification/deviceregistry/resource-manager/Microsoft.DeviceRegistry/stable/2024-11-01/deviceregistry.json. So we should not add StringIsNotEmpty() validation since they're optional fields too.

2025-05-13 21:15 UTC, mryanlo commented on website/docs/r/device_registry_asset.html.markdown
> +* `default_topic` - (Optional) Object that describes the default topic information for the asset.
added to the schema

2025-05-13 23:38 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource.go
> +			if defaultTopicPathChanged || defaultTopicRetainChanged {
merged the two properties into one block property

2025-05-15 18:01 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_asset_resource.go
> +			ValidateFunc: validation.StringIsNotEmpty,
i removed this property since only one value is accepted and will be accepted for the future (CustomLocation)

2025-05-15 18:09 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_assetendpointprofile_resource.go
> +		"extended_location_type": {
Removed for previous reason

2025-05-15 20:23 UTC, mryanlo commented on internal/services/deviceregistry/device_registry_assetendpointprofile_resource.go
> +		"authentication_method": {
made certificate the default and made authentication block.

2025-05-15 20:38 UTC, mryanlo commented on website/docs/r/device_registry_asset.html.markdown
> +* `default_events_configuration` - (Optional) Stringified JSON that contains connector-specific default configuration for all events. Each event can have its own configuration that overrides the defa
see my response above

2025-05-15 20:46 UTC, mryanlo commented
> Hi @mryanlo, I've taken a look over this PR. Just to provide a heads up, as this is a large PR, it will likely take multiple reviews to fully cover everything, I've left some comments inline on my first pass.
> 
> I've skipped the test configuration entirely for now, as we'll have to discuss this within the team since it deviates significantly from how we usually do our testing.

Hi @sreallymatt thank you for the initial review. I've been addressing your feedback. We have a few questions for you and the rest of the team:

1. For adding all of the validation from the ARM spec, we'd like to ask why we must do this here in Terraform? None of our other client-tooling that CRUDs azure resources (sdks, CLIs, etc) do this and they all let the validation happen the RP-level and/or ARM specification. I understand this saves us an API call, but we have changed the validation at various times on the RP and ARM level as requirements came in. We would like to have a single point of validation and maintaining both validations across our own service/ARM and terraform will be tedious. 
2. the reason why this PR is so big is because i had to update the `vendor` folder to include all the go-azure-sdk APIs that the Terraform code would call (generated by running `go mod vendor`). Would it make more sense to separate the vendor folder changes and the service/resource changes into two separate PRs?

2025-05-16 17:07 UTC, sreallymatt commented
> Hi @sreallymatt thank you for the initial review. I've been addressing your feedback. We have a few questions for you and the rest of the team:
> 
> 1. For adding all of the validation from the ARM spec, we'd like to ask why we must do this here in Terraform? None of our other client-tooling that CRUDs azure resources (sdks, CLIs, etc) do this and they all let the validation happen the RP-level and/or ARM specification. I understand this saves us an API call, but we have changed the validation at various times on the RP and ARM level as requirements came in. We would like to have a single point of validation and maintaining both validations across our own service/ARM and terraform will be tedious.
> 2. the reason why this PR is so big is because i had to update the `vendor` folder to include all the go-azure-sdk APIs that the Terraform code would call (generated by running `go mod vendor`). Would it make more sense to separate the vendor folder changes and the service/resource changes into two separate PRs?

1. From a Terraform provider perspective, it would be a bad user experience to rely on the API to do all of the validation as any validation errors would surface during an apply operation, rather than during a plan. Ideally, once Terraform has planned the changes, and the user has approved them, all changes should be applied without any errors. There are exceptions to this, but generally we aim to validate the user's configuration prior to the apply stage.

2. This is fine, the vendored dependencies are required

2025-05-16 18:16 UTC, mryanlo commented on website/docs/r/device_registry_asset.html.markdown
> +terraform import azurerm_device_registry_asset.example C:/Program Files/Git/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/adr-terraform-rg/providers/Microsoft.DeviceRegistry/asset
this was an issue with git bash using the full computer directory path and not what i entered. fixing in re-generation of the documentation

2025-05-16 18:17 UTC, mryanlo commented on website/docs/r/device_registry_asset_endpoint_profile.html.markdown
> +terraform import azurerm_device_registry_asset_endpoint_profile.example C:/Program Files/Git/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/adr-terraform-rg/providers/Microsoft.Dev
this was an issue with git bash using the full computer directory path and not what i entered. fixing in re-generation of the documentation

2025-05-22 20:48 UTC, mryanlo commented
> > Hi @sreallymatt thank you for the initial review. I've been addressing your feedback. We have a few questions for you and the rest of the team:
> > 
> > 1. For adding all of the validation from the ARM spec, we'd like to ask why we must do this here in Terraform? None of our other client-tooling that CRUDs azure resources (sdks, CLIs, etc) do this and they all let the validation happen the RP-level and/or ARM specification. I understand this saves us an API call, but we have changed the validation at various times on the RP and ARM level as requirements came in. We would like to have a single point of validation and maintaining both validations across our own service/ARM and terraform will be tedious.
> > 2. the reason why this PR is so big is because i had to update the `vendor` folder to include all the go-azure-sdk APIs that the Terraform code would call (generated by running `go mod vendor`). Would it make more sense to separate the vendor folder changes and the service/resource changes into two separate PRs?
> 
> Hi @mryanlo, to answer your questions:
> 
> 1. From a Terraform provider perspective, it would be a bad user experience to rely on the API to do all of the validation as any validation errors would surface during an apply operation, rather than during a plan. Ideally, once Terraform has planned the changes, and the user has approved them, all changes should be applied without any errors. There are exceptions to this, but generally we aim to validate the user's configuration prior to the apply stage.
> 2. This is fine, the vendored dependencies are required

Hi @sreallymatt thank you for your reply.

I discussed issue #1 with my team some more and, while we understand what you're saying and would prefer for the validation, we would all like to request if an exception can be made to not add the validation to both Terraform and the Azure cloud service (our API specification in ARM and our service's ResourceProvider/RP). Along with the aforementioned reasons i have provided, some of our validation is very complex and belongs in the cloud service only that cannot be done statically (e.g. validation of unique names of the DataPoints objects in property `Dataset.#.DataPoints.#.Name`, where we must loop through all the data points and validate they have unique names). This kind of logic is too complicated for us to perform on the client/Terraform side. Even if we excluded this complex validation logic from Terraform, it would be a hassle to keep track of the validations we perform on the cloud that are also included in Terraform or not, and maintenance will be difficult moving forward. We recognize that Terraform would prefer to not make the api call and fail during the planning phase, but given all of these requirements on our side, we want to make the call to keep validation at the swagger and RP level and just return the failure back.

2025-05-28 20:52 UTC, mryanlo commented on website/docs/r/device_registry_asset.html.markdown
> +* `datasets` - (Optional) Array of datasets that are part of the asset. Each dataset describes the data points that make up the set.
done

2025-05-29 21:28 UTC, sreallymatt commented
@mryanlo, after discussing this with the team we would still like to see the properties validated, at least where possible. This includes regexes for names, max/min values for integers, etc. We recognize this adds a bit of extra maintenance effort, but we do this for almost all other resources to provide a better UX.

The example mentioned (`e.g. validation of unique names of the DataPoints objects in property Dataset.#.DataPoints.#.Name, where we must loop through all the data points and validate they have unique names`), may actually be possible within a `CustomizeDiff` but it would be okay if that validation is left out. (Though, we should still add validation on the `name` field itself, to ensure it matches a regex if the service has naming restrictions)

2025-08-04 16:53 UTC, mryanlo commented
Hi @sreallymatt @stephybun, sorry for the delay in response. We have been really busy with other work on our end that this became less of a priority but still needed work. Do you think you can please remove the stale label? We would like to still get back to this work soon. thanks!

2026-03-31 21:09 UTC, sreallymatt commented
Closing this PR for now as it has been stale for some time. Feel free to re-open once you are ready to work on this again

2026-03-31 21:09 UTC, closed without merging