Service fabric cluster upgrade policy
terraform-providers/terraform-provider-azurerm pull request #6273
Opened 2020-03-27 00:21 UTC by JSchenken

Address #6152 

Add upgrade_description property, and necessary other blocks, to service_fabric_cluster resource. Documentation also added.

2020-04-24 19:19 UTC, JSchenken commented
@katbyte @tombuildsstuff  Could you take a look at this PR when you have some time? My current project relies on it. Thanks!

2021-02-16 18:14 UTC, katbyte requested changes
Hey @JSchenken - thank your for this PR and we're really sorry its taken this long to give it a review, it seems to have fallen through the cracks 😞 

I've given the schema a look at and i left some suggestions inline to clean it up and improve the UX, let me know what you think

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +			"upgrade_description": {
description doesn't make sense, could we chanege thi to
```suggestion
			"upgrade_policy": {
```

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +						"force_restart": {
we usually put enabled in the name on booleans
```suggestion
						"force_restart_enabled": {
```

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +						"health_check_retry_timeout": {
could we add the units here?
```suggestion
						"health_check_retry_timeout_min|hours|seccons": {
```

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +							Type:     schema.TypeString,
should this be an int instead of a string?

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +						},
could we validate this property?

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +						},
could we vlaidate this property?

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +						},
could we validate this one too?

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +						},
could we include units in these names and validate? also consider using TypeInt?

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +									"max_percent_unhealthy_applications": {
coulw we move percent to be at the end?
```suggestion
									"max_unhealthy_applications_percent": {
```

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +									},
and vcalidate this is 0-100?

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +									},
same here

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +									"max_percent_upgrade_domain_delta_unhealthy_nodes": {
and move percent to the end here, as well as validate the int is 0-100?

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +						"delta_health_policy": {
What is the difference between delta health policy and health policy?

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +									"max_percent_delta_unhealthy_applications": {
we probably don't need to include delta here as its in the block name already?

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +									"application_delta_health_policy": {
same here?
```suggestion
									"application": {
```

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +												"application_type": {
and remove application here
```suggestion
												"type": {
```

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +												"default_service_type_delta_health_policy": {
same goes here
```suggestion
												"default_service_policy": {
```

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +												"service_type_delta_health_policy": {
and here
```suggestion
												"service_policy": {
```

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +															"service_type": {
```suggestion
															"type": {
```

2021-02-16 18:14 UTC, katbyte commented on azurerm/internal/services/servicefabric/resource_arm_service_fabric_cluster.go
> +															"max_percent_delta_unhealthy_services": {
```suggestion
															"max_unhealthy_services_percent": {
```

2021-03-01 02:24 UTC, katbyte commented
closing as this was superseded by #10713

2021-03-01 02:24 UTC, closed without merging