add support for git repo volume - "azurerm_container_group"
terraform-providers/terraform-provider-azurerm pull request #7924
Opened 2020-07-28 08:43 UTC by njuCZ

fix #7875

2020-10-25 23:30 UTC, mbfrahry requested changes
Hey @njuCZ. This is nearly there, we just need to add some additional checks to ensure we create the volume correctly

2020-10-25 23:30 UTC, mbfrahry commented on azurerm/internal/services/containers/container_group_resource.go
> +		if gitRepoVolume := expandGitRepoVolume(volumeConfig["git_repo"].([]interface{})); gitRepoVolume != nil {
We'll need to do some logic to make sure that either `git_repo` is specified or the share name/storage account information is specified. We'll also want to check that both aren't specified. The last check will be that all the share name and storage account information is specified if `git_repo` isn't specified. If one of those checks fail, we'll need to raise that error for the user.

2020-10-26 05:45 UTC, njuCZ commented
@mbfrahry I have added some validation, and all acctest could pass, Could you have a look again when free?

2020-10-26 22:50 UTC, mbfrahry approved these changes
LGTM!

2020-10-26 22:51 UTC, merged