Add azuread auth to vnet gateway vpn client
terraform-providers/terraform-provider-azurerm pull request #8294
Opened 2020-08-31 05:31 UTC by jon-walton

This adds support for Azure Active Directory authentication to Virtual Network Gateway vpn clients.

fixes #6805
fixes #5079

2020-09-01 08:50 UTC, tombuildsstuff requested changes
hey @jon-walton 

Thanks for this PR :)

Taking a look through this is looking good - if we can fix up the comments then this otherwise LGTM 👍 

Thanks!

2020-09-01 08:50 UTC, tombuildsstuff commented on azurerm/internal/services/network/virtual_network_gateway_resource.go
> +						"aad_issuer": {
can we add an [acceptance test](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/network/tests/virtual_network_gateway_resource_test.go#L112-L129) covering these new fields?

2020-09-01 08:50 UTC, tombuildsstuff commented on website/docs/r/virtual_network_gateway.html.markdown
> +* `aad_issuer` - (Optional) The STS url for your tenant
can we also document these fields in the data source docs too (./website/docs/d/virtual_network_gateway.html.markdown)?

2020-09-01 10:23 UTC, jon-walton commented
Hi @tombuildsstuff . Thanks for taking a look so quickly. I've pushed the changes you've asked for

2020-09-02 10:23 UTC, tombuildsstuff approved these changes
hey @jon-walton 

Thanks for pushing those changes - taking a look through here aside from one minor comment (which I hope you don't mind but I'm going to push a commit to fix) this otherwise LGTM 👍 

Thanks!

2020-09-02 10:23 UTC, tombuildsstuff commented on azurerm/internal/services/network/tests/virtual_network_gateway_resource_test.go
> +  depends_on          = [azurerm_public_ip.test]
this isn't necessary since there's an interpolated reference below

```suggestion
```

2020-09-02 10:53 UTC, jon-walton commented
Great, thank you!

2020-09-04 11:04 UTC, tombuildsstuff commented
Tests seem fine (the only failing test 'TestAccAzureRMVirtualNetworkGatewayConnection_updatingSharedKey' is also failing in master, so is out-of-scope for this) 👍

2020-09-04 11:05 UTC, merged