Update `azurerm_linux|windows_virtual_machine` and `azurerm_linux|windows_virtual_machine_scale_set` - Support `encryption_at_host_enabled`
terraform-providers/terraform-provider-azurerm pull request #8322
Opened 2020-09-02 09:25 UTC by ArcturusZhang

Supersede #8134

2020-09-02 09:29 UTC, ArcturusZhang commented
Tests are passing:
```
=== RUN   TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabled
=== PAUSE TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabled
=== CONT  TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabled
--- PASS: TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabled (318.19s)
=== RUN   TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledUpdate
=== PAUSE TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledUpdate
=== CONT  TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledUpdate
--- PASS: TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledUpdate (349.75s)
=== RUN   TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledWithCMK
=== PAUSE TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledWithCMK
=== CONT  TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledWithCMK
--- PASS: TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledWithCMK (601.90s)
=== RUN   TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHost
=== PAUSE TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHost
=== CONT  TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHost
--- PASS: TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHost (241.76s)
=== RUN   TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostUpdate
=== PAUSE TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostUpdate
=== CONT  TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostUpdate
--- PASS: TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostUpdate (324.41s)
=== RUN   TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostWithCMK
=== PAUSE TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostWithCMK
=== CONT  TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostWithCMK
--- PASS: TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostWithCMK (589.60s)
=== RUN   TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabled
=== PAUSE TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabled
=== CONT  TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabled
--- PASS: TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabled (283.23s)
=== RUN   TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledUpdate
=== PAUSE TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledUpdate
=== CONT  TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledUpdate
--- PASS: TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledUpdate (417.15s)
=== RUN   TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledWithCMK
=== PAUSE TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledWithCMK
=== CONT  TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledWithCMK
=== RUN   TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabled
=== PAUSE TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabled
=== CONT  TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabled
--- PASS: TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabled (631.12s)
--- PASS: TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabled (388.23s)
=== RUN   TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledUpdate
=== PAUSE TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledUpdate
=== CONT  TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledUpdate
--- PASS: TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledUpdate (415.94s)
=== RUN   TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledWithCMK
=== PAUSE TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledWithCMK
=== CONT  TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledWithCMK
--- PASS: TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledWithCMK (547.36s)

2020-09-03 06:35 UTC, ArcturusZhang commented
All tests have passed:
```
=== RUN   TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabled
=== PAUSE TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabled
=== CONT  TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabled
--- PASS: TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabled (287.18s)
=== RUN   TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledUpdate
=== PAUSE TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledUpdate
=== CONT  TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledUpdate
--- PASS: TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledUpdate (418.35s)
=== RUN   TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledWithCMK
=== PAUSE TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledWithCMK
=== CONT  TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledWithCMK
--- PASS: TestAccLinuxVirtualMachine_otherEncryptionAtHostEnabledWithCMK (567.91s)
=== RUN   TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHost
=== PAUSE TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHost
=== CONT  TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHost
--- PASS: TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHost (235.12s)
=== RUN   TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostUpdate
=== PAUSE TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostUpdate
=== CONT  TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostUpdate
--- PASS: TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostUpdate (305.41s)
=== RUN   TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostWithCMK
=== PAUSE TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostWithCMK
=== CONT  TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostWithCMK
--- PASS: TestAccAzureRMLinuxVirtualMachineScaleSet_otherEncryptionAtHostWithCMK (590.23s)
=== RUN   TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabled
=== PAUSE TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabled
=== CONT  TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabled
--- PASS: TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabled (357.87s)
=== RUN   TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledUpdate
=== PAUSE TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledUpdate
=== CONT  TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledUpdate
--- PASS: TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledUpdate (782.34s)
=== RUN   TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledWithCMK
=== PAUSE TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledWithCMK
=== CONT  TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledWithCMK
--- PASS: TestAccWindowsVirtualMachine_otherEncryptionAtHostEnabledWithCMK (794.18s)
=== RUN   TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabled
=== PAUSE TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabled
=== CONT  TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabled
--- PASS: TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabled (346.02s)
=== RUN   TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledUpdate
=== PAUSE TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledUpdate
=== CONT  TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledUpdate
--- PASS: TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledUpdate (465.22s)
=== RUN   TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledWithCMK
=== PAUSE TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledWithCMK
=== CONT  TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledWithCMK
--- PASS: TestAccAzureRMWindowsVirtualMachineScaleSet_otherEncryptionAtHostEnabledWithCMK (700.09s)
PASS
```

2020-09-04 10:57 UTC, tombuildsstuff approved these changes
LGTM 👍

2020-09-04 14:44 UTC, tombuildsstuff requested changes
The tests have picked up a bug here - if we can fix that up then this should otherwise be good to merge 👍

2020-09-04 14:44 UTC, tombuildsstuff commented on azurerm/internal/services/compute/windows_virtual_machine_scale_set_resource.go
> +					string(compute.AutomaticByPlatform),
these should be:

```suggestion
 					string(compute.UpgradeModeAutomatic),
 					string(compute.UpgradeModeManual),
 					string(compute.UpgradeModeRolling),
```

2020-09-07 02:14 UTC, ArcturusZhang commented
Hi @tombuildsstuff I have resolved the last comment, could you please have a look again?

2020-09-09 06:17 UTC, tombuildsstuff approved these changes
LGTM 👍

2020-09-09 08:14 UTC, WodansSon commented
![image](https://user-images.githubusercontent.com/20408400/92572830-c7f4fa80-f239-11ea-89fd-21aeef2c4598.png)

2020-09-09 08:14 UTC, merged