support managed identity for "azurerm_spring_cloud_app"
terraform-providers/terraform-provider-azurerm pull request #8336
Opened 2020-09-03 03:39 UTC by njuCZ

![image](https://user-images.githubusercontent.com/2786738/92068651-0e7dcb80-edda-11ea-9256-1cbc568bba45.png)

2020-09-03 06:45 UTC, tombuildsstuff requested changes
hi @njuCZ 

Thanks for this PR.

I've taken a look through and left some comments inline but if we can fix those up and the tests pass then this otherwise LGTM 👍 

Thanks!

2020-09-03 06:45 UTC, tombuildsstuff commented on azurerm/internal/services/appplatform/spring_cloud_app_resource.go
> +							DiffSuppressFunc: suppress.CaseDifference,
this should be case sensitive - if the API is returning them lower-cased that's an API bug which needs to be fixed

2020-09-03 06:45 UTC, tombuildsstuff commented on azurerm/internal/services/appplatform/spring_cloud_app_resource.go
> +							}, true),
this should be case sensitive since these are Constants

2020-09-03 06:45 UTC, tombuildsstuff commented on azurerm/internal/services/appplatform/spring_cloud_app_resource.go
> +		return fmt.Errorf("waiting for creation/updation of Spring Cloud App %q (Spring Cloud Service %q / Resource Group %q): %+v", name, serviceName, resourceGroup, err)
```suggestion
		return fmt.Errorf("waiting for creation/update of Spring Cloud App %q (Spring Cloud Service %q / Resource Group %q): %+v", name, serviceName, resourceGroup, err)
```

2020-09-03 06:45 UTC, tombuildsstuff commented on azurerm/internal/services/appplatform/spring_cloud_app_resource.go
> +		return fmt.Errorf("creating/updating Spring Cloud App %q (Spring Cloud Service %q / Resource Group %q): %+v", name, serviceName, resourceGroup, err)
```suggestion
		return fmt.Errorf("creating/update Spring Cloud App %q (Spring Cloud Service %q / Resource Group %q): %+v", name, serviceName, resourceGroup, err)
```

2020-09-03 06:45 UTC, tombuildsstuff commented on website/docs/r/spring_cloud_app.html.markdown
> +* `identity` - (Optional) A Managed Service Identity block as defined below.
```suggestion
* `identity` - (Optional) An `identity` block as defined below.
```

2020-09-03 06:45 UTC, tombuildsstuff commented on website/docs/r/spring_cloud_app.html.markdown
> +* `identity` - An `identity` block as defined below, which contains the Managed Service Identity information for this Spring Cloud Application.
this is an argument so it's already exported

```suggestion
```

2020-09-03 08:23 UTC, njuCZ commented
@tombuildsstuff I have modifed this PR according to the suggestions. Could you please have a look again?

2020-09-04 12:12 UTC, tombuildsstuff approved these changes
LGTM 👍

2020-09-04 12:58 UTC, tombuildsstuff commented
Tests pass:

<img width="373" alt="Screenshot 2020-09-04 at 14 58 30" src="https://user-images.githubusercontent.com/666005/92241793-1a8f8900-eebf-11ea-85e1-e9ee81e2bd2c.png">

2020-09-04 13:01 UTC, merged