Update name validation for azurerm_storage_share_directory
terraform-providers/terraform-provider-azurerm pull request #8366
Opened 2020-09-07 04:28 UTC by neil-yechenwei

fixes https://github.com/terraform-providers/terraform-provider-azurerm/issues/8341

2020-09-07 23:25 UTC, manicminer commented
@neil-yechenwei Thanks for this update. Hope you don't mind, I've pushed some extra changes to support single character directory names, and ensure each directory component conforms. Also, in my testing, double dashes in filenames seemed to work so I removed that check.

2020-09-08 23:01 UTC, WodansSon requested changes
@neil-yechenwei Thanks for the PR! It mostly LGTM, however I did leave one very minor comment. Thanks again for the PR 🚀

2020-09-09 01:49 UTC, neil-yechenwei commented on azurerm/helpers/validate/storage.go
> +			errors = append(errors, fmt.Errorf("%s must start and end with a letter and end only with a number or letter", k))
updated

2020-09-10 03:09 UTC, neil-yechenwei commented
@manicminer , thanks for your commit, but after tested, I found the name can start with number and hyphen.
![image](https://user-images.githubusercontent.com/19754191/92675367-cb7ba500-f351-11ea-879f-0495dfada193.png)
![image](https://user-images.githubusercontent.com/19754191/92675406-e77f4680-f351-11ea-9c6c-552dd7474d62.png)
![image](https://user-images.githubusercontent.com/19754191/92676750-cbc96f80-f354-11ea-87da-023b804296b4.png)
![image](https://user-images.githubusercontent.com/19754191/92676758-d126ba00-f354-11ea-8de7-5f35385c6676.png)

2020-09-10 03:37 UTC, neil-yechenwei commented
@WodansSon , Thanks for your comment. I've updated code according by the newest name validation rules.

2020-09-10 07:46 UTC, WodansSon approved these changes
@neil-yechenwei Thanks for pushing those updates, LGTM! 🚀

2020-09-10 07:47 UTC, WodansSon commented
![image](https://user-images.githubusercontent.com/20408400/92696789-3bad0b00-f2ff-11ea-8107-7526fa5d180d.png)

2020-09-10 07:48 UTC, merged