make sku_name suppress case difference - azurerm_key_vault
terraform-providers/terraform-provider-azurerm pull request #8467
Opened 2020-09-15 08:52 UTC by njuCZ

fix #8457

now, the portal's default behaviour for "sku" is "Standard". after terraform import there will be diff because only "standard" and "premium" is accepted.

2020-09-24 20:46 UTC, katbyte requested changes

2020-09-24 20:46 UTC, katbyte commented on azurerm/internal/services/keyvault/key_vault_resource.go
> +				DiffSuppressFunc: suppress.CaseDifference,
Could we have a link to an bug/issue here that describes why we need to do this?

2020-09-25 08:05 UTC, njuCZ commented
@katbyte I have added a link to the rest-api-specs issue, could you please have a look again?

2020-09-27 02:40 UTC, njuCZ commented
it seems there is some problem with the CI, I will close and reopen it

2020-10-03 19:44 UTC, katbyte requested changes
thanks, Instead of just making it fully case insensitive could we just allow `standard` and `premium` in addition to the camel cased ones?

2020-10-09 05:07 UTC, njuCZ commented
@katbyte according to service team's reply https://github.com/Azure/azure-rest-api-specs/issues/10943#issuecomment-702984955  sku_name is not case-sensitive, I am afraid that the portal will change again. I think it's better to make it fully case insensitive

2020-10-20 14:21 UTC, scp-mb commented
Is there any estimates on when this could be merged and released? We're looking at using Pulumi to manage some key vaults which under the hood uses the terraform azurerm provider, but importing resources will fail due to this case mismatch.

2020-10-22 11:17 UTC, tombuildsstuff commented
Closing this in favour of #8983 which instead rewrites the casing to ensure it's consistent with what the SDK defines, meaning the configuration is the source of truth here.

2020-10-22 11:17 UTC, closed without merging