New data source: `azurerm_databricks_workspace`
terraform-providers/terraform-provider-azurerm pull request #8502
Opened 2020-09-17 08:40 UTC by favoretti

Fixes #8475

2020-09-17 10:51 UTC, tombuildsstuff requested changes
hey @favoretti 

Thanks for this PR :)

Taking a look through this mostly LGTM - if we can fix up the comments then we should be able to run the tests and get this merged 👍 

Thanks!

2020-09-17 10:51 UTC, tombuildsstuff commented on azurerm/internal/services/databricks/databricks_workspace_data_source.go
> +	d.Set("workspace_url", resp.WorkspaceURL)
can we pull these from `resp.Properties` instead?

2020-09-17 10:51 UTC, tombuildsstuff commented on azurerm/internal/services/databricks/tests/databricks_workspace_data_source_test.go
> +  name                = "example-workspace"
we need to create/reference an existing workspace here :)

2020-09-17 10:51 UTC, tombuildsstuff commented on azurerm/internal/services/databricks/tests/databricks_workspace_data_source_test.go
> +  resource_group_name = "azurerm_resource_group.test.name"
```suggestion
  resource_group_name = azurerm_resource_group.test.name
```

2020-09-17 10:51 UTC, tombuildsstuff commented on website/docs/d/databricks_workspace.html.markdown
> +* `id` - The ID of the Databricks Workspace in Azure Management plane.
we can simplify this to:

```suggestion
* `id` - The ID of the Databricks Workspace.
```

2020-09-17 12:49 UTC, favoretti commented
```
(⎈ |eastus2-fxs-oscar-np-fxc:build-agents)➜  terraform-providers/terraform-provider-azurerm git:(favoretti/databricks_workspace_datasource) $ make acctests SERVICE='databricks' TESTARGS='-run=TestAccDataSourceAzureRMDatabricksWorkspace' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/databricks/tests/ -run=TestAccDataSourceAzureRMDatabricksWorkspace -timeout 60m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccDataSourceAzureRMDatabricksWorkspace_basic
=== PAUSE TestAccDataSourceAzureRMDatabricksWorkspace_basic
=== CONT  TestAccDataSourceAzureRMDatabricksWorkspace_basic
--- PASS: TestAccDataSourceAzureRMDatabricksWorkspace_basic (569.69s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/databricks/tests	570.802s
```

2020-09-19 18:56 UTC, katbyte approved these changes
Thanks @favoretti - LGTM 👍

2020-09-19 18:56 UTC, merged