Removed azuread dependency wherever applicable for AAD Diagnostic set…
terraform-providers/terraform-provider-azurerm pull request #8580
Opened 2020-09-22 17:47 UTC by PriyankaRanganath

…ting feature

This PR is for removing azuread dependency from azurerm wherever applicable. I have implemented azure AD diagnostic settings feature in azurerm provider. But I am unable to test them due to cyclic dependency between azurerm and azuread providers.
To avoid that, this PR has removed azuread dependencies wherever applicable and provided equivalent functions for the same.

2020-09-30 07:16 UTC, PriyankaRanganath commented
Hi @manicminer , can you please review the PR along with [this ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8581) too ?
They are sitting idly for past 4-5 days and waiting for review.

2020-10-03 06:00 UTC, katbyte requested changes
Thanks for fixing this mistake @PriyankaRanganath! aside from one comment i've left inline this looks good

2020-10-03 06:00 UTC, katbyte commented on azurerm/internal/acceptance/data.go
> +		RandomInteger:   AccRandTimeInt(),
then this can go back to
```suggestion
		RandomInteger:   tf.AccRandTimeInt(),
```

2020-10-03 06:22 UTC, PriyankaRanganath commented on azurerm/internal/acceptance/data.go
>  	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/features"
Hi @katbyte, I already tried that. If I use azurerm tf randint function, lot of acceptance tests fails due to too much length restrictions in names or other properties. That's why I supplied a new function same as the one used in azuread tf provider

2020-10-03 16:46 UTC, katbyte commented on azurerm/internal/acceptance/data.go
>  	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/features"
That shouldn't be the case? the functions are almost identical? regardless can you swap it and we'll handle it on our end if there is an issue with it

2020-10-05 05:51 UTC, PriyankaRanganath commented
Hi @katbyte , Have removed the extra randint function and added reference to azurerm tf randint function as requested.

2020-10-05 15:36 UTC, katbyte approved these changes
Thanks @PriyankaRanganath - LGTM 👍

2020-10-05 15:36 UTC, merged