Azure active directory diagnostic settings feature
terraform-providers/terraform-provider-azurerm pull request #8581
Opened 2020-09-22 18:14 UTC by PriyankaRanganath

Added AAD Diagnostic settings resource feature as per the [github issue](https://github.com/terraform-providers/terraform-provider-azuread/issues/178).

Added inside azurerm provider as technically the AAD Diagnostic settings are created using Azure RM endpoints(management.azure.com) rather than Microsoft Graph or legacy Azure AD Graph API

2020-10-08 12:04 UTC, manicminer requested changes
Hi @PriyankaRanganath, thanks for this PR! I've added some review comments, however I've had trouble testing this and based on my findings I think an upstream issue may prevent us from merging this.

Whilst the API responds OK using an access token from a user, when I try to run the tests authenticating as a service principal I get 403 errors. I've looked at creating a custom IAM role with the necessary permissions and assigning it at subscription level, and also assigning the Global Administrator directory role to the SP, but this did not resolve the 403 issue. There's some [StackOverflow chatter](https://stackoverflow.com/questions/53666223/azure-permissions-over-microsoft-aadiam-diagnosticsettings-write) and a [blog post](https://cloud-right.com/2018/12/azure-ad-api-logs-flaws) concluding that this API does not support authenticating with a bearer token issued for a service principal. Unfortunately my findings seem to agree, and we can't use a resource that doesn't work for service principals.

I've opened an upstream issue [here](https://github.com/Azure/azure-rest-api-specs/issues/11085)

2020-10-08 12:30 UTC, PriyankaRanganath commented
Hello @manicminer ,

In order to run the AAD Diagnostic settings test cases, we need to have the sp given application permissions under Azure Management services as Global Admin role is not sufficient.
Unfortunately, The Azure management services only allow User impersonation permissions to be assigned, application services can not be assigned to the SP as seen below: 
![image](https://user-images.githubusercontent.com/69572399/95457498-a0a36180-098e-11eb-857c-c3ed2b51ae96.png)


The trick I did to run the tests was to not setup test env variables. I opened a cmd prompt and logged in using az cli with an user who has global admin role and given user impersonation permissions to azure management services API. Along with that I only setup env variables for test locations (export ARM_TEST_LOCATION=eastus, export ARM_TEST_LOCATION_ALT etc) and made the tests run under the scope of the user and not service principal.

The upstream issue you raised is because of the the sp not being able to assign **application permissions** to access the azure service management APIs.
Do you think we can still make this PR merged until the SP is given application permissions? I would be very happy if it can be merged while the upstream issue is being tracked.

2020-10-08 12:34 UTC, manicminer commented
@PriyankaRanganath Thanks, that's helpful - I've linked to your post in the upstream issue.

Unfortunately the issue is more than inconvenience when testing. We can't ship a feature that operators cannot use with service principal authentication.

2020-10-09 12:15 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +			Create: schema.DefaultTimeout(30 * time.Minute),
CRUD timing updated to 15,5, 15 and 5 respectively

2020-10-09 12:15 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/registration.go
> +		"azurerm_aad_diagnostic_settings": azureADDiagnosticSettingsResource(),
done

2020-10-09 12:17 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/tests/diagnostic_settings_resource_test.go
> +  name                = "%s"
name I had passed specifically to test update test case. but yeah used randint instead of string

2020-10-09 12:17 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/tests/diagnostic_settings_resource_test.go
> +  name                		= "%s"
name I had passed specifically to test update test case. but yeah used randint instead of string

2020-10-09 12:18 UTC, PriyankaRanganath commented on website/azurerm.erb
> +                  <a href="/docs/providers/azurerm/r/aad_diagnostic_settings.html">azurerm_aad_diagnostic_settings</a>
yup. Done

2020-10-09 12:18 UTC, PriyankaRanganath commented on website/docs/r/aad_diagnostic_settings.html.markdown
> +# azurerm_aad_diagnostic_settings
done

2020-10-09 12:18 UTC, PriyankaRanganath commented on website/docs/r/aad_diagnostic_settings.html.markdown
> +resource "azurerm_aad_diagnostic_settings" "example" {
done

2020-10-09 12:18 UTC, PriyankaRanganath commented on website/docs/r/aad_diagnostic_settings.html.markdown
> +terraform import azurerm_aad_diagnostic_settings.example /providers/microsoft.aadiam/diagnosticSettings/aad-diag-test
done

2020-10-09 12:19 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +				Optional: true,
done

2020-10-09 12:19 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +				Optional: true,
done

2020-10-09 12:19 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +				Required: true,
done

2020-10-09 12:19 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +				Optional: true,
done

2020-10-09 12:20 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +							),
done

2020-10-09 12:21 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +										Optional: true,
No. Retention policy is optional and applicable only when we want to achieve into storage accounts

2020-10-09 12:21 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +			"type": {
same as above

2020-10-09 12:21 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +	}
yup added requiredwith and atleastoneof:)

2020-10-09 12:21 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +	name := d.Get("name").(string)
done

2020-10-09 12:22 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +		return fmt.Errorf("failed to retrieve Azure Active Directory Diagnostic settings %q: %+v", name, err)
done

2020-10-09 12:22 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +func parseDiagnosticSettingResourceId(id string) (map[string]string, error) {
done

2020-10-09 12:22 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +	name := resMap["diagnosticSettings"]
updated after updating parseDiagnosticSettingResourceId

2020-10-09 12:22 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +	name := resMap["diagnosticSettings"]
parseDiagnosticSettingResourceId

2020-10-09 12:22 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +	resMap, err := parseDiagnosticSettingResourceId(d.Id())
parseDiagnosticSettingResourceId

2020-10-09 12:24 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +	resMap, err := parseDiagnosticSettingResourceId(d.Id())
updated after updating parseDiagnosticSettingResourceId

2020-10-09 12:25 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/tests/diagnostic_settings_resource_test.go
> +  name                     = "stgacc%s"
done

2020-10-09 12:26 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +				Optional: true,
done

2020-10-09 12:26 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +										Optional:     true,
same as above

2020-10-09 12:28 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +		res, err := expandDiagnosticLogSettings(d)
yes. Updated

2020-10-09 12:28 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +		return fmt.Errorf("error creating diagnostic settings for AAD %q: %+v", name, err)
done

2020-10-09 12:28 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +			return fmt.Errorf("state validation failed for diagnostic settings %q: %+v", name, err)
done

2020-10-09 12:29 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +		return fmt.Errorf("failed to retrieve Azure Active Directory Diagnostic settings %q: %+v", name, err)
done

2020-10-09 12:31 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +		return fmt.Errorf("Cannot read ID for Azure Active Directory Diagnostic settings %q", name)
done

2020-10-09 12:31 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +	diagnosticLogSettings := d.Get("logs").([]interface{})
updated

2020-10-09 12:32 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +		return fmt.Errorf("Error while fetching AAD Diagnostic settings %s: %+v", name, err)
done

2020-10-09 12:32 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +	d.Set("type", resp.Type)
removed

2020-10-09 12:33 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +		if aad.AuditLogs == logSetting.Category || aad.SignInLogs == logSetting.Category {
removed

2020-10-09 12:33 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +		d.Set("logs", flattenDiagnosticSettingLogs(settings.Logs))
done

2020-10-09 12:35 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +	idURL, err := url.Parse(id)
the Diag setting resource returns id of following format "providers/microsoft.aadiam/diagnosticSettings/<name>", not **"/providers/microsoft.aadiam/diagnosticSettings/<name>"**(notice the first "/" here), due to which pareRequestUri fails. So I had to resort to Parse function

2020-10-09 12:36 UTC, PriyankaRanganath commented on azurerm/internal/services/aadmgmt/diagnostic_settings_resource.go
> +	}
done

2020-10-22 09:34 UTC, manicminer commented
As this is currently blocked due to the aforementioned API issue, I'm going to close this for now. We can re-visit this once the upstream issue is resolved.

2020-10-22 09:34 UTC, closed without merging