Adds new resource for azurerm_security_center_auto_provisioning
terraform-providers/terraform-provider-azurerm pull request #8595
Opened 2020-09-23 12:48 UTC by benc-uk

As per the proposal in issue #8550 this adds a new subscription level resource `azurerm_security_center_auto_provisioning` in order to support the auto provisioning feature of Security Center

Includes tests, which have been run and pass

Fixes Issue #8550

2020-10-22 07:05 UTC, jackofallops requested changes
Hi @benc-uk 

Thanks for this PR, looking good so far, there's a few comments/questions below.  

Could you add the docs for this new resource too?

2020-10-22 07:05 UTC, jackofallops commented on azurerm/internal/services/securitycenter/azurerm_security_center_auto_provisioning.go
> +func resourceArmSecurityCenterAutoProvisioningDelete(_ *schema.ResourceData, _ interface{}) error {
Is there a "default" state that we should return this to? e.g. if it defaults to `Off`, and the user has it previously configured `On`, would the expectation from the user be that it is switched `Off` by deletion of the resource?

2020-10-22 07:05 UTC, jackofallops commented on azurerm/internal/services/securitycenter/azurerm_security_center_auto_provisioning.go
> +	}
Can we check for an empty value here too, setting an empty string in the state would be undesirable.
```suggestion
	if resp.ID == nil || *resp.ID == "" {
		return fmt.Errorf("Security Center Auto Provisioning ID missing")
	}
```

2020-10-22 08:35 UTC, benc-uk commented
Hey @jackofallops all good suggestions, make all the changes plus a couple of other v minor improvements

2020-10-27 07:01 UTC, jackofallops approved these changes

2020-10-27 07:03 UTC, jackofallops commented
Tests passing (1 fail unrelated)
![image](https://user-images.githubusercontent.com/11830746/97267692-7670f100-1822-11eb-9cfa-866973512c33.png)

2020-10-27 07:05 UTC, merged