`azurerm_mssql_virtual_machine` - Add support for `storage_configuration_settings`
terraform-providers/terraform-provider-azurerm pull request #8623
Opened 2020-09-25 06:19 UTC by mbfrahry

Fixes #6874

2020-09-25 20:27 UTC, katbyte requested changes
Aside from some comments about the property this is looking good

2020-09-25 20:27 UTC, katbyte commented on azurerm/internal/services/mssql/mssql_virtual_machine_resource.go
> +			"storage_configuration_settings": {
I think settings is redundant here
```suggestion
			"storage_configuration": {
```

2020-09-25 20:27 UTC, katbyte commented on azurerm/internal/services/mssql/mssql_virtual_machine_resource.go
> +						"disk_configuration_type": {
as is configuration?
```suggestion
						"disk_type": {
```

2020-09-25 20:27 UTC, katbyte commented on azurerm/internal/services/mssql/mssql_virtual_machine_resource.go
> +						"sql_data_settings":    helper.StorageSettingSchema(),
as is sql?
```suggestion
						"data_settings":    helper.StorageSettingSchema(),
```

2020-09-25 20:27 UTC, katbyte commented on azurerm/internal/services/mssql/mssql_virtual_machine_resource.go
> +						"sql_log_settings":     helper.StorageSettingSchema(),
```suggestion
						"log_settings":     helper.StorageSettingSchema(),
```

2020-09-25 20:27 UTC, katbyte commented on azurerm/internal/services/mssql/mssql_virtual_machine_resource.go
> +						"sql_temp_db_settings": helper.StorageSettingSchema(),
```suggestion
						"temp_db_settings": helper.StorageSettingSchema(),
```

2020-09-29 03:27 UTC, a30000931 commented
looks great - happy to help test this out

2020-09-29 15:04 UTC, katbyte requested changes
Thanks @mbfrahry - looks like the tests are failing thou:

```	[TestAccAzureRMMsSqlVirtualMachine_storageConfigurationSettings] [Test Output]
=== RUN   TestAccAzureRMMsSqlVirtualMachine_storageConfigurationSettings
=== PAUSE TestAccAzureRMMsSqlVirtualMachine_storageConfigurationSettings
=== CONT  TestAccAzureRMMsSqlVirtualMachine_storageConfigurationSettings
    TestAccAzureRMMsSqlVirtualMachine_updateAutoPatching: testing.go:684: Step 0 error: Check failed: Check 2/4 error: azurerm_mssql_virtual_machine.test: Attribute 'auto_patching.0.day_of_week' expected "Sunday", got ""
    TestAccAzureRMMsSqlVirtualMachine_complete: testing.go:684: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        UPDATE: azurerm_mssql_virtual_machine.test
          auto_patching.#:                               "0" => "0"
          id:                                            "/subscriptions/*******/resourceGroups/acctestRG-mssql-200929043203782538/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/acctest-VM-200929043203782538" => "/subscriptions/*******/resourceGroups/acctestRG-mssql-200929043203782538/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/acctest-VM-200929043203782538"
          key_vault_credential.#:                        "0" => "0"
          r_services_enabled:                            "true" => "true"
          sql_connectivity_port:                         "1433" => "1433"
          sql_connectivity_type:                         "PRIVATE" => "PRIVATE"
          sql_connectivity_update_password:              "Password1234!" => "Password1234!"
          sql_connectivity_update_username:              "sqllogin" => "sqllogin"
          sql_license_type:                              "PAYG" => "PAYG"
          storage_configuration.#:                       "1" => "0"
          storage_configuration.0.data_settings.#:       "0" => ""
          storage_configuration.0.disk_type:             "" => ""
          storage_configuration.0.log_settings.#:        "0" => ""
          storage_configuration.0.storage_workload_type: "" => ""
          storage_configuration.0.temp_db_settings.#:    "0" => ""
          virtual_machine_id:                            "/subscriptions/*******/resourceGroups/acctestRG-mssql-200929043203782538/providers/Microsoft.Compute/virtualMachines/acctest-VM-200929043203782538" => "/subscriptions/*******/resourceGroups/acctestRG-mssql-200929043203782538/providers/Microsoft.Compute/virtualMachines/acctest-VM-200929043203782538"
        ```

2020-10-02 20:47 UTC, mbfrahry commented
Those tests have been failing on master as well. Thoughts on fixing it in another PR?

2020-10-02 23:12 UTC, katbyte approved these changes
+1

2020-10-02 23:20 UTC, merged