azurerm_role_definition: don't add `scope` to `assignable_scopes`
terraform-providers/terraform-provider-azurerm pull request #8624
Opened 2020-09-25 06:34 UTC by magodo

fix #8577

2020-09-25 09:09 UTC, magodo commented
The two failures in the [test result](https://ci-oss.hashicorp.engineering/buildConfiguration/TerraformOpenSource_TerraformProviders_AzureRMPublic_AZURERM_SERVICE_PUBLIC_AUTHORIZATION/148472) seems unrelated to my changes.

2020-10-01 11:31 UTC, jackofallops requested changes
Hi @magodo 

Thanks for this PR, I've suggested a way to avoid a breaking change here that I believe should work correctly. It will require the tests to be updated also.

2020-10-01 11:31 UTC, jackofallops commented on website/docs/r/role_definition.html.markdown
```suggestion
* `assignable_scopes` - (Optional) One or more assignable scopes for this Role Definition, such as `/subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333`, `/subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGroup`, or `/subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGroup/providers/Microsoft.Compute/virtualMachines/myVM`.
~> **NOTE:** The value for `scope` is automatically included in this list if no other values are supplied.
```

2020-10-12 03:43 UTC, magodo commented
@jackofallops Thank you for your comments, I have updated the code and added another test for the case that no assinable scopes is specified. Please take another look!

2021-01-27 22:40 UTC, katbyte approved these changes
Thanks @magodo - this LGTM 👍

2021-01-27 22:41 UTC, merged