new resource: azurerm_kusto_iothub_data_connection
terraform-providers/terraform-provider-azurerm pull request #8626
Opened 2020-09-25 07:32 UTC by njuCZ

2020-10-02 20:17 UTC, katbyte requested changes
Thanks @njuCZ - overall this looks good but could we get a complete and update test? thanks!

2020-10-02 20:17 UTC, katbyte commented on azurerm/internal/services/kusto/tests/kusto_iothub_data_connection_resource_test.go
> +func TestAccAzureRMKustoIotHubDataConnection_basic(t *testing.T) {
Could we add a complete test which sets _all_ optional properties and then an update test that goes basic -> complete -> basic?

2020-10-09 02:43 UTC, njuCZ commented
@katbyte complete test is hard for this resource, because the optional fields "table_name", "mapping_rule_name" are kusto RP data plane resource. Fow now, we could not create them through terraform. and I found existing resource `azurerm_kusto_eventhub_data_connection` keeps these fields and no complete acctest.

Do you think we would better delete these fields or just keep them and no test?

2020-10-27 17:10 UTC, katbyte commented
@njuCZ - can we just delete the properties we cannot test and leave the rest for now? thanks

2020-10-28 05:24 UTC, njuCZ commented
@katbyte Thanks for your advice, I have deleted these fields. Please have a look again when free.

2020-12-16 05:06 UTC, njuCZ commented
just rebased the latest master branch and resolve conflicts

2021-02-19 15:39 UTC, katbyte commented
@njuCZ - this is failing to build with:
```
[15:38:08]	[Step 4/5] ./kusto_cluster_customer_managed_key_resource.go:11:2: imported and not used: "github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure"
[15:38:08]	[Step 4/5] ./kusto_eventhub_data_connection_resource.go:16:2: validate redeclared as imported package name
[15:38:08]	[Step 4/5] 	previous declaration at ./kusto_eventhub_data_connection_resource.go:14:2
[15:38:08]	[Step 4/5] ./kusto_eventhub_data_connection_resource.go:90:19: undefined: "github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/kusto/validate".ValidateEventHubConsumerName
[15:39:30]	[Step 4/5] Process exited with code 2
[15:39:30]	[Step 4/5] Process exited with code 2 (Step: Compile Test Binary (Command Line))
[15:39:30]	[Step 4/5] Step Compile Test Binary (Command Line) failed
[15:39:30]	[Step 4/5] Error message is logged
```

2021-02-20 04:39 UTC, njuCZ commented
@katbyte I have rebased this PR, now it could build successfully and acctest could pass.
![image](https://user-images.githubusercontent.com/2786738/108583990-a49db200-7378-11eb-9bd4-5e20fb9cbb61.png)

2021-02-22 22:35 UTC, katbyte approved these changes
Thanks @njuCZ - LGTM 👍

2021-02-22 22:35 UTC, merged