Update `azurerm_linux|windows_virtual_machine_scale_set` - Fix #8422
terraform-providers/terraform-provider-azurerm pull request #8627
Opened 2020-09-25 09:15 UTC by ArcturusZhang

Fixes #8422

2020-09-25 09:16 UTC, ArcturusZhang commented
New test case is passing:
```
=== RUN   TestAccAzureRMLinuxVirtualMachineScaleSet_otherVmExtensionsOnlySettings
=== PAUSE TestAccAzureRMLinuxVirtualMachineScaleSet_otherVmExtensionsOnlySettings
=== CONT  TestAccAzureRMLinuxVirtualMachineScaleSet_otherVmExtensionsOnlySettings
--- PASS: TestAccAzureRMLinuxVirtualMachineScaleSet_otherVmExtensionsOnlySettings (359.83s)
PASS
```

2020-09-29 07:10 UTC, jackofallops requested changes
Hi @ArcturusZhang 
Thanks for this, just a couple of really minor changes but otherwise LGTM 👍

2020-09-29 07:10 UTC, jackofallops commented on azurerm/internal/services/compute/virtual_machine_scale_set.go
> +			settings, err := structure.ExpandJsonFromString(settingsRaw.(string))
```suggestion
		settingsRaw, ok := extensionRaw["settings"].(string)
		if ok && settingsRaw != "" {
			settings, err := structure.ExpandJsonFromString(settingsRaw)
```

2020-09-29 07:10 UTC, jackofallops commented on azurerm/internal/services/compute/virtual_machine_scale_set.go
> +			protectedSettings, err := structure.ExpandJsonFromString(protectedSettingsRaw.(string))
```suggestion
		protectedSettingsRaw, ok := extensionRaw["protected_settings"].(string)
		if ok && protectedSettingsRaw != "" {
			protectedSettings, err := structure.ExpandJsonFromString(protectedSettingsRaw)
```

2020-09-29 08:01 UTC, ArcturusZhang commented on azurerm/internal/services/compute/virtual_machine_scale_set.go
> +			settings, err := structure.ExpandJsonFromString(settingsRaw.(string))
Done

2020-09-29 08:01 UTC, ArcturusZhang commented on azurerm/internal/services/compute/virtual_machine_scale_set.go
> +			protectedSettings, err := structure.ExpandJsonFromString(protectedSettingsRaw.(string))
Done

2020-09-29 08:02 UTC, ArcturusZhang commented
Hi @jackofallops thanks for the review, I have made some changes please have a look, thanks

2020-09-29 08:04 UTC, ArcturusZhang commented
And @jackofallops rather than doing this patch on this particular resource, maybe an update to the `structure.ExpandJsonFromString` to make it could accept an empty string is a better idea?

We have almost exactly the same issue here: https://github.com/terraform-providers/terraform-provider-azurerm/pull/8668

2020-09-29 08:38 UTC, jackofallops commented
I had considered this, but changing that behaviour is likely to have unexpected effects elsewhere (such as potentially sending empty values where `nil` is expected). I think the current approach is appropriate for the time being, and is within our immediate domain of control, rather than changing the plugin-sdk.

2020-09-29 08:39 UTC, jackofallops approved these changes
Thanks @ArcturusZhang - LGTM now 👍

2020-09-29 08:39 UTC, merged