New data source `azurerm_images`
terraform-providers/terraform-provider-azurerm pull request #8629
Opened 2020-09-25 09:40 UTC by ArcturusZhang

Fixes #8417

2020-10-22 15:09 UTC, manicminer requested changes
Hi @ArcturusZhang, thanks for this PR!

Overall this looks great and I have just a few minor suggestions, however I'm not convinced that it addresses the linked issue? Could you look at adding the `tags_filter` attribute to the `azurerm_image` resource too?

2020-10-23 09:43 UTC, ArcturusZhang commented
Hi @manicminer thanks for the review. I will get the comments resolved soon.

And to clarify, 
> Could you look at adding the tags_filter attribute to the azurerm_image resource too?
Do you mean that we need to add `tags_filter` to the `azurerm_image` data source?

2020-10-23 10:13 UTC, manicminer commented
> Do you mean that we need to add `tags_filter` to the `azurerm_image` data source?

Sorry, that is indeed what I meant :)

2020-10-27 03:55 UTC, ArcturusZhang commented on azurerm/internal/services/compute/images_data_source.go
> +		return fmt.Errorf("unable to find any images")
Done

2020-10-27 03:56 UTC, ArcturusZhang commented on azurerm/internal/services/compute/images_data_source.go
> +			return fmt.Errorf("Images (Resource Group %q) was not found", resourceGroup)
Done

2020-10-27 03:56 UTC, ArcturusZhang commented on azurerm/internal/services/compute/images_data_source.go
> +		return fmt.Errorf("retrieving Images (Resource Group %q): %+v", resourceGroup, err)
Done

2020-10-27 03:57 UTC, ArcturusZhang commented on azurerm/internal/services/compute/images_data_source.go
> +func flattenImages(ctx context.Context, iterator compute.ImageListResultIterator, filterTags map[string]*string) ([]interface{}, error) {
Done

2020-10-27 03:59 UTC, ArcturusZhang commented on azurerm/internal/services/compute/images_data_source.go
> +	for ; iterator.NotDone(); err = iterator.NextWithContext(ctx) {
Done

2020-10-27 04:02 UTC, ArcturusZhang commented
Hi @manicminer I have made some changes, please have a look.

I do not think we should do too many things in one PR, therefore I might create another PR to add `tags_filter` for the azurerm_image data source. And I changed the description so that this PR will not close the coresponding issue.

2020-11-02 02:22 UTC, ArcturusZhang commented on azurerm/internal/services/compute/tests/images_data_source_test.go
> +				ExpectError: regexp.MustCompile("unable to find any images"),
Oh sorry I missed this one.

2020-11-02 02:25 UTC, ArcturusZhang commented
Hi @manicminer I have resolved the comment, could you please have a look again? thanks

2020-11-02 12:46 UTC, manicminer approved these changes

2020-11-02 12:47 UTC, manicminer commented
Test results:

![Screenshot 2020-11-02 at 12 46 36](https://user-images.githubusercontent.com/251987/97869511-88163500-1d09-11eb-8ace-a176868b1666.png)

2020-11-02 12:48 UTC, merged