Update `azurerm_policy_set_definition` - Fix #8663
terraform-providers/terraform-provider-azurerm pull request #8668
Opened 2020-09-29 03:32 UTC by ArcturusZhang

Fixes #8663

2020-09-29 10:07 UTC, jackofallops requested changes
Hi @ArcturusZhang 
Thanks for this PR, just one comment below but otherwise LGTM 👍

2020-09-30 02:36 UTC, ArcturusZhang commented on azurerm/internal/services/policy/policy_set_definition_resource.go
>  				return nil, fmt.Errorf("unmarshalling `parameter_values`: %+v", err)
Done

2020-09-30 02:36 UTC, ArcturusZhang commented
Hi @jackofallops I have made some changes, please have a look

2020-09-30 11:45 UTC, tombuildsstuff submitted a review, later dismissed
hi @ArcturusZhang 

Thanks for pushing those changes - taking a look through there's another thing I've spotted here but if we can fix that up then this otherwise LGTM 👍 

Thanks!

2020-09-30 11:45 UTC, tombuildsstuff commented on azurerm/internal/services/policy/tests/policy_set_definition_resource_test.go
> +        "equals": "eastus"
this won't work in regions other than Azure Public - so we need to pass this in here

2020-10-08 13:09 UTC, jackofallops approved these changes

2020-10-08 14:17 UTC, jackofallops commented
Tests passing (2 failures are existing / unrelated)
![image](https://user-images.githubusercontent.com/11830746/95470949-46e46c80-0979-11eb-9f63-3e2aced1dcac.png)

2020-10-08 14:17 UTC, merged