`azurerm_cosmosdb_mongo_database` doesn't call get throughput api when cosmos account is serverless
terraform-providers/terraform-provider-azurerm pull request #8673
Opened 2020-09-29 08:43 UTC by yupwei68

Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/8661

=== RUN   TestAccAzureRMCosmosDbMongoDatabase_basic
=== PAUSE TestAccAzureRMCosmosDbMongoDatabase_basic
=== CONT  TestAccAzureRMCosmosDbMongoDatabase_basic
--- PASS: TestAccAzureRMCosmosDbMongoDatabase_basic (1726.68s)
=== RUN   TestAccAzureRMCosmosDbMongoDatabase_complete
=== PAUSE TestAccAzureRMCosmosDbMongoDatabase_complete
=== CONT  TestAccAzureRMCosmosDbMongoDatabase_complete
--- PASS: TestAccAzureRMCosmosDbMongoDatabase_complete (1794.50s)
=== RUN   TestAccAzureRMCosmosDbMongoDatabase_autoscale
=== PAUSE TestAccAzureRMCosmosDbMongoDatabase_autoscale
=== CONT  TestAccAzureRMCosmosDbMongoDatabase_autoscale
--- PASS: TestAccAzureRMCosmosDbMongoDatabase_autoscale (2084.84s)
=== RUN   TestAccAzureRMCosmosDbMongoDatabase_serverless
=== PAUSE TestAccAzureRMCosmosDbMongoDatabase_serverless
=== CONT  TestAccAzureRMCosmosDbMongoDatabase_serverless
--- PASS: TestAccAzureRMCosmosDbMongoDatabase_serverless (1724.47s)

2020-09-29 17:01 UTC, katbyte requested changes
Aside from one comment this LGTM 👍

2020-09-30 01:34 UTC, yupwei68 commented on azurerm/internal/services/cosmos/cosmosdb_mongo_database_resource.go
> +}
hi kt, I've noticed there's this function. But as for this case, the parameter is `[]Capability`, `Capability` is a struct with a field Name.

2020-10-04 18:20 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_mongo_database_resource.go
> +}
COuld we just do this inline then as this function is not likely to be re-used elsewhere?

2020-10-09 11:38 UTC, yupwei68 commented
@katbyte Thanks for your comments. Please continue reviewing.

2020-10-29 06:43 UTC, jackofallops commented
Hi @yupwei68 

Which region/location are you running this test in?  It fails on the test suite with:
```TestAccAzureRMCosmosDbMongoDatabase_serverless: testing.go:684: Step 0 error: errors during apply:
Error: Error creating CosmosDB Account "acctest-ca-201028162029940851" (Resource Group "acctestRG-cosmos-201028162029940851"): Error creating/updating CosmosDB Account "acctest-ca-201028162029940851" (Resource Group "acctestRG-cosmos-201028162029940851"): documentdb.DatabaseAccountsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="EnableServerless is not valid for Mongo accounts with ServerVersion equal to 3.2.\r\nActivityId: eb658304-a4ef-455b-821f-6dc4e56adeae, Microsoft.Azure.Documents.Common/2.11.0"```

`MongoDBv3.4` capability appears to create a `v3.2` service?

2020-11-04 08:10 UTC, yupwei68 commented
Hi @jackofallops  Previously it worked. Currently I've updated the acctest to get it passed with mongo version 3.6.
=== RUN   TestAccAzureRMCosmosDbMongoDatabase_serverless
=== PAUSE TestAccAzureRMCosmosDbMongoDatabase_serverless
=== CONT  TestAccAzureRMCosmosDbMongoDatabase_serverless
--- PASS: TestAccAzureRMCosmosDbMongoDatabase_serverless (1548.01s)

2020-11-05 06:59 UTC, jackofallops commented
Tests passing:
![image](https://user-images.githubusercontent.com/11830746/98207988-6a78e380-1f34-11eb-84ea-7d25592305e9.png)

2020-11-05 07:00 UTC, jackofallops approved these changes
Thanks for addressing the comments / changes @yupwei68 - LGTM now 👍

2020-11-05 07:01 UTC, merged

2020-11-06 10:23 UTC, mariussm commented
Hi, the same issue exists for azurerm_cosmosdb_sql_database