Corrected the example given
terraform-providers/terraform-provider-azurerm pull request #8743
Opened 2020-10-05 11:37 UTC by ross-bohr

The example is specifying the RG name in Azure as "example" but in the shell command example given the RG name is "group1" thus this change is correcting the HCL script to match the name "group1".

2020-10-05 15:48 UTC, katbyte requested changes
Could we keep the resource group name as example and change the import statement? thanks!

2020-10-05 15:48 UTC, katbyte commented on website/docs/r/resource_group.html.markdown
> +  name     = "group1"
```suggestion
  name     = "example"
```

2020-10-08 18:19 UTC, katbyte approved these changes
Hey @ross-bohr  - hope you don't mind but i pushed the changes to get this merged today. Thanks! LGTM 👍

2020-10-08 18:20 UTC, merged

2020-10-08 18:22 UTC, ross-bohr commented
@katbyte No worries, it's good now, thanks! :)