`azurerm_mssql_database` - add support for `long_term_retention_policy` and `short_term_retention_policy`
terraform-providers/terraform-provider-azurerm pull request #8765
Opened 2020-10-06 16:08 UTC by jackofallops

encompasses and supersedes #6194 

closes #1802

2020-10-06 22:49 UTC, mbfrahry requested changes
This looks good but I did have one point to chat about around defaulting values

2020-10-06 22:49 UTC, mbfrahry commented on azurerm/internal/services/mssql/mssql_database_resource.go
> +		skuName = *props.CurrentServiceObjectiveName
Should we check for nil here?

2020-10-07 07:13 UTC, jackofallops commented on website/azurerm.erb
> +                  <a href="/docs/providers/azurerm/r/mssql_database.html">azurerm_mssql_database</a>
Thanks!  Look like I skipped a commit by accident when rebasing for conflicts.

2020-10-07 14:42 UTC, mbfrahry approved these changes
LGTM!

2020-10-07 16:22 UTC, jackofallops commented
Tests passing (failures unrelated to change / transient)
![image](https://user-images.githubusercontent.com/11830746/95359096-a97a3180-08c1-11eb-9377-e5e4cadc5e2e.png)

2020-10-07 16:23 UTC, merged