New data source: mysql server
terraform-providers/terraform-provider-azurerm pull request #8787
Opened 2020-10-07 23:35 UTC by Lucretius

Resolves https://github.com/terraform-providers/terraform-provider-azurerm/issues/4924

This is not a resource I have ever used, but I followed along the existing resource to build out the data source, and reused the tests (adding in the data source at the end of each) and checking the values.

2020-10-12 12:09 UTC, manicminer requested changes
Hi @Lucretius, thanks for this PR! I have some minor suggestions below, including a way to dry out the tests a bit. If we can fix these up, this looks good to merge.

2020-10-12 12:09 UTC, manicminer commented on website/docs/d/mysql_server.html.markdown
> +A `identity` block supports the following:
```suggestion
An `identity` block exports the following:
```

2020-10-12 12:09 UTC, manicminer commented on website/docs/d/mysql_server.html.markdown
> +a `threat_detection_policy` block supports the following:
```suggestion
A `threat_detection_policy` block exports the following:
```

2020-10-12 12:09 UTC, manicminer commented on website/docs/d/mysql_server.html.markdown
> +* `threat_detection_policy` - Threat detection policy configuration, known in the API as Server Security Alerts Policy. The `threat_detection_policy` block supports fields documented below.
```suggestion
* `threat_detection_policy` - Threat detection policy configuration, known in the API as Server Security Alerts Policy. The `threat_detection_policy` block exports fields documented below.
```

2020-10-12 15:56 UTC, Lucretius commented
Thanks @manicminer - I've accepted all the suggestions, thanks for that (wish Github let me accept them all in one commit instead of one at a time).  Also gives me a good idea of what to watch out for in the future.

2020-10-12 16:22 UTC, manicminer commented
@Lucretius great! could you update the other tests too? (`testAccDataSourceAzureRMMySQLServer_basicWithIdentity`, `testAccDataSourceAzureRMMySQLServer_autogrow` and `testAccDataSourceAzureRMMySQLServer_complete`)

2020-10-13 06:14 UTC, manicminer requested changes
@Lucretius Thanks for making those changes. When running the tests, I spotted some other issues that I missed earlier.

2020-10-13 06:14 UTC, manicminer commented on website/docs/d/mysql_server.html.markdown
> +* `name` - (Required) Specifies the name of the MySQL Server. Changing this forces a new resource to be created. This needs to be globally unique within Azure.
```suggestion
* `name` - (Required) Specifies the name of the MySQL Server.
```

2020-10-13 06:14 UTC, manicminer commented on website/docs/d/mysql_server.html.markdown
> +* `resource_group_name` - (Required) The name of the resource group in which to create the MySQL Server. Changing this forces a new resource to be created.
```suggestion
* `resource_group_name` - (Required) The name of the resource group for the MySQL Server.
```

2020-10-13 06:14 UTC, manicminer commented on azurerm/internal/services/mysql/tests/mysql_server_data_source_test.go
> +`, testAccAzureRMMySQLServer_basic(data, version), data.RandomInteger)
The data source needs to reference an original resource attribute so Terraform can infer the correct order, as without it, it tries to look up the MySQL server before it's created.

```suggestion
  name                = azurerm_mysql_server.test.name
  resource_group_name = azurerm_resource_group.test.name
}
`, testAccAzureRMMySQLServer_basic(data, version))
```

2020-10-13 06:14 UTC, manicminer commented on azurerm/internal/services/mysql/tests/mysql_server_data_source_test.go
> +`, testAccAzureRMMySQLServer_basicWithIdentity(data, version), data.RandomInteger)
```suggestion
  name                = azurerm_mysql_server.test.name
  resource_group_name = azurerm_resource_group.test.name
}
`, testAccAzureRMMySQLServer_basic(data, version))
```

2020-10-13 06:14 UTC, manicminer commented on azurerm/internal/services/mysql/tests/mysql_server_data_source_test.go
> +`, testAccAzureRMMySQLServer_autogrow(data, version), data.RandomInteger)
```suggestion
  name                = azurerm_mysql_server.test.name
  resource_group_name = azurerm_resource_group.test.name
}
`, testAccAzureRMMySQLServer_basic(data, version))
```

2020-10-13 06:14 UTC, manicminer commented on azurerm/internal/services/mysql/tests/mysql_server_data_source_test.go
> +`, testAccAzureRMMySQLServer_complete(data, version), data.RandomInteger)
```suggestion
  name                = azurerm_mysql_server.test.name
  resource_group_name = azurerm_resource_group.test.name
}
`, testAccAzureRMMySQLServer_basic(data, version))
```

2020-10-13 06:14 UTC, manicminer commented on azurerm/internal/services/mysql/tests/mysql_server_data_source_test.go
> +					resource.TestCheckResourceAttr(data.ResourceName, "ssl_minimal_tls_version_enforced", "TLS1_1"),
This isn't set in the config
```suggestion
```

2020-10-13 06:29 UTC, Lucretius commented
Thanks again for clarifying the issues with the tests, sorry there were so many!  I'll keep them in mind in future PRs.

2020-10-13 19:16 UTC, manicminer commented
@Lucretius I pushed some additional minor test fixes (some of the configs were pointing at the wrong test config funcs and some attribute check values didn't match the configuration). The tests now pass. Thanks again!

![Screenshot 2020-10-13 at 20 15 09](https://user-images.githubusercontent.com/251987/95905631-0463cb00-0d91-11eb-963d-f5b8102096a0.png)

2020-10-13 20:45 UTC, merged