`azurerm_sql_failover_group` document example added
terraform-providers/terraform-provider-azurerm pull request #8845
Opened 2020-10-12 02:03 UTC by yupwei68

Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/8778

2020-10-12 09:43 UTC, tombuildsstuff requested changes
hi @yupwei68 

Thanks for this PR - I've taken a look through and left a couple of comments inline but if we can fix those up then this otherwise looks good to me

Thanks!

2020-10-12 09:43 UTC, tombuildsstuff commented on website/docs/r/sql_failover_group.html.markdown
> +-> **NOTE:** The failover group will create a secondary database for each database listed in `databases`. If the secondary databases need to be managed through Terraform, they should be defined as re
this resource is `sql` but the example is `mssql`- does this want updating to be `sql` until the replacement resources are present?

2020-10-12 09:43 UTC, tombuildsstuff commented on examples/mssql/failover_group/variables.tf
> +  description = "The prefix used for all resources used by this NetApp Account"
this isn't a NetApp Account

```suggestion
  description = "The prefix used for all resources created as a part of this example"

```

2020-10-13 01:34 UTC, yupwei68 commented
@tombuildsstuff Thanks for your comments. Please continue reviewing.

2020-10-15 02:08 UTC, katbyte approved these changes
Thanks @yupwei68 - LGTM 👍

2020-10-15 02:09 UTC, merged