Adding support for os_disk_image_size to get the disk size of the image
terraform-providers/terraform-provider-azurerm pull request #8904
Opened 2020-10-15 15:36 UTC by harshavmb

Adding support for os_disk_image_size to get the disk size of the image

2020-10-19 06:15 UTC, tombuildsstuff requested changes
hey @harshavmb 

Thanks for this PR - taking a look through this is looking good, if we can fix up the comments then this otherwise looks good to me 👍 

Thanks!

2020-10-19 06:15 UTC, tombuildsstuff commented on azurerm/internal/services/compute/shared_image_version_data_source.go
> +			d.Set("os_disk_image_size", osDiskImageSize)
since this is in GB - can we make this:

```suggestion
			d.Set("os_disk_image_size_gb", osDiskImageSize)
```

2020-10-19 06:15 UTC, tombuildsstuff commented on azurerm/internal/services/compute/shared_image_version_data_source.go
> +			osDiskImageSize := -1
can we default this to 0, rather than -1, to match the rest of the provider here?

2020-10-19 06:15 UTC, tombuildsstuff commented on website/docs/d/shared_image_version.html.markdown
> +* `os_disk_image_size` - The size of the OS disk snapshot which was the source of this Shared Image Version.
```suggestion
* `os_disk_image_size_gb` - The size of the OS disk snapshot (in Gigabytes) which was the source of this Shared Image Version. 
```

2020-10-19 08:22 UTC, harshavmb commented
> hey @harshavmb
> 
> Thanks for this PR - taking a look through this is looking good, if we can fix up the comments then this otherwise looks good to me 👍
> 
> Thanks!

Hi @tombuildsstuff ,

Thanks for the review. I made suggested changes. Hope you are okay with these changes!

Thanks,
Harsha

2020-10-20 08:59 UTC, tombuildsstuff approved these changes
LGTM - thanks for this @harshavmb

2020-10-20 09:54 UTC, tombuildsstuff approved these changes
LGTM - thanks for this @harshavmb

2020-10-20 10:11 UTC, merged