Allow azurerm_data_factory_linked_service_data_lake_storage_gen2 to auth with managed identity
terraform-providers/terraform-provider-azurerm pull request #8938
Opened 2020-10-19 08:58 UTC by dnlbunting

Closes  #6501

Adds a use_managed_identity flag to azurerm_data_factory_linked_service_data_lake_storage_gen2.

If both use_managed_identity=true and service_principal_key or service_principal_id are specified raises an error.

First contribution so feel free to add feedback

2020-10-26 22:11 UTC, mbfrahry requested changes
Hey @dnlbunting, thanks for opening this PR! Things look nearly there but some of the validation you wrote can be better surfaced at the plan level so we error before Terraform even applies. I've detailed some of what you need below and feel free to reach out if you have any questions around it.

2020-10-26 22:11 UTC, mbfrahry commented on azurerm/internal/services/datafactory/data_factory_linked_service_data_lake_storage_gen2_resource.go
> +				Optional: true,
We'll want to add `ConflictsWith` here too to make sure we don't specify it with the other service principal attributes.

2020-10-26 22:11 UTC, mbfrahry commented on azurerm/internal/services/datafactory/data_factory_linked_service_data_lake_storage_gen2_resource.go
> +				Optional: true,
And to round it all out we should throw in `AtLeastOneOf` with all of these attributes to make sure at least one of them gets specified when creating this resource.

2020-10-26 22:18 UTC, mbfrahry reviewed
Actually, would it make sense to just infer that we should use managed identity if we don't specify the service principal? Or is it better for the user to purposefully specify that they want managed identity?

2020-10-29 09:19 UTC, dnlbunting commented
@mbfrahry Thanks for the pointers on the schema validation, I'll make those changes. IMO making the managed identity opt-in rather the the default was clearer, since the managed identity has to be explicitly enabled in the parent ADF resource too.

2020-10-29 16:54 UTC, mbfrahry commented
That works for me! I'll look forward to the schema validation changes

2020-11-02 23:30 UTC, mbfrahry approved these changes
LGTM!

2020-11-02 23:31 UTC, mbfrahry commented
Thanks for this @dnlbunting. It should make it into the next release!

2020-11-02 23:31 UTC, merged