Upgrade containerservice API to 2020-09-01
terraform-providers/terraform-provider-azurerm pull request #8982
Opened 2020-10-22 09:11 UTC by favoretti

In prep for #8657

2020-10-22 18:56 UTC, favoretti commented
Fixing acceptance tests atm, will take a few more days I think...

2020-10-23 15:15 UTC, favoretti commented
@tombuildsstuff I think now we should be ready to review this.

2020-10-30 18:43 UTC, tombuildsstuff requested changes
hey @favoretti 

Thanks for this PR - apologies for the delayed review here.

As discussed offline, I was hoping to dig in deeper into these comments today to be able to confirm the migration path (e.g. if we should rip these out, since they're no longer usable due to the breaking change on the AKS API side - or if we should keep them supported and deprecated for now, raising an error if the fields specified).

Unfortunately I didn't get a chance to do that today - but generally speaking we'd tend to deprecate this field, and then remove it in 3.0 - rather than ripping this out and introducing a breaking config change - to follow the semantic versioning rules here (the best we can, anyway). What that means is introducing a "DeprecationMessage" to the items in the schema to raise the deprecation alert in the Terraform CLI - and an error during creation for the Pod Security Policy which can no longer be configured, if that's set to true - what do you think?

Thanks!

2020-10-30 18:43 UTC, tombuildsstuff commented on azurerm/internal/services/containers/kubernetes_nodepool.go
> -				},
this'd be a breaking change - can we revert this and deprecate this field (with a message) and error if this is set during creation?

2020-10-30 18:43 UTC, tombuildsstuff commented on azurerm/internal/services/containers/tests/kubernetes_cluster_data_source_test.go
> +					// It seems like it doesn't return version property anymore?
entirely possibly, the transition period wasn't that long so maybe we need to default this in the response now?

2020-10-31 11:17 UTC, favoretti commented on azurerm/internal/services/containers/kubernetes_cluster_node_pool_resource.go
> +				Computed: true,
Because this property is always returned apparently. I wasn't too sure how to go about this to be honest.

2020-10-31 11:38 UTC, favoretti commented
Hey @tombuildsstuff, thank you for the review! Committed your suggestions, will work on deprecation tomorrow/monday.

2020-11-03 22:58 UTC, favoretti commented
@tombuildsstuff resolved everything but 2 things, will try to catch you on slack tomorrow to talk about those, not really sure what to do about them.

2020-11-04 18:34 UTC, tombuildsstuff approved these changes
hey @favoretti 

Thanks for pushing those changes - taking a look through, aside from one minor comment this otherwise LGTM 👍 

Thanks!

2020-11-04 18:34 UTC, tombuildsstuff commented on azurerm/internal/services/containers/kubernetes_nodepool.go
> -			"node_taints":           nodeTaints,
so this isn't a breaking change, for now we'll need to set an empty list into the state:

```suggestion
			"node_taints":           []string{},
```

(we can remove this once we remove the field in 3.0)

2020-11-05 10:07 UTC, tombuildsstuff commented
As discussed offline - the "addOnProfile" blocks are intentionally failing (both in master and this branch) due to a behavioural difference between Azure Public and other Azure Environments - where the Kubernetes Dashboard is enabled by default in Azure Public up until Kubernetes 1.18/1.19 (at which point it's no longer available), but isn't available (at all) in some other Azure Environments (China, USGovernment). As such whilst it's unfortunate these tests fail, it's required to be able to covers these scenarios when using different versions of AKS in different Azure Environments - but the resource itself works fine 👍

2020-11-05 10:08 UTC, tombuildsstuff approved these changes
LGTM 👍

2020-11-05 10:09 UTC, tombuildsstuff commented
Ignoring some intentionally failing tests for the "AddOnProfile", due to the behaviour of AKS in Azure Public - and one temporary AKS failure the tests otherwise look good:

<img width="589" alt="Screenshot 2020-11-05 at 11 08 40" src="https://user-images.githubusercontent.com/666005/98227182-437fd900-1f57-11eb-9acd-ee77905c3d6c.png">

2020-11-05 10:15 UTC, merged