azurerm_vpn_gateway - support block "bgp_peering_addresses"
terraform-providers/terraform-provider-azurerm pull request #9035
Opened 2020-10-27 08:10 UTC by njuCZ

After confirmed with service team, this field "bgp_peering_addresses" could not be set when creating, otherwise the rest api will report error. It could only be updated.

![image](https://user-images.githubusercontent.com/2786738/97273857-d1c8d080-186e-11eb-9183-97289dfe4ff5.png)

2020-10-27 21:59 UTC, katbyte requested changes
Thanks for the PR @njuCZ - however i think the block/properties are poorly named and confusing.

it seems like the block is tied to an "instance" and then these are the addresses for it? we should name the block something that is a bit more explicit, like `bgp_ip|instance_peering_addresses` and then inside `ip|instance_id` ?

2020-10-27 21:59 UTC, katbyte commented on azurerm/internal/services/network/vpn_gateway_resource.go
> +									},
could we validate this?

2020-10-27 21:59 UTC, katbyte commented on website/docs/r/vpn_gateway.html.markdown
> +* `ip_configuration_id` - (Required) The ID of IP configuration which belongs to gateway.
Could we explain what this property is more? configuration is very vauge

2020-10-27 21:59 UTC, katbyte commented on website/docs/r/vpn_gateway.html.markdown
> +* `custom_bgp_ip_addresses` - (Required) The list of custom BGP peering addresses which belong to IP configuration.
grammer
```suggestion
* `custom_bgp_ip_addresses` - (Required) The list of custom BGP peering addresses which belong to the above IP configuration.
```

2020-10-27 21:59 UTC, katbyte commented on azurerm/internal/services/network/vpn_gateway_resource.go
> +									"ip_configuration_id": {
Should this be called something else? ip configuration id implied an azure resource, when its a text string? 

what does this value represent and is there a more descriptive/accurate name?

2020-10-27 21:59 UTC, katbyte commented on azurerm/internal/services/network/vpn_gateway_resource.go
> +						"bgp_peering_addresses": {
should this be 
```suggestion
						"bgp_peering_ip_addresses": {
```

or
```suggestion
						"ip_bgp_peering_addresses": {
						"instance_bgp_peering_addresses": {
```
given that ip_configuration_id seems to tie it into something that is not an ip resource id?

also the properties within could be
ip_???
custom_ips
default_ips
tunnel_ips

givenits within a block `bgp_peering_addresses` i think we can drop it from all the contained properties

2020-10-27 21:59 UTC, katbyte commented on website/docs/r/vpn_gateway.html.markdown
> +* `tunnel_ip_addresses` - The list of tunnel public IP addresses which belong to IP configuration.
grammer and could we expand on this

2020-10-27 21:59 UTC, katbyte commented on website/docs/r/vpn_gateway.html.markdown
> +* `default_bgp_ip_addresses` - The list of default BGP peering addresses which belong to IP configuration.
grammer and could we expand on this

2020-10-28 10:41 UTC, njuCZ commented
Hi @katbyte thanks for your review. After consulting the service team further, they say `IpconfigurationID` is fixed to `Instance0` and `Instance1`. Users could not change it.

The portal's experience is: creating VPN Gateway only needs parameters of `AS number` and `gateway scale units`. and updating could only update custom bgp ip address, the picture is shown blow
![image](https://user-images.githubusercontent.com/2786738/97409434-8f6bc600-1938-11eb-8aea-cfa4838c1d22.png)

So my sugggestion is to make `IpconfigurationID` computed, and limit the size of `instance_bgp_peering_address` block to 2. Do you think it is ok? I have modified this PR, could you have a look again?

2020-11-09 22:14 UTC, katbyte requested changes
Hey @njuCZ - i've been thinking about this on and off for a week and i dont' this the current schema is very clear or good ux. I've left some comments inline but basically i think creating two named blocks might be the best and most clear solution here? WDYT?

2020-11-09 22:14 UTC, katbyte commented on azurerm/internal/services/network/tests/vpn_gateway_resource_test.go
> +    instance_bgp_peering_address {
This isn't exactly clear, maybe it would be best to create two named blocks?
```suggestion
    instance_0_bgp_peering_address {
```

2020-11-09 22:14 UTC, katbyte commented on azurerm/internal/services/network/tests/vpn_gateway_resource_test.go
> +    instance_bgp_peering_address {
and then
```suggestion
    instance_1_bgp_peering_address {
```

2020-11-09 22:14 UTC, katbyte commented on azurerm/internal/services/network/vpn_gateway_resource.go
> +						"instance_bgp_peering_address": {
Maybe its best to split this into two named blocks to match the portal?

2020-11-10 10:13 UTC, njuCZ commented
@katbyte thanks for your review, I have modifed this PR, please have a look when free

2020-11-10 19:08 UTC, katbyte approved these changes
Thanks @njuCZ - LGTM 👍

2020-11-10 19:09 UTC, merged