[WIP] Add azurerm_data_factory_trigger_tumbling_window resource closes #9126
terraform-providers/terraform-provider-azurerm pull request #9127
Opened 2020-11-02 18:25 UTC by dnlbunting

2021-01-21 09:16 UTC, dnlbunting commented
Hey @tombuildsstuff @mbfrahry would it be possible to get a review on this, still keen to get this resources merged, thanks!

2021-05-01 02:21 UTC, katbyte requested changes
Thanks for the PR @dnlbunting - sorry its taken so long to review. I've given this a look over and it's off to a great start. Iv'e left some comments inline to address and it should be good to merge after they are resolved.

2021-05-01 02:21 UTC, katbyte commented on website/docs/r/data_factory_trigger_tumbling_window.html.markdown
> +Datafactory triggers are created in the "Stopped" state and must be manually enabled to start triggering.  The API prevents updates to triggers in the "Started" state, so they must be manually paused
could we pause them, update, and restart if needed?

2021-05-01 02:21 UTC, katbyte commented on website/docs/r/data_factory_trigger_tumbling_window.html.markdown
> +    example = "@{formatDateTime(trigger().outputs.windowStartTime,'yyyy-MM-dd')}"
could we pass this in formatted instead of this rather unclear series of functions

2021-05-01 02:21 UTC, katbyte commented on website/docs/r/data_factory_trigger_tumbling_window.html.markdown
> +* `pipeline_name` - (Required) The name of the pipeline to be triggered, there is a one to one relationship between pipelines and Tumbling Window Triggers.
would this make more sense as 
```suggestion
* `triggered_pipeline_name` - (Required) The name of the pipeline to be triggered, there is a one to one relationship between pipelines and Tumbling Window Triggers.
```

2021-05-01 02:21 UTC, katbyte commented on azurerm/internal/services/datafactory/data_factory_trigger_tumbling_window_resource_test.go
> +func TestAccAzureRMDataFactoryTriggerTumblingWindow_complete(t *testing.T) {
as this updates it should be
```suggestion
func TestAccAzureRMDataFactoryTriggerTumblingWindow_update(t *testing.T) {
```

2021-05-25 19:35 UTC, katbyte commented
hey @dnlbunting - as its been about a month with no response and there are conflicts now i'm going to close this PR. but once you have time and fix it up please to open a new PR and we can get this merged!

2021-05-25 19:35 UTC, closed without merging