new resource - "azurerm_synapse_managed_private_endpoint"
terraform-providers/terraform-provider-azurerm pull request #9260
Opened 2020-11-11 07:08 UTC by njuCZ

![image](https://user-images.githubusercontent.com/2786738/98780435-b691bf80-242f-11eb-9c90-59de1e99693e.png)

2020-11-26 05:08 UTC, katbyte requested changes
Thanks for the PR @njuCZ - i've left some comments inline to address.

2020-11-26 05:08 UTC, katbyte commented on azurerm/internal/services/synapse/parse/synapse_managed_private_endpoint.go
> +func SynapseManagedPrivateEndpointID(input string) (*SynapseManagedPrivateEndpointId, error) {
Could we switch to the new generated IDs for this resource/package?

2020-11-30 05:09 UTC, njuCZ commented on website/docs/r/synapse_managed_private_endpoint.html.markdown
> +* `group_id` - (Required) Specifies the sub resource name which the Synapse Private Endpoint is able to connect to. Changing this forces a new resource to be created.
this resource is almost the same with "private_endpoint" resource. In the schema of that resource, `group_id` is renamed to `subresource_names`, and I followed the same description here. Should I also keep the same schema name?

2020-11-30 05:10 UTC, njuCZ commented on azurerm/internal/services/synapse/client/client.go
> +	"github.com/Azure/azure-sdk-for-go/services/preview/synapse/2019-06-01-preview/managedvirtualnetwork"
yes, a new dependency package only applicable to synapse

2020-11-30 07:16 UTC, njuCZ commented
@katbyte thanks for the suggestions, I have updated this PR, and generate IDs for all synapse resource. I have rerun all acctest in this package.

![image](https://user-images.githubusercontent.com/2786738/100579313-f78a3f00-331e-11eb-9cc1-942fef89114f.png)

2020-12-08 19:24 UTC, katbyte requested changes

2020-12-08 19:24 UTC, katbyte commented on website/docs/r/synapse_managed_private_endpoint.html.markdown
> +* `group_id` - (Required) Specifies the sub resource name which the Synapse Private Endpoint is able to connect to. Changing this forces a new resource to be created.
As it stands its confusing so might be best to rename this, if it is `subresource_names` in the other it would make sense to rename it to taht here

2020-12-08 19:24 UTC, katbyte commented on website/docs/r/synapse_managed_private_endpoint.html.markdown
> +* `group_id` - (Required) Specifies the sub resource name which the Synapse Private Endpoint is able to connect to. Changing this forces a new resource to be created.
As its singual `subresource_name`

2020-12-09 03:01 UTC, njuCZ commented on website/docs/r/synapse_managed_private_endpoint.html.markdown
> +* `group_id` - (Required) Specifies the sub resource name which the Synapse Private Endpoint is able to connect to. Changing this forces a new resource to be created.
done

2020-12-09 03:03 UTC, njuCZ commented
@katbyte thanks for your suggestion. I have renamed the field "group_id" to "subresource_name", please have a look again when free

2020-12-10 23:38 UTC, katbyte approved these changes
thanks @njuCZ - LGTM 👍

2020-12-10 23:39 UTC, merged