add field for virtual network gateway and virtual network gateway connection
terraform-providers/terraform-provider-azurerm pull request #9330
Opened 2020-11-16 02:02 UTC by chenjianfei2017

2020-11-18 17:24 UTC, katbyte requested changes
i've left some comments inline to address

2020-11-18 17:24 UTC, katbyte commented on website/docs/d/virtual_network_gateway.html.markdown
> +* `private_ip_address_enabled` - Whether private IP needs to be enabled on this gateway for connections or not.
grammer?
```suggestion
* `private_ip_address_enabled` - Whether a private IP will be used for this  gateway for connections.
```

or if the description is right
```suggestion
* `private_ip_address_required` - Whether private IP needs to be enabled on this gateway for connections or not.
```

2020-11-19 06:01 UTC, chenjianfei2017 commented
@katbyte  Thanks for your review! I changed the code according to your comments. pls help to review this pr.

2020-11-24 00:13 UTC, katbyte approved these changes
Thanks, LGTM now 👍

2020-11-25 01:47 UTC, chenjianfei2017 commented
@katbyte Could you pls help to merge this pr, I have no permission to merge, thx.

2020-11-26 04:51 UTC, katbyte commented
Was waiting for tests to pass, they have now so merging!

2020-11-26 04:51 UTC, merged