[Resource][Data Source] ACR Scope Map and Tokens
terraform-providers/terraform-provider-azurerm pull request #9402
Opened 2020-11-19 17:44 UTC by Lucretius

- Data Source for `azurerm_container_registry_token`
- Data Source for `azurerm_container_registry_scope_map`
- Resource for `azurerm_container_registry_token`
- Resource for `azurerm_container_registry_scope_map`
- Documentation for each
- Tests for each, they all pass running against my own Azure environment.

There are passwords for the token which I would like to expose but there is no way to delete them once generated.  Perhaps they might be better suited as a data source, similar to how we handle the sas tokens?

2021-01-12 09:13 UTC, shashken commented
@Lucretius @tombuildsstuff Any updates on this PR?

2021-02-02 00:01 UTC, katbyte requested changes
Hi @Lucretius - sorry for the delay in reviewing this, overall it looks good but we'll need to fix up the merge conflicts and move to the new testing framework. Once thats done this should be good to merge!

2021-02-02 00:01 UTC, katbyte commented on website/docs/r/container_registry_token.html.markdown
> +resource "azurerm_resource_group" "rg" {
could we use example for all names
```suggestion
resource "azurerm_resource_group" "example" {
```

2021-02-02 00:01 UTC, katbyte commented on website/docs/r/container_registry_token.html.markdown
> +  name     = "resourceGroup1"
```suggestion
  name     = "example-resource-group"
```

2021-02-02 00:01 UTC, katbyte commented on website/docs/r/container_registry_token.html.markdown
> +  name                     = "containerRegistry1"
```suggestion
  name                     = "ExampleRegistry"
```

and so forth

2021-04-16 22:16 UTC, katbyte commented
closing as this PR has been superseded by #11350

2021-04-16 22:16 UTC, closed without merging