AKS: add support for ingress-appgw addon
terraform-providers/terraform-provider-azurerm pull request #9419
Opened 2020-11-23 12:51 UTC by derkoe

Closes #7384

2020-12-16 09:39 UTC, Buthrakaur commented
Is there any ETA on this to be merged and released, please?

2021-03-09 16:07 UTC, picardsrcd commented
@tombuildsstuff do you have an ETA to having this merged in and released? 
From a workaround perspective, ill look at enabling the addon using CLI in the interim.

2021-03-18 06:24 UTC, mazen423 commented
That pull request needs attention to be deployed

2021-03-29 16:48 UTC, katbyte requested changes
Hey @derkoe - thanks for the pr, however it appears to be missing a test for the new block and updates to the docs. Could we get those added?

2021-03-29 16:48 UTC, katbyte commented on azurerm/internal/services/containers/kubernetes_addons.go
> +				"ingress_appgw": {
could we not abbreviate this?
```suggestion
				"ingress_app_gateway": {
```

2021-03-29 16:48 UTC, katbyte commented on azurerm/internal/services/containers/kubernetes_addons.go
> +							"appgw_id": {
```suggestion
							"gateway_id": {
```

2021-03-29 16:48 UTC, katbyte commented on azurerm/internal/services/containers/kubernetes_addons.go
> +							"appgw_name": {
is it possible to pull this out of the gateway id?

2021-03-29 16:48 UTC, katbyte commented on azurerm/internal/services/containers/kubernetes_addons.go
> +							"appgw_subnet_id": {
given the block name containers app gateway could we
```suggestion
							"subnet_id": {
```

also is this something we could load from the gateway? or does it potentially have multiple?

2021-03-29 16:48 UTC, katbyte commented on azurerm/internal/services/containers/kubernetes_addons.go
> +							"appgw_subnet_prefix": {
```suggestion
							"subnet_prefix": {
```
also is this something we could load from the gateway? or does it potentially have multiple?

2021-04-14 12:44 UTC, cwiederspan commented
@derkoe Any chance this is still being worked on? I also have the same need and it looks like you're off to a great start to getting this going. I haven't been a contributor on this project yet, but I'm willing to try if there's anything I can do to help.

2021-04-15 06:35 UTC, derkoe commented
@cwiederspan I'm sorry but we are not using Application Gateway anymore so my focus is not on this PR anymore. Maybe you can take over?

2021-04-20 08:31 UTC, magodo commented
This feature has been picked up by #11376, for which I've just done a review. Probably people here can also subscribe that PR, which contains more comprehensive test and document.

2021-04-27 03:28 UTC, katbyte commented
I'm going to close this in favour of #11376 as @derkoe is no longer working on this

2021-04-27 03:28 UTC, closed without merging