add partition_key_version attribute to resource azurerm_cosmosdb_sql_container
terraform-providers/terraform-provider-azurerm pull request #9496
Opened 2020-11-26 14:45 UTC by ankushjain3005

Azure Cosmos DB now supports large partition keys with values up to 2 KB. This pull request captures adding an attribute partition_key_version which can be used to set this configuration. This [URL](https://docs.microsoft.com/en-us/azure/cosmos-db/large-partition-keys?tabs=dotnetv3) has more details about this.
This is the issue id [#8653](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8653).

2020-11-26 14:46 UTC, ankushjain3005 commented
Test Result:

`
ankujai@Ankujai-lp MINGW64 ~/go/src/github.com/terraform-providers/terraform-provider-azurerm (master)
$ TF_ACC=1 go test -v ./azurerm/internal/services/cosmos/ -run TestAccAzureRMCosmosDbSqlContainer -timeout 60m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"                === RUN   TestAccAzureRMCosmosDbSqlContainer_basic
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_basic
=== RUN   TestAccAzureRMCosmosDbSqlContainer_basic_serverless
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_basic_serverless
=== RUN   TestAccAzureRMCosmosDbSqlContainer_complete
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_complete
=== RUN   TestAccAzureRMCosmosDbSqlContainer_update
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_update
=== RUN   TestAccAzureRMCosmosDbSqlContainer_autoscale
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_autoscale
=== RUN   TestAccAzureRMCosmosDbSqlContainer_indexing_policy
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_indexing_policy
=== RUN   TestAccAzureRMCosmosDbSqlContainer_partition_key_version
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_partition_key_version
=== CONT  TestAccAzureRMCosmosDbSqlContainer_basic
=== CONT  TestAccAzureRMCosmosDbSqlContainer_indexing_policy
=== CONT  TestAccAzureRMCosmosDbSqlContainer_autoscale
=== CONT  TestAccAzureRMCosmosDbSqlContainer_partition_key_version
=== CONT  TestAccAzureRMCosmosDbSqlContainer_complete
=== CONT  TestAccAzureRMCosmosDbSqlContainer_update
=== CONT  TestAccAzureRMCosmosDbSqlContainer_basic_serverless
--- PASS: TestAccAzureRMCosmosDbSqlContainer_basic_serverless (1077.73s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_basic (1090.11s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_partition_key_version (1159.99s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_complete (1196.99s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_update (1303.25s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_indexing_policy (1424.73s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_autoscale (1562.54s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cosmos      1572.680s

`

2020-12-03 06:05 UTC, katbyte requested changes
Thanks @ankushjain3005 - overall this looks good, once the comments i've left inline are addressed (and testes pass) this should be good to merge!

2020-12-03 06:05 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_sql_container_resource.go
>  	}
We could make this something like
```suggestion
	if partitionkeypaths != "" {
		db.SQLContainerCreateUpdateProperties.Resource.PartitionKey = &documentdb.ContainerPartitionKey{
			Paths: &[]string{partitionkeypaths},
			Kind:  documentdb.PartitionKindHash,
		}
		
		if v, ok := d.GetOk("partition_key_version"); ok {
			db.SQLContainerCreateUpdateProperties.Resource.PartitionKey.Version = utils.Int32(int32(partitionKeyVersion.(int))),
		}
	}
```

2020-12-03 06:05 UTC, katbyte commented on azurerm/internal/services/cosmos/cosmosdb_sql_container_resource.go
> -		db.SQLContainerCreateUpdateProperties.Resource.PartitionKey = &documentdb.ContainerPartitionKey{
Same as above

2020-12-03 06:58 UTC, ankushjain3005 commented on azurerm/internal/services/cosmos/cosmosdb_sql_container_resource.go
>  	}
resolved

2020-12-03 06:58 UTC, ankushjain3005 commented on azurerm/internal/services/cosmos/cosmosdb_sql_container_resource.go
> -		db.SQLContainerCreateUpdateProperties.Resource.PartitionKey = &documentdb.ContainerPartitionKey{
resolved

2020-12-03 07:28 UTC, ankushjain3005 commented
resolved the comments and reran the test. here are the results

$ TF_ACC=1 go test -v ./azurerm/internal/services/cosmos/ -run TestAccAzureRMCosmosDbSqlContainer -timeout 60m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc" === RUN
go: downloading github.com/tombuildsstuff/giovanni v0.15.0
=== RUN   TestAccAzureRMCosmosDbSqlContainer_basic
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_basic
=== RUN   TestAccAzureRMCosmosDbSqlContainer_basic_serverless
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_basic_serverless
=== RUN   TestAccAzureRMCosmosDbSqlContainer_complete
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_complete
=== RUN   TestAccAzureRMCosmosDbSqlContainer_update
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_update
=== RUN   TestAccAzureRMCosmosDbSqlContainer_autoscale
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_autoscale
=== RUN   TestAccAzureRMCosmosDbSqlContainer_indexing_policy
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_indexing_policy
=== RUN   TestAccAzureRMCosmosDbSqlContainer_partition_key_version
=== PAUSE TestAccAzureRMCosmosDbSqlContainer_partition_key_version
=== CONT  TestAccAzureRMCosmosDbSqlContainer_basic
=== CONT  TestAccAzureRMCosmosDbSqlContainer_autoscale
=== CONT  TestAccAzureRMCosmosDbSqlContainer_update
=== CONT  TestAccAzureRMCosmosDbSqlContainer_indexing_policy
=== CONT  TestAccAzureRMCosmosDbSqlContainer_complete
=== CONT  TestAccAzureRMCosmosDbSqlContainer_partition_key_version
=== CONT  TestAccAzureRMCosmosDbSqlContainer_basic_serverless
--- PASS: TestAccAzureRMCosmosDbSqlContainer_partition_key_version (1369.94s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_complete (1369.94s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_basic_serverless (1369.95s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_basic (1369.98s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_indexing_policy (1398.07s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_update (1401.23s)
--- PASS: TestAccAzureRMCosmosDbSqlContainer_autoscale (1885.70s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cosmos      1898.769s

2020-12-07 07:35 UTC, katbyte approved these changes
Thanks @ankushjain3005 - LGTM 👍

2020-12-07 07:35 UTC, merged