Support new properties for azurerm_resource_group_template_deployment
terraform-providers/terraform-provider-azurerm pull request #9652
Opened 2020-12-03 11:54 UTC by neil-yechenwei

This PR is to add new properties "on_error_deployment", "template_link" and "parameters_link".

API Spec: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json

2020-12-07 10:39 UTC, tombuildsstuff commented
@neil-yechenwei what's the use-case adding these fields is looking to solve? is there a Github issue for this?

2020-12-07 12:24 UTC, neil-yechenwei commented
@tombuildsstuff , attached the github issues for new properties [`OnErrorDeployment`](https://github.com/terraform-providers/terraform-provider-azurerm/issues/9718), [`TemplateLink` and `ParametersLink`](https://github.com/terraform-providers/terraform-provider-azurerm/issues/9719).

2021-02-15 09:00 UTC, tombuildsstuff requested changes
hi @neil-yechenwei 

Thanks for this PR.

I've taken a look through and left some comments inline, however after discussing this internally we've come to the conclusion that the `on_error_deployment` field doesn't make sense in Terraform.

In addition whilst we could look to support the `parameters_link` field here - we believe there's more downsides than upsides to doing so at this time, namely since this isn't likely to be reused across deployments, and may contain sensitive variables (which would have to be public, a huge security risk) - instead it'd make more sense to define these using the `parameters_content` against the deployment itself. That said, as mentioned in #9719, should a compelling use-case for this field become available we can take another look.

As such whilst I'd like to thank you for this contribution - since we believe these fields don't make sense in Terraform at this time I'm going to close this PR for the moment.

Thanks!

2021-02-15 09:01 UTC, closed without merging

2021-02-18 07:41 UTC, neil-yechenwei commented on azurerm/internal/services/resource/resource_group_template_deployment_resource.go
> +			"on_error_deployment": {
@tombuildsstuff , thanks for your comment. May I ask why it doesn't make sense in Terraform?