[WIP] Managed Disk Resource: Added support for network_access_policy
terraform-providers/terraform-provider-azurerm pull request #9862
Opened 2020-12-14 20:31 UTC by cmendible

Fixes: #9796

2020-12-15 20:43 UTC, martinbjorgan commented
@cmendible I was also working on this, you beat me to it :) 
I think we also should add the `disk_access_id` parameter to the managed disk resource since that is required if `AllowPrivate` is used?

2020-12-15 20:51 UTC, cmendible commented
Hi! That's the reason I added the WIP prefix. Wwe need to be sure what else is needed for that specific case...

2020-12-15 20:53 UTC, martinbjorgan commented
@cmendible Missed  that! Sorry :)

2020-12-16 08:11 UTC, cmendible commented
@martinbjorgan confirmed [here](https://docs.microsoft.com/en-us/azure/virtual-machines/disks-enable-private-links-for-import-export-portal?WT.mc_id=AZ-MVP-5002618) that `disk_access_id` is required when the NeworkAccessPolicy is set to `AllowPrivate` and also that the field is supported in update operations: [Disks - Create Or Update](https://docs.microsoft.com/en-us/rest/api/compute/disks/createorupdate?WT.mc_id=AZ-MVP-5002618).

Can you open an issue to add `azurerm_disk_access` as a new resource so you can tackle that one?

2020-12-16 08:16 UTC, martinbjorgan commented
@cmendible Sure, I'll give it a whirl

2020-12-23 10:37 UTC, cmendible commented
PR #9889 (adds the `azurerm_disk_access` resource) must be merged so we can add a test for `network_access_policy = AllowPrivate` which requires a `disk_access_id`

2020-12-23 11:25 UTC, martinbjorgan commented
@cmendible I'm almost done with tests for the resource, data source is done. 
Hopefully I'm done with those after the 24th

2021-01-11 11:39 UTC, cmendible commented
> PR #9889 (adds the `azurerm_disk_access` resource) must be merged so we can add a test for `network_access_policy = AllowPrivate` which requires a `disk_access_id`

PR #9889 was merged and test for `network_access_policy = AllowPrivate` are in place.

@katbyte can you please review this one?

2021-02-04 06:02 UTC, katbyte requested changes
Thanks for the PR @cmendible - overall this looks great! i've just left some comments inline to address before merge

2021-02-04 06:02 UTC, katbyte commented on azurerm/internal/services/compute/managed_disk_resource_test.go
> +		ctx := acceptance.AzureProvider.Meta().(*clients.Client).StopContext
could we remove this and use `data.CheckWithClient`? as we are removing all usages of acceptance.AzureProvider for binary testing

2021-04-15 04:14 UTC, katbyte requested changes
Thanks @cmendible - but i think this change is going to break existing configs as tests are now failing with:

```
An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_managed_disk.test will be updated in-place
          ~ resource "azurerm_managed_disk" "test" {
                id                    = "/subscriptions/*******/resourceGroups/acctestRG-210415031958219440/providers/Microsoft.Compute/disks/acctestd-210415031958219440"
                name                  = "acctestd-210415031958219440"
              - network_access_policy = "AllowAll" -> null
                tags                  = {
                    "cost-center" = "ops"
                    "environment" = "acctest"
                }
                # (7 unchanged attributes hidden)
        
                # (1 unchanged block hidden)
            }
```

maybe we need to mark that as computed?

2021-04-15 13:57 UTC, cmendible commented
> Thanks @cmendible - but i think this change is going to break existing configs as tests are now failing with:
> 
> ```
> An execution plan has been generated and is shown below.
>         Resource actions are indicated with the following symbols:
>           ~ update in-place
>         
>         Terraform will perform the following actions:
>         
>           # azurerm_managed_disk.test will be updated in-place
>           ~ resource "azurerm_managed_disk" "test" {
>                 id                    = "/subscriptions/*******/resourceGroups/acctestRG-210415031958219440/providers/Microsoft.Compute/disks/acctestd-210415031958219440"
>                 name                  = "acctestd-210415031958219440"
>               - network_access_policy = "AllowAll" -> null
>                 tags                  = {
>                     "cost-center" = "ops"
>                     "environment" = "acctest"
>                 }
>                 # (7 unchanged attributes hidden)
>         
>                 # (1 unchanged block hidden)
>             }
> ```
> 
> maybe we need to mark that as computed?

@katbyte I ran some tests and it should be fixed.

2021-04-25 19:38 UTC, katbyte requested changes
Thanks @cmendible - overall looks good and i've left some comments inline

2021-04-25 19:38 UTC, katbyte commented on azurerm/internal/services/compute/managed_disk_resource_test.go
> +func TestAccAzureRMManagedDisk_create_withNetworkPolicy(t *testing.T) {
for consistency 
```suggestion
func TestAccAzureRMManagedDisk_networkPolicy(t *testing.T) {
```

2021-04-25 19:38 UTC, katbyte commented on azurerm/internal/services/compute/managed_disk_resource_test.go
> +func TestAccAzureRMManagedDisk_update_withNetworkPolicy(t *testing.T) {
```suggestion
func TestAccAzureRMManagedDisk_networkPolicy_update(t *testing.T) {
```

2021-04-25 19:38 UTC, katbyte commented on azurerm/internal/services/compute/managed_disk_resource_test.go
> +func TestAccAzureRMManagedDisk_import_withNetworkPolicy(t *testing.T) {
i don't think we need this as it duplicate the main import check?

2021-04-25 19:38 UTC, katbyte commented on azurerm/internal/services/compute/managed_disk_resource_test.go
> +		},
after every step in every test we generally have an import step, could we add these please?

2021-04-25 19:38 UTC, katbyte commented on azurerm/internal/services/compute/managed_disk_resource_test.go
> +func TestAccAzureRMManagedDisk_create_withAllowPrivateNetworkPolicy(t *testing.T) {
```suggestion
func TestAccAzureRMManagedDisk_allowPrivateNetworkPolicy(t *testing.T) {
```

ad so forth

2021-04-25 19:38 UTC, katbyte commented on azurerm/internal/services/compute/managed_disk_resource_test.go
> +func TestAccAzureRMManagedDisk_import_withAllowPrivateNetworkPolicy(t *testing.T) {
ditto here, i think we can drop this test

2021-04-25 19:38 UTC, katbyte commented on azurerm/internal/services/compute/managed_disk_resource_test.go
> +func testAccAzureRMManagedDisk_create_withNetworkPolicy(data acceptance.TestData) string {
and then update the config function names

2021-04-28 16:28 UTC, katbyte requested changes
Thanks @cmendible - aside from the tests failing with:
```
------- Stdout: -------
=== RUN   TestAccAzureRMManagedDisk_networkPolicy
=== PAUSE TestAccAzureRMManagedDisk_networkPolicy
=== CONT  TestAccAzureRMManagedDisk_networkPolicy
    testing.go:620: Step 1/2 error: Error running apply: exit status 1
        
        Error: [ERROR] disk_iops_read_write and disk_mbps_read_write are only available for UltraSSD disks
        
          on terraform_plugin_test.tf line 11, in resource "azurerm_managed_disk" "test":
          11: resource "azurerm_managed_disk" "test" {
        
--- FAIL: TestAccAzureRMManagedDisk_networkPolicy (104.83s)
FAIL

------- Stderr: -------
2021/04/28 06:39:36 [DEBUG] not using binary driver name, it's no longer needed
2021/04/28 06:39:36 [DEBUG] not using binary driver name, it's no longer needed
```

this is looking good to go!

2021-04-28 20:22 UTC, cmendible commented
@katbyte fixed the tests in: d64af57

2021-04-28 21:27 UTC, katbyte requested changes
@cmendible - looks like we have another casing issue 😪 

```
------- Stdout: -------
=== RUN   TestAccAzureRMManagedDisk_networkPolicy_create_withAllowPrivate
=== PAUSE TestAccAzureRMManagedDisk_networkPolicy_create_withAllowPrivate
=== CONT  TestAccAzureRMManagedDisk_networkPolicy_create_withAllowPrivate
    testing.go:620: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_managed_disk.test will be updated in-place
          ~ resource "azurerm_managed_disk" "test" {
              ~ disk_access_id        = "/subscriptions/*******/resourceGroups/ACCTESTRG-210428201256204039/providers/Microsoft.Compute/diskAccesses/accda210428201256204039" -> "/subscriptions/*******/resourceGroups/acctestRG-210428201256204039/providers/Microsoft.Compute/diskAccesses/accda210428201256204039"
                id                    = "/subscriptions/*******/resourceGroups/acctestRG-210428201256204039/providers/Microsoft.Compute/disks/acctestd-210428201256204039"
                name                  = "acctestd-210428201256204039"
                tags                  = {
                    "cost-center" = "ops"
                    "environment" = "acctest"
                }
                # (9 unchanged attributes hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccAzureRMManagedDisk_networkPolicy_create_withAllowPrivate (189.25s)
FAIL

------- Stderr: -------
2021/04/28 20:12:54 [DEBUG] not using binary driver name, it's no longer needed
2021/04/28 20:12:55 [DEBUG] not using binary driver name, it's no longer needed
```

could we open an issue on the SDK describing this issue and link to it on the property? which i believe we'll need to diffsuppress case

2021-04-29 15:37 UTC, cmendible commented
Opened issue to the Azure SDK team here: https://github.com/Azure/azure-rest-api-specs/issues/14192

And `suppress.CaseDifference` added to the code here: f0cc2de

2021-04-29 17:56 UTC, katbyte approved these changes
Thanks @cmendible - LGTM 👍

2021-04-29 17:56 UTC, merged