CDN endpoint: Test for Premium_Verizon, optional values fix
terraform-providers/terraform-provider-azurerm pull request #9902
Opened 2020-12-16 21:51 UTC by AliAllomani

* Added test for "Premium_Verizon" SKU for azurerm_cdn_profile
* Assigning the parameters `EndpointProperties.ContentTypesToCompress`, `EndpointProperties.GeoFilters` and `EndpointProperties.DeliveryPolicy` only when values are set for `content_types_to_compress`, `geo_filter`, `global_delivery_rule` and `delivery_rule`. Fixes #9895

2020-12-27 17:31 UTC, katbyte requested changes
Thanks for the PR @AliAllomani - Aside from two questions i have left inline this looks good! Once those are addressed this should be good to merge

2020-12-27 17:31 UTC, katbyte commented on azurerm/internal/services/cdn/cdn_endpoint_resource.go
> +		if _, ok := d.GetOk("content_types_to_compress"); ok {
I don't think we need this check? or does the API return a default value?

2020-12-27 17:31 UTC, katbyte commented on azurerm/internal/services/cdn/cdn_endpoint_resource.go
> +		if _, ok := d.GetOk("geo_filter"); ok {
I don't think we need this check? or does the API return a default value?

2020-12-27 18:13 UTC, katbyte commented
Additionally these tests are failing:
```
TestAccCdnEndpoint_deliveryRule
TestAccCdnEndpoint_globalDeliveryRule
TestAccCdnEndpoint_withGeoFilters

```

2020-12-27 20:40 UTC, AliAllomani commented
Updated and passed acceptance tests

```
--- PASS: TestAccCdnEndpoint_withGeoFilters (470.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cdn	472.676s

--- PASS: TestAccCdnEndpoint_deliveryRule (633.33s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cdn	635.827s

--- PASS: TestAccCdnEndpoint_PremiumVerizon (708.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cdn	710.972s

--- PASS: TestAccCdnEndpoint_globalDeliveryRule (581.30s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cdn	586.211s
```

2020-12-27 23:47 UTC, katbyte approved these changes
Thanks @AliAllomani! - this LGTM  now 👍

2020-12-27 23:48 UTC, merged

2021-01-14 16:20 UTC, GlenColby commented
@katbyte @AliAllomani 

This still isnt fixed. in 2.42 of the azureRM provider, version 0.13.5 of Terraform

`resource "azurerm_cdn_profile" "CDN" {
  name                                = "${var.PREFIX}${var.ENVIRONMENT}cdn${var.LOCATION}"
  resource_group_name      = var.GLOBAL_NAMESPACE
  location                            = var.LOCATION
  sku                                  = "Premium_Verizon"

  tags = {
    environment   = var.ENVIRONMENT
  }
}

resource "azurerm_cdn_endpoint" "UserManagementWebAppProdEndpoint" {
  name                            = "${var.PREFIX}${var.ENVIRONMENT}cdn${var.LOCATION}p"
  profile_name                 = azurerm_cdn_profile.CDN.name
  location                        = var.LOCATION
  resource_group_name  = var.GLOBAL_NAMESPACE
  is_http_allowed            = false
  
  origin {
    name      = "UserManagementProdCDN"
    host_name = replace(var.USERS_PROD_STATIC_WEBSITE,"/\\//","")
  }

  querystring_caching_behaviour = "NotSet"

  optimization_type  = "GeneralWebDelivery"
  

  origin_host_header = replace(var.USERS_PROD_STATIC_WEBSITE,"/\\//","")

  tags = {
    environment   = var.ENVIRONMENT
  }

  depends_on = [azurerm_cdn_profile.CDN]
}`

The above still throws the following error

"cdn.EndpointsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="We couldn’t configure QueryStringCachingBehavior, IsCompressionEnabled, ContentTypesToCompress, GeoFilters and DeliveryPolicy for premium profile endpoints. You’ll need to manage these endpoints in the supplemental portal."

This worked back in azureRM < 2.6.

The issue was listed here https://github.com/terraform-providers/terraform-provider-azurerm/issues/1109 and closed while people were still reporting it not working.