Support for Event Grid Domain/Topic system managed identity
terraform-providers/terraform-provider-azurerm pull request #9906
Opened 2020-12-17 07:38 UTC by jrauschenbusch

Fixes https://github.com/terraform-providers/terraform-provider-azurerm/issues/9525

```sh
make acctests SERVICE='eventgrid' TESTARGS='-run=TestAccEventGridTopic_basicWithIdentity' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/eventgrid/tests/ -run=TestAccEventGridTopic_basicWithIdentity -timeout 60m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccEventGridTopic_basicWithIdentity
=== PAUSE TestAccEventGridTopic_basicWithIdentity
=== CONT  TestAccEventGridTopic_basicWithIdentity
--- PASS: TestAccEventGridTopic_basicWithIdentity (116.60s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/eventgrid/tests     118.483s
```

```sh
make acctests SERVICE='eventgrid' TESTARGS='-run=TestAccEventGridDomain_basicWithIdentity' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/eventgrid/tests/ -run=TestAccEventGridDomain_basicWithIdentity -timeout 60m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccEventGridDomain_basicWithIdentity
=== PAUSE TestAccEventGridDomain_basicWithIdentity
=== CONT  TestAccEventGridDomain_basicWithIdentity
--- PASS: TestAccEventGridDomain_basicWithIdentity (119.35s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/eventgrid/tests     121.912s
```

2021-05-13 19:08 UTC, mbfrahry requested changes
Hey @jrauschenbusch! This is looking mostly good but we need to flesh out the docs a little and add another test

2021-05-13 19:08 UTC, mbfrahry commented on website/docs/r/eventgrid_topic.html.markdown
> +A `identity` block exports the following:
```suggestion
A `identity` block supports the following:
```

We should also call out `identity_ids`

And in the export section of the docs, we want to call out `principal_id` and `tenant_id`

2021-05-13 19:08 UTC, mbfrahry commented on website/docs/r/eventgrid_domain.html.markdown
> +A `identity` block exports the following:
The same doc note should be applied here

2021-05-13 19:08 UTC, mbfrahry commented on azurerm/internal/services/eventgrid/eventgrid.go
> +			return nil, fmt.Errorf("`identity_ids` can only be specified when `type` includes `UserAssigned`")
We should have a test where we use `identity_ids` as well

2021-07-30 17:08 UTC, katbyte commented
Hey @jrauschenbusch - as theres been no activity on this since may i'm going to close it. Please do reopen it when you have time to address the comments! thanks

2021-07-30 17:08 UTC, closed without merging